### ISSUE TITLE
Garbage on the display seen during warm booting

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#10]
**Dasharo version**
1.0.0

**Dasharo variant**
Firewall

**Affected component(s) or functionality**
Graphics display

**Brief summary**
After warm boot (powering the platform with power button after previous power off) the screen displays garbage when switching display modes on some lower parts of the screen.

**How reproducible**
Sometimes.

**How to reproduce**

1. Boto to OS.
2. Perform power off.
3. Press the power button.
4. Observe garbage output on the lower part of the screen when booting to SeaBIOS or bootloader/Linux kernel.

**Expected behavior**
Screen output is clean or contains the bootsplash/bootloader menu only.

**Actual behavior**
The lower part of the screen contains garbage.

**Screenshots**
![linux_protectli](https://user-images.githubusercontent.com/30656491/109320879-d7e8b100-7850-11eb-80d2-39a4a93f5fd1.jpeg)

**Additional context**
None

**Solutions you've tried**
None

**Comment by pietrushnic** [comment]
@miczyg1 it would be great to have a reason for closing this one. Why it is marked as invalid?

**Comment by miczyg1** [comment]
@pietrushnic it was detected on pre-release binary, not a release one. Also not reproduced on release binary thus marked as invalid.

**Comment by pietrushnic** [comment]
@miczyg1 co I assume Dasharo version field should not be v1.0.0? And definitely comment like yours now should be here. There always have to be a reason for changing the state of issues.
