### ISSUE TITLE
MinnowBoard Turbot network boot- missing options  

### ISSUE THREAD

**Issue by wiktormowinski** [Dasharo/dasharo-issues#1002]
### Component

Dasharo firmware

### Device

other

### Dasharo version

v0.9.0-rc1

### Test case ID

NBT001-007.001

### Brief summary

seems like not all ipxe functionalities were implemented yet

### How reproducible

always

### How to reproduce

1. Power on the DUT.
2. Hold the BOOT_MENU_KEY to enter the UEFI Boot Menu.
3. Select the Network Boot and Utilities option using the arrow keys and press Enter.

### Expected behavior

all ipxe network boot options aviable

### Actual behavior

only these are aviable

```
   ------------------------ Dasharo Network Boot Menu -----------------------  
   Autoboot (DHCP)                                                             
   Dasharo Tools Suite                                                         
   OS installation (netboot.xyz official server)                               
   iPXE Shell                                                                  
```

**Comment by filipleple** [comment]
As discussed here - https://github.com/Dasharo/dasharo-issues/issues/892 - the advanced options aren't implemented anywhere other than Protectli, so the menu looks as expected
