### ISSUE TITLE
Poor discrete graphics performance

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#1009]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

n/a

### Test case ID

n/a

### Brief summary

Default power limits are too conservative. GPU-Z reports power throttling at merely 20W.

### How reproducible

100%

### How to reproduce

- boot to windows
- start gpu-z
- start graphics stresstest on discrete GPU (e.g. Furmark)
- monitor power draw in gpu-z

### Expected behavior

GPU power draw should be at around 80W on AC and 40W on battery

### Actual behavior

Power is limited to ~20W, causing worse performance than just using the integrated GPU.

**Comment by mkopec** [comment]
Looks like nvidia-powerd on Linux and the counterpart on Windows can't read the processor power budget and fails to enable dynamic power boost. I think this may be the problem.

```
Aug 21 11:48:23 ubuntu-V560TND systemd[1]: Started nvidia-powerd.service - nvidia-powerd service.
Aug 21 11:48:23 ubuntu-V560TND /usr/bin/nvidia-powerd[1017]: nvidia-powerd version:1.0(build 1)
Aug 21 11:48:24 ubuntu-V560TND /usr/bin/nvidia-powerd[1017]: Failed to get Processor Power Budget
Aug 21 11:48:24 ubuntu-V560TND /usr/bin/nvidia-powerd[1017]: Failed to start GPU Boost controller
Aug 21 11:48:24 ubuntu-V560TND /usr/bin/nvidia-powerd[1017]: Failed to initialize Dynamic Boost
Aug 21 11:48:24 ubuntu-V560TND /usr/bin/nvidia-powerd[1017]: Failed to detach GPU id 256
Aug 21 11:48:24 ubuntu-V560TND systemd[1]: nvidia-powerd.service: Main process exited, code=exited, status=1/FAILURE
Aug 21 11:48:24 ubuntu-V560TND systemd[1]: nvidia-powerd.service: Failed with result 'exit-code'.
```

strace suggests it fails right after reading some MSRs, so it's possible it just doesn't support Meteor Lake yey:

[powerd-strace.log.txt](https://github.com/user-attachments/files/16689808/powerd-strace.log.txt)

**Comment by mkopec** [comment]
I got Intel DTT to detect the dGPU and apply a power share policy, but apparently DTT only works when the dGPU is at <= 50% usage, so it disengages when gaming for example. NVIDIA Dynamic Boost is supposed to take over at this point according to DTT docs.

Nvidia control panel on Windows detects Dynamic Boost in the control panel, unfortunately  nvidia-powerd still crashes without any errors :(

Despite all that the GPU is still limited to ~30W (depends on GPU variant) resulting in performance about the same as the iGPU. I don't know what else is missing.

Insyde firmware has a NvdGPUPei module, I'm not yet sure what it does, it could be required in Dasharo as well.

We currently don't execute the GPU's option ROM, because it causes breakage in UEFI rendering and breaks the iGPU in Windows. I guess we may need it to fix this issue.

**Comment by philipandag** [comment]
The performance is still bad on v0.9.1-rc5. ~35fps in furmark

**Comment by wessel-novacustom** [comment]
> The performance is still bad on v0.9.1-rc5. ~35fps in furmark on V540TND

Are you running kernel 6.8 or the manually installed 6.9?

I have seen that the NVIDIA graphics card is no longer active after installing kernel 6.9 ...

**Comment by philipandag** [comment]
I have been testing it on Windows for exactly the reason you mentioned. NVIDIA drivers don't work on 6.9 kernels, 6.10 kernels don't boot at all on Ubuntu, kernel 6.8 causes "bricks" on almost every suspend.

**Comment by wessel-novacustom** [comment]
Yeah, same here for the kernels we tried so far.

**Comment by mkopec** [comment]
Made some progress in https://github.com/Dasharo/coreboot/pull/548/commits/950f78bdbfaa995ac71ff9a140d9469c6d9f253f

The 4060 in the unit I tested with now maxes out at 37W on Linux, so at least some improvement. I'm still working on eliminating differences with vendor firmware's dGPU ACPI, the dynamic boost params should now be the same as Insyde, still working on the rest of functions.

**Comment by mkopec** [comment]
Fixed by https://github.com/Dasharo/ec/pull/62/commits/d2ba5e67e6733e7c21fcd0cc1faf4befdab4c294 , to be closed when confirmed fixed in rc6

**Comment by SebastianCzapla** [comment]
With EC of rc6 the GPU chip power draw is upwards of 91,5W according to GPU-Z.

**Comment by wessel-novacustom** [comment]
> With EC of rc6, according to GPU-Z power draw of GPU chips is: Around 90 watts when plugged to AC (Windows) Around 10 watts when on battery (Windows)

Is this good? @mkopec

**Comment by mkopec** [comment]
yes that's good, this means the limiter is no longer active

**Comment by SebastianCzapla** [comment]
"Beginning with Windows 10 20H1, the Windows OS assigns the graphics processor to use for various applications, and overrides any settings made in the NVIDIA Control Panel > Manage 3D Settings > Preferred graphics processor setting for that application." from [https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nv3d/Setting_the_Preferred_Graphics_Processor.htm](nvidia documentation)

Can you try to use those settings to force Uniengine to use dGPU?

**Comment by wessel-novacustom** [comment]
> "Beginning with Windows 10 20H1, the Windows OS assigns the graphics processor to use for various applications, and overrides any settings made in the NVIDIA Control Panel > Manage 3D Settings > Preferred graphics processor setting for that application." from [https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nv3d/Setting_the_Preferred_Graphics_Processor.htm](nvidia-documentation)
> 
> Can you try to use those settings to force Uniengine to use dGPU?

I just did that through the Windows settings, since the option is not available in the NVIDIA control panel. Unfortunately, it didn't have any effect.

**Comment by SebastianCzapla** [comment]
I have retested this with v0.9.1-rc7, here's some observations:

Furmark easily stresses GPU to 100%, resulting in expected and correct power draw.
Uniengine benchmark results however are subpar, just like in screenshot you provided. However, this is not an issue of not enough power, as Uniengine just cannot stress the GPU enough, even with ultra setting and tesselation GPU utilization barely reaches ~35%.

My assumption is that Uniengine simply cannot utilize full potential of GPU, perhaps due to age

**Comment by mkopec** [comment]
Unigine can definitely use 100% of the GPU, the problem is that it eats the entire platform power budget, the CPU throttles to hell and ends up bottlenecking the CPU. 

are you testing with the 180W power supply connected?

**Comment by mkopec** [comment]
Made some improvements in https://github.com/Dasharo/ec/pull/62/commits/015a444f5efb5c9d8b2131e23efc8fbad8185b56 , I get 15444pts in Unigine Superposition 1080p high now. This is a good result compared to some other laptops with the same gpu

**Comment by wessel-novacustom** [comment]
> Made some improvements in [Dasharo/ec@015a444](https://github.com/Dasharo/ec/commit/015a444f5efb5c9d8b2131e23efc8fbad8185b56) , I get 15444pts in Unigine Superposition 1080p high now. This is a good result compared to some other laptops with the same gpu

That's insane. I never got more than 1000 points.

:-)

**Comment by Rot127** [comment]
If anyone comes around this issue, because there are still lags in games (max. power usage around 20W): change the fan profile in the BIOS to "Performance".
There seems to be a bug with Nvidia + DirectX not using the GPU fully if it is set to "Silent".
Running a benchmark using Vulkan or OpenGL works perfectly fine, even with a silent fan profile.
