### ISSUE TITLE
v0.9.1-rc3 v560tne '/sys/devices/pci0000:00/0000:00:02.0/drm/card*/*HDMI*/status': No such file or directory

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1016]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

--

### Test case ID

DSP002.001

### Brief summary

'/sys/devices/pci0000:00/0000:00:02.0/drm/card*/*HDMI*/status': No such file or directory

### How reproducible

100%

### How to reproduce

connect external monitor via hdmi, run the test

### Expected behavior

Should pass

### Actual behavior

fails beacuse of a file in sysfs missing
[Uploading display-ports-and-lcd-support.robot_log.zip…]()

**Comment by mkopec** [comment]
the 00:02.0 in the command points to the iGPU, but on the TNx models the HDMI port is wired to the discrete graphics which is PCI device 01:00.0...

the previous releases probably passed because the VBT from iGPU models was used, this release fixed that - but now the tests need to be updated. I'd just replace `/sys/devices/pci0000:00/0000:00:02.0/drm/card*` with `/sys/class/drm/card*/

**Comment by philipandag** [comment]
Will be changed in https://github.com/Dasharo/open-source-firmware-validation/pull/477

**Comment by philipandag** [comment]
I forgot to add the more important thing, which is why this issue is on `dasharo-issues`. I tried to do the test manually but there was no video output. May be important that I used a displayport monitor and a HDMI to displayport cable.

**Comment by philipandag** [comment]
On windows the display is also not working
[display-ports-and-lcd-support.robot_log.zip](https://github.com/user-attachments/files/16706742/display-ports-and-lcd-support.robot_log.zip)

**Comment by mkopec** [comment]
> May be important that I used a displayport monitor and a HDMI to displayport cable.

these are usually directional and only work in the DisplayPort source -> HDMI sink direction, try with a HDMI to HDMI cable

**Comment by philipandag** [comment]
That must've been it. Thank you.
