### ISSUE TITLE
V540TND Setup menu is very small after updating from v0.9.1-rc2 to v0.9.1-rc3

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1019]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

--

### Test case ID

--

### Brief summary

Setup menu is very small after updating from v0.9.1-rc2 to v0.9.1-rc3

### How reproducible

On this one device, always, did not try to reflash again

### How to reproduce

Enter Setup menu

### Expected behavior

I suppose it should fill the whole screen or at least be bigger because now it is hard to read. Before flashing to v0.9.1-rc3 it was indeed filling the whole screen.

### Actual behavior

Fills about 10% in the center

### Screenshots

![image](https://github.com/user-attachments/assets/46b243f5-74bc-4ee3-993b-4ce833bbecd6)

**Comment by mkopec** [comment]
Should be fixed in the next release: https://github.com/Dasharo/coreboot/commit/66abce327e64a05f36f84a05a92266187459fa9b#diff-c3813b53bad91245db156383bf52e219d8b8b501675ced726a7f218dff5446c9

**Comment by wessel-novacustom** [comment]
I noticed that it fills the screen if Serial Port Console Redirection is turned off: https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#serial-port-configuration

**Comment by philipandag** [comment]
> I noticed that it fills the screen if Serial Port Console Redirection is turned off:
I confirm.

**Comment by macpijan** [comment]
This is actually intended and there is no way around it.
If serial redirection is enabled, the on-screen menu must adjust to the size of the one on the serial, which is very limited in size. It also must adjust to the serial performance, which makes going through menus very slow.

**Comment by philipandag** [comment]
In RC4 serial redirection is off by default so it is solved then.

**Comment by philipandag** [comment]
I have just noticed that not only the serial port redirection is turned off by default, but the `Serial Port Configuration` submenu in `Dasharo System Features`  is missing entirely in RC4. Is this intended?

**Comment by philipandag** [comment]
The `Serial Port Configuration` submenu is back in v0.9.1-rc5
