### ISSUE TITLE
SMBIOS string: Wifi vs non-Wifi version 

### ISSUE THREAD

**Issue by handmeatowel** [Dasharo/dasharo-issues#102]
**The problem you're addressing (if any)**
The _MSI Pro Z690-A DDR4_ (SKU 7D25-002R) is recognized as _MSI Pro Z690-A Wifi DDR4_ (SKU 7D25-012R).

**Describe the solution you'd like**
Have checked if Wifi is present or not and populate SMBIOS strings accordingly

**Where is the value to a user, and who might that user be?**
No real value, it's just "wrong".

**Describe alternatives you've considered**
./.

**Additional context**
I've tested the non-Wifi version and everything seems to be running normally.

**Comment by pietrushnic** [comment]
@handmeatowel thanks for the report. We would appreciate if you could join [Dasharo Matrix community](https://matrix.to/#/#dasharo:matrix.org)

**Comment by miczyg1** [comment]
Fixed upstream: https://review.coreboot.org/c/coreboot/+/68078
