### ISSUE TITLE
V560TNE Windows detects but does not use dGPU NVI002.002

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1020]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

--

### Test case ID

NVI002.002

### Brief summary

dGPU is always inactive

### How reproducible

100%

### How to reproduce

Try to run gpu intensive software

### Expected behavior

the dgpu is used

### Actual behavior

the igpu is used instead

### Screenshots

![image](https://github.com/user-attachments/assets/46bb920e-bfa3-48bf-97dc-f6bfb39fc658)

### Solutions you've tried

Tried rebooting, forcing to use the dgpu via settings System->Display->Graphics, turning on performance mode, using other benchmarks. The Nvidia tray icon always says the dgpu is inactive.

**Comment by mkopec** [comment]
hmm, I'm not sure how windows picks the gpu in ms hybrid, but I installed furmark 2 on the same device you tested with and it seems to work fine. I don't think this is our bug
