### ISSUE TITLE
V560TNE SMS001.001 Sleep mode is deep suggesting unsupported S3 sleep

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1022]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

--

### Test case ID

SMS001.001

### Brief summary

Platform Sleep Type missing, `[s2idle] deep`

### How reproducible

100%

### How to reproduce

`sudo cat /sys/power/mem_sleep`

### Expected behavior

Should be `[s2idle] shallow`

### Actual behavior

Is `[s2idle] deep`

### Screenshots

![image](https://github.com/user-attachments/assets/ce6d3c44-4a96-42e5-91d3-43203c7c430f)
```bash
ubuntu@3mdeb:~$ sudo cat /sys/power/mem_sleep
[sudo] password for ubuntu:
[s2idle] deep
ubuntu@3mdeb:~$ 
```

### Additional context

https://novacustom.com/forum/d/155-questions-regarding-the-upcoming-v54-notebook-and-dasharo-coreboot/2
S3 sleep should not even be supported, that is probably why the option to change it is missing from setup menu, but the result in OS suggests S3 sleep is enabled according to our unified test documentation.

**Comment by mkopec** [comment]
There's probably a flag somewhere telling the OS that S3 is supported, that needs to be disabled. In any case, it also sees the LPIT flag instructing OS to prefer s2idle, so s2idle is used by default.

**Comment by philipandag** [comment]
The same on V540TND with v0.9.1-rc5

**Comment by mkopec** [comment]
SMS was removed from test scope, closing

**Comment by mkopec** [comment]
Removed nonfuctional S3 remnants in commit https://github.com/Dasharo/coreboot/pull/548/commits/ee301898586faf5fc9e2acb026838f522a1cb273
