### ISSUE TITLE
Fn+4 (soft microphone switch) doesn't work on Novacustom MTL V540TU and V560TU

### ISSUE THREAD

**Issue by wiktormowinski** [Dasharo/dasharo-issues#1023]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

v0.9.0

### Brief summary

seems like the mic soft switch key is not implemented yet

### How to reproduce

go to audio settings and oserve the mic activity while trying to toggle the soft switch via Fn+4 key combination

alternatively
on these machines write 
`sudo dmesg -w` 
in terminal
then try the Fn+4 key combination

### Expected behavior

it should be recognized as mic switch

### Actual behavior

in settings combination yields no effect 
on V540TU we get the following message in `dmesg`
[68722.430749] atkbd serio0: Unknown key pressed (translated set 2, code 0x81 on isa0060/serio0).
[68722.430760] atkbd serio0: Use 'setkeycodes e001 <keycode>' to make it known.
[68722.549533] atkbd serio0: Unknown key released (translated set 2, code 0x81 on isa0060/serio0).
[68722.549545] atkbd serio0: Use 'setkeycodes e001 <keycode>' to make it known.
and on V560TU it's just "4"

**Comment by wessel-novacustom** [comment]
Duplicate of https://github.com/Dasharo/dasharo-issues/issues/1006

**Comment by wiktormowinski** [comment]
we won't need that then

**Comment by wessel-novacustom** [comment]
No, but I guess #1006 needs to be assigned to: https://github.com/Dasharo/dasharo-issues/milestone/48

**Comment by macpijan** [comment]
> No, but I guess https://github.com/Dasharo/dasharo-issues/issues/1006 needs to be assigned to: https://github.com/Dasharo/dasharo-issues/milestone/48

Added
