### ISSUE TITLE
V560TND v0.9.1-rc3 USB-C current limiting not triggering Windows

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1026]
### Component

Dasharo firmware, Dasharo Tools Suite

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

--

### Test case ID

UTC020.002

### Brief summary

power draw grows over the adapter's rating and OC protection turns it off

### How reproducible

On Walink 130 W adapter - never, on noname 90 W adapter - 100% if there is a sufficient load 

### How to reproduce

Run both ThrottleStop and Furmark at the same time while connected to the 90 W adapter

### Expected behavior

The power draw should stop at around 80-90 W 

### Actual behavior

It exceeds 90 W and falls back to 0 W in a cycle - the adapters OC protection is triggered

### Additional context

The Walink adapter seems to be fine and is used at 120 W of the rated 130 W but it may just mean that it's rating is sufifcient for powering the laptop at full power. I have not tried stressing both CPU and GPU on Ubuntu yet

**Comment by mkopec** [comment]
USB-PD 3.0 only supports 100W and the laptop will only negotiate a 100W contract, so if it's pulling 120W, it means the dock isn't engaging OCP when it should, so that's also a fail

**Comment by philipandag** [comment]
Fixed in RC4. When connected to 130W Walink adapter 99.9W are pulled, when connected to 80W no-name adapter the power draw reaches up to 81W which is within the error margin.
