### ISSUE TITLE
Power State After Power Failure is in reality Power on AC

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1028]
### Component

Dasharo documentation

### Device

other

### Dasharo version

--

### Dasharo Tools Suite version

--

### Test case ID

PSF

### Brief summary

test documentation and EDK2 setup description is misleading on laptops

### How reproducible

100%

### How to reproduce

Read https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/360-power-after-fail/
or enter Setup menu

### Expected behavior

The documentation and setup menu should describe that the feature does anything when an AC adapter is connected, not when power is restored after failure.

### Actual behavior

It does not suggesting that the power state should be restored for example when battery is disconnected and reconnected

**Comment by mkopec** [comment]
fixed by https://github.com/Dasharo/edk2/pull/169
