### ISSUE TITLE
Touchpad issues on NovaCustom NS70 notebook (two bugs)

### ISSUE THREAD

**Issue by micmarluc** [Dasharo/dasharo-issues#103]
**Dasharo version**
v1.1.0

**Dasharo variant**
NovaCustom NS70MU i5-1135G7

**Affected component(s) or functionality**
Touchpad

**Brief summary**
When you slide your finger on the touchpad, the pointer moves badly, and it is impossible to use several fingers (for example to scroll a web page or to simulate the right click...): it's the first bug.
When this bug is solved (see below), **another bug** often appears: the mouse pointer freezes when your desktop appears...

**How reproducible**
It's very difficult to answer this question!
The first bug appears with almost all linux distributions I tested (Ubuntu, Mint, Manjaro, Fedora). Curiously, this bug appears very frequently (often 100% but not always...) when system partitions are installed on M2 NVMe SSD, and much less often when the same partitions are installed on M2 SATA SSD or 2.5" SATA SSD !
The proposed solution (see below) solves the problem but, randomly, another bug appears: the mouse pointer freezes as soon as the desktop is displayed! You have to use a mouse to unlock it...
I finally noticed that there were apparently no bugs with a fresh install of Ubuntu-Mate with the latest kernel (5.18.0-051800-generic) and with a fresh install of LinuxMint with kernel 5.13 .0-44-generic.

**How to reproduce**

1. Turn on the laptop.
2. When logged in, try using the touchpad

**Expected behavior**
When using the touchpad, the pointer moves smoothly and stops exactly where you want it. If we use two fingers, we can simulate the right click, or we can scroll a page on the screen...

**Actual behavior**
When using the touchpad, the pointer moves poorly and it is difficult to bring it to a specific location. In addition, it is impossible to use several fingers (right click, scrolling pages, etc.). When this bug is fixed, another bug often appears: the mouse pointer freezes as soon as the desktop is displayed. 

**Screenshots**

**Additional context**

**Solutions you've tried**
- Open the /etc/default/grub file as root
- Replace "quiet splash" by "quiet splash modprobe.blacklist=psmouse" and save the file
- Update grub: `sudo update-grub`
- Reboot the computer
Then the first bug is solved (correct movement of the pointer, use of several fingers...), but unfortunately the second bug often appears (freeze of the pointer) and for this second bug, I don't know any solution.

- Note that if I use a fresh install of Ubuntu-Mate with the latest kernel (5.18.0-051800-generic) and with a fresh install of LinuxMint with kernel 5.13.0-44-generic, it seems that there is no bug, the "modprobe.blacklist=psmouse" option is not even necessary.

- Also note that the "modprobe.blacklist=psmouse" option works well if you are using rEFInd instead of Grub to boot directly to the linux kernel (use the F2 key to add the option)

**Comment by wessel-novacustom** [comment]
I have had contact with @micmarluc. We should be sure that we are using the same firmware binary, especially the ME region, as some sold units might have been dispatched with an Intel ME version that is officially not compatible. We will be back soon with a procedure to make sure that you have the right ME version, as having the right ME version might solve the problem.

**Comment by wessel-novacustom** [comment]
@micmarluc I think the issue has been completed now with [this documented post-installation step](touchpad-multi-touch-support). Could you close the ticket, please?
