### ISSUE TITLE
V560TNE ACPI Errors when waking from suspend

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1032]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc4

### Dasharo Tools Suite version

--

### Test case ID

SUSP005.001

### Brief summary

After waking the laptop once showed ACPI errors and then keyboard stopped working

### How reproducible

Only one time

### How to reproduce

No idea. I was just running the SUSP005.001 automatic test and tried to login to Ubuntu after that

### Expected behavior

There should not be any errors and all basic functionality should work after waking from suspend

### Actual behavior

The keyboard stopped working, the screen freezed for about 15 seconds and then only the touchpad worked.

### Screenshots

![first encountered errors](https://github.com/user-attachments/assets/2a70cc6a-9288-4ef0-b215-cac087612ec1)
![longer output after a while](https://github.com/user-attachments/assets/b44181de-5e95-46d0-a0f4-c1ae6a24e687)

### Additional context

I tried pressing `Suspend` in the UI which resulted in weird state where the login screen was still visible but the power LED was blinking as if the laptop was supended. Then the same ACPI errors flashed for a fraction of second and the screen went black. The laptop stopped responding to any input. After a couple seconds of pressing the keyboard and touching the touchpad the errors appeared again and the output was longer.

### Solutions you've tried

After an EC reset the device seems to work fine.

**Comment by philipandag** [comment]
After updating to kernel 6.9 The device wakes up fine but there are errors from fwts:
[platform-suspend-and-resume.robot_log.zip](https://github.com/user-attachments/files/16814199/platform-suspend-and-resume.robot_log.zip)

**Comment by mkopec** [comment]
The ACPI errors are gone on Ubuntu 24.10 / Linux v6.11.

If the suspend issues appear in the next RC, we can create a separate issue for that.
