### ISSUE TITLE
V560TNE Intel ME lspci entry name is wrong

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1034]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc4

### Dasharo Tools Suite version

--

### Test case ID

MNE002.001

### Brief summary

lspci entry with id 00:16:0 is not Intel ME

### How reproducible

100%

### How to reproduce

run `lspci | grep 00:16:0` with Intel ME enabled

### Expected behavior

should find an entry like:
`00:16:0 Intel Corporation Meteor Lake Management Engine Interface`

### Actual behavior

there is an entry:
`00:16:0 Communication controller: Intel Corporation Device 7e70 (rev20)`

### Additional context

I believe the name on the right of the device ID is determined by mapping the device ID to some table of names. This may be an error with this table in the OS, not with the ME.

### Solutions you've tried

rebooting

**Comment by zirblazer** [comment]
That is entirely OS side, it should have some kind of PCI DeviceID name database. It knows that the PCI VendorID is Intel Corporation, but the DeviceID 7E70 has no actual name associated to it, so it just displays the hex ID.

According to datasheet: https://www.intel.com/content/www/us/en/content-details/792044/intel-core-ultra-processor-datasheet-volume-1-of-2.html
PCI DeviceID 7E70h located at 00:16.0 (22 in decimal) should be called Intel CSME: HECI #1. But again, knowing that is on OS side.

**Comment by philipandag** [comment]
Thanks for pointing to the documentation. It sorts out my problem. I wonder if the issue should just be closed or forwarded somewhere else.

**Comment by mkopec** [comment]
Try `lspci -q` to pull in the latest PCI ID database.

This is an OS issue and not firmware, @philipandag please open an issue in the osfv repo
