### ISSUE TITLE
Integrate dTPM with HAP enabled in EDK/UEFI on MSI boards 

### ISSUE THREAD

**Issue by MykeHalk** [Dasharo/dasharo-issues#1039]
### The problem you're addressing (if any)

The dTPM is also disabled when HAP bit enabled.

### Describe the solution you'd like

I noticed that this a feature in the heads firmware, would it be possible to integrate it into the UEFI firmware as well? When HAP is enabled check header for dTPM. Not sure if there are some conflicts I am unaware about that allows heads to have this feature and not EDK payload. 

### Where is the value to a user, and who might that user be?

Not sure but first thing that comes to mind is some games are starting to require Secure Boot and TPM to be enabled to play them.

Some people might want to have ME disabled so they can sleep at night knowing that its one less attack surface that they don't have to worry about but still have a discrete TPM for instances that require it. Heads also does not implement secure boot afaik.

I feel like this would benefit an average users that is slightly security focused but does not want to compromise functionality of his system.

### Describe alternatives you've considered

Using heads itself but it does not support secure boot so its trading on thing for another.

**Comment by miczyg1** [comment]
It was already done when releasing heads variant. it is not available for UEFI just because there was no release for UEFI variant.

**Comment by PapiJalopy** [comment]
> it is not available for UEFI just because there was no release for UEFI variant.

Could you explain what you mean by this? Are we not able to integrate this into EDK2 for MSI Z790-P boards?

**Comment by miczyg1** [comment]
> Could you explain what you mean by this? 

dTPM support has been added after v0.9.1 version has been released. So if you would like to use dTPM, you would have to build the binary yourself from `dasharo-4.21` branch on coreboot repository

**Comment by SergiiDmytruk** [comment]
I don't think it's out of scope, but looks like I need to update configuration a bit to enable it (thought it's automatic).  This is a very early preparation for upcoming releases (tags will move, testing hasn't started yet), so thanks for pointing this out right away @MykeHalk.  I've updated https://github.com/Dasharo/coreboot/pull/565 with changes that should enable dTPM if you're eager to test it.
