### ISSUE TITLE
V540TND keyboad illumination changes on coldboot

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1055]
### Component

Dasharo firmware, EC firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.1-rc5

### Dasharo Tools Suite version

--

### Test case ID

ECR25

### Brief summary

The keyboard backlight setting changes after a coldboot

### How reproducible

100% in 2 tries on Ubuntu and 2 tries on Windows

### How to reproduce

Boot an OS, change backlight setting (alternating turned off and full brightness is the easiest to notice), disconnect all external power supplies and disconnect the battery. Connect the battery back, boot into an OS

### Expected behavior

The backlight setting from before the coldboot should remain

### Actual behavior

The backlight setting changes. In all tests the default was off and I have changed it to the max brightness. After coldboot it's always back to being off.

### Screenshots

cbmem logs from Ubuntu, for `-2` (boot before coldboot) and `-1` (the coldboot)
[cbmem-keyboard-backlight-1.log](https://github.com/user-attachments/files/17010188/cbmem-keyboard-backlight-1.log)
[cbmem-keyboard-backlight-2.log](https://github.com/user-attachments/files/17010189/cbmem-keyboard-backlight-2.log)

**Comment by mkopec** [comment]
No need to disconnect the battery to perform a coldboot. Just shut down, unplug wall adapter and wait a second.

The EC saves settings upon (graceful) shutdown, so you have to go through the proper shutdown, instead of hot-removing AC and battery completely

**Comment by philipandag** [comment]
Does it mean that the AC needs to be plugged in for a warmboot and without it the os shutdown results in a coldboot? In that case the Dasharo test specification needs updates because it says to remove the battery. 
https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio/#ecr025001-permanent-keyboard-illumination-after-cold-boot-firmware

**Comment by mkopec** [comment]
Power states explained in https://docs.dasharo.com/transparent-validation/ec-information/ec-explained/ , closing
