### ISSUE TITLE
Docking station sometimes prevents entering S0ix

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1056]
### Component

Dasharo firmware, EC firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.1-rc5

### Dasharo Tools Suite version

--

### Test case ID

UTC011.004

### Brief summary

The laptop wakes up from suspend, plays USB plug in/out sounds

### How reproducible

Happened only once and I couldn't reproduce it again in three retries.

### How to reproduce

Suspend the laptop with the docking station connected. The docking station has an audio jack, a USB keyboard, two USB flashdrives, Ethernet cable and a Display Port display connected via usb-c.

### Expected behavior

The device should enter suspend (power diode blinking rhythmically) after a while and wake up after pressing some key / touching the touchpad etc. 

### Actual behavior

The power diode was blinking irregularly, sometimes the ON state was shorter, sometimes it was so long I tought the device mighy have woken up from suspend. The irregularities in the blinking were accompanied by the sounds of a USB device being plugged out and plugged in immediately after the "out" sound ended.

### Additional context

 I haven't recorded this phenomenon. Probably the issue should be closed after a while if no one else experiences this behavior because I have no idea how to reproduce it.

**Comment by mkopec** [comment]
> The power diode was blinking irregularly

so the OS is constantly entering and exiting S0ix

> The irregularities in the blinking were accompanied by the sounds of a USB device being plugged out and plugged in immediately after the "out" sound ended.

maybe some device is disconnecting on s0ix entry, which then wakes up the device? hard to say without logs

**Comment by mkopec** [comment]
Need `cbmem -1` and `dmesg `logs here

**Comment by filipleple** [comment]
Managed to get the `SUSP005` S0ix suspend test to pass on V540TND rc-7 with the docking station plugged in
