### ISSUE TITLE
USB-C port doesn't work on NV41MZ

### ISSUE THREAD

**Issue by ghost** [Dasharo/dasharo-issues#106]
**Dasharo version**
v1.1.0

**Dasharo variant**
I actually don't know (where can you check that?).

**Affected component(s) or functionality**
The driver for the USB-C/Thunderbolt port.

**Brief summary**
I have a dual-boot Windows/Kubuntu setup on an NV41MZ, and unlike what issue #61 claims, Thunderbolt does **not** work for me. In Linux, Plasma's Thunderbolt settings simply says "Thunderbolt subsystem not initialized", while Windows gives a -12 (insufficient resources) error on the Thunderbolt port, as well as a few other device errors on other USB devices that I don't quite remember, but which are probably related.

**How reproducible**
For me, it's almost 100% reproducible: I tried to connect an external GPU to the computer, which doesn't work at all on Linux.
On Windows, I managed to get the OS to recognize it exactly once (though I have no idea what I did differently that time, if anything), but when I tried to run a program on it, it froze constantly.

**How to reproduce**

1. Connect a device to the USB-C port.
2. Nothing happens.

**Expected behavior**
The USB-C port should work normally.

**Actual behavior**
Most of the time, neither Windows nor Linux recognizes any device connected to the port.

**Screenshots**
I don't have any available right now, but if you need it, I can add some Windows Device Manager screenshots later.

**Additional context**
N/A

**Solutions you've tried**
 I tried to connect an external SSD to the same port to see if it was just Thunderbolt, but the OS didn't recognize that, either.

**Comment by wessel-novacustom** [comment]
I see, thank you.

We will have to replace your motherboard and verify the USB-C connection. I am sorry for this inconvenience.

We have had email contact today. Could you please email me your current address? We will then supply you a return label and instructions to send your device back to us for repair.

**Comment by wessel-novacustom** [comment]
The laptop was applied for warranty. We will close the ticket if it turns out to be a hardware issue.

**Comment by wessel-novacustom** [comment]
Windows showing one problematic ACPI device in Device Manager is a known problem.

There is an ongoing discussion about this, which can be followed [here](https://github.com/Dasharo/dasharo-issues/issues/57).
