### ISSUE TITLE
Intel Serial IO I2C Host Controller - Device Manager error code 10

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#1065]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc5

### Brief summary

Device Manager reports error code 10 for the Intel Serial IO I2C Host Controller

### How reproducible

100% reproducible.

### How to reproduce

1. Flash Dasharo v0.9.0-rc5 on the V560TNE including the belonging Dasharo EC.
2. Install Windows, including all updates and optional updates.
3. Check the Device Manager for devices showing errors.

### Expected behavior

No devices are listed with errors.

### Actual behavior

The Intel Serial IO I2C Host Controller reports error 10:
_STATUS_DEVICE_POWER_FAILURE_

### Screenshots

![grafik](https://github.com/user-attachments/assets/01f34d48-5329-4c59-91d2-48a357e43e8b)

### Additional context

We haven't tested `v0.9.1-rc6` yet.

**Comment by mkopec** [comment]
Can't reproduce on rc6, @wessel-novacustom can you confirm if it happens on rc6 too?

**Comment by wessel-novacustom** [comment]
@mkopec solved with `rc6`.
