### ISSUE TITLE
On external HDMI display isn't video output NV41MZ v1.2.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#107]
**Dasharo version**
v.1.2.0

**Dasharo variant**
Clevo NV41MZ

**Affected component(s) or functionality**
External HDMI display

**Brief summary**
On external HDMI display isn't video output .

**How reproducible**
100%

**How to reproduce**

1. Connect Monitor with the DUT via HDMI cable.

**Expected behavior**
The image should be displayed on the external HDMI display.

**Actual behavior**
On external HDMI display isn't video output .

**Screenshots**

**Additional context**
Windows 11

**Solutions you've tried**
3 different cables and 2 different monitors.

**Comment by mkopec** [comment]
Intel iGPU driver was missing
