### ISSUE TITLE
Zooming and scrolling via Touchpad aren't detected correctly NV41MZ v1.2.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#108]
**Dasharo version**
v.1.2.0

**Dasharo variant**
Clevo NV41MZ

**Affected component(s) or functionality**
Touchpad

**Brief summary**
Touchpad isn't fully functional

**How reproducible**
100%

**How to reproduce**

1. Open C:\Windows in Windows Explorer.
2. Scrolling with 2 fingers to move the content of the window.
3. Pinching with 2 fingers to zoom in and zooms out the content.

**Expected behavior**
Zooming and scrolling are detected correctly by the operating system.

**Actual behavior**
Scrolling and pinching with 2 fingers didn't work

**Screenshots**

**Additional context**
Windows 11

**Solutions you've tried**

**Comment by mkopec** [comment]
Were the I2C drivers installed when testing? I've installed all the drivers from Windows Update and multitouch started working for me.

@macpijan Maybe we should add a test setup step to run Windows Update and ensure all the drivers are installed before testing anything else

**Comment by Pokisiekk** [comment]
@mkopec I just install Windows 11 and future to ssh connection, nothing more.

**Comment by mkopec** [comment]
Fixed by installing Intel I2C drivers
