### ISSUE TITLE
V540TND v0.9.1-rc6: Triple display support fails

### ISSUE THREAD

**Issue by SebastianCzapla** [Dasharo/dasharo-issues#1082]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.1-rc6

### Test case ID

UTC007.005

### Brief summary

Echo11 docking station fails to provide output for 3 screens

### How reproducible

100%

### How to reproduce

Connect Echo11 docking station to the DUT.
Into the 3 usb-c ports, connect 3 screens using these connectors:
USB-C to HDMI cable
USB-C to DP cable
USB-C to VGA cable

### Expected behavior

All three screens output display.

### Actual behavior

VGA screen outputs video while in firmware, once loaded into Ubuntu, VGA screen no longer works, and works only if DP cable is disconnected

**Comment by miczyg1** [comment]
The specs say that up to two 5K displays are possible: https://www.sonnettech.com/product/echo11-thunderbolt4-dock/overview.html

There are some limitations in this PDF as well: https://www.sonnettech.com/support/downloads/manuals/Thunderbolt_4_Dock_Compatibility.pdf

So it is not necessarily dock or FW failure.

**Comment by miczyg1** [comment]
The manual: https://www.sonnettech.com/support/downloads/manuals/echo_11_tb4_dock_qsg.pdf
Says:

`Although the dock supports connection of up to two displays via Thunderbotl ports...`

**Comment by SebastianCzapla** [comment]
According to documentation provided by Michał, dock's tested display capability is valid, two display setup worked with all combiations of these connections:
USB-C to HDMI cable
USB-C to DP cable
USB-C to VGA cable

Three display test should be removed from the testing scope.
Issue to might be closed

**Comment by mkopec** [comment]
triple display with USB4 tunneling without an MST hub won't work. USB4 carries two full DP links, no more.
