### ISSUE TITLE
Various issues with cbmem on Dell OptiPlex 7010

### ISSUE THREAD

**Issue by SebastianCzapla** [Dasharo/dasharo-issues#1084]
### Component

other

### Device

Dell OptiPlex 7010

### Dasharo version

v0.1.0 (EDK2 with TXT)

### Brief summary

cbmem -L and cbmem -1 experience issues with exceeding log size

### How reproducible

100%

### How to reproduce

Build cbmem from source or get it from cloud
cd coreboot/util/cbmem && make

Run cbmem -L or cbmem -1 as root on Optiplex 7010

### Expected behavior

cbmem -L prints finite log entries
cbmem -1 prints full log from last boot

### Actual behavior

cbmem -L -> last log entry has event data that takes almost ~45kB of hex data, with segfault at the end
cbmem -1 -> has truncated output

### Additional context

[optiplex-cbmem-various-logs.zip](https://github.com/user-attachments/files/17328507/optiplex-cbmem-various-logs.zip)

### Solutions you've tried

Building cbmem from optiplex branch, building it from dasharo branch, using cbmem from cloud, all fail the same way

**Comment by miczyg1** [comment]
`*** Pre-CBMEM romstage console overflowed, log truncated! ***` is a cause of HW limitation.

There is a limit how much info you can save from pre-RAM boot logs. Cache is finite and small, and it's main purpose is to get code executed, rather than store some log data. So this one is not fixable.

Regarding the `cbmem -L` this might be a bug in coreboot or cbmem itself. The TPM log should be properly terminated to be parsed properly, or cbmem should detect invalid entries...

**Comment by miczyg1** [comment]
https://review.coreboot.org/c/coreboot/+/84926

**Comment by philipandag** [comment]
Using cbmem built from https://review.coreboot.org/c/coreboot/+/84926 I'm getting some output. 

```
ubuntu@3mdeb:~/coreboot/util/cbmem$ sudo ./cbmem -L
[sudo] password for ubuntu: 
TCPA log:
	Specification: 1.21
	Platform class: PC Client
TCPA log entry 1:
	PCR: 2
	Event type: Action
	Digest: cf11730b6290e3ad42e0753f436edfe1612ec0fc
	Event data: FMAP: FMAP
TCPA log entry 2:
	PCR: 2
	Event type: Action
	Digest: 1492d8863c7ae484a3042c78e361293a7e127fd6
	Event data: CBFS: bootblock
TCPA log entry 3:
	PCR: 2
	Event type: Action
	Digest: c1922cd3de966dc40257073496ae306ee0ffa1f6
	Event data: CBFS: cmos.default
TCPA log entry 4:
	PCR: 2
	Event type: Action
	Digest: 512ba90b9fa643744748aa9065862695321a44a5
	Event data: CBFS: fallback/romstage
TCPA log entry 5:
	PCR: 2
	Event type: Action
	Digest: fd2b3cf1bd64b3928ffc916d7799c76e5fa96de0
	Event data: CBFS: cmos_layout.bin
TCPA log entry 6:
	PCR: 2
	Event type: Action
	Digest: 44ea2be7b0f459f129e42124be9a1622f6f3b2e9
	Event data: CBFS: fallback/postcar
TCPA log entry 7:
	PCR: 2
	Event type: Action
	Digest: 8efffbbf487c06d4328ce4fbba2314554f2a2925
	Event data: CBFS: cpu_microcode_blob.bin
TCPA log entry 8:
	PCR: 2
	Event type: Action
	Digest: ea3f3ba2449d59b7cf13ee645d640ba6a018acad
	Event data: CBFS: vbt.bin
TCPA log entry 9:
	PCR: 2
	Event type: Action
	Digest: d599814817d3b807dfb4abc462b4606fac62b4c9
	Event data: CBFS: fallback/dsdt.aml
TCPA log entry 10:
	PCR: 2
	Event type: Action
	Digest: fd2b3cf1bd64b3928ffc916d7799c76e5fa96de0
	Event data: CBFS: cmos_layout.bin
TCPA log entry 11:
	PCR: 2
	Event type: Action
	Digest: 3b14fb8ffb3515c4b42b11f46687915cb6a500a0
	Event data: CBFS: fallback/payload
Invalid TPM1.2 log entry overflowing cbmem area
```

**Comment by miczyg1** [comment]
This patch fixes the non-zero TPM log: https://review.coreboot.org/c/coreboot/+/84927/

**Comment by SebastianCzapla** [comment]
Fixed and tested, as mentioned above, closing
