### ISSUE TITLE
Custom Secure Boot key enrollment

### ISSUE THREAD

**Issue by ghost** [Dasharo/dasharo-issues#1088]
### The problem you're addressing (if any)

Currently, Dasharo firmware does not allow a user to enroll their own custom Secure Boot keys which can be problematic for users who want to control their own keys for Secure Boot.

### Describe the solution you'd like

Allow users to enrol their own custom Secure Boot keys.

### Where is the value to a user, and who might that user be?

Any user who wants to control their own keys instead of trusting the OEM to properly manage their Secure Boot keys.

**Comment by pietrushnic** [comment]
@duck09 can you explain what you tried and what hardware?

Did you read this https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration ?
