### ISSUE TITLE
Incorrect Optiplex documentation: Initital deployment documentation has several minor mistakes

### ISSUE THREAD

**Issue by ixf4regnio** [Dasharo/dasharo-issues#1089]
### Component

Dasharo documentation

### Device

Dell OptiPlex 7010, Dell OptiPlex 9010

### Brief summary

cbfstool command has identical -n txt_bios_acm.bin for both vendor roms

### How to reproduce

https://docs.dasharo.com/variants/dell_optiplex/initial-deployment/#firmware-preparation has a potential copy&paste error at the `-n` parameter (both `txt_bios_acm.bin`):
```
cbfstool coreboot.rom add -f IVB_BIOSAC_PRODUCTION.bin -n txt_bios_acm.bin -t raw
cbfstool coreboot.rom add -f SNB_IVB_SINIT_20190708_PW.bin -n txt_bios_acm.bin -t raw
```

Above, the `EC firmware` and `BIOS ACM file` file paths include whitespaces which screws up pasting the lines. This might be intended, but I don't see why it would be?! :thinking: 

### Expected behavior

Different values for the `-n` parameter should be provided

### Actual behavior

Same values are disencouraging to try this

### Additional context

Not much to say about this, sorry.

### Solutions you've tried

Thought about using `-n txt_bios_snb.bin` for the second rom, but being unable to find good documentation about this step I was too afraid of bricking my device and instead decided to ask for your help.

**Comment by miczyg1** [comment]
@ixf4regnio obviously, these errors and whitespaces are not intended.

https://github.com/Dasharo/docs/pull/920

Let me know if these are all mistakes you have found.

**Comment by ixf4regnio** [comment]
Hi @miczyg1,

thanks for your quick response and action. You actually found two whitespace misses I didn't see :sweat_smile: The ones I meant which are in lines 134 and 140, look for `"-3fe3- 42a0-"`. Might be a markup rendering error, but in the final document you cannot copy and paste those lines without getting an error.

Thanks for your work and best regards.

**Comment by ixf4regnio** [comment]
@miczyg1 

Just FYI: Using your corrections from the [linked PR](https://github.com/Dasharo/docs/pull/920), I was able to successfully flash my Optiplex 7010 SFF on the weekend :tada:

**Comment by ixf4regnio** [comment]
Closing this as resolved (once the PR is merged)
