### ISSUE TITLE
Touchpad responsiveness V56 Series

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#1090]
### Component

Dasharo firmware, EC firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0

### Brief summary

The touchpad is not very precise can be buggy when the CPU load is high

### How reproducible

100% reproducible

### How to reproduce

1. Install Qubes OS and login.
2. Cause a high CPU load, for example by starting multiple Qubes.
3. When one Qube has started while the others are still starting, try to use the touchpad with some precise tasks like increasing the window.

### Expected behavior

1. The touchpad always responses in the same way, not depending on the CPU load.
2. The touchpad is precise and you can easily move to the window's corner to increase the window.

### Actual behavior

1. The touchpad has a buggy responsiveness when the CPU load is high. 
2. The touchpad is either moving fast or not moving at all. It seems to under track and then over track and does not sense small movements maybe fine work difficult.

### Additional context

I'm not sure if this can be improved by firmware. The 1st point of the _Actual behavior_ list can possible be EC related?
The V54 Series seems to behave better, more precisely.

**Comment by wessel-novacustom** [comment]
> I cannot reproduce the issue... I tried creating and then starting 20 VMs, and run tight loop inside to generate CPU load, yet touchpad remained responsive the whole time.
> Details
> 
> ```
> for i in {01..20}; do qvm-create -l red test$i; done
> for i in {01..20}; do qvm-run test$i "while true; do true; done" & : ; done
> ```

- Thank you for trying! What kernel were you using? Do you have Q-HD+ or F-HD+?

**Comment by marmarek** [comment]
If you can reproduce it reliably, try `xl sched-credit2 -d 0 -w 512` or even `-w 1024` - does it help?

**Comment by mkopec** [comment]
@wessel-novacustom The affected unit may have a different touchpad model that we haven't seen, and so it may work over legacy PS/2 instead of I2C.

Could you run https://github.com/Dasharo/dts-scripts/blob/main/reports/touchpad-info on Linux? It's included in DTS so that's probably easiest

**Comment by wessel-novacustom** [comment]
> @wessel-novacustom The affected unit may have a different touchpad model that we haven't seen, and so it may work over legacy PS/2 instead of I2C.
> 
> Could you run https://github.com/Dasharo/dts-scripts/blob/main/reports/touchpad-info on Linux? It's included in DTS so that's probably easiest, or on Ubuntu if that doesn't work

I don't think it's legacy PS/2 since two finger scrolling is still working, which I think is never with legacy PS/2.

The touchpad is working fine most of the time, just not under very specific circumstances like a high CPU load.

> If you can reproduce it reliably, try `xl sched-credit2 -d 0 -w 512` or even `-w 1024` - does it help?

I will try soon.

**Comment by wessel-novacustom** [comment]
> > @wessel-novacustom The affected unit may have a different touchpad model that we haven't seen, and so it may work over legacy PS/2 instead of I2C.
> > Could you run https://github.com/Dasharo/dts-scripts/blob/main/reports/touchpad-info on Linux? It's included in DTS so that's probably easiest, or on Ubuntu if that doesn't work
> 
> I don't think it's legacy PS/2 since two finger scrolling is still working, which I think is never with legacy PS/2.
> 
> The touchpad is working fine most of the time, just not under very specific circumstances like a high CPU load.
> 
> > If you can reproduce it reliably, try `xl sched-credit2 -d 0 -w 512` or even `-w 1024` - does it help?
> 
> I will try soon.

@marmarek It helps, the touchpad is way more predictable.

Do you know if I can use the same command on other distros like Ubuntu and Fedora?

**Comment by marmarek** [comment]
No, this one is very specific to Qubes (or other Xen systems)
