### ISSUE TITLE
Multiple broken links in documentation

### ISSUE THREAD

**Issue by krystian-hebel** [Dasharo/dasharo-issues#1092]
### Component

Dasharo documentation

### Device

Protectli FW6, Protectli VP2410, Protectli VP2420, Protectli VP4630, Protectli VP4650, Protectli VP4670, Protectli VP6630, Protectli VP6650, Protectli VP6670, other

### Brief summary

Review done before merging PRs to documentation is inadequate. Output of `mkdocs serve` shows a warning for each broken link, but it is hidden between a few hundred `INFO` lines.

### How to reproduce

Click on `Releases` on https://docs.dasharo.com/unified/protectli/overview/#fw6

### Expected behavior

Browser navigates to list of releases.

### Actual behavior

404

### Additional context

https://paste.dasharo.com/?c7e5b8307c34a8ed#7HZvr9UpGctQxiXiSCe35cQNXJhKrdGJfgoRgzrvYojc - this is an output of `mkdocs serve` on current `master`. It has 300 informative lines about absolute links (which most likely will break when the files are moved around, e.g. to unified directory) and 22 warnings about broken links. Not all of the warnings are printed at the end, so one has to scroll the screen through all the `INFO` noise to notice them.

### Solutions you've tried

Similar issue happened when I was working on TrenchBoot documentation, the easy-but-tedious solution is to do what `mkdocs` suggests and [change all absolute links to relative ones](https://github.com/TrenchBoot/TrenchBoot.github.io/commit/c52b72b397cee35e9243a5ee56ddaf603ba8e8cb). This will get rid of almost all of the `INFO`s (only last few lines are left, with time summary and link to local preview), which makes it easier to focus on real issues.

Another part of the problem is that we currently don't demand from neither authors nor reviewers to check the output of `mkdocs serve`. This can be fixed by adding instruction to README, e.g. [like this one](https://github.com/TrenchBoot/TrenchBoot.github.io/commit/7e8a06ce9b52bee2cda44d57baf9b5a10ef8ca87).

**Comment by macpijan** [comment]
> Another part of the problem is that we currently don't demand from neither authors nor reviewers to check the output of mkdocs serve. This can be fixed by adding instruction to README, e.g. [like this one](https://github.com/TrenchBoot/TrenchBoot.github.io/commit/7e8a06ce9b52bee2cda44d57baf9b5a10ef8ca87).

Sound like could be added to CI checks as well?

**Comment by krystian-hebel** [comment]
> Sound like could be added to CI checks as well?

Yes, if possible.

**Comment by macpijan** [comment]
OTOH

![image](https://github.com/user-attachments/assets/98edea2b-1c82-4e20-b5d4-cac6a0bcc342)

Do you think we need the links on the right in body, if we have the same links in navigation tab on the left?

**Comment by krystian-hebel** [comment]
Probably not, but it would be empty without those, and other platforms have more content in these tabs.

**Comment by macpijan** [comment]
@BeataZdunczyk We have to handle that, please review these pages, I am in favor of removing the duplicate links since we already have them in the navigation tab. Especially if it would simplify the work to be done with relative links as suggested by Krystian.

**Comment by miczyg1** [comment]
```
[33mWARNING -  [0mRedirect target 'unified/protectli/releases.md#fw6' does not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/releases.md#v1000-series' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/releases.md#vp46xx' does not
           exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/releases.md#vp66xx' does not
           exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/releases.md#vp2410' does not
           exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/releases.md#vp2420' does not
           exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/building_manual.md#fw6' does not
           exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/building_manual.md#v1000-series'
           does not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/building_manual.md#vp46xx' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/building_manual.md#vp66xx' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/building_manual.md#vp2410' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/building_manual.md#vp2420' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/firmware_update.md#fw6' does not
           exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/firmware_update.md#v1000-series'
           does not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/firmware_update.md#vp46xx' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/firmware_update.md#vp66xx' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/firmware_update.md#vp2410' does
           not exist!
[33mWARNING -  [0mRedirect target 'unified/protectli/firmware_update.md#vp2420' does
           not exist!
```

Not sure about this one but rediretcs are working. Maybe the syntax should be different...

I have already fixed a couple of rebase/squash mistakes for the PR 851 already:
https://github.com/Dasharo/docs/pull/902
https://github.com/Dasharo/docs/commit/7be93ba5b90761509e02b0c1497300535aa54bd7 (when noticed old links give 404).

**Comment by filipleple** [comment]
So far I've managed to get it down to 
```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - variants/hardware-compatibility-list.md
  - variants/msi_z690/building-manual.md
  - variants/msi_z690/cpu-hcl.md
  - variants/msi_z690/development.md
  - variants/msi_z690/faq.md
  - variants/msi_z690/firmware-update.md
  - variants/msi_z690/gpu-hcl.md
  - variants/msi_z690/initial-deployment.md
  - variants/msi_z690/memory-hcl.md
  - variants/msi_z690/openness_analysis.md
  - variants/msi_z690/overview.md
  - variants/msi_z690/recovery.md
INFO    -  Doc file 'unified-test-documentation/dasharo-compatibility/320-fwupd-firmware-update.md' contains an absolute link '/unified/novacustom/fwupd-usage', it was left as is.
INFO    -  Doc file 'unified-test-documentation/dasharo-compatibility/320-fwupd-firmware-update.md' contains an absolute link '/unified/novacustom/fwupd-usage', it was left as is.
INFO    -  Documentation built in 5.65 seconds
INFO    -  [19:16:30] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [19:16:30] Serving on http://127.0.0.1:8000/
INFO    -  [19:16:34] Browser connected: http://127.0.0.1:8000/unified/protectli/overview/
INFO    -  Shutting down...
```

**Comment by filipleple** [comment]
All problems gone as of https://github.com/Dasharo/docs/pull/924
