### ISSUE TITLE
V56: Wrong model identifier

### ISSUE THREAD

**Issue by jans23** [Dasharo/dasharo-issues#1102]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Brief summary

The model identifier shows V54x_6x_TU wrongly

### How to reproduce

Open the configuration dialogue of Dasharo firmware and look at the model displayed at the top left.

### Expected behavior

It should show a model starting with "V56..."

### Actual behavior

It shows model "V54x_6x_TU" eventhough it is a V56.

### Screenshots

![IMG_20241020_073526900](https://github.com/user-attachments/assets/91c1c477-c6e8-441c-9122-899e8b6a422c)

**Comment by mkopec** [comment]
The identifier V54x_6x_TU stands for V54xTU AND V56xTU. Note that this is to ensure Windows Update can autoinstall the OEM's drivers automatically - if they didn't match the OEM's identifiers, WU not recognize it as the same board.

**Comment by jans23** [comment]
Ahh, the second part "6x" means "V56"? Not very intuitive to me...

**Comment by wessel-novacustom** [comment]
Windows Updates are important for our customers and I didn't realise that this was the reason that the model string was not changed. Please close the issue.

**Comment by mkopec** [comment]
SMBIOS Mainboard Version is set correctly on these models, maybe we could extend the BIOS setup screen to print those instead
