### ISSUE TITLE
UUID, Serial, Logo change not supported by the coreboot image

### ISSUE THREAD

**Issue by JanPrusinowski** [Dasharo/dasharo-issues#1109]
### Component

Dasharo firmware

### Device

Protectli VP3230

### Dasharo version

v0.9.0-rc2

### Dasharo Tools Suite version

develop

### Test case ID

DCU - Suite

### Brief summary

UUID, Serial, Logo change not supported by the coreboot image

### How reproducible

100%

### How to reproduce

run: `robot -v snipeit:no -L TRACE -v rte_ip:192.168.10.35 -v config:protectli-vp3230 -v sonoff_ip:192.168.10.27 -v device_ip:192.168.10.40 -v fw_file:./protectli_vp32xx_v0.9.0_rc2.rom dasharo-compatibility/dcu.robot`

### Expected behavior

Serial, UUID and Logo can be changed by the dcu and tests pass

### Actual behavior

All of the tests fail.

### Screenshots

[log - DCU - Fails.zip](https://github.com/user-attachments/files/17517983/log.-.DCU.-.Fails.zip)
![image](https://github.com/user-attachments/assets/c2910922-8ec4-42d2-9c02-40dee3787d4b)
![image](https://github.com/user-attachments/assets/c2c51d0f-b94c-4b34-aa0b-11898e68c754)
![image](https://github.com/user-attachments/assets/491bd34a-53ea-4637-8217-8d5218289355)
![image](https://github.com/user-attachments/assets/ce00f3c0-316d-4977-977f-b895358d32b1)

### Additional context

`/sys/firmware/acpi/bgrt/image` is not created and cant be checked. So logo is not changed. However DCU reports a success when changing the logo in fw.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/coreboot/pull/584

Logo change is supported, however if the display was nto working, the logo was not displayed, thus BGRT table was not present. PR fixes the display as well as enables S/N and UUID customization

**Comment by SebastianCzapla** [comment]
```bash
sczapla in /opt/dasharo/osfv/core/dcu on main λ ./dcuc logo /opt/dasharo/firmware/releases/protectli_vp32xx_adln/v0.9.0-rc4/protectli_vp32xx_v0.9.0_rc4.rom -l logo.bmp 
/opt/dasharo/firmware/releases/protectli_vp32xx_adln/v0.9.0-rc4/protectli_vp32xx_v0.9.0_rc4.rom: No such file or directory
BOOTSPLASH region not found
Customizable logo not supported by the /opt/dasharo/firmware/releases/protectli_vp32xx_adln/v0.9.0-rc4/protectli_vp32xx_v0.9.0_rc4.rom image
```

**Comment by miczyg1** [comment]
Freshly downloaded from our cloud:

```
cbfstool protectli_vp32xx_v0.9.0_rc4.rom layout -w
This image contains the following sections that can be accessed with this tool:

'SI_ALL' (read-only, size 5242880, offset 0)
'SI_DESC' (size 4096, offset 0)
'SI_ME' (size 5238784, offset 4096)
'SI_BIOS' (read-only, size 11534336, offset 5242880)
'SMMSTORE' (preserve, size 262144, offset 5242880)
'RW_MISC' (read-only, size 294912, offset 5505024)
'UNIFIED_MRC_CACHE' (read-only, size 262144, offset 5505024)
'RECOVERY_MRC_CACHE' (size 131072, offset 5505024)
'RW_MRC_CACHE' (size 131072, offset 5636096)
'RW_VPD' (preserve, size 8192, offset 5767168)
'RW_NVRAM' (preserve, size 24576, offset 5775360)
'BOOTSPLASH' (CBFS, size 524288, offset 5799936)
'RW_SECTION_A' (read-only, size 5210112, offset 6324224)
'VBLOCK_A' (size 65536, offset 6324224)
'FW_MAIN_A' (CBFS, size 5144320, offset 6389760)
'RW_FWID_A' (size 256, offset 11534080)
'WP_RO' (read-only, size 5242880, offset 11534336)
'RO_VPD' (preserve, size 16384, offset 11534336)
'RO_SECTION' (read-only, size 5226496, offset 11550720)
'FMAP' (read-only, size 2048, offset 11550720)
'RO_FRID' (size 256, offset 11552768)
'RO_FRID_PAD' (size 1792, offset 11553024)
'GBB' (size 12288, offset 11554816)
'COREBOOT' (CBFS, size 5210112, offset 11567104)
```

The BOOTSPLASH region is there. Buggy DCU? @SebastianCzapla

**Comment by miczyg1** [comment]
```
./dcu logo ~/protectli_vp32xx_v0.9.0_rc4.rom -l ../dasharo-blobs/protectli/bootsplash.bmp 
Setting ../dasharo-blobs/protectli/bootsplash.bmp as custom logo
Success
```

**Comment by SebastianCzapla** [comment]
Sorry, missed closing the issue. This seems to be buggy dcu, especially in the case of dcuc, which is used within tests. This error occurs when a files are provided via ./coreboot.rom or /path/to/coreboot.rom to dcuc, which results in improper mounting to the container.

When running tests with only filename as argument, as well as a display connected, issue is not present.
