### ISSUE TITLE
APU4 Reproducible Builds

### ISSUE THREAD

**Issue by coval3nte** [Dasharo/dasharo-issues#1113]
### Component

Dasharo firmware

### Device

PC Engines APU4

### Dasharo version

v24.05.00.01

### Brief summary

sha256 not matching with dasharo

### How to reproduce

# [SBOM](https://docs.dasharo.com/variants/pc_engines/releases_seabios/)

## part 1

```sh
#!/bin/bash
git clone https://review.coreboot.org/coreboot
cd coreboot
git checkout 24.05 -b patchqueue
git clone https://github.com/Dasharo/dasharo-pq.git .git/patches
cd .git/patches
git checkout 24.05.00.01
cd -
ln -s patches .git/patches/patchqueue
touch .git/patches/patchqueue/status
guilt init
guilt push -a
```

> `guilt applied` patches are **86**, which is [fine](https://github.com/Dasharo/dasharo-pq/tree/24.05.00.01/patches)

> submodules commit hashes match SBOM 

## part 2

> coreboot-sdk version not present in SBOM

```sh
#!/bin/bash
cd ../
git clone https://github.com/pcengines/pce-fw-builder
cd pce-fw-builder
git checkout b538c921e7032fee8ef70f2925edf52e65307979
docker build . -t pcengines/pce-fw-builder:2024-03-30_cccada28f7
./build_apus.sh ../coreboot seabios_apu4
```

### Expected behavior

[expected hash](https://dl.3mdeb.com/open-source-firmware/Dasharo/pcengines_apu2/v24.05.00.01/pcengines_apu4_seabios_v24.05.00.01.rom.sha256)

### Actual behavior

got 3 different hashes while trying build

**Comment by pietrushnic** [comment]
@coval3nte, thanks; I will take care of it ASAP.

**Comment by pietrushnic** [comment]
For tracking purposes, let me add what hashes you get while building above using the above procedure (based on what was reported on matrix).

```sh
/coreboot
5a0207e56a (tag: 24.05, patchqueue) Documentation: Finalize 24.05 release notes
/coreboot/.git/patches
c86db36 (HEAD, tag: 24.05.00.01) add gitignore-add-memstest86plus_v5-and-sortbootorder-payloads

seabios_apu4.sha256sum
fd4bf67129c32489851e443ef15916ca0819100d88c553ce405c43e80097bfe4 seabios_apu4.rom
```

**Comment by pietrushnic** [comment]
That's completely normal git takes timestamp of the patch application into the hash calculation formula under consideration, so whenever you apply queue, you will get different hash, I tried one more time and have different one:

```sh
git log -1 --oneline
0a088dea043a (HEAD -> guilt/patchqueue) gitignore: add memtest86plu_v5 and sortbootorder payloads
```

Regarding `seabios_apu4.rom`, I keep getting the same hash after rebuilding, so it is not when it gets into the binary. I will use the hex dump release binary and what I get here to determine the difference.

**Comment by pietrushnic** [comment]
We already knew the issue while working on the build: https://github.com/Dasharo/dasharo-issues/issues/890

**Comment by pietrushnic** [comment]
And the tag:

```diff
(...)
1547c1512
< #define COREBOOT_VERSION "v24.05.00.01"
---
> #define COREBOOT_VERSION "24.05-86-g0a088dea043a"
1566c1531
< COREBOOT_VERSION: v24.05.00.01
---
> COREBOOT_VERSION: 24.05-86-g0a088dea043a
2445c2410
< v24.05.00.01
---
> 24.05-86-g0a088dea043a
10818c10783
< v24.05.00.01
---
> 24.05-86-g0a088dea043a
10820c10785
< v24.05.00.01
---
> 24.05-86-g0a088dea043a
```

I think consistent tagging is the missing step for reproducibility. Verifying that, I will create a pull request if that is the case.

**Comment by pietrushnic** [comment]
@coval3nte adding correct tag should fix the reproducibility issues: https://github.com/Dasharo/dasharo-pq/pull/7/files
