### ISSUE TITLE
Include the graphics VBT file in DTS HCL log dumps 

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#1118]
### The problem you're addressing (if any)

One crucial component of firmware is the graphics VBT file. Right now, we either have to extract it from stock firmware (and usually guess which one to use), or boot Linux and obtain the working file ourselves.

### Describe the solution you'd like

We can find the active, working VBT in debugfs, at `/sys/kernel/debug/dri/0/*_vbt`, for example `i915_vbt`. This can be automatically copied and included in the HCL dumps.

### Where is the value to a user, and who might that user be?

It would reduce time spent on a trivial, repetitive activity and make the HCL dumps even more useful

**Comment by mkopec** [comment]
+1, I've also recently wished we dumped the active VBT in HCL reports

**Comment by miczyg1** [comment]
We are only interested in i915 VBT I think, others may only make the report unnecessarily larger.

@mkopec WDYT?
