### ISSUE TITLE
No PC Speaker Beep during boot on MSI Z790-P Wifi

### ISSUE THREAD

**Issue by JanPrusinowski** [Dasharo/dasharo-issues#1127]
### Component

Dasharo firmware

### Device

MSI Pro Z790-P

### Dasharo version

msi_ms7e06_v0.9.2_ddr5-rc3

### Test case ID

ERR001.001, ERR002.001

### Brief summary

There is no sound comming out of the PC Speaker

### How reproducible

100%

### How to reproduce

Reboot the platform and wait for a beep.

### Expected behavior

There should be a beep.

### Actual behavior

No sound is produced.

### Solutions you've tried

Reversing polarity of PC Speaker, Trying a different PC Speaker.

**Comment by miczyg1** [comment]
@JanPrusinowski our builds do not beep during boot on MSI paltform.

**Comment by miczyg1** [comment]
Is it in the scope? https://docs.dasharo.com/variants/msi_z790/test-matrix/ I don't see ERR test cases anywhere?

ERR001.001 is for error beeps
ERR002.001 is for boot beeps.

So per your issue description, only ERR002.001 should fail. For ERR001.001 to pass, you have to simulate an error path, e.g. remove memory modules.

**Comment by JanPrusinowski** [comment]
![image](https://github.com/user-attachments/assets/0966c4f8-bc53-4c85-a994-8a41fd7133eb)
It is in the scope - just was not tested before. @BeataZdunczyk can we remove this test from the scope then? I'll re check the ERR001.001 to make sure and let know.

**Comment by JanPrusinowski** [comment]
@miczyg1 I took the ram out. There was no beep when I tried to turn on the DUT.  I have tried to reverse the polarity on the buzzer - there was no difference.

**Comment by JanPrusinowski** [comment]
@miczyg1 ok So there is a beep when the Ram is out
