### ISSUE TITLE
ESP Scan with OS-specific .efi files fail on MSI Z790-P board

### ISSUE THREAD

**Issue by JanPrusinowski** [Dasharo/dasharo-issues#1128]
### Component

Dasharo firmware

### Device

MSI Pro Z790-P

### Dasharo version

msi_ms7e06_v0.9.2_ddr5-rc3

### Test case ID

ESP001.001

### Brief summary

No additional Boot options availible in Boot Menu

### How reproducible

100%

### How to reproduce

robot -v snipeit:no -L TRACE -v rte_ip:192.168.10.127 -v config:msi-pro-z690-a-ddr5 -v sonoff_ip:192.168.10.253 -v pikvm_ip:192.168.10.226 -v device_ip:192.168.10.197 -v fw_file:./msi_ms7e06_v0.9.2_ddr5-rc3.rom dasharo-compatibility/esp-scanning.robot

### Expected behavior

Additional OSes to Boot Options are availible.

### Actual behavior

No additional boot options.

### Screenshots

![image](https://github.com/user-attachments/assets/fcff8298-9269-418c-9af8-4c7f20219b1b)
[log.zip](https://github.com/user-attachments/files/17660618/log.zip)

**Comment by miczyg1** [comment]
@JanPrusinowski what's the problem exactly? On the screenshot I can see the additional OSes are added:
- Windows Boot Manager (on Intel SSD...)
- Ubuntu (on Intel SSD...)

**Comment by JanPrusinowski** [comment]
The test adds additional boot options for OSes which are not actually installed. Like 
```@{SYSTEMS_FOR_ESP_TESTING}=     Suse Boot Manager (on
...                             RedHat Boot Manager (on
...                             RedHat (on
...                             Fedora (on
...                             CentOS (on
...                             OpenSuse (on
...                             Debian (on
...                             Qubes OS (on```
Test adds those options by adding files to `/mnt/disk_image/EFI/` however after doing so those options are not visible in Boot Menu.

**Comment by miczyg1** [comment]
Did you ensure the disk you are mentioning is mounted and visible in the firmware? And the paths/files are correct?

Note that these boot options are only added for non-removable devices.

**Comment by miczyg1** [comment]
![image](https://github.com/user-attachments/assets/f4d4eb98-5def-43d1-ae1d-7077d98ac409)
There seem to be a typo here: `dts-base-i${DL_CACHE_DIR}/mage-v1.2.8.iso`. The `${DL_CACHE_DIR}/` is in the middle of the filename...

**Comment by miczyg1** [comment]
For each excluded path there must be `--exclude` param:
![image](https://github.com/user-attachments/assets/cb4352c3-3ffa-48c9-ac33-dda67555d3e7)

So the correct command would be:

`rsync -a --ignore-existing --exclude /mnt/disk_image/EFI/Ubuntu --exclude /mnt/disk_image/EFI/Microsoft /mnt/disk_image/EFI/* /boot/efi/EFI/`

No wonder the tests are breaking existing OSes...

**Comment by JanPrusinowski** [comment]
I have added the image manually and OSes are visible now. This is a OSFV issue after all.

**Comment by miczyg1** [comment]
@JanPrusinowski my comments above about the typos are valid still. I will create an issue for it.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/open-source-firmware-validation/issues/567
