### ISSUE TITLE
`Press any key to continue` accepts only enter

### ISSUE THREAD

**Issue by m-iwanicki** [Dasharo/dasharo-issues#1136]
### Component

Dasharo Tools Suite

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1

### Dasharo Tools Suite version

v2.0.0

### Brief summary

UI text says `Press any key to continue` but works only for Enter key

### How reproducible

100%

### How to reproduce

1. Enter `K` option to launch SSH server
2. Press any key other than Enter

### Expected behavior

Any key press should continue the script

### Actual behavior

Only by pressing Enter can we continue the script

### Screenshots

```
Waiting for network connection ...
Network connection have been established!
Starting SSH server!
Now you can log in into the system using root account.
Stopping server will not drop all connected sessions.
Listening on IPs: 192.168.1.20/24
Press any key to continue.
```

**Comment by PLangowski** [comment]
Integrating [this](https://github.com/Dasharo/dts-scripts/pull/42) should close this issue
