### ISSUE TITLE
USB-C display doesn't work 

### ISSUE THREAD

**Issue by wiktormowinski** [Dasharo/dasharo-issues#1155]
### Component

Dasharo firmware

### Device

Protectli VP3210

### Dasharo version

v0.9.0-rc4

### Dasharo Tools Suite version

-

### Test case ID

UTC004.001

### Brief summary

the screen doesn't display anything 

### How reproducible

100% - throughout many trials, the screen didn't turn on even once

### How to reproduce

on protectli VP3210 (dasharo 0.9.0 rc4) try to plug screen via USB-c (on platform side) to HDMI (on screen side) cable and get the graphic otuput displayed on the screen.

### Expected behavior

the screen should work and display what's going on the machine

### Actual behavior

the screen is getting no signal on connected port

### Solutions you've tried

i know some platforms behave a bit quirky when plugging DP or HDMI so i tried plugging it in when the platform is powered off but to no avail

also trying both usb-c ports proved useful in the past (on account of only one port being active), not this time though

**Comment by miczyg1** [comment]
I have checked again and bot hUSb-C ports work with USB-C to DisplayPort adapter. So something maybe wrong with your cable/adapter...
