### ISSUE TITLE
dmesg errors in QubesOS dom0

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#1171]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

Heads v0.9.0-rc2

### Dasharo Tools Suite version

n/a

### Test case ID

STB002.002

### Brief summary

Several errors in QubesOS dom0

### How reproducible

100%

### How to reproduce

- boot into Qubes
- open dom0 terminal
- type `sudo dmesg -l err,warn,crit,emerg`

### Expected behavior

no unexpected boot errors

### Actual behavior

some new errors:

https://paste.dasharo.com/?77ac55b29ca88e7b#7gqRBpfS8LRg51EaAchWHmhpWszoZyAWH4T8xCHYfQB1

**Comment by mkopec** [comment]
not sure how to interpret the APIC ID errors, @marmarek do you think you can help here?

**Comment by marmarek** [comment]
Which CPU?

**Comment by marmarek** [comment]
I'm more worried about XSAVE message, but I can't reproduce it on my side (checked both Qubes OS 4.2 and 4.3). Is there anything special about this setup? Some custom Xen version maybe?

**Comment by mkopec** [comment]
> Which CPU?

155H

> Is there anything special about this setup? Some custom Xen version maybe?

No, just Qubes 4.2.3 with kernel-latest

**Comment by mkopec** [comment]
moved to https://github.com/QubesOS/qubes-issues/issues/9652

**Comment by lfinbob** [comment]
On my NV54 laptop with intel 155H CPU and no dGPU I get lots of errors upon booting the latest Qubes kernel:

coreboot: `0.9.0 07/17/2024`
kernel: `6.12.5-2.qubes.fc37.x86_64`

Highlight-Reel of the errors:
https://forum.qubes-os.org/t/novacustom-nv54-laptop-no-dgpu/31574/2

Full dmesg:
https://paste.dasharo.com/?5f7ca75269c53207#61PUokVHQN6ngGrQ3AbpgmNxgaZusEuDV54r2KdNHQ59

**Comment by lfinbob** [comment]
Dmesg after resuming from S3:
https://paste.dasharo.com/?b7d863b677514d2b#61SqSfZoYYADKu5AuESbimZAoLthnRQiBVV6YVch5xQD
It shows a new error regarding the DDR5 temperature sensor (spd5118)
