### ISSUE TITLE
USB Keyboard doesnt work in firmware | SeaBIOS | Dell Optiplex

### ISSUE THREAD

**Issue by wiktormowinski** [Dasharo/dasharo-issues#1174]
### Component

Dasharo firmware

### Device

Dell OptiPlex 7010

### Dasharo version

v0.1.0 rc-2 seabios

### Dasharo Tools Suite version

-

### Test case ID

USB002.001

### Brief summary

usb keyboard doesnt react in firmware 

### How reproducible

seems like 100%

### How to reproduce

plug in usb keyboard
power on the DUT 
press ESC for boot menu or press NumLock and see if the diode lights up

### Expected behavior

the DUT should react to pressed keys

### Actual behavior

no boot menu & num lock doesnt light up the num pad diode, indicating the keyboard isn't getting power

### Additional context

the keyboard works just fine in ubuntu

**Comment by miczyg1** [comment]
@wiktormowinski SeaBIOS is very tight about the USB timeouts. Try to set `SEABIOS_USB_SIGATT_TIME` in coreboot config to 1000 (milliseconds) or more. Default is just 100ms, which does not always is enough to detect all devices.

**Comment by wiktormowinski** [comment]
i've tried with 3'000,  30'000 and even 300'000 and it seems like this option just elongates boot time and doesn't help the keyboard problem unfortunately

**Comment by filipleple** [comment]
So it turns out USB keyboard does work reliably in firmware (PiKVM), but having PiKVM plugged in and plugging in another one doesn't. That's most likely because of the default `NUM_USB_KEYBOARD=1` in SeaBIOS. I'll change it to `2` in rc3 so that recognizing different keyboards can be tested without dismantling the PiKVM setup, like in EDK2.

**Comment by miczyg1** [comment]
> So it turns out USB keyboard does work reliably in firmware (PiKVM), but having PiKVM plugged in and adding another one doesn't. That's because SeaBIOS only supports one USB keyboard at a time.

Yes, SeaBIOS is not that smart.
