### ISSUE TITLE
Wrong CPU clock speed displayed in setup menu

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#1179]
### Component

Dasharo firmware

### Device

Protectli VP3210

### Dasharo version

v0.9.0-rc6

### Brief summary

Wrong CPU clock speed is displayed in setup menu

### How reproducible

100%

### How to reproduce

Enter setup menu

### Expected behavior

It should display the max clock speed for the CPU, in this case 3.40 GHz

### Actual behavior

It displays 0.8 GHz (probably the current clock speed).

### Screenshots

```
 VP3210
 Intel(R) N100                                       0.80 GHz
 Dasharo (coreboot+UEFI) v0.9.0-rc6                  16384 MB RAM @ 4800 MHz



   Select Language            <Standard English>         This is the option
                                                         one adjusts to change
 > User Password Management                              the language for the
 > Device Manager                                        current system
 > Dasharo System Features
 > One Time Boot
 > Boot Maintenance Manager

   Continue
   Reset

```

**Comment by miczyg1** [comment]
> It should display the max clock speed for the CPU

@filipleple it is an incorrect statement. The setup menu always displays the BASE frequency of the processor. In this case 0.8GHz is the base frequency of the Intel N100.

E.g. MSI with i5-12600K display 3.7GHz (base)., while max is 4.9GHz
