### ISSUE TITLE
Dasharo setup full screen mode

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#118]
**The problem you're addressing (if any)**
Dasharo setup menu is currently a small window with a lot of unused space around it.

**Describe the solution you'd like**
have the setup window to stretch to fullscreen.

**Where is the value to a user, and who might that user be?**
Better readability of the setup windows and better UX.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by miczyg1** [comment]
https://github.com/Dasharo/edk2/pull/22

**Comment by mkopec** [comment]
seems to be partially implemented already? https://github.com/Dasharo/dasharo-issues/issues/177

**Comment by miczyg1** [comment]
@mkopec the PR linked above by me is implementing that and actually awaits your review...

**Comment by mkopec** [comment]
I know, but it looks like at least some of the functionality is already implemented as shown in the photo in #177 
Will try to test if I get a chance

**Comment by wessel-novacustom** [comment]
This has been implemented, I think the issue should be closed.

**Comment by miczyg1** [comment]
THat's roght
