### ISSUE TITLE
Audio subsystem detection fails on Windows on VP3210

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#1186]
### Component

Dasharo firmware

### Device

Protectli VP3210

### Dasharo version

v0.9.0-rc6

### Test case ID

AUD001.002 Audio subsystem detection (Windows)

### Brief summary

`Get-WmiObject -class Win32_SoundDevice` returns nothing

### How reproducible

100%

### How to reproduce

Run [AUD001.002](https://github.com/Dasharo/open-source-firmware-validation/blob/main/dasharo-compatibility/audio-subsystem.robot#L44) or just type `Get-WmiObject -class Win32_SoundDevice` into PowerShell on VP3210

### Expected behavior

It should return an audio device

### Actual behavior

It returns nothing

### Screenshots

```
PS C:\Users\user> Get-WmiObject -class Win32_SoundDevice
PS C:\Users\user>
```

**Comment by miczyg1** [comment]
@filipleple is an HDMI monitor plugged in? The board has only display audio.

**Comment by filipleple** [comment]
@miczyg1 it is, and I've verified via Windows GUI sound settings that the monitor is detected with the correct model and vendor name as a sound output. So it looks like a testing issue instead, I'm guessing we should probe a different class strictly for display audio devices

**Comment by BeataZdunczyk** [comment]
> So it looks like a testing issue instead, I'm guessing we should probe a different class strictly for display audio devices

@filipleple could you either raise an issue for this and link it here, or transition this one to the OSFV repository?
