### ISSUE TITLE
PS/2 enable/disable option.

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#123]
**The problem you're addressing (if any)**
Dasharo always enables PS/2 ports if a keyboard or mouse is connected.

**Describe the solution you'd like**
Add an option to enable or disable PS/2 ports.

**Where is the value to a user, and who might that user be?**
Some people may not want the PS/2 to be enabled. Faster boot.

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by marmarek** [comment]
I see this option present ("Enable PS2 Controller"), it is enabled, but PS/2 keyboard doesn't work in firmware. It does work in the OS.

**Comment by miczyg1** [comment]
@marmarek thanks for the report. I guess the detection method which I added as well may not be working well for all keyboards... The original problem was that PS/2 keyboard was unconditionally added as input device in UEFI. Interfacing a non-existent keyboard (if not connected) caused significant boot delays e.g. in Ventoy.

**Comment by macpijan** [comment]
Option is there, for PS/2 issues in UEFI we have the linked issue.
