### ISSUE TITLE
Capsule update support

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#124]
**The problem you're addressing (if any)**
Dasharo firmware may be only installed with flashrom currently. This is often a problem when Secure Boot is enabled. This also prevents from using mechanisms such as SMM BIOS write protection (aka EISS).

**Describe the solution you'd like**
Implement support for Dasharo firmware updates running coreboot as a base.

**Where is the value to a user, and who might that user be?**
Easy update mechanism compliant with UEFI specification. Support for fwupd or Windows in the future. Better UX.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by macpijan** [comment]
Tracked in: https://github.com/Dasharo/dasharo-issues/issues/423
