### ISSUE TITLE
Firmware performance reporting

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#125]
**The problem you're addressing (if any)**
Dasharo firmware does not report its performance

**Describe the solution you'd like**
Report the overall firmware performance using ACPI FPDT (firmware performance data table). Some work has been already done on uefi_payload_improvements branch on Dasharo/edk2

**Where is the value to a user, and who might that user be?**
Easy check how much time firmware took to boot. E.g. `systemd-analyze` on Linux

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by macpijan** [comment]
This would be very useful to track boot time changes with our releases.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/edk2/pull/25

**Comment by miczyg1** [comment]
Work is not complete yet. It seems coreboot uses TSC for measurements, UEFI Paylaod uses different timer (HPET or LAPIC) which has different resolution/frequency. The discrepancy causes the reported performance to not match reality.

**Comment by pietrushnic** [comment]
TBH, this has to be aligned. We must also gather these topics to be handled by coreboot or OSFF. If coreboot continues in a positive direction, we could bring that to leadership.

@macpijan do you think it makes sense to start a discussion e.g. on the coreboot mailing list? IMHO UEFI compatibility should at least be optional in coreboot. It would be good for future ideas of grand unified firmware interface for all firmware binary blobs (silicon init).

**Comment by miczyg1** [comment]
What for? it is onyl a matter of using correct TimerLib in UefiPayload. No need to raise anything on coreboot ML or leadership.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/edk2/pull/85

**Comment by miczyg1** [comment]
Support is added and configurable build-time
