### ISSUE TITLE
Add option for resizable BARs enabling

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#127]
**The problem you're addressing (if any)**
Dasharo does not support resizable BARs.

**Describe the solution you'd like**
Add an option to enable or disable resizable BARs as it may be useful for certain graphics cards with huge memory resources.

**Where is the value to a user, and who might that user be?**
Sometimes resizable BARs may conflict with GPU virtualization so the user should be able to disable the resizable BARs if needed.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ziguana** [comment]
What's involved in enabling this? It sounds like upstream already added support for ReBAR earlier this year.

https://github.com/coreboot/coreboot/commit/8c93feda7f6cf7bfd90ecfa55e8bc73872c62f81

Would enabling `PCIEXP_SUPPORT_RESIZABLE_BARS` and setting `PCIEXP_DEFAULT_MAX_RESIZABLE_BAR_BITS` in the following config make it work? Going to try anyway.

https://github.com/Dasharo/coreboot/blob/msi_ms7d25/release/configs/config.msi_ms7d25_ddr5

**Comment by ziguana** [comment]
I set the flags and rebuilt `msi_ms7d25/release`. Got some kind of weird error during flashing.

```
Reading ich descriptor... done.
Using region: "bios".
Reading old flash chip contents... done.
Erasing and writing flash chip... Transaction error between offset 0x01b04000 and 0x01b03fff (= 0x01b04000 + -1)!
Reading current flash chip contents... done. Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
No usable erase functions left.
FAILED!
Uh oh. Erase/write failed. Checking if anything has changed.
Reading current flash chip contents... done.
Apparently at least some data has changed.
Your flash chip is in an unknown state.
Get help on IRC (see https://www.flashrom.org/Contact) or mail
flashrom@flashrom.org with the subject "FAILED: <your board name>"!-------------------------------------------------------------------------------
DO NOT REBOOT OR POWEROFF!
```

I rebooted and after a long while the machine came up. The logs have some ACPI errors, not sure if they're related to the changed flags:

```
[    0.180890] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.HEC1 (20221020/dspkginit-438)
[    0.180893] fbcon: Taking over console
[    0.180898] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.SATA (20221020/dspkginit-438)
[    0.180914] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.FSPI (20221020/dspkginit-438)
[    0.180941] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.PEG1.MCHC (20221020/dspkginit-438)
[    0.180944] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.PEG1.MCHC.PEG1 (20221020/dspkginit-438)
[    0.180948] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.PEG1.MCHC.DPTF (20221020/dspkginit-438)
[    0.180952] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.PEG1.MCHC.PEG1.MCHC (20221020/dspkginit-438
)
[    0.180955] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.PEG1.MCHC.DPTF.MCHC (20221020/dspkginit-438
)
[    0.180958] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.PEG0.MCHC (20221020/dspkginit-438)
[    0.180962] ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.RP03.MCHC (20221020/dspkginit-438)
```

However, the logs also show that ReBAR is on:
```
[   20.003112] i915 0000:03:00.0: [drm] BAR2 resized to 16384M
[   20.003126] i915 0000:03:00.0: [drm] Local memory IO size: 0x00000003fa000000
[   20.003127] i915 0000:03:00.0: [drm] Local memory available: 0x00000003fa000000
```

**Comment by ziguana** [comment]
It sounds like the next step here would be to create a menu option for ReBAR and to bounce out of `configure_adjustable_base()`/etc. when it is not set.

**Comment by miczyg1** [comment]
> It sounds like the next step here would be to create a menu option for ReBAR and to bounce out of `configure_adjustable_base()`/etc. when it is not set.

Exactly.

haven't seen such ACPI errors before.

Regarding the flashrom issue, you would have to disable BIOS lock in Dasahro System Features -> Security Options in the Setup.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/DasharoModulePkg/pull/27
https://github.com/Dasharo/edk2/pull/71
https://github.com/Dasharo/coreboot/pull/383

**Comment by BeataZdunczyk** [comment]
Closing this issue as the changes have been merged. We are currently completing testing for the release, and further updates will be provided on testing issues https://github.com/Dasharo/dasharo-issues/issues/612 and https://github.com/Dasharo/dasharo-issues/issues/613.
