### ISSUE TITLE
Laptop didn't wake up after flashing coreboot signed with wrong vboot keys NV4X v1.2.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#144]
**Dasharo version**
v1.2.0

**Dasharo variant**
Clevo NV41MZ/MB

**Affected component(s) or functionality**
Vboot

**Brief summary**
Vboot didn't revert to booting from the recovery slot after flashing coreboot signed with wrong vboot keys.

**How reproducible**
100%

**How to reproduce**

1. Build or download flashrom.
2. Flash coreboot signed with wrong vboot keys by executing the following command: `sudo flashrom -p internal --fmap -i RW_SECTION_A -w [binary]`
3. Restart the DUT.

**Expected behavior**
Vboot should revert to booting from the recovery slot.

**Actual behavior**
Laptop didn't wake up and power LED lights up orange and blinks green.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by mkopec** [comment]
Fixed by commit https://github.com/Dasharo/coreboot/commit/5c2533a44889e85affc9ff822614af5f088ae45b - let's retest and then we'll close this issue

**Comment by Pokisiekk** [comment]
After retest, everything works

**Comment by mkopec** [comment]
Thanks
