### ISSUE TITLE
The NVIDIA graphics power management isn't properly functional NV41MB v1.2.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#145]
**Dasharo version**
v1.2.0, v1.3.0, v1.4.0

**Dasharo variant**
Clevo NV41MB

**Affected component(s) or functionality**
NVIDIA graphics power management.

**Brief summary**
The card is on whole time. 

**How reproducible**
100%

**How to reproduce**

1. Run the following command `cat /sys/class/drm/card1/device/power/runtime_status`

**Expected behavior**
The card should have suspend status and powers on only while it's used.

**Actual behavior**
The card have always active status.

**Screenshots**

**Additional context**
Ubuntu 22.04

**Solutions you've tried**

**Comment by mkopec** [comment]
Couple of ideas:

- Is the latest nvidia driver installed? IIRC power management was a little better with `nvidia-driver-510`
- Is the on-demand profile selected in nvidia control panel?
- Does power management work on Windows, or is it broken there as well?

**Comment by Pokisiekk** [comment]
`nvidia-driver-510` was installed and on-demand profile was selected in nvidia control panel.
On Windows 11 power management works correctly.

**Comment by wessel-novacustom** [comment]
Do you know if this problem happens with Insyde proprietary firmware too?

**Comment by Pokisiekk** [comment]
I just test it on dasharo firmware v1.2.0

**Comment by mkopec** [comment]
What's the status of this with v1.3.0? If I recall correctly we made some changes to the nvidia driver setup in the documentation recently which helped with sleep mode, did that also affect power management?

As a side note, it worked for me while testing locally

**Comment by Pokisiekk** [comment]
@mkopec The problem still occurs on v1.3.0, automated tests never pass.
NVIDIA graphics power management didn't work properly also when I tested it manually, even after installing drivers.

**Comment by macpijan** [comment]
`NV40MB 1` Ubuntu 22.04. NVidia is correctly in `suspend` state when not used.

**Comment by mkopec** [comment]
Added a recommendation in the docs to enable NVIDIA On-demand mode, otherwise the card will not shut down automatically.
