### ISSUE TITLE
MSI Z690 Installation Manual SMBIOS data

### ISSUE THREAD

**Issue by handmeatowel** [Dasharo/dasharo-issues#146]
**Dasharo version**
1.0.0

**Dasharo variant**
./.

**Question text**
Following the installation manual ([https://docs.dasharo.com/variants/msi_z690/installation-manual/](https://docs.dasharo.com/variants/msi_z690/installation-manual/)) leads to the following error:
```
~/coreboot$ ./util/cbfstool/cbfstool msi_ms7d25_v1.0.0.rom add -f system_uuid.txt -n system_uuid -t raw -r FW_MAIN_A
E: Could not add [system_uuid.txt, 36 bytes (0 KB)@0x0]; too big?
E: Failed to add 'system_uuid.txt' into ROM image.
E: Failed while operating on 'FW_MAIN_A' region!
E: The image will be left unmodified.
```

**Comment by miczyg1** [comment]
Forgot to expand the CBFS region first... Here's the fix: https://github.com/Dasharo/docs/pull/223

**Comment by miczyg1** [comment]
PR merged, closing.
