### ISSUE TITLE
Add ACPI LED device for laptop keyboard backlight

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#147]
**The problem you're addressing (if any)**

Keyboard backlight is not currently controllable from the OS and is handled entirely in firmware.

**Describe the solution you'd like**

Dasharo should have a LED device in ACPI that would allow the user to change the keyboard backlight state from within the OS.

**Where is the value to a user, and who might that user be?**

- Users will be able to affect the keyboard backlight via a `sysfs` entry in `/sys/class/leds`
- Keyboard backlight state will be saved and restored by systemd across reboots and suspend cycles
- Keyboard backlight behavior will be more customizable (finer-grained brightness control, optional save/restore)

**Describe alternatives you've considered**

Handle keyboard hotkeys and save/restore in firmware entirely. This has proven to be difficult due to the EC firmware resetting the backlight by itself

**Additional context**

- Kernel LED control documentation: https://docs.kernel.org/leds/leds-class.html
- Kernel LED ACPI documentation: https://www.kernel.org/doc/html/latest/firmware-guide/acpi/dsd/leds.html
- systemd automatically creates save/restore services for led devices with function name `kbd_backlight`: https://github.com/systemd/systemd/blob/9dd98db27d62b593120faf25fc8364ac3801d41a/rules.d/99-systemd.rules.in#L65

**Comment by miczyg1** [comment]
Add labels for the laptops? @mkopec

**Comment by mkopec** [comment]
@miczyg1 done

**Comment by wessel-novacustom** [comment]
Sounds like a good idea.

**Comment by mkopec** [comment]
Since we've migrated to Open EC firmware, this is already done.
