### ISSUE TITLE
Charging via Thunderbolt 4 Port cause problem NV41MB v1.2.1

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#150]
**Dasharo version**
v1.2.1

**Dasharo variant**
Clevo NV41MB

**Affected component(s) or functionality**
Charging via Thunderbolt 4 port

**Brief summary**
When USB Type-C PD power supply is connected via the docking station or directly to Thunderbolt 4, the DUT run into problem.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT and log into Windows 11.
2. Connect the docking station to the Thunderbolt 4 port.
3. Connect the charger plug to the docking station.
4. Wait for problem occurs. 
OR
1. Power on the DUT and log into Windows 11.
2. Connect the charger plug to the Thunderbolt 4 port.
3. Wait for problem occurs. 

**Expected behavior**
Battery is charging

**Actual behavior**
The DUT run into problem, like on attached image.

**Screenshots**
![IMG-6728](https://user-images.githubusercontent.com/101700648/175293759-69578c07-8ba8-4bee-9e55-a999887ddd6a.jpg)

**Additional context**

**Solutions you've tried**

**Comment by mkopec** [comment]
The NV41MB unit has a defective Thunderbolt port, i think we should do tests on the NV40MB unit instead since its TBT port is fixed. See https://github.com/Dasharo/dasharo-issues/issues/61#issuecomment-1150881165

**Comment by Pokisiekk** [comment]
It's normal that charging via Thunderbolt 4 Port works properly on Ubuntu 22.04?

**Comment by mkopec** [comment]
It may charge alright but the GPU will run into issues after a while (like `GPU has fallen off the bus` in dmesg, and it'll stay constantly on). Windows will just BSOD, but Linux will keep running for some time :)

**Comment by Pokisiekk** [comment]
I retest this on the NV40MB and the DUT is charging properly.

**Comment by mkopec** [comment]
Thanks!
