### ISSUE TITLE
Blank screen upon boot; failure to POST?

### ISSUE THREAD

**Issue by unilock** [Dasharo/dasharo-issues#151]
(I'm not sure if this should be a bug report or a support request, so bear with me.)

**Dasharo version**
v1.0.0

**Dasharo variant**
msi_ms7d25

**Affected component(s) or functionality**
Motherboard

**Brief summary**
When powering on the desktop (with the below configuration), all CPU + chassis fans spin and light up, and the monitor (attached via DP directly to motherboard (iGPU)) is initialized, but remains at a blank, black screen indefinitely. Pressing the power button once turns off the desktop immediately, leading me to believe the motherboard is failing to POST.

**How reproducible**
Not reproducible (by me - I only have one of these motherboards, and do not own the hardware to reflash the BIOS chip)

**How to reproduce**

1. Attempt to turn on the computer
2. The computer does not POST

**Expected behavior**
The computer POSTs, shows the Dasharo splash screen,  and boots to the OS as normal.

**Actual behavior**
The computer boots to a blank screen, remaining there until forcibly powered off.

**Screenshots**
N/A

**Additional context**
Prior to this issue occurring, the following took place:
1. I installed Pop!_OS 22.04 and used it for a few hours total
3. I installed Linux kernel 5.18.6 via [mainline](https://github.com/bkw777/mainline)
4. I powered off the computer completely + powered it back on
5. The monitor turned off once I had entered my password to my user profile, leading me to force the computer to power off
6. The computer booted again just fine, but ran into the same problem afterwards, leading me to proceed with another forced shutdown
7. Upon reboot, the computer stopped POSTing, as described in this issue

Booting with the monitor attached to the dGPU (via DP) results in the same behavior, except the display is never initialized. (Read: the monitor does not wake from sleep mode.)

My hardware:
- Motherboard: MSI PRO Z690-A WIFI DDR4
- CPU: Intel Core i5-12400
- dGPU: ASUS ROG STRIX RX 5500 XT GAMING OC
- RAM: 32GB (4x8GB) XPG DDR4-3000 CL16-18-18 (P/N: AX4U300036G16-BWZ) (may not have been running at 3000MHz; that was an XMP profile)
- PSU: 750W NZXT C750 (2022)
- Chassis: [Fractal Focus G](https://www.fractal-design.com/products/cases/focus/focus-g/gunmetal-gray/)

**Solutions you've tried**
- Booting with no peripherals attached other than the CPU, RAM, monitor (DP), chassis front panel cables, and fans
- Booting without the dGPU attached
- Booting with only one RAM module installed (in DIMM slot A1)
- Reseating the CPU and RAM
- Removing and reinserting the CMOS battery

**Comment by pietrushnic** [comment]
@unilock thank you for that report. Firmware team will look into deeper soon.

First question is if you have backup of vendor BIOS and means to recover?

**Comment by miczyg1** [comment]
@unilock I would definitely try with iGPU only for the time being. If the monitor wakes up from sleep mode when connected to iGPU, it means that memory is initialized already. Note changing memory population will trigger full memory initialization and require a longer POST time.

You may try again with removing the CMOS battery, but be sure to unplug the PSU as well. The platform should not have any power source for at least 1 minute.

The problem with dGPU never being initialized could be the unsigned OptionROM used to initialize the graphics and UEFI Secure Boot denies loading it. That would explain the display connected to dGPU not being initialized.

Ad.4 and Ad.5 This sounds really like some Linux driver problem or a problem with X server.

We will try to reproduce the same steps on our side (although without dGPU, as we do not have such model) and see if we face the same problem.

**Comment by unilock** [comment]
Removing the CMOS battery and disconnecting the PSU, then leaving the desktop alone for ~6 minutes didn't help, unfortunately. Nor did letting it stay on the blank screen for ~10 minutes.
This is with only the CPU and RAM installed, of course.

**Comment by miczyg1** [comment]
> It may not have been clear, but the dGPU was working fine before this issue started occurring, both in the firmware and OS. Also, I don't have Secure Boot enabled.

Ohh, then something really weird happened here... We will prepare some documentation/procedures for you how to recover from such situations using the RaspberryPi or equivalent for example.

**Comment by unilock** [comment]
Excellent! Before reflashing the stock BIOS, and if possible with a Raspberry Pi, should I collect logs of the motherboard's current boot sequence?

**Comment by miczyg1** [comment]
@unilock I doubt you will be able to collect any logs from the current machine state. The backup of the original firmware is important.

**Comment by unilock** [comment]
> Ohh, then something really weird happened here... We will prepare some documentation/procedures for you how to recover from such situations using the RaspberryPi or equivalent for example.

@miczyg1 Any update on the guide for using a Raspberry Pi to recover from a "bricked" firmware?

**Comment by unilock** [comment]
Any progress? Sorry for being a pest, but this is my only desktop, and a laptop can only do so much.

**Comment by miczyg1** [comment]
I should be able to prepare it on Monday since I got some spare time. Apologies for the delay, those past weeks were very busy on our side.

**Comment by unilock** [comment]
Looking forward to it :)

**Comment by miczyg1** [comment]
I have checked the prerequisites for Raspberry Pi recovery method and it looks like flashing the chip will be impossible without an additional converter form 3.3V to 1.8V. The SPI flash on MSI board operates on 1.8V while RPi on 3.3V.

So a set like this: https://www.amazon.com/programmer-ch341a-Programmer-Adapter-Converter/dp/B07WP9FKZ2
would be necessary to make it work. Also a set of jumper wires like these: https://www.adafruit.com/product/1919
(note the pitch of 2.54mm on one end and 2mm pitch on the second end is important). We cannot proceed without it. An USB 2.0 extension cable would be also convenient if you don't have one.

Alternatively we could use a level shifting hat or RPi: https://www.tindie.com/products/cburgess129/level-shifting-hat-for-raspberry-pi-18v-33v-5v-2/ but another set of wires would be needed for this one. So I would opt for CH341A.

**Comment by zirblazer** [comment]
Note than there is also this guy: https://github.com/Dasharo/dasharo-issues/issues/178
...who is using a CH341A (Which should also be compatible with 1.8V, not all are) with a WSON probe. Read from this post onwards: https://github.com/Dasharo/dasharo-issues/issues/111#issuecomment-1207168465
Seems like a viable alternative, too.

**Comment by unilock** [comment]
Fortunately, I do already own a CH341A (and a 1.8V level shifter IIRC), and I'll look into getting a WSON probe. Maybe taping it to the motherboard while flashing the firmware would hold it in place well enough?

Although, before I purchase anything, might it be worth [shorting the JBAT1 jumper](https://github.com/Dasharo/dasharo-issues/issues/111#issuecomment-1207486469) to reset the CMOS?

**Comment by zirblazer** [comment]
Shorting the JBAT1 jumper should be equivalent to removing the battery, which you already did. Not that you can lose anything by trying again...

From what I read from the guy that tried with the WSON probe, he had to manually hold it for the entire reading/flashing duration. I would ask him what he is using, he seems ahead of the curve at this precise moment cause he already has it working.

**Comment by unilock** [comment]
@renehoj Since you have experience with flashing the Z690 using a CH341A, could you give some insight on how to attach the programmer to the firmware chip?

**Comment by renehoj** [comment]
You need a wson test probe like this https://www.aliexpress.com/item/4001317203417.html make sure you get it in the right size

The pins on the chip are:
1 CS     8 Vcc
2 SO     7 
3           6 CLK
4 GND  5 SI

pin 1 has a small dot on the chip

Connect the pins on the chip to the matching pins on the side of the CH341A, if it doesn't work you probably need to swap 2 and 5 they are the only pins that does have the exact matching names.

The CH341A uses 3.3v Vcc, which is what I have been using, but the chip is only designed for 2V. I don't think writing it once will kill it, but you never know.

If you want to be safe you should get a step-down converter when you order the probe just to be safe, it will allow you to convert Vcc from the CH341A to 1.8 or 2V

**Comment by unilock** [comment]
OK, I've purchased an 8x6mm WSON8 probe from here:
https://aliexpress.com/item/3256804113101513.html
It should be here in about a month (of course). I'll report back with how flashing the firmware goes once I've received it.

**Comment by renehoj** [comment]
https://www.aliexpress.com/item/4001317203417.html

You probably should consider getting something like that, it will take 5v input and give you 1.8v output. You can power it from the CH341A and get the correct Vcc for the chip, maybe you get something that doesn't need any assembly.

**Comment by renehoj** [comment]
If you have any electronic repair shops in your area, you could try and call them and ask how much it would cost to have them flash the firmware for you. They should have a bench power supply and the eprom programmer, in which case you probably only need to pay for the time it takes them to program the chip.

It might be cheaper than buying the equipment yourself, if you don't plan to use it again in the future.

**Comment by unilock** [comment]
Unfortunately most electronic repair shops in my area only do basic mobile/laptop repairs (screens, batteries, etc.). I doubt any of them have an EPROM programmer.
Besides, the WSON8 probe only cost $13, and I already have the rest of the required tools. I'm sure it'll be useful at some point in the future, too.

**Comment by pietrushnic** [comment]
@klutzies sorry we were silent for so long. Can you try to get though new documentation and provide feedback? We hope it will help you in recovery.

**Comment by miczyg1** [comment]
By new documentation we mean CH341A recovery here https://docs.dasharo.com/variants/msi_z690/recovery/

**Comment by klutzies** [comment]
Hi, sorry for the nonresponse! I have the probe, level shifter, and CH341a flasher all ready. Just have to get around to putting in the work to flash the damn thing.

I'll let you know when that happens :)

**Comment by unilock** [comment]
Good news! The CH341a recovery procedure worked!! (as documented in the "Dasharo Universe" docs)

Bad news: recreating and flashing the Dasharo firmware from scratch (using release `v1.1.0`) resulted in the same "no POST" problem as I had originally (immediately after flashing + force-powering down after the "failed" memory training + rebooting).

More good news, maybe - the issue with Linux loading a blank screen after logging in with the dGPU attached occurs on the stock MSI firmware as well, so that's one less thing to worry about? (it's probably fixed in a newer version of the kernel; I only tested with the kernel I had installed at the time the desktop was first bricked)

**Comment by zirblazer** [comment]
Recently a major issue was discovered with IGPs in that only 12600K+ CPUs actually initialized the IGP properly. Since you have a 12400, is possible that you were hitting this: https://github.com/Dasharo/dasharo-issues/issues/274
Is very likely that your whole issue was caused by this. It may have worked in the first flash if Dasharo defaulted to boot from a working drive, whereas after dissambling the system and changing stuff it may have went to UEFI Shell instead.

**Comment by miczyg1** [comment]
@unilock you may try to flash the [v1.1.1 RC3](https://cloud.3mdeb.com/index.php/s/5Tpxw9zScTnof9M/download) binary that helped with @zirblazer issues and has the patch for IGP. Note this binary has no ME or descriptor built-in so flash only the BIOS region. We will try to officially release v1.1.1 ASAP.

**Comment by unilock** [comment]
@zirblazer That sounds about right, though I wonder what made Linux stop booting? I'm guessing it was filesystem corruption from forcing it to shut down so many times, leading it to boot to "emergency" mode, in which it couldn't load its own framebuffer(?) driver... hm.

@miczyg1 Would I flash v1.1.1 RC3 alone over the stock BIOS? Or would I flash the v1.1.0 binary I made, then flash the v1.1.1 RC3 `bios` region over it?
If the latter, would I do the v1.1.1 RC3 flash from the suggested live Linux system immediately after flashing v1.1.0, or would I have to reboot the system first, then flash v1.1.1 RC3 manually?
Also, how would that all work if I were to use the coreboot image I [signed myself](https://docs.dasharo.com/guides/vboot-signing/)?

(Speaking of, there's a (semi-)bug in that process: the [key generation guide](https://docs.dasharo.com/guides/vboot-signing/#generating-keys) says to use Docker, which is difficult to do on a live Linux system, since you can't (easily) grant yourself the required `docker` group. Without being added to said group, the key generation script fails with "permission denied" when creating the user-specified output directory.

I worked around this by creating a temporary directory at the root of the live filesystem (`/`), cloning the `dasharo-tools` repository to said directory, recursively changing the directory and all its contained files' and folders' permissions to 777, and finally running the script. Obviously, this isn't quite ideal...)

**Comment by miczyg1** [comment]
> Would I flash v1.1.1 RC3 alone over the stock BIOS? Or would I flash the v1.1.0 binary I made, then flash the v1.1.1 RC3 bios region over it?

@unilock you can flash v1.1.1 RC3 directly over stock. Just use the `--ifd -i bios` option for flashrom and you should be fine. Remember to reboot and then wait for PC speaker signal or SATA LED blink as a signal to power off the board.

If you flash over v1.1.0, a simple reboot is sufficient.

> Also, how would that all work if I were to use the coreboot image I [signed myself](https://docs.dasharo.com/guides/vboot-signing/)?

If you have v1.1.0 signed, you may sign the v1.1.1 RC3 the same way as explained in the link. If you migrate from v1.1.0 to v.1.1.1 RC3 you may change the `--ifd -i bios` flashrom parameters and use `--fmap -i WP_RO -i RW_SECTION_A -i RW_SECTION_B`, that way you will keep current boot options you have created and all other settings (including already trained memory settings - so faster boot after update).

> (Speaking of, there's a (semi-)bug in that process: the [key generation guide](https://docs.dasharo.com/guides/vboot-signing/#generating-keys) says to use Docker, which is difficult to do on a live Linux system, since you can't (easily) grant yourself the required docker group. Without being added to said group, the key generation script fails with "permission denied" when creating the user-specified output directory.

`docker` groups is not required, sudo will have to be used in such case. However, I understand `docker` is not best for portability. But on the other hand, compiling and installing vboot utils is troublesome, docker helps to make it work in any environment. I would have to check if Dasahro Tools Suite has the same exact copy of vboot utils (I hope it has).

**Comment by tmburton** [comment]
> 

FYI, I was unable to flash v1.1.1 RC3 with `--ifd -i bios`. It failed. I was able to with `--fmap -i RW_SECTION_A -i RW_SECTION_B`

**Comment by miczyg1** [comment]
@tmburton v1.1.0 has a vboot recovery region lock, it won't allow to flash whole BIOS region. First, you have to disable BIOS boot medium lock in the setup (Dasharo System Features -> Dasharo Security Options)

**Comment by unilock** [comment]
Sorry for the late response - Dasharo v1.1.1 RC3 works great! No more blank screen after flashing. Thanks so much :)
(Note that I meant to test with my dGPU installed before responding to this thread, but haven't been able to get around to it - I imagine it does work, though; at least after booting into the OS.)
I'll close this issue now.

@miczyg1
>  you may change the `--ifd -i bios` flashrom parameters and use `--fmap -i WP_RO -i RW_SECTION_A -i RW_SECTION_B`

Did you mean to include `-i WP_RO`? The official [firmware update guide](https://docs.dasharo.com/variants/msi_z690/firmware-update/#version-v110-or-newer) doesn't mention it in its own `flashrom` command:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/11802133/214044484-b8592ca5-3500-4d7c-8159-3f45475b48e2.png">

> `docker` groups is not required, sudo will have to be used in such case.

Weird: I was able to install Docker and use it with `sudo` without logging out + back in on my *complete* installation of Pop!_OS 22.04. Maybe it's only an issue with live environments?

> I would have to check if Dasharo Tools Suite has the same exact copy of vboot utils (I hope it has).

Having a live environment specifically for dumping the stock BIOS and downloading + patching + flashing Dasharo would be very useful :)
(for others, that is - hopefully I won't need it any time soon!)

**Comment by miczyg1** [comment]
> Did you mean to include -i WP_RO? The official [firmware update guide](https://docs.dasharo.com/variants/msi_z690/firmware-update/#version-v110-or-newer) doesn't mention it in its own flashrom command

Yes, because depending on which version you are migrating from, it may be needed to include WP_RO. The firmware update guide however probably does not take into account all possibilities but it has a notice:

> Version v1.1.0 had to change the flashmap layout and requires usage of the [procedure below](https://docs.dasharo.com/variants/msi_z690/firmware-update/#version-older-than-v110) when migrating from v1.0.0 or older.

> (assuming you could get the motherboard to boot off a USB drive - is there a coreboot startup key combo that can force that to happen?)

There isn't unfortunately.

**Comment by unilock** [comment]
Oops, I forgot to mention - PS/2 isn't working with Dasharo v1.1.1 RC3; not in the UEFI, nor the OS. (at least, my keyboard - a Microsoft Natural Keyboard Elite - isn't)
Maybe this is suited for a new issue?

**Comment by miczyg1** [comment]
@unilock hmmm... Definitely applicable for a new issue, but I don't understand why it doesn't work in OS. I have verified v1.1.1-rc3 with a PS/2 keyboard and it worked well.

**Comment by Firminator** [comment]
That worked. I'm on v1.1.1RC3 now and I can confirm tha my IGP output issue is fixed. Good job everyone.

**Comment by unilock** [comment]
@miczyg1 My bad, PS/2 *does* work in the OS; just not in the "pre-boot" OS environment that asks for the disk encryption password (through LUKS).

Actually - the reason for my original issue was likely because, since coreboot wasn't initializing the iGPU, and because I had such a pre-boot environment installed, the OS was never able to load its own graphics drivers - leaving me stuck on the password prompt, hidden behind a blank screen.

I didn't think of this at the time, since the computer acts mostly the same in the pre-boot environment as it does in the UEFI - e.g. the keyboard "lock" keys don't function (caps lock, etc.), and the power button instantly shuts off the computer when you release it, instead of needing to be held for a few seconds otherwise.
I didn't realize the possibility that it had reached that screen, and I just needed to enter the disk encryption password to continue.

Regardless, my PS/2 keyboard remains nonfunctional in the UEFI; I'll open a new issue.
