### ISSUE TITLE
Building VP46xx with `-j $(nproc)` fails

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#157]
**Dasharo version**

v1.0.16

**Dasharo variant**

Dasharo Firewall

**Affected component(s) or functionality**

Building

**Brief summary**

Parallel building of Dasharo for VP46xx fails with the following error message:

```
    CC         bootblock/drivers/pc80/tpm/tis.o
    CC         bootblock/drivers/smmstore/store.o
    CC         bootblock/drivers/spi/bitbang.o
src/drivers/smmstore/store.c:5:10: fatal error: fmap_config.h: No such file or directory
 #include <fmap_config.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```

**How reproducible**

**How to reproduce**

1. run `make -j $(nproc)` to build coreboot
2. wait until building crashes

**Expected behavior**

Compiling in parallel for faster build times should be possible.

**Actual behavior**

Parallel building fails.

**Screenshots**

none

**Additional context**

none

**Solutions you've tried**

Removing `-j $(nproc)` from the make command in the build script disables parallel building and lets compilation proceed

**Comment by miczyg1** [comment]
I don't think multiple jobs compilation was ever reliable with coreboot build system. It looks like broken Makefile dependencies, not really our fault. Feel free to look for it if you want.
