### ISSUE TITLE
Add to the MSI PRO Z690-A WIFI DDR4 MCL the Kingston Fury Beast Black KF432C16BB1/16 and PNY XLR8 8GBF1X08QFHH38-135-K-HXR

### ISSUE THREAD

**Issue by zirblazer** [Dasharo/dasharo-issues#158]
**Dasharo version**
Dasharo 1.0.0 for MSI PRO Z690-A WIFI DDR4

**CPU**

Processor: Intel Core i5 12600K
BOX: BX8071512600K
S/N: U10L2X2900204
SSpec: SRL4T (Same on Processor)
Batch: X141J510 (Same on Processor)
Made in Vietnam
Can enable AVX512 when tested with MSI stock 1.2 BIOS with older Microcode

**GPU**
Integrated
 

**Memory**

* Configuration: 4 sticks, not tested with 1 or 2
Kingston Fury Beast Black KF432C16BB1/16
https://www.kingston.com/dataSheets/KF432C16BB1_16.pdf
9905734 - 117.B00G
16 GiB DDR4 UDIMM non-ECC 2Rx8
JEDEC Profile / DDR4 2400 MHz / 17-17-17 / 1.2V
XMP Profiles 1 and 2 not tested

Attached decode-dimms_kingston.log, dmidecode_memory_kingston.txt, spd_kingston.zip and dasharo_taiphoonburner_cpuz_kingston.png
Serial Numbers are different between modules, so all 4 SPDs should differ

**Memory**

* Configuration: 4 sticks, not tested with 1 or 2
PNY XLR8 8GBF1X08QFHH38-135-K-HXR
Most likely this 2 x 8 GiB kit, didn't checked the box SKU: https://www.pny.com/anarchy-x-ddr4-red?sku=MD16GK2D4320016AXR
8 GiB DDR4 UDIMM non-ECC 1Rx8???
JEDEC Profile / DDR4 2133 MHz / 15-15-15 / 1.2V
XMP Profile (Only 1) not tested

Attached decode-dimms_pny.log, dmidecode_memory_pny.txt, spd_pny.zip and dasharo_taiphoonburner_cpuz_pny.png
SPD doesn't include Serial Numbers so is possible than all 4 are the same
The SPD seems to be completely broken because Thaiphoon Burner reports CRC32 errors
decode-dimms is empty - it detects 0 DIMMs

**Memory**
Mixed memory
DIMMA1: PNY XLR8 8GBF1X08QFHH38-135-K-HXR
DIMMA2: Kingston Fury Beast Black KF432C16BB1/16
DIMMB1: Kingston Fury Beast Black KF432C16BB1/16
DIMMB2: PNY XLR8 8GBF1X08QFHH38-135-K-HXR

POST and boots fine, reported 48 GiB installed
decode-dimms reported 2 installed modules (The Kingston ones)

![dasharo_taiphoonburner_cpuz_kingston](https://user-images.githubusercontent.com/32025193/177019845-cf0d2c1f-c215-4232-8f9c-16f699ddf16a.png)
![dasharo_taiphoonburner_cpuz_pny](https://user-images.githubusercontent.com/32025193/177019847-360d5361-3577-44e0-9256-eb775a757f80.png)
[decode-dimms_kingston.log](https://github.com/Dasharo/dasharo-issues/files/9033881/decode-dimms_kingston.log)
[decode-dimms_pny.log](https://github.com/Dasharo/dasharo-issues/files/9033882/decode-dimms_pny.log)
[dmidecode_memory_kingston.txt](https://github.com/Dasharo/dasharo-issues/files/9033883/dmidecode_memory_kingston.txt)
[dmidecode_memory_pny.txt](https://github.com/Dasharo/dasharo-issues/files/9033884/dmidecode_memory_pny.txt)
[spd_kingston.zip](https://github.com/Dasharo/dasharo-issues/files/9033888/spd_kingston.zip)
[spd_pny.zip](https://github.com/Dasharo/dasharo-issues/files/9033889/spd_pny.zip)

**Comment by artur-rs** [comment]
It should be automatically added: https://github.com/Dasharo/dasharo-issues/blob/master/.github/ISSUE_TEMPLATE/hcl-report.md

**Comment by pietrushnic** [comment]
:thinking: maybe it doesn't work or it didn't work at point of adding this issue?

**Comment by zirblazer** [comment]
Most likely I completely break the expected format, I didn't used the template.

**Comment by artur-rs** [comment]
not necessarily, I think we should/need to setup github actions for that, I'm not very familiar with these issues templates and whether they are working as we expect

**Comment by Pokisiekk** [comment]
Added to Memory HCL: https://docs.dasharo.com/variants/msi_z690/memory-hcl/

**Comment by miczyg1** [comment]
@Pokisiekk the entries in memory HCL for this report are bad. Here we have a mixed memory topology, so it should be reported like this:

DIMM vendor | Part Number | Size | SPD profile | Configuration 1/2/4
-- | -- | -- | -- | --
Kingston | [KF432C16BB1/16](https://www.kingston.com/dataSheets/KF432C16BB1_16.pdf) | 16GB | JEDEC: DDR4-2400 CL17-17-17 1.2V | -/✔/-
PNY | [8GBF1X08QFHH38-135-K-HXR](https://www.pny.com/anarchy-x-ddr4-red?sku=MD16GK2D4320016AXR) | 8GB | JEDEC: DDR4-2133 CL15-15-15 1.2V | -/✔/-

**Comment by Pokisiekk** [comment]
@miczyg1 Configuration: 4 sticks, not tested with 1 or 2
Of course, we can add/mark a mixed configuration somehow, but single two modules of each type haven't been tested.

**Comment by miczyg1** [comment]
I have got information that there were 4x non-mixed configurations tested as well as 2x2 mixed configuration tested. But I can only see non-mixed added in PR

**Comment by miczyg1** [comment]
https://github.com/Dasharo/docs/pull/284
