### ISSUE TITLE
Intel XTU on Windows reports "The platform does not support overclocking" on the MSI PRO Z690-A WIFI DDR4 with a K-series Processor

### ISSUE THREAD

**Issue by zirblazer** [Dasharo/dasharo-issues#159]
**Dasharo version**
Dasharo 1.0.0 for MSI PRO Z690-A WIFI DDR4

**Affected component(s) or functionality**
Overclocking

**Brief summary**
Intel XTU (Extreme Tuning Utility) 7.8.0.21 on Windows 11 installs properly, but after opening XTU, it says "The platform does not support overclocking". This is with a Core i5 12600K.

**How reproducible**
100%

**How to reproduce**
1. Download Intel XTU installer (Current version is 7.8.0.21) from here:
https://www.intel.com/content/www/us/en/download/17881/intel-extreme-tuning-utility-intel-xtu.html
2. Install and reboot
3. Open XTU and check System Information section

**Expected behavior**
XTU should allow to modify most values on the interface instead of being grayed out.
Didn't checked on MSI stock Firmware yet, but K-series Processor + Z-series Chipset = overclock possible. You're actually paying Intel a premium for overclocking capabilities on these parts, so I'm not expecting it to not work on stock Firmware.

**Actual behavior**
XTU System Information section reports "The platform does not support overclocking". Almost all options in Advanced Tuning section with the notorious exceptions of PL1 (Turbo Boost Power Max) and PL2 (Turbo Boost Short Power Max) are grayed out.
EDIT: After benchmarking a bit with CineBench R23, it seems that the CPU honors lower PL1/PL2 values because score goes down to 10631 points when testing 50W/50W, whereas in either default 125W/150W or 4096/4096W I get a bit over 16400. HWinfo64 never reported more than 133W Package power in either of those, so I assume there were no changes.

**Screenshots**
Two screenshots attached.

**Additional context**
According to the Alder Lake Intel Firmware Support Package (FSP) Integration Guide: https://github.com/intel/FSP/blob/master/AlderLakeFspBinPkg/Docs/AlderLake_FSP_Integration_Guide.pdf

Most likely related to OcSupport as mentioned in 13.112.2.20, could be a global enable switch. Yet the OverclockingConfig.h mentioned there is not on the public repository...

![dasharo_intel-xtu_failure1](https://user-images.githubusercontent.com/32025193/177022916-4c8383a9-1ef1-470a-8c63-7abd0e109b5c.png)
![dasharo_intel-xtu_failure2](https://user-images.githubusercontent.com/32025193/177022918-10276f64-5c34-4c02-990e-0909a5647344.png)

**Comment by miczyg1** [comment]
Fixed with the two commits:

https://github.com/Dasharo/coreboot/commit/92967db1d5f422530bfc2936939cc00c6ab2eee7
https://github.com/Dasharo/coreboot/commit/e51c547abfaa5b19c1819fd1139a7e06d5859fef

Will be available in v1.1.1

**Comment by BeataZdunczyk** [comment]
Closing this issue as it has been resolved in the v1.1.1 release. Please refer to https://docs.dasharo.com/variants/msi_z690/releases/#v111-2023-02-23 for further details.
