### ISSUE TITLE
Display does not work with FreeBSD and other BSD systems

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#16]
**Dasharo version**
1.0.3-rc1

**Dasharo variant**
Firewall

**Affected component(s) or functionality**
Display in OS

**Brief summary**
FreeBSD does not display messages on the monitor, only on the serial console

**How reproducible**
100%

**How to reproduce**

1. Flash Dasharo FIrewall 1.0.4-rc1 on FW4 Geminilake
2. Boot the FreeBSD 
3. Observe garbaged screen

**Expected behavior**
FreeBSD displayed booting messages and login prompt

**Actual behavior**
FreeBSD displays garbaged screen instead of boot messages.

**Screenshots**
None

**Additional context**
Related issue: https://github.com/Dasharo/dasharo-issues/issues/13

**Solutions you've tried**
Same as in https://github.com/Dasharo/dasharo-issues/issues/13

**Comment by miczyg1** [comment]
Related to https://github.com/Dasharo/dasharo-issues/issues/13
Fixed by integrating UEFI payload.

**Comment by IgorBagnucki** [comment]
@miczyg1 You mentioned that this issue is fixed by now. Can this issue be closed?

**Comment by miczyg1** [comment]
Yes
