### ISSUE TITLE
USB Flash Drive made with Ventoy has a 10-15 second delay between Ventoy Boot Menu and OS Boot Loader

### ISSUE THREAD

**Issue by zirblazer** [Dasharo/dasharo-issues#160]
**Dasharo version**
Dasharo 1.0.0 for MSI PRO Z690-A WIFI DDR4

**Affected component(s) or functionality**
Behavior of a specific Software

**Brief summary**
Using the Ventoy tool to create a booteable USB Flash Drive and booting from at least the Linux LiveCD ISOs I tested has an unexplained delay that is not existant on the stock MSI Firmware.

**How reproducible**
100%

**How to reproduce**
1. Download Ventoy for Windows (Current version 1.0.78). Linux version untested yet
2. Unzip and execute Ventoy2Disk.exe

3. Format an USB Flash Drive (Will delete everything on it) with the following parameters from Option Menu:
Secure Boot Support (Comes on by default)
Partition Style GPT (Default is MBR)

4. After formatting, on File Explorer there should be a Windows accessible Disk Partition named Ventoy
Create a folder (I named mine ISO), and move there the testing Linux LiveCD ISOs
I'm using Ubuntu 22.04 (ubuntu-22.04-desktop-amd64.iso) and Arch Linux June 2022 (archlinux-2022.06.01-x86_64.iso)

5. Reboot computer, boot from the USB Flash Drive formatted with Ventoy
6. (One time only) If it is the first time booting Ventoy, you may have to enroll Ventoy Key manually and reboot: 
https://www.ventoy.net/en/doc_secure.html
7. The Ventoy Boot Menu will appear near instantly, it is an ISO selection screen
Selecting either Ubuntu or Arch Linux will result in a _ appearing on screen for 10-15 seconds
Afterwards, Ubuntu or Arch Linux Boot Loader menu appears normally

**Expected behavior**
On MSI stock 1.43 BIOS, the transition from Ventoy Boot menu to the OS Boot Menu is near instant

**Actual behavior**
Selecting either Ubuntu or Arch Linux ISOs will result in a _ appearing on screen for 10-15 seconds
Afterwards, Ubuntu or Arch Linux Boot Loader menu appears normally

**Solutions you've tried**
Tried with Secure Boot disabled and it behaves the same.

**Comment by miczyg1** [comment]
Confirmed the delay between Ventoy menu and GRUB menu of Ubuntu 22.04 ISO. Also the MOK enrollment doesn't seem to work when the menu pops up on Dasharo.

**Comment by Hypocrite1127** [comment]
I can also confirm the delay, but it's ~5 seconds on my machine. MOK enrollment works fine.

**Comment by miczyg1** [comment]
The reason for delay is the PS/2 keyboard driver, which polls for the keyboard to reset it, despite it is not present/plugged. This needs a fix. Interesting that MOK enrollment worked in your case...

**Comment by zirblazer** [comment]
I recall than the MOK enrollment system from the blue boxes menu when you boot with Secure Boot enabled actually worked the very first time I booted Ventoy, but not on any successive reflashes when going from Dasharo to MSI stock and viceversa. Had to enroll the keys from within Firmware. I have no idea WHY it worked, is not like there are many options to play with. However, my memory could also be wrong and I could have been using MSI Firmware.
The delay as stated above was already identified and workarounded in private, the only thing missing is pushing an official fix.

**Comment by zirblazer** [comment]
Confirming than the delays fully dissapeared on Dasharo v1.1.0.

Didn't tested Secure Boot enrollment.

**Comment by miczyg1** [comment]
> Confirming than the delays fully dissapeared on Dasharo v1.1.0.
> 
> Didn't tested Secure Boot enrollment.

Secure Boot enrollment still doesn't work apparently...

**Comment by zirblazer** [comment]
> Secure Boot enrollment still doesn't work apparently...

It seems to work fine as of 1.1.3 RC. MOK Manager can enroll properly Ventoy key and doesn't crash on the process.
