### ISSUE TITLE
support for Self-Encrypting Drives (SED) with TCG OPAL/TCG Enterprise

### ISSUE THREAD

**Issue by vlado2222** [Dasharo/dasharo-issues#161]
**The problem you're addressing (if any)**

Implement support for [Self-Encrypting Drives (SEDs)](https://en.wikipedia.org/wiki/Hardware-based_full_disk_encryption) with [TCG OPAL/TCG Enterprise](https://en.wikipedia.org/wiki/Opal_Storage_Specification).

**Describe the solution you'd like**

Menu in BIOS where you can enable/disable encryption, perform disk sanitisation, set drive groups that share the same password, etc. 
Then during boot-up you have to enter password to unlock a group of drives.

**Where is the value to a user, and who might that user be?**

There are many SSDs/HDDs which support hardware level encryption and currently I'm not aware of any "home consumer grade" motherboard which supports this.

**Describe alternatives you've considered**

Alternative is to use software based encryption which might provide better security at the expense of performance because it consumes CPU cycles.

**Additional context**

examples of SSDs with TCG OPAL: 
Crucial MX100/MX200/MX300/[MX500](https://www.crucial.com/products/ssd/crucial-mx500-ssd)
[Crucial P5 Plus NVMe](https://www.crucial.com/products/ssd/crucial-p5-plus-ssd)
Samsung [950 PRO](https://semiconductor.samsung.com/resources/data-sheet/Samsung_SSD_950_PRO_Data_Sheet_Rev_1_2.pdf); [960 PRO/EVO](https://semiconductor.samsung.com/resources/brochure/NVMe_SSD_960_PRO_EVO_Brochure_Rev_1_1.pdf); [970 PRO/EVO](https://semiconductor.samsung.com/resources/brochure/SSD_970_PRO_EVO_Plus_Brochure_210712.pdf); [980 PRO](https://www.samsung.com/semiconductor/global.semi.static/Samsung_NVMe_SSD_980_PRO_with_Heatsink_Datasheet_211101.pdf)
Samsung [840](https://support.rm.com/_rmvirtual/media/downloads/samsung_ssd_840_evo_data_sheet_rev_1_0.pdf)/[850](https://semiconductor.samsung.com/resources/data-sheet/Samsung_SSD_850_EVO_Data_Sheet_Rev_3_1.pdf)/[860](https://semiconductor.samsung.com/resources/data-sheet/Samsung_SSD_860_EVO_Data_Sheet_Rev1.pdf)/[870](https://semiconductor.samsung.com/resources/data-sheet/Samsung_SSD_870_EVO_Data_Sheet_Rev1.1.pdf) EVO
[SanDisk X400](https://www.sandisk.com/content/dam/sandisk-main/en_us/assets/resources/enterprise/data-sheets/X400-datasheet-v1-1.pdf)* only drives with SKU starting with SD8TB8U are SED drives*
some [Intel SSDs](https://www.intel.com/content/www/us/en/support/articles/000030541/memory-and-storage.html)

examples of HDDs with TCG Enterprise:
Western Digital UltraStar series
[Seagate enterprise drives](https://www.seagate.com/files/staticfiles/support/docs/manual/Interface%20manuals/100515636c.pdf)

**Comment by vlado2222** [comment]
@pietrushnic I have only two self-encrypting drives: SanDisk X400 and Seagate ST8000NM0115. The seagate holds data, so I can't use it for experiments. The biggest problem is that I don't own MSI PRO Z690-A mobo and I don't plan upgrading my PC in near future. It shouldn't be a problem for you to find TCG OPAL compatible drive. Most SSDs for business class laptops do support it. Otherwise, you can buy used Crucial MX100/MX300/MX500 or Samsung 840 EVO for less than 25 USD and a used SED HDD can be obtained for similarly low price.

Thank you very much for your efforts! Next time I'll be upgrading my PC I'll definitely look into Dasharo compatible motherboards.

**Comment by mkopec** [comment]
@miczyg1 

> lack of OPAL SED disks

We have a bunch of Samsung PRO and EVO disks at the office, they definitely support TCG OPAL

**Comment by miczyg1** [comment]
@mkopec feel free to test: https://github.com/Dasharo/edk2/blob/dasharo/UefiPayloadPkg/UefiPayloadPkg.dsc#L93

**Comment by mkopec** [comment]
OpalPasswordDxe does not build at the moment. Probably needs some fixing up after some of our recent changes?

**Comment by miczyg1** [comment]
Ahh yes, the PPi changes could break it. It looks like the QEMu PPI lib we use is missing the function outlined in the trace. Probably all you have to do is to copy it from `SecurityPkg/Library/DxeTcg2PhysicalPresenceLib/DxeTcg2PhysicalPresenceLib.c` to `OvmfPkg/Library/Tcg2PhysicalPresenceLibQemu/DxeTcg2PhysicalPresenceLib.c`

**Comment by vlado2222** [comment]
> There was research that UEFI implemented 'Sanitize' was in some cases badly implemented by vendors. Buggy. As in the GUI made you believe the drive was sanitized but when checking the drive there was still data on it. Be mindful when adding this. It might be feature creep and not worth the trouble if it doesn't work properly.

For example here is [article](https://threatpost.com/samsung-crucials-flawed-storage-drive-encryption-leaves-data-exposed/138838/) about discovered vulnerabilities in SED. In response Samsung and [Crucial](https://www.crucial.com/support/ssd/mx300-firmware-instructions) issued FW update to fix the reported vulnerabilities. Security is a constant cat-and-mouse game... a never-ending race. Even software based encryption can be broken. However software encryption is inherently easier to fix. 

If Dasharo successfully implements SED support, they could use it in their advantage and market their motherboards as the only* home consumer grade motherboards with SED support.

**Comment by pietrushnic** [comment]
@vlado2222 any chance you could test firmware if we would send you rc binary?

**Comment by pietrushnic** [comment]
> The biggest problem is that I don't own MSI PRO Z690-A mobo and I don't plan upgrading my PC in near future.

I guess we would rely on our own tests and we will close this issue based on that.

**Comment by mkopec** [comment]
> Now i need to use password to unlock the disk even before I can enter the BIOS Setup Menu. Is this expected?

Yes, that is expected with the current implementation

> After suspend, it fails to unlock I assume as I can see following (which was expected at this point):

That would be expected if the disk was powered off completely while in suspend (d3cold). In the future it's possible to explore disabling d3cold for the disk, since that shouldn't prevent the laptop from going to sleep, and would keep the disk unlocked in standby.

**Comment by macpijan** [comment]
So i run:

```
cat /sys/bus/pci/devices/0000\:01\:00.0/d3cold_allowed
1

sudo sh -c "echo 0 > /sys/bus/pci/devices/0000\:01\:00.0/d3cold_allowed"
cat /sys/bus/pci/devices/0000\:01\:00.0/d3cold_allowed
0
```

> if the laptop still goes to sleep

It looks like it does

> if the disk works after suspend

it works after suspend

**Comment by mkopec** [comment]
Nice. So it should be a pretty simple fix in firmware, I believe

**Comment by macpijan** [comment]
But it would consume a bit more energy this way?

**Comment by mkopec** [comment]
So the SSD itself would consume around 5mW in d3hot, so basically negligible. The PCIe link would also stay in a shallower standby state so it may consume a bit more power.

**Comment by rafkoch** [comment]
1. @vlado2222 I understand that your idea to "Implement support for [Self-Encrypting Drives (SEDs)](https://en.wikipedia.org/wiki/Hardware-based_full_disk_encryption) with [TCG OPAL/TCG Enterprise](https://en.wikipedia.org/wiki/Opal_Storage_Specification)" is done in this PR called "[Opal fixes](https://github.com/Dasharo/edk2/pull/27)" so in my opinion this task is ready to move to CLOSED status.

2. @mkopec I propose to put idea "to explore disabling d3cold for the disk, since that shouldn't prevent the laptop from going to sleep, and would keep the disk unlocked in standby." described [here](https://github.com/Dasharo/dasharo-issues/issues/161#issuecomment-1292171472) to the backlog.

**Comment by miczyg1** [comment]
Yes, this one can be closed already.
