### ISSUE TITLE
DTS should dump more information about the system (ME, ACM, TPM)

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#164]
**The problem you're addressing (if any)**

We should get more information from system we report hardware compatibility for. Information like ME, ACM and TPM.

**Describe the solution you'd like**

It should be researched what tools in Linux can get ME, ACM and TPM information.

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by kotylamichal** [comment]
At this time I found these tools:

- https://github.com/mjg59/mei-amt-check for ME, example output from README:
```
Intel AMT is present
AMT is provisioned
Flash: 9.5.40
Netstack:	9.5.40
AMTApps:	9.5.40
AMT:	9.5.40
Sku:	8200
VendorID:	8086
Build Number:	1892
Recovery Version:	9.5.40
Recovery Build Num:	1892
Legacy Mode:   False
```

- https://www.intel.com/content/www/us/en/download/19392/28632/intel-converged-security-and-management-engine-version-detection-tool-intel-csmevdt.html?v=t it may give some info about ACM but I'm not sure that will be enough

-`tpm_version` from `tpm-tools` package

**Comment by kotylamichal** [comment]
If I understand license things correctly, we cannot use https://github.com/mjg59/mei-amt-check GPL-2.0 software in our MIT `meta-dts-ce`

**Comment by pietrushnic** [comment]
@kotylamichal we can and there is zero issue with that. We do not include GPL code in MIT code, we use MIT code to compile and include GPL code. There is zero issue with that. Unless you think about some different usage. MIT Yocto layers compile and include in images GPL code all the time (e.g. U-Boot or Linux kernel).

**Comment by kotylamichal** [comment]
@miczyg1 maybe you can help here:

Intel [CSMEVDT](https://www.intel.com/content/www/us/en/download/19392/28632/intel-converged-security-and-management-engine-version-detection-tool-intel-csmevdt.html?v=t) tool do not return any data about ACM. Do you know any useful tools? Or which data about ACM do we need?

**Comment by kotylamichal** [comment]
@miczyg1 one more question: https://github.com/mjg59/mei-amt-check tool return info:

```
Error: Management Engine refused connection. This probably means you don't have AMT
```
when I run it on laptop NS51MU - is that correct? On my HP desktop AMT is detected as provisioned  and return  some data like AMT, SKU, VendorID

**Comment by macpijan** [comment]
> Intel [CSMEVDT](https://www.intel.com/content/www/us/en/download/19392/28632/intel-converged-security-and-management-engine-version-detection-tool-intel-csmevdt.html?v=t) tool do not return any data about ACM. Do you know any useful tools? Or which data about ACM do we need?

It depends on the platform and firmware. Not each platform has ACM at all.
None of the Dasharo released firmware has ACM.

**Comment by macpijan** [comment]
> when I run it on laptop NS51MU - is that correct?

yes

**Comment by kotylamichal** [comment]
@macpijan ok, thanks for the answer. There is only one question left:

That Intel [CSMEVDT](https://www.intel.com/content/www/us/en/download/19392/28632/intel-converged-security-and-management-engine-version-detection-tool-intel-csmevdt.html?v=t) tool - I'm not sure about their close license. Can you verify that we can use it in our Yocto build? If not, I have a second idea: it's just python script(s), so we can add question in `dts` script - something like:

```
Do you want to download Intel CSMEVDT property tool, execute it and send logs from that software to dasharo.com? [Y/n]
```

**Comment by miczyg1** [comment]
https://github.com/mjg59/mei-amt-check may be good for AMT. ME information can be dumped either from sysfs or using intelmetool from coreboot utilities.

ACM information? Which information and what for? I can't see a use case here. If we dump the firmware binary, it will either contain ACM or not. Further parsing of the ACM can be done later if needed.

**Comment by miczyg1** [comment]
> @miczyg1 one more question: https://github.com/mjg59/mei-amt-check tool return info:
> 
> ```
> Error: Management Engine refused connection. This probably means you don't have AMT
> ```
> 
> when I run it on laptop NS51MU - is that correct? On my HP desktop AMT is detected as provisioned and return some data like AMT, SKU, VendorID

This utility has latest commit dated on 2018, it may not support latest Management Engines and AMT.

**Comment by kotylamichal** [comment]
@TomaszAIR 

Ok, so the current status of how we dump data:

- TPM info was copied from `/sys/class/tpm/` it is more reliable than dump `tpm_version`, which does not work for me on NV laptop (maybe because it is not a tool for tpm2?)
- ME info is from `intelmetool -m`
- We don't need ACM data so I skip this
- AMT: as @miczyg1 maybe it not support latest ME/AMT but it was not in the scope of this issue, so I do not look for a better solution. `mei-amt-check` still is in the `dasharo-hcl-report`, it may be useful

**Comment by TomaszAIR** [comment]
@kotylamichal README of met-amt-check says it is heavily based on https://github.com/torvalds/linux/blob/master/samples/mei/mei-amt-version.c which is from ~2021, maybe we could use this one? Did you research that?

**Comment by kotylamichal** [comment]
@TomaszAIR no, because initially, it was not in the scope of this issue. Should I look at it and try to update `mei-amt-check` tool?

**Comment by TomaszAIR** [comment]
@kotylamichal let's give it a try.

**Comment by kotylamichal** [comment]
@TomaszAIR I compared it to the latest kernel [sample](https://raw.githubusercontent.com/torvalds/linux/master/samples/mei/mei-amt-version.c) - there are no crucial differences between this and `mei-amt-tool`. Support of old or new versions of AMT depends on kernel and driver which create `/dev/mei` device. That tool just reads data from it.

So, in my opinion, this is not worth required effort and we can skip that for now

**Comment by TomaszAIR** [comment]
Ok, thanks for checking that. Let just leave `mei-amt-check` tool then.

**Comment by rafkoch** [comment]
I moved this issue (card) to DONE column in project "Nlnet October 2022", because its status is CLOSED.
Moreover both PR's are merged.
