### ISSUE TITLE
DTS should recognize not only IBV firmware but also Dasharo and other open-source firmware

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#165]
**The problem you're addressing (if any)**

It is very important to use HCL for reporting already working Dasharo hardware, so we should work perfectly fine while booting Dasharo or any other open-source firmware.

With coreboot based firmware we should definitely try to dump `cbmem` output.

**Describe the solution you'd like**

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by TomaszAIR** [comment]
@kotylamichal I left review, I think every coreboot based fw should be able to dump `cbmem` output so lets just do that. In other cases we will just get an error or something like that which is fine.

**Comment by TomaszAIR** [comment]
Review addressed, issue closed by merging meta-dts-ce#8

**Comment by rafkoch** [comment]
I moved this issue (card) to DONE column in project "Nlnet October 2022", because its status is CLOSED.
Moreover PR is merged.
