### ISSUE TITLE
DTS CE version should have ability to backup and recover BIOS

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#166]
**The problem you're addressing (if any)**

DTS CE flashed on USB should be able to backup BIOS (it can be through HCL report stored locally). It also should be able to recover/rollback from USB stored HCL report original BIOS. Rollback/recovery should be available only if compatible binary was detected.

Network booted DTS CE should provide that option only for Dasharo Bronze Patreons, what means all users who paid directly or indirectly Dasharo Subscription.

**Describe the solution you'd like**

**Where is the value to a user, and who might that user be?**

This should improve and simplify documentation of all Dasharo implementation for all supported hardware. It also makes OEM and end user operation seamless.

**Describe alternatives you've considered**

**Additional context**

**Comment by esesyn01** [comment]
@TomaszAIR As I see this, for now, I think first we have to close issue #220. Then, having a UUID somewhere in the system and a key which is for Dasharo Bronze Patreons, there will display a new menu entry `3) Rollback BIOS from HCL report`. If the local or USB-stored HCL report has the same UUID in its name, the automatic restoring will start.

**Comment by kotylamichal** [comment]
@TomaszAIR I cannot do more now, but it may be a good base for the final script: https://github.com/Dasharo/meta-dts-ce/pull/15/files

example output:
```
//Fri, 28 Oct 2022 150755 GMT
/nowy.md/Fri, 28 Oct 2022 150739 GMT
/test2.odt/Fri, 28 Oct 2022 135517 GMT
/test3.md/Fri, 28 Oct 2022 150755 GMT
/testfolder//Fri, 28 Oct 2022 140434 GMT
```
of course, we need to fix formatting with that slashes and grep out non-tar files because here is part of status frame, and folders also are listed too
