### ISSUE TITLE
The inconvenience of using external headsets VP46XX v.1.0.16

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#167]
**Dasharo version**
v.1.0.16

**Dasharo variant**
Protectli vp46xx

**Affected component(s) or functionality**
Jack slot, external headsets or headphones

**Brief summary**
After connect the headset to the device nothing happen, the need to manually turn on the headphones and microphone

**How reproducible**
100%

**How to reproduce**

1. Boot into System.
2. Connect the headset.
3. Run [youtube ](https://www.youtube.com/) for testing headphones and [mic check](https://www.onlinemictest.com/) for testing microphone.

**Expected behavior**
After connect headset on both Windows and Ubuntu should be displayed windows with information about connected headset or information, that something is plugged in Jack slot. The sound in the headphones should turn on automatically (on Ubuntu turns on), and microphone also.

**Actual behavior**
After connect the headset to the device nothing happen, only on Ubuntu sound in the headphones turned on automatically but microphone on both system not. 

**Screenshots**

**Additional context**
Windows 11, Ubuntu 22.04, Ubuntu 20.04

**Solutions you've tried**
Ubuntu -> Settings -> Sound, and change input device to turn on connected microphone.
Windows 11-> Settings -> System -> Sound -> All sound devices, then I test all output and input devices and the one that works, I set it to default

**Comment by Pokisiekk** [comment]
Boot with HDMI display -> HDMI audio by default (exactly Intel(R) Display Audio)
Boot with HDMI display and headset -> HDMI audio by default
Boot with Display Port -> Speakers audio by default, when attach headset, it work but tomorrow this didn't work like now.
Boot with Display Port and headset -> Speakers audio by default
When speakers audio is set by default and change the display output from Display Port to HDMI, Windows change default option to HDMI audio.

**Comment by miczyg1** [comment]
> When speakers audio is set by default and change the display output from Display Port to HDMI, Windows change default option to HDMI audio.

This is rather expected, the same happens on many devices I own too.

> Boot with Display Port -> Speakers audio by default, when attach headset, it work but tomorrow this didn't work like now.
> Boot with Display Port and headset -> Speakers audio by default

Display port has no audio so this is understandable and expected.

> Boot with HDMI display -> HDMI audio by default (exactly Intel(R) Display Audio)
> Boot with HDMI display and headset -> HDMI audio by default

So it seems Windows prefers HDMI Audio over everything else. Still I am not sure if HDA verbs will help @mkopec

**Comment by miczyg1** [comment]
I wouldn't say it is an issue... Just Windows' defaults may not be everybody's defaults...

**Comment by Pokisiekk** [comment]
I did additional audio tests:
Windows 11, Vendor firmware - works and the sound switches automatically after plugging in the headphones - but there are still no notifications
Windows 11, Dasharo firmware - previously checked: https://github.com/Dasharo/dasharo-issues/issues/167#issuecomment-1184143486
Ubuntu 22.04, Vendor firmware - works and the sound switches automatically after plugging in the headphones - but there are still no notifications
Ubuntu 22.04, Dasharo firmware - doesn't work (it worked before), I do not know what this may be caused by, the changes are that I tested with a connected DP, not HDMI as before because I didn't have any HDMI output after installing the system and I also used other headphones.
However, I checked how it looks on Ubuntu 20.04 in this configuration and the headphones work normally there.

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/protectli_vp46xx/releases/#v110-2023-06-05) are the binaries in version v.1.1.0 for VP4670, on which the issue does not occur
