### ISSUE TITLE
Talos II : Heads console output only on BMC console, not VGA

### ISSUE THREAD

**Issue by tlaurion** [Dasharo/dasharo-issues#168]
Version: unreleased (after 0.5. To be edited with precision upon next release)

Latest tests with unreleased version supported my single CPU! Hurray! (More testing later end of month... Other reports?)

Current issue now is to have Heads payload output to vga console, which seems to miss either AST+DRM in kernel config and/or proper skiboot passed arguments.

Off-channel notes:
- To have kgpe-d16 FBwhiptail, the following was needed: https://github.com/osresearch/heads/blob/master/config/linux-kgpe-d16_server-whiptail.config#L172-L174 with linux config supporting both DRM and AST: https://github.com/osresearch/heads/blob/master/config/linux-kgpe-d16_server-whiptail.config#L172-L174
- The following was needed to be passed to have output to bmc in headsless config https://github.com/osresearch/heads/blob/master/config/coreboot-kgpe-d16_server.config#L15

_Originally posted by @tlaurion in https://github.com/Dasharo/dasharo-issues/issues/80#issuecomment-1184522663_

**Comment by SergiiDmytruk** [comment]
This is more complicated than it seems.

Used petitboot’s config for reference as it appears on VGA console. After enabling more drivers VGA somewhat works, but it doesn't always show up. usb-init enables VGA console when it's off. This dependency is at least partially explained by:
```
[   27.662570] input: OpenBMC virtual_input as /devices/pci0003:00/0003:00:00.0/0003:01:00.0/usb1/1-3/1-3.1/1-3.1:1.0/0003:1D6B:0104.0001/input/input0
[   27.733295] hid-generic 0003:1D6B:0104.0001: input: USB HID v1.01 Keyboard [OpenBMC virtual_input] on usb-0003:01:00.0-3.1/input0
[   27.751772] input: OpenBMC virtual_input as /devices/pci0003:00/0003:00:00.0/0003:01:00.0/usb1/1-3/1-3.1/1-3.1:1.1/0003:1D6B:0104.0002/input/input1
[   27.769055] hid-generic 0003:1D6B:0104.0002: input: USB HID v1.01 Mouse [OpenBMC virtual_input] on usb-0003:01:00.0-3.1/input1
```

The second console is separate from the text one (hvc0 is text and VGA is tty0 and tty1).  When petitboot is in use, text and VGA consoles run two independent instances of petitboot.  Likely need to do the same for Heads in init scripts.

`usb-init` followed by `setsid gui-init > /dev/tty0 2>&1 < /dev/tty0 &` seems to work, but ignores keyboard sometimes. Bash run like this complains that it `can't access tty`, which might explain input issues.

Here's WIP image [zImage.bundled.gz](https://github.com/Dasharo/dasharo-issues/files/9159039/zImage.bundled.gz), but there is still things to do:
 * why console doesn't always work
 * why input isn't always processed after USB is on
 * modify init scripts to always load USB modules (in the right order, currently kernel prints warnings about it, but it's an old Heads revision) and start on multiple consoles

**Comment by tlaurion** [comment]
Some quick notes on Heads.

If USB keyboard is needed, it needs to be defined under board config otherwise HID module is not loaded. 
HID is desired as module and not to be build in kernel

https://github.com/osresearch/heads/pull/1145

**Comment by krystian-hebel** [comment]
Is it possible that similar issue is present on other platforms but no one notices, as they have real USB keyboard connected and HID driver is always loaded?

**Comment by tlaurion** [comment]
@krystian-hebel all ps2 offering platforms removed USB HID in past Heads PR.

Not so relevant here since Talos II doesn't offer ps2 ports for keyboard and mouse, only USB.

But for platforms offering ps2 connectivity, HID should be optional and declared as such in separate usb-keyboard board option (important for Qubes sys-usb creation with exclusive access on that seperate controller).

Sorry, brain slow today.

**Comment by SergiiDmytruk** [comment]
Seems to work now, at least screen and input is initialized every time in latest tests. [Changes](https://github.com/osresearch/heads/pull/1002/files/bec3000767b9dfdfda12d08b453c07619b01ee97..29003aa9d4405e6c26fae4114d01b30340e6200e) are in three new commits in https://github.com/osresearch/heads/pull/1002. Mind that the PR has an old base and building USB_HID as a module won't work there.

New image: [zImage.bundled.gz](https://github.com/Dasharo/dasharo-issues/files/9169744/zImage.bundled.gz)

**Comment by macpijan** [comment]
I can confirm the VGA output works in the OpenBMC KVM with the updated heads. See attached screenshot:

![Uploading 2022-07-27T21:26:04,844850519+02:00.png…]()
