### ISSUE TITLE
Dasharo coreboot repository doesn't seem to be good place for binary blobs

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#17]
**The problem you're addressing (if any)**

It is rather a bad idea to keep binaries inside coreboot repositories. Those should be separated. Do we know are the licenses for distributing those binaries?

**Describe the solution you'd like**

Create separate repo if the binary redistribution license allows that, if not use binary extraction scripts that help build target Dasharo release for a given platform.

**Where is the value to a user, and who might that user be?**

There is no legal confusion about binaries redistribution.

**Describe alternatives you've considered**

**Additional context**

**Comment by macpijan** [comment]
We store the blobs here already: https://github.com/Dasharo/dasharo-blobs
