### ISSUE TITLE
Q: Support for Alder Lake laptops

### ISSUE THREAD

**Issue by jmacato** [Dasharo/dasharo-issues#174]
**Question text**

Hey folks! Super awesome job with bringing up coreboot to a very modern platform! I've been waiting for this a long time haha (also kinda sick of being stuck with old and slow hardware just to have a better and more trustable TCB...)

Anyways, for my question: Is it possible to support Alder lake laptops with Dasharo/Coreboot? Sorry if the question is too broad but yeah. It'll be fun to see a modern gaming laptop with this firmware.. or perhaps yet another Thinkpad :)

**Comment by miczyg1** [comment]
We might have something coming soon. Stay tuned :)
