### ISSUE TITLE
Ultrawide resolution support in setup menu

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#177]
**The problem you're addressing (if any)**

TianoCore setup menu is displayed in 16:9 on an ultrawide display, causing pillarboxing

**Describe the solution you'd like**

Support for ultrawide (21:9 and beyond) aspect ratio

**Where is the value to a user, and who might that user be?**

- Fullscreen setup menu on ultrawide displays
- Smoother Linux booting (console doesn't move on GPU driver load)

**Describe alternatives you've considered**

n/a

**Additional context**

The monitor's OSD tells me that it's displaying at native resolution (3440x1440)

Tested on Lenovo ThinkCentre M700 (integrated GPU + libgfxinit)

Photo:
![20220731_133814](https://user-images.githubusercontent.com/3678707/182024728-0467010f-bdb7-436f-a23b-77333116c160.jpg)

**Comment by mkopec** [comment]
While we're at it, we could also change the font size in TianoCore, it's hard to read on large resolution displays :)

**Comment by miczyg1** [comment]
I believe the fonts are hardcoded here: MdeModulePkg/Universal/Console/GraphicsConsoleDxe/LaffStd.c

Question is how to make them larger... Standard glyph cell is 8x19 pixels. Everything would have to be changed including the hardcoded font.

**Comment by mkopec** [comment]
Looks like this is no longer an issue on `common-base-4.21` and latest Dasharo edk2.
