### ISSUE TITLE
MSI PRO Z690-A WIFI DDR4 with certain discrete Video Card (Radeon 5600XT) slow down graphics performance to a crawl during POST and early boot

### ISSUE THREAD

**Issue by zirblazer** [Dasharo/dasharo-issues#181]
**Dasharo version**
Dasharo v1.0.0 for MSI PRO Z690-A WIFI DDR4

**Affected component(s) or functionality**
Whatever takes care Firmware side of loading and initializing the Video Card Option ROM

**Brief summary**
I currently have two 5600XT (MSI Radeon RX 5600 XT GAMING X) with latest VBIOS (GPU-Z dump matches https://www.techpowerup.com/vgabios/220715/msi-rx5600xt-6144-200405 ) installed, but also happens with only one.
Loading the Option ROM works, and if a Monitor is plugged to either card I see Firmware related screens. However, with the card installed, the graphical performance during POST and before booting an OS is disastrous, up to the point that you can actually see how text and graphics in the Setup Menu are draw to screen as blocks. This also affects usability, since in the Setup menu, moving around highlighting options takes a while, and it instead appears as if it buffers keyboard input. The timeout bar during Dasharo splash screen that usually last 3 seconds takes more than twice to be draw to screen, as if everything was waiting for GPU to finish drawing first. Ventoy also slowly fills the screen with its splash screen.
After it finally loads something else (Not sure if GRUB, but at least after the OS side GPU Drivers are loaded), performance seems to resume as normal. Albeit just visually, I didn't bothered to benchmark yet.

**How reproducible**
100%

**How to reproduce**
Install my exact card on the Motherboard and turn it on. No idea how many cards could be affected.

**Expected behavior**
Same graphical performance during Firmware code than as if the card wasn't installed.

**Actual behavior**
See Brief summary.

**Screenshots**
I could potentially record this with a smartphone, but I don't think it will be helpful.

**Additional context**
Secure Boot was tested both Enabled and Disabled. No changes.

**Solutions you've tried**
I'm too lazy to dissamble the productivity computer to swap the 5600XT for the previous generation Radeon RX 570 just to see if it happens with a Polaris era card.
Also, after booting, dmesg on Dasharo reports that amdgpu "fetched VBIOS from ROM" whereas on MSI BIOS 1.70 it says "fetched VBIOS from VFCT" instead, which may be related to the Option ROM performance issue. I have no idea if there is an AMD standard that requires Option ROM to be copied to the ACPI VFCT Table during Firmware POST instead of executing directly or whatever else, but is the only hint I found.

**Comment by zirblazer** [comment]
Well, I dissambled both systems and tested with a single MSI Radeon RX 570 4G ARMOR OC with this VBIOS: https://www.techpowerup.com/vgabios/198234/msi-rx570-4096-171109
It worked with no issues in either slot. Will try inserting a single 5600XT next, since all my tests were with two.

**Comment by zirblazer** [comment]
Attached logs from:

cbmem -1
dmesg
lspci -nnvvvxxx

With a single 5600XT on the main 16x slot, single 5600XT on second 16x slot, and two on both slots.


[1x5600xt_1stslot_cbmem.log](https://github.com/Dasharo/dasharo-issues/files/9428424/1x5600xt_1stslot_cbmem.log)
[1x5600xt_1stslot_dmesg.log](https://github.com/Dasharo/dasharo-issues/files/9428425/1x5600xt_1stslot_dmesg.log)
[1x5600xt_1stslot_lspci-nnvvvxxxx.log](https://github.com/Dasharo/dasharo-issues/files/9428426/1x5600xt_1stslot_lspci-nnvvvxxxx.log)
[1x5600xt_2ndslot_cbmem.log](https://github.com/Dasharo/dasharo-issues/files/9428427/1x5600xt_2ndslot_cbmem.log)
[1x5600xt_2ndslot_dmesg.log](https://github.com/Dasharo/dasharo-issues/files/9428428/1x5600xt_2ndslot_dmesg.log)
[1x5600xt_2ndslot_lspci-nnvvvxxxx.log](https://github.com/Dasharo/dasharo-issues/files/9428429/1x5600xt_2ndslot_lspci-nnvvvxxxx.log)
[2x5600xt_twoslots_cbmem.log](https://github.com/Dasharo/dasharo-issues/files/9428430/2x5600xt_twoslots_cbmem.log)
[2x5600xt_twoslots_dmesg.log](https://github.com/Dasharo/dasharo-issues/files/9428431/2x5600xt_twoslots_dmesg.log)
[2x5600xt_twoslots_lspci-nnvvvxxxx.log](https://github.com/Dasharo/dasharo-issues/files/9428432/2x5600xt_twoslots_lspci-nnvvvxxxx.log)

**Comment by miczyg1** [comment]
My 6500XT card doesn't work at all in the firmware. Display starts working only in OS.

**Comment by miczyg1** [comment]
> My 6500XT card doesn't work at all in the firmware. Display starts working only in OS.

This one fixes my issue: https://github.com/Dasharo/edk2/pull/37

**Comment by zirblazer** [comment]
There are no slow downs during Firmware boot or setup menu with both 5600XT installed on Dasharo v1.1.0. Didn't tested with only one.

Note than everything works properly right after a power cycle, but video performance during Firmware stages is around equal or even worse than before and appears to hang if doing warm reboots under Linux (Tested with a 2 years old Arch Linux install and Ubuntu 22.04.1 LiveCD). Rebooting under Windows 11 works properly, after many reboots there are no slowdowns.
Is important to note, on Windows 11 I'm running with the second 5600XT disabled in Device Manager due to the 2x5600XT issue which remains unsolved, whereas in Linux amdgpu does bring it up. So I would think than the second GPU may be left in a broken state after drivers initialize it.

**Comment by zirblazer** [comment]
I have been thinking than the symptoms are EXTREMELY similar to what I recall that happened with PCI Passthrough on Xen / QEMU-VFIO, where it was suggested to dump the Option ROM of the card and sideload it on VM launch because in many cases, the card was only good for passthroughing a single time and you had to power cycle to not suffer slowdowns or quirky behavior, which seems to be because the Option ROM was modified in-memory after execution. Sounds familiar?

**Comment by miczyg1** [comment]
> I have been thinking than the symptoms are EXTREMELY similar to what I recall that happened with PCI Passthrough on Xen / QEMU-VFIO, where it was suggested to dump the Option ROM of the card and sideload it on VM launch because in many cases, the card was only good for passthroughing a single time and you had to power cycle to not suffer slowdowns or quirky behavior, which seems to be because the Option ROM was modified in-memory after execution. Sounds familiar?

Xen/QEMU-VFIO should pass the VFCT ACPI table too with the OptionROM memory reported in the table. Otherwise there may be some problems.

**Comment by zirblazer** [comment]
After major troubleshooting, this ended up being traced back to the USB Hub issue. I almost always have two USB Flash Drives plugged in, one in a Port on the 4-Port column that is wired on the USB Hub, and the other in one of the front USB headers. Moving the USB Flash Drive from the 4-Port column to the second front USB actually solved the issue, so there are no more performance slowdown issues on Firmware stages with 2x5600XT installed.
For reference, warm reboots on Windows works properly, but a warm reboot on Linux leaves something related to that USB Port/Hub in a bad state. But I suppose that should be troubleshooted separately, as the issue is not the 2x5600XT themselves any longer.
