### ISSUE TITLE
Popup with information about recovery mode is displayed after flashing with a valid binary NS50/70 v1.3.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#185]
**Dasharo version**
v.1.3.0

**Dasharo variant**
NS50/70

**Affected component(s) or functionality**
internal flashing, vboot

**Brief summary**
Popup with information about recovery mode is displayed after flashing with a valid binary, but only one time.

**How reproducible**
100% - after noticed the problem

**How to reproduce**

1. Power on the laptop.
2. Boot into Ubuntu 20.04.
3. Flash coreboot signed with wrong vboot keys by executing the following command:
`flashrom -p internal --fmap -i RW_SECTION_A -w [coreboot binary]`
4. Power off and then power on the laptop.
5. Boot into Ubuntu 20.04.
6. Flash dasharo firmware by executing the following command:
`flashrom -p internal --ifd -i bios -w novacustom_ns5x_v1.3.0.rom`
7. Power off and then power on the laptop.

**Expected behavior**
The laptop boots normal, BIOS_KEYS are displayed.

**Actual behavior**
Popup with information about recovery mode is displayed.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by miczyg1** [comment]
> ~50% - hard to judge

So it does not always happen? I would understand if it was always one time, because the platform has to boot first to clear the recovery request. @mkopec that is how it works I guess?

**Comment by Pokisiekk** [comment]
@miczyg1 This isn't a test case and for the first boot after flashing I didn't experience it, but I didn't look at it either, hence the assessment 
After the problem was noticed, it appeared constantly

**Comment by miczyg1** [comment]
> @miczyg1 This isn't a test case and for the first boot after flashing I didn't experience it, but I didn't look at it either, hence the assessment After the problem was noticed, it appeared constantly

If so, the report should be updated with the confirmed information. If I understand correctly the platform is stuck in recovery mode?

**Comment by Pokisiekk** [comment]
The problem occurs only after the first boot after flashing, a popup appears with the information about recovery mode (I can click Enter) - there is no problem with the next boots

**Comment by mkopec** [comment]
@miczyg1 Perhaps we should trigger an additional reset after clearing the recovery request? In any case, logs including booting from recovery, flashing "good" firmware, rebooting (into recovery), and rebooting again (into slot A) would help understand this. Something to consider when fixing this later

**Comment by Pokisiekk** [comment]
The problem was due to an incorrect flashing approach, dasharo firmware in step 6 should be flashed by executing `flashrom` command with `--famp -i RW_SECTION_A` instead of `--ifd -i bios`. The problem doesn't occur in this configuration.
