### ISSUE TITLE
Talos II - Where to buy assembled TPM module?

### ISSUE THREAD

**Issue by tlaurion** [Dasharo/dasharo-issues#192]
Otherwise, Heads is not Heads on Talos II :(

**Comment by macpijan** [comment]
This is the TPM board we have used for development/testing which can be obtained and connected via a few jumper wires: https://www.mouser.pl/ProductDetail/Infineon-Technologies/IRIDIUM9645TPMI2CTOBO1?qs=W0yvOO0ixfHgfd%2FpOiiiXQ%3D%3D

The TPM PCB for this module was designed and  is available here: https://github.com/3mdeb/talos-tpm-module

I expect to have a few samples produced for testing soon.

**Comment by macpijan** [comment]
The test batch of modules arrived at our place. Another rework was required so the connector matches properly to the board's connector.

Finaly, when reworked module is instedted this way to the board, it does operate correctly:

![1666250187086](https://user-images.githubusercontent.com/19353650/198990063-b4a88a65-9198-49da-b0e8-b21378999e39.jpg)

We have already made relevant changes in the v1.1 design: https://github.com/3mdeb/talos-tpm-module so it looks like this: 
![Image Pasted at 2022-10-21 11-35](https://user-images.githubusercontent.com/19353650/198990207-0d47aa86-c47f-4454-bc3b-688d82472e0c.png)

We should be able to put in store a few reworked 1.2 modules from the test series, as they still should be usable modules.
It should happen this week.

**Comment by macpijan** [comment]
Module from the first bath is available in the shop: https://3mdeb.com/shop/modules/tpm-1-2-compatible-with-raptor-computing-systems-talos-ii-mainboard/
