### ISSUE TITLE
Keyboard backlight turns off automatically

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#195]
**Dasharo version**

1.3.0

**Dasharo variant**

NS70MU

**Affected component(s) or functionality**

Probably EC firmware

**Brief summary**

Keyboard backlight turns OFF automatically once turned ON.

**How reproducible**

100%

**How to reproduce**

1. Keyboard backlight is OFF by default
2. Turn keyboard backlight ON
3. Keyboard backligh turns OFF automatically after some time (around 30s)

**Expected behavior**

- the preference is to have ON be default - on low brightness
- it should remain set to ON when switched ON

**Actual behavior**

- Keyboard backlight is OFF by default, no matter what the previous setting was.
- Keyboard backligh turns OFF automatically after some time (around 30s)

**Screenshots**

**Additional context**

**Solutions you've tried**

none

**Comment by mkopec** [comment]
@macpijan Which OSes are affected? I'm not seeing this behavior on Ubuntu 22.04

**Comment by wessel-novacustom** [comment]
The issue was submitted on my behalf.

I have to be more specific about the problem.

But at least on all devices, we would like the keyboard backlight state to be saved (and restored after suspend or S0 turned-off).

**Comment by macpijan** [comment]
@wessel-novacustom There were two issues reported as I understood:
1. Keyboard backlight is not saved between reboots (this one is clear)
2. Keyboard backlight turns off automatically once it was set to some value

Could  you please clarify whether the issue `2` is valid?

**Comment by wessel-novacustom** [comment]
2 is not applicable any longer. Please only proceed with issue 1.

**Comment by macpijan** [comment]
Thanks for clarification
