### ISSUE TITLE
Dasharo Tools Suite reports errors on the screen when booting

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#196]
**Dasharo version**

v1.0.1

**Dasharo variant**

**Affected component(s) or functionality**

Dasharo Tools Suite

**Brief summary**

Some errors/warnings just after the boot
It is distracting for the user

**How reproducible**

100%

**How to reproduce**

1. Boot DTS
2. Observe the screen for unnecessary error/warning messages

**Expected behavior**

There is no error/warnings visible to the user, which
are concerning and can also clutter the selection menu.

**Actual behavior**

There are unnecessary messages presented to the user.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment]
@TomaszAIR This is report from the customer, so I do not have screenshots. Please see if these can be muted for the next release.

**Comment by macpijan** [comment]
![1663661812399](https://user-images.githubusercontent.com/19353650/191205380-81f35be2-ac4b-46d9-afd6-d0f969c3cf6d.jpg)

@TomaszAIR Attched screenshot. Can we get rid of these netdev information from the main screen? It is polluting the input for of a customer.

**Comment by TomaszAIR** [comment]
Yes, we will try to silence those kind of logs from the terminal. Changes will be released with DTS-CE v1.0.2

**Comment by TomaszAIR** [comment]
![1665746190250](https://user-images.githubusercontent.com/46576094/195834609-1a58b6ae-49e8-4a11-9091-07a10b0f974c.jpg)

Fixed in v1.0.2 available from http://boot.3mdeb.com/dts.ipxe. Photo above taken right after booting to the system with ethernet cable connected. Could you verify and close the issue if happy with results?

**Comment by wessel-novacustom** [comment]
This has been solved indeed, thank you.

**Comment by TomaszAIR** [comment]
Thank you! Ok, so I will close this issue.

@macpijan cc
