### ISSUE TITLE
Customizable fan curve (fan profiles)

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#197]
**The problem you're addressing (if any)**

Some users prefer silent laptop over the performance (caused by throttling). Some the other way around.

**Describe the solution you'd like**

Customizable fan curve to be selected by users.

**Where is the value to a user, and who might that user be?**

Laptop user should be happy about performance/silence ratio according to one's preferences.

**Describe alternatives you've considered**

Maybe to have at least two profiles (performance and silent) to select in the firmware menu.
That should satisfy most of the users on the very basic level in terms of the fan curves modification.

**Additional context**

**Comment by wessel-novacustom** [comment]
Just to clarify: some users prefer to have good performance and can accept some fan noise, while most users will prefer a bit more throttling but a fan that can not or barely be heard.

So I would suggest a BIOS option where you can select Quiet or Entertainment as performance profile, where Quiet is the standard.

OS independence is important, I believe.

This should be seen differently from any ideas to overwrite CPU and fan settings from the operating system.

**Comment by macpijan** [comment]
Two fan profiles selectable via firmware menu was already implemented for NovaCustom models: https://docs.dasharo.com/unified/novacustom/fan-profiles/

Setting these from OS is tracked here: https://github.com/Dasharo/dasharo-issues/issues/424
