### ISSUE TITLE
Waking up from sleep on Ubuntu 22.04 is not 100% reliable

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#205]
**Dasharo version**
v1.3.0, v1.4.0

**Dasharo variant**
NV41MZ/MB, NS70PU, NS5xMU

**Affected component(s) or functionality**
Waking up from sleep

**Brief summary**
Attempting to wake the DUT from sleep using keyboard fail when using the touchpad earlier during sleep.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT
2. Boot Ubuntu 22.04.
3. Press `Fn+F12` or press power button.
4. After a while, use touchpad in any way.
5.  Click any button on the keyboard.

**Expected behavior**
The DUT will wake up from sleep and the system will ask for a password.

**Actual behavior**
The DUT won't wake up from sleep.

**Solutions you've tried**
Press power button to wake up from sleep

**Comment by Pokisiekk** [comment]
I updated the issue due to deeper investigation of the problem, also on other models.

**Comment by macpijan** [comment]
I do not quite get this report.
It says: `Waking up from sleep on Ubuntu 22.04 is not 100% reliable` and it says it is `100% reproducible`. But I can wake my device up, and I'm sure you do as well.

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/novacustom_ns5x_adl/releases/#v160-2023-04-07) are the binaries in version v.1.6.0 for NS5x/7x ADL, on which the issue does not occur

**Comment by wessel-novacustom** [comment]
This issue no longer occurs and needs to be closed.

**Comment by PLangowski** [comment]
I can confirm that the issue no longer occurs as of Dasharo `v1.5.2`
