### ISSUE TITLE
BIOS lock feature (configurable via Setup Menu option) should be enabled for all vboot platforms

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#209]
**The problem you're addressing (if any)**

Dasharo should aim for having 100% common code across platforms.
Features can be configured via configuration options, but not via adding code to certain branches.

**Describe the solution you'd like**

The solution was introduced here, for example:
- https://github.com/Dasharo/coreboot/pull/166/files
- https://github.com/Dasharo/coreboot/pull/184/files
- https://github.com/Dasharo/DasharoModulePkg/pull/1/files
- https://github.com/Dasharo/DasharoModulePkg/pull/2/files
- https://github.com/Dasharo/edk2/pull/19/files

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by macpijan** [comment]
Just for more context, the documentation on testing this feature is here: https://docs.dasharo.com/unified-test-documentation/dasharo-security/20J-bios-lock-support/

**Comment by wessel-novacustom** [comment]
It has been implemented: https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#dasharo-security-options

The issue should be closed.
