### ISSUE TITLE
All firmware releases supporting vboot should be signed with Dasharo keys

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#210]
**The problem you're addressing (if any)**

Today, most of the binaries we publish use vboot development keys and we instruct users to re-signed later if desired.

**Describe the solution you'd like**

By defeault, we should use Dasharo vboot keys for signing (leving the re-sign option for interested users, of course).

**Where is the value to a user, and who might that user be?**

The default security for user increases, as they will not be able to apply random update (as the DEV keys are publicly available).

**Describe alternatives you've considered**

**Additional context**

**Comment by pietrushnic** [comment]
@macpijan @miczyg1 I'm pretty sure that discussion happens in another place. This ticket is either a duplicate or at least should have a reference to that other place.

**Comment by miczyg1** [comment]
I can't recall right now if such place exists.

**Comment by wessel-novacustom** [comment]
Is it correct that this has been implemented meanwhile?

If so, the issue should be closed.

**Comment by miczyg1** [comment]
Yes, we are signing with our own vboot keys already.
