### ISSUE TITLE
BIOS lock feature is not documented

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#211]
**Dasharo version**

N/A

**Dasharo variant**

N/A

**Affected component(s) or functionality**

documentation

**Brief summary**

BIOS lock feature is not documented
See here: https://github.com/Dasharo/dasharo-issues/issues/209

**How reproducible**

100%

**How to reproduce**

**Expected behavior**

All features have user documentation

**Actual behavior**

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by miczyg1** [comment]
Documented in https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#dasharo-security-options
