### ISSUE TITLE
CI for DTS that publish DTS CE on boot.dasharo.com

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#217]
**The problem you're addressing (if any)**

DTS integration process is not automated. Back in the days we build `pxe-server` approach of which some version is hosted at boot.3deb.com. DTS CE is also available there, but images have to be manually uploaded. In quite simple way this operation can be automated.

**Describe the solution you'd like**

GH Action fro DTS CE building that automatically upload result to boot.3mdeb.com

**Where is the value to a user, and who might that user be?**

Users need most recent tools with patches to avoid complex compilation of flashrom, fwupd and other open-source firmware related toolchain.

**Describe alternatives you've considered**

**Additional context**

Topic was discussed back in the days as part of PC Engines [issue](https://github.com/3mdeb/pxe-server/issues/28)

**Comment by TomaszAIR** [comment]
@pietrushnic should DTS CE be published on boot.3mdeb.com or maybe boot.dasharo.com - we have here also this issue https://github.com/Dasharo/dasharo-issues/issues/54

**Comment by TomaszAIR** [comment]
I updated the issue title. We should work on this CI after https://github.com/Dasharo/dasharo-issues/issues/54

**Comment by kotylamichal** [comment]
@macpijan here is our proposition to resolve that issue:

- IT team creates VM with 200GB storage where we will build DTS CE by using github selfhosted runners
- IT team creates VM with subdomain boot.dasharo.com
- created VM after successful build will push:
- - system image to boot.dasharo.com
- - cache to cache.dasharo.com (https://github.com/Dasharo/dasharo-issues/issues/232)

**Comment by kotylamichal** [comment]
@macpijan I see that something is deployed already on boot.dasharo.com, so maybe we do not need to create a new VM?

cc @TomaszAIR

**Comment by TomaszAIR** [comment]
@kotylamichal I see we publish DTS image on http://boot.dasharo.com/dts-ce/dts.ipxe. Please, let's change that to http://boot.dasharo.com/dts/dts.ipxe. Just drop the `ce` from the name.

**Comment by kotylamichal** [comment]
@TomaszAIR done https://github.com/Dasharo/meta-dts-ce/pull/5/commits/16973da124252455bf3979b4a21ad6de321e2fde

**Comment by TomaszAIR** [comment]
Resolved by merging https://github.com/Dasharo/meta-dts-ce/pull/5, artifacts are deployed to boot.dasharo.com and refresh cache stored on cache.dasharo.com
