### ISSUE TITLE
Push hwdb quirks to upstream systemd

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#218]
**The problem you're addressing (if any)**

Currently we're asking the users to manually add a tweak to get the touchpad toggle key to work. This is inconvenient and makes for poor UX.

**Describe the solution you'd like**

Push these quirks to upstream systemd so that they're available to all users automatically

**Where is the value to a user, and who might that user be?**

Touchpad key works OOTB once systemd with the patches lands in distros

**Describe alternatives you've considered**

n/a

**Additional context**

The changes would go here: https://github.com/systemd/systemd/blob/main/hwdb.d/60-keyboard.hwdb

**Comment by TomaszAIR** [comment]
@mkopec what we would like here to achieve is to upstream those changes

```
        KEYBOARD_KEY_f7=191"
        KEYBOARD_KEY_f8=191"
```

here -> https://github.com/systemd/systemd/blob/main/hwdb.d/60-keyboard.hwdb#L280 ?

**Comment by mkopec** [comment]
@TomaszAIR We need to add a new entry in that document with the following contents:

```
evdev:atkbd:dmi:bvn*:bvr*:svnNotebook:pnNS50_70MU:*
evdev:atkbd:dmi:bvn*:bvr*:svnNotebook:pnNV4XMB,ME,MZ:*
evdev:atkbd:dmi:bvn*:bvr*:svnNotebook:pnNS5x_NS7xPU:*
evdev:atkbd:dmi:bvn*:bvr*:svnNotebook:pnNV4xPZ:*
        KEYBOARD_KEY_f7=191"
        KEYBOARD_KEY_f8=191"
```

**Comment by kotylamichal** [comment]
@mkopec can you describe more these two lines?
```
        KEYBOARD_KEY_f7=191
        KEYBOARD_KEY_f8=191
```

what is f7, f8, and 191? If I remove first line (`KEYBOARD_KEY_f7=191`) then it still works on NV41PZ. It is really required?

**Comment by mkopec** [comment]
f7 and f8 are generated by stock proprietary EC firmware (touchpad disable / enable, which mirrors hardware touchpad disable), whereas on open EC firmware we only generate f8

**Comment by kotylamichal** [comment]
@mkopec it was merged here: https://github.com/systemd/systemd/pull/25516. Please close that issue if you think that is OK

**Comment by macpijan** [comment]
Good job @kotylamichal !
Any idea which systemd release will contain this update?
Any idea we can hope for it to land into Ubuntu 22.04 with next updates?

**Comment by kotylamichal** [comment]
@macpijan I do not have any ideas, I think `systemd` releases are not cyclically scheduled. I have asked about that on IRC, waiting for the answer.

About Ubuntu: latest LTS version  - 22.04 uses systemd v249 (https://launchpad.net/ubuntu/jammy/+package/systemd), which was released almost 2 years ago: https://github.com/systemd/systemd/releases?q=249&expanded=true, so I do not think that can be done in the near future. In the previous LTS version - 20.04, there were no major systemd updates (https://launchpad.net/ubuntu/focal/+package/systemd), so I am not sure that it will happen. 

Probably we can expect update to the next systemd release on non-LTS ubuntu 22.10 (https://launchpad.net/ubuntu/kinetic/+package/systemd), or in the next LTS which is not planned yet
