### ISSUE TITLE
Ethernet controllers reversed order on FW6D/E

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#22]
**Dasharo version**
Dasharo 1.0.x

**Dasharo variant**
Firewall

**Affected component(s) or functionality**
Network boot

**Brief summary**
Network boot is slow because starts from the last NIC instead of the first one. Tested with XCP-ng network installer

**How reproducible**
100%

**How to reproduce**

1. Boot FW6D/E
2. Launch iPXE
3. Let iPXE get IP configuration automatically

**Expected behavior**
iPXE starts DHCP autoconfiguration on NIC closest to the power jack. 

**Actual behavior**
iPXE starts DHCP autoconfiguration on NIC furthest away from the power jack. 

**Screenshots**
None

**Additional context**
None

**Solutions you've tried**
None

**Comment by macpijan** [comment]
not reproduced
