### ISSUE TITLE
Configure early boot DMA protection with IOMMU

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#222]
**The problem you're addressing (if any)**
A rogue PCIe device may mess up the firmware/OS integrity with DMA transactions. IOMMU should be utilized to protect against such attacks.

**Describe the solution you'd like**
Configure the firmware to set up IOMMU early in the boot process and make firmware aware of IOMMU protection.

**Where is the value to a user, and who might that user be?**
https://github.com/Dasharo/dasharo-issues/issues/219#issuecomment-1273577043

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by miczyg1** [comment]
Enabled the DMA protection for whole usable memory in coreboot, but as expected every device using/needing DMA now fails, i.e. can't use any USB device or disk :upside_down_face: At least I have a confirmation that the DMA protection works :) Now the UEFIPayload needs to handle the allocation of DMA-allowed buffers for those I/O devices.

**Comment by miczyg1** [comment]
Here are the patches:
https://review.coreboot.org/c/coreboot/+/68449
https://review.coreboot.org/c/coreboot/+/68450

Next step would be to get IOMMU working in UEFI payload. I think I will reuse this:
https://github.com/tianocore/edk2-platforms/tree/master/Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdDxe
This should cover everything we need now.

Also worth looking at would be: https://github.com/tianocore/edk2-platforms/tree/master/Silicon/Intel/IntelSiliconPkg/Feature/PcieSecurity

**Comment by miczyg1** [comment]
Sent a patch to gerrit that allows cloning edk2-platform repo https://review.coreboot.org/c/coreboot/+/68872
So that we will be able to include VT-d driver in UEFI payload.

**Comment by miczyg1** [comment]
PR with Intel VT-d driver integration: https://github.com/Dasharo/edk2/pull/28

**Comment by miczyg1** [comment]
I also had to do a workaround in the VT-d driver because coreboot already did PCI enumeration and it break dependencies of UEFI: https://github.com/Dasharo/edk2-platforms/commit/3323ed481d35096fb6a7eae7b49f35eff00f86cf

**Comment by miczyg1** [comment]
And the PR with configuration https://github.com/Dasharo/coreboot/pull/250

**Comment by rafkoch** [comment]
@miczyg1 what are we waiting for in this task,  for more than a month, before we move it to the CLOSED status?

**Comment by miczyg1** [comment]
We would also like to have a setup option to enable/disable DMA protection

**Comment by rafkoch** [comment]
@miczyg1 for me, this looks like an additional improvement idea that was not in the original scope of issue. Please separate it to the backlog for future releases and link it here. Thank you.

**Comment by miczyg1** [comment]
There it is: https://github.com/Dasharo/dasharo-issues/issues/275

**Comment by rafkoch** [comment]
Nice, I moved this isssue to DONE column.
