### ISSUE TITLE
USB stack enable/disable option

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#223]
**The problem you're addressing (if any)**
Lack of USB stack configuration in the firmware setup.

**Describe the solution you'd like**
Implement a USB configuration menu allowing to enable/disable USB stack.

**Where is the value to a user, and who might that user be?**
Qubes OS certification requires the USB stack to be disabled by default for security purposes. An option to disable USB would bring Dasharo firmware closer to certification.

**Describe alternatives you've considered**
None

**Additional context**
https://groups.google.com/u/1/g/qubes-devel/c/08uSf2i-FTo

**Comment by miczyg1** [comment]
Code complete: https://github.com/Dasharo/edk2/pull/26

**Comment by miczyg1** [comment]
Few more things to do would be:
1. To check for PS/2 keyboard before disabling USB entirely and lock out the firmware from USB keyboard.
2. Disable only the onboard XHCI controller and let external USB controllers for trusted input devices to be operational.

**Comment by wessel-novacustom** [comment]
This feature [has been integrated](https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#usb-configuration) and the issue should be closed, unless @miczyg1 your latest comment is still relevant (?).

**Comment by miczyg1** [comment]
My latest comment is still relevant, but could be probably converted to separate issues first, before we close this one
