### ISSUE TITLE
Low level interfering crackling/popping of the speakers while playing no sound

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#224]
*Issue migrated from GitLab*

**Dasharo version**

v0.5.0

**Hardware details**

Clevo NV40MZ-i7

**Affected component(s) or functionality**

Speakers

**Brief summary**

While not playing any sound, the speakers are lightly cracking, like an interfering sound.

**How reproducible**

100% reproducible.

**How to reproduce**

1. Turn on the laptop.
2. Boot into Windows or Ubuntu.
3. Notice the speakers that are very lightly cracking or popping.

**Expected behavior**

No speakers crackling.

**Actual behavior**

Speakers crackling.

**Screenshots**

-

**Additional context**

This issue does not happen on original Insyde firmware. Perhaps the speakers are muted if no sound is detected?

**Solutions you've tried**

None.

/cc @macpijan

**Comment by mkopec** [comment]
Note: This is likely to be coil whine that appears while the device is idle (especially noticeable in deeper C-states)

**Comment by macpijan** [comment]
Report from NovaCustom is that the Insyde firmware has the same behavior.

**Comment by mkopec** [comment]
Happens every time the device reaches C-state C8 or lower, including when it's idling with the screen locked (or in self-refresh) and in S0ix sleep.

**Comment by Brice123456789** [comment]
NovaCustom NV40 computer, Intel Core i5. Firmware 1.4. Debian 12 GNOME.

This behavior happens with power-profiles-daemon in "Performance mode".
The use of TLP instead of power-profiles-daemon triggers this too.

**Comment by wessel-novacustom** [comment]
@mkopec is there any possible firmware solution for this, you think?

**Comment by wessel-novacustom** [comment]
That's great. How exactly can we enable this? Can that be done by firmware?

**Comment by mkopec** [comment]
> Can that be done by firmware?

@wessel-novacustom  Yes, it's a set of options in Intel FSP

**Comment by wessel-novacustom** [comment]
Ok, perfect. It would be great if it could be implemented for a next firmware update or even the October update.

**Comment by wessel-novacustom** [comment]
https://github.com/Dasharo/coreboot/pull/428#issuecomment-1825255713

**Comment by wessel-novacustom** [comment]
The noise has been reduced massively with the latest test binaries indeed, so I believe this should be marked as solved @mkopec.

**Comment by mkopec** [comment]
RFI mitigation on TGL might also help with Bluetooth and WiFi reception :) Not sure about ADL though

**Comment by wessel-novacustom** [comment]
For anyone still having this issue, please also check: https://forum.qubes-os.org/t/otherss-who-bought-a-nv41-and-have-noise-issues/20436/2

It applies for both the NV40 and NV41 Series.
