### ISSUE TITLE
Support for the MSI PRO Z690-A DDR5 variant

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#226]
**The problem you're addressing (if any)**
Lack of MSI PRO Z690-A support in coreboot and Dasharo.

**Describe the solution you'd like**
Add coreboot support for the MSI PRO Z690-A DDR5 variant which is almost identical to the MSI PRO Z690-A DDR4 variant.

**Where is the value to a user, and who might that user be?**
People with DDR5 variant will be able to run Dasharo. There were also many requests to support the board.

**Describe alternatives you've considered**
MSI PRO Z790-A/Z790-P port.

**Additional context**
None

**Comment by miczyg1** [comment]
coreboot patch: https://review.coreboot.org/c/coreboot/+/68448 (untested yet, waiting for hardware to arrive)

**Comment by weareanomalouswearearegion** [comment]
@macpijan 
You might be aware of this already, but if you look closely at (online pictures of) the MSI Z790-P (D4, D5, WiFi, Non WiFi), the PCB is virtually identical to the Z690-A, and the VRMs also feature the same 14-stage 55A A&O DrMOS design. AFAIK the only real things that have been changed would be the chipset itself and the heatsink designs. It's likely very little tweaks (or even none at all) are needed to get that working as well (maybe an updated FSP package perhaps?). Unfortunately, I would think the Z790-A will be a more challenging port as it looks like a brand new design. Considering the Z790-P family is already another good candidate in addition to the DDR5 Z690-A, I believe it may be wise to consider the Z790-P for Dasharo first, if there are further plans on expanding board support.

@miczyg1 
Very interesting that only the only actual change of code is to change the `.type` parameter to `[MEM_TYPE_DDR5](https://doxygen.coreboot.org/d9/d02/alderlake_2include_2soc_2meminit_8h.html#ad756268621f03e4812b68792b291fff5ac81a54f1a84f2a47145d3dd65ceb86f9)`, which was what I suspected previously. Having just bought a Z690-A DDR5 board which was ~$30 USD (currency converted) cheaper than the DDR4 version a few weeks ago, I was kind of tempted to just modify the `.type` parameter within the `ddr4_mem_config` struct and then compile it, but did not get around doing it due to other commitments. Glad to know an official version is coming. Keep up the great work guys!

**Comment by miczyg1** [comment]
Found a few bugs while enabling the new board, in total 4 patches:
https://review.coreboot.org/c/coreboot/+/68448
https://review.coreboot.org/c/coreboot/+/68710
https://review.coreboot.org/c/coreboot/+/68711
https://review.coreboot.org/c/coreboot/+/68712

The DDR5 variant is already booting Ubuntu 22.04.

**Comment by pietrushnic** [comment]
@macpijan what are the expected exit criteria? Shouldn't we consider this issue done?

**Comment by 6d6178667269747a** [comment]
@miczyg1, which HW revision is your board of. I have a MSI MS-7D25 Ver 2.1 (DDR5 version) and I can't access the SPI flash from the JTMP1 header and I have a different SPI chip itself (MXIC mx25u25673g instead of Winbond). Did you face similar issues on development?

**Comment by zirblazer** [comment]
> Which HW revision is your board of. I have a MSI MS-7D25 Ver 2.1 (DDR5 version) and I can't access the SPI flash from the JTMP1 header and I have a different SPI chip itself (MXIC mx25u25673g instead of Winbond). Did you face similar issues on development?

What do you mean with "different SPI chip itself"? There was never a Winbond. On DDR4 variant, the chip is actually the same Macronix MX25U25673G that you currently have on yours: https://docs.dasharo.com/variants/msi_z690/hardware-matrix/

**Comment by 6d6178667269747a** [comment]
And the JTPM1 header is still working for you? For me only pin 1(CS), 2(VCC) and 7(GND) are connected to JTPM1 pin 5, 1 and 7. So SPI Clock, MISO and MOSI is missing for me.

**Comment by 6d6178667269747a** [comment]
[SPI flash](https://docs.dasharo.com/images/ch341a_rec/msi_flash.jpg)

**Comment by zirblazer** [comment]
> And the JTPM1 header is still working for you? For me only pin 1(CS), 2(VCC) and 7(GND) are connected to JTPM1 pin 5, 1 and 7. So SPI Clock, MISO and MOSI is missing for me.

I can't answer that since I always used the Software flash method but...


> https://docs.dasharo.com/images/ch341a_rec/msi_flash.jpg

...completely missed this.

The DDR4 version is known to have at least two PCB revisions, 1.1 and 1.2, and there was no differences identified that I recall. But according to the recovery photos that Winbond is on a 1.1 board, same as the Macronix. So it seems that it may come with either Flash memory.

**Comment by miczyg1** [comment]
JTPM header will work as external flashing method if you connect: VCC, GND, SPI Clock, MISO and MOSI. For CS pin you have to directly connect a cable to the marked SPI chip pin, as JTPM1 CS pin is for TPM only and is different from the BIOS chip.

**Comment by weareanomalouswearearegion** [comment]
My MS-7D25 DDR5 (non Wi-Fi) board has ver2.1 PCB as well, and it has the same MXIC chip too.

@6d6178667269747a any reason to use this method? I believe a WSON clip seems like the better choice here, considering you have to make direct contact with the SPI flash anyway.

**Comment by miczyg1** [comment]
@weareanomalouswearearegion personally I think it is harder to maintain a stable hand clipping onto 8 pins simultaneously than just keep a single cable on 1 pin. Of course connecting the cables to JTPM1 takes some time and care to do it right.

**Comment by 6d6178667269747a** [comment]
I soldered cables to all of SPI flash pins (connection tested successfully) and tried to access it with
https://docs.dasharo.com/variants/msi_z690/recovery/ and
https://docs.dasharo.com/variants/msi_z690/development/
but the SPI chip is not found by flashrom. I used the same USB flasher as in the description. 
flashrom should detect the chip MX25U25673G as MX25U25635F, because they share the same id (0x2539), but the pinout differs. the same is true between W25Q256JW and MX25U25673G.

**Comment by miczyg1** [comment]
@6d6178667269747a try to pass `-V` parameter to flashrom, it will print the chip probing verbose information, there you will see what ID is actually read by flashrom

**Comment by pietrushnic** [comment]
@6d6178667269747a would you mind to post pictures of board and SPI area?

**Comment by 6d6178667269747a** [comment]
![spi_area_msi_z690](https://user-images.githubusercontent.com/79062963/198851168-02b9b05b-a34a-4e1c-abc9-d8d8d077995a.jpeg)

**Comment by codewiz** [comment]
I also have an MSI MS-7D25 V2.1. The flash is a Winbond 25Q256JWEQ, and the DIMMs are Corsair Dominator DDR5-5600 (CMT32GX5M2B5600C36).

I bought this kit to dump the original firmware and flash coreboot: https://www.amazon.com/dp/B07V2M5MVH

Are there any known-good images I could try now, or should I wait for an official release?

**Comment by miczyg1** [comment]
@codewiz the first good-known image will be the one that we will release officially soon (a matter of few days).

**Comment by pietrushnic** [comment]
@codewiz what is your use case for Dasharo compatible with MSI Z690-A DDR5? We trying to gather information about workloads used by community to push project in correct direction. What would be most wanted features for you?

**Comment by codewiz** [comment]
@pietrushnic, thanks for asking, but this is just a personal learning project: I brought a single MSI Z690-A to play with Coreboot on modern hardware.

Several years ago, I [flashed Coreboot on a spare Thinkpad](https://codewiz.org/wiki/CorebootX230) for fun.  Back then, the hardest challenge was the LCD panel initialization, but I imagine it will be a lot easier with a desktop.

The features I will need are:
 - Loading the VGA bios from an AMD Radeon Vega 64
 - Booting from NVMe and external USB sticks
 - Automatically load GRUB from the EFI partition
 - Enough ACPI compatibility to run Linux 6.x and Windows 11
 - No secure boot required
 - Fan speed management
 - Nice to have: ability to configure cpu, memory clocks and voltages

I ran some CPU benchmarks on this machine with the built-in firmware and the XMP profile:
https://openbenchmarking.org/result/2208148-CODE-GOREBOO85,2208071-CODE-LEMP11I90
Would be good to compare it with the same hardware initialized by Coreboot

**Comment by zirblazer** [comment]
@6d6178667269747a
Did you ever tried this? https://github.com/Dasharo/dasharo-issues/issues/226#issuecomment-1293606157

@codewiz
In its current state, the DDR4 version already boots from NVMe SSDs and USB Flash Drives, can autodetect \EFI\BOOT\BOOTX64.EFI from an ESP and allows to manually create Boot Entries with custom parameters then sort it with Boot Order, and can boot Windows 11. Secure Boot is optional but defaults to enabled (Is going to default to disabled on next release). Secure Boot factory configuration also comes with the two Microsoft certificates built-in and fTPM also works, so you can install W11 as it complies with both SB and TPM requeriments.
Fan speed management is handled by Super I/O functions, no manual controls in Firmware yet (And no idea if there are OS side tools to manage it). No way to configure out-of-specification/overclocking functionality yet, most notorious one is memory clocks defaulting to whatever the JEDEC profile of a module is, so no XMP.
dGPU Option ROM is actually loaded but there are multiple reported issues with some Radeons not working properly at Firmware stage (Either no video output, or super slow graphics performance to the point that you can see it drawing on screen line by line).

**Comment by codewiz** [comment]
I should probably report this in the coreboot repo, but I checked out `msi_ms7d25/release_next` and tried building it with `./build.sh ddr5`, but it failed with a couple of issues:

* Package flashrom not installed in the docker image
* The intel-microcode submodule was not checked out

```
+ docker run --rm -it -u 1000 -v /home/bernie/src/coreboot:/home/coreboot/coreboot -v /home/bernie/.ssh:/home/coreboot/.ssh -w /home/coreboot/coreboot coreboot/coreboot-sdk:2021-09-23_b0d87f753c /bin/bash -c 'make olddefconfig && make -j20'
...
Package flashrom was not found in the pkg-config search path.
Perhaps you should add the directory containing `flashrom.pc'
to the PKG_CONFIG_PATH environment variable
No package 'flashrom' found
Microcode error: 3rdparty/intel-microcode/intel-ucode/06-97-02 does not exist
Microcode error: 3rdparty/intel-microcode/intel-ucode/06-97-05 does not exist
```

**Comment by miczyg1** [comment]
@codewiz thanks for that, Added submodule checkout to the build script. Flashrom not found is just a warning and it does not prevent building.

**Comment by miczyg1** [comment]
> * Loading the VGA bios from an AMD Radeon Vega 64

By default Dasharo firmware loads option ROMs from PCI devices, including VBIOSes.

> * Fan speed management

This will be tough. The Super I/O runs proprietary firmware and there is close to zero information about the hardware monitor and fan control registers. For now we consider it not doable.

> * Nice to have: ability to configure cpu, memory clocks and voltages

We have tickets for those:
https://github.com/Dasharo/dasharo-issues/issues/137
https://github.com/Dasharo/dasharo-issues/issues/87
https://github.com/Dasharo/dasharo-issues/issues/138
https://github.com/Dasharo/dasharo-issues/issues/136
https://github.com/Dasharo/dasharo-issues/issues/134

But these require a lot of work and will not be available soon.

**Comment by codewiz** [comment]
Thanks you both for all the advice and for carrying on this exciting work!

> Added submodule checkout to the build script. Flashrom not found is just a warning and it does not prevent building.

I tried again with branch `msi_ms7d25/release`, and  `git submodule update --init --checkout` still failed for me within the container (git 2.32.0), but it ran just fine outside of it (git 2.38.1).

The build process ran to the end and produced a rom file along with a scary warning:

```
/usr/bin/ld: /home/coreboot/coreboot/build/util/vboot_lib/libvboot_util.a(2crypto.o): warning: relocation in read-only section `.rodata.vb2_sig_names'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
    CREATE GBB (without BMPFV)
successfully created new GBB to: build/gbb.stub.tmp
    SETUP GBB
 - import root_key from 3rdparty/vboot/tests/devkeys/root_key.vbpubk: success
 - import recovery_key from 3rdparty/vboot/tests/devkeys/recovery_key.vbpubk: success
successfully saved new image to: build/gbb.region.tmp
    WRITE GBB

        ** WARNING **
coreboot has been built without an Intel Firmware Descriptor.
Never write a complete coreboot.rom without an IFD to your
board's flash chip! You can use flashrom's IFD or layout
parameters to flash only to the BIOS region.

WARNING: prepare_slot: VBLOCK_A keyblock is invalid.
WARNING: prepare_slot: VBLOCK_B keyblock is invalid.
    FLASHMAP Layout generated for RO, A and B partition.
+ cp build/coreboot.rom msi_ms7d25_v1.1.0-dirty_ddr5.rom
+ '[' 0 -eq 0 ']'
+ echo 'Result binary placed in /home/bernie/src/coreboot/msi_ms7d25_v1.1.0-dirty_ddr5.rom'
Result binary placed in /home/bernie/src/coreboot/msi_ms7d25_v1.1.0-dirty_ddr5.rom
+ sha256sum msi_ms7d25_v1.1.0-dirty_ddr5.rom
```


Before proceeding, I'll wait for the [WSON8 probe](https://www.amazon.com/dp/B0BKP819W9) to arrive and test the recovery process. Also, I would rather start with an image that someone booted successfully on similar hardware.

> I guess those CPUs are largely different - [passmark comparison](https://www.cpubenchmark.net/compare/4794vs4692/Intel-i7-1255U-vs-Intel-i7-12700F)

You're right, it's indeed [a wildly unfair comparison](https://mstdn.io/@codewiz/108785794115862334)!
I'll re-run the benchmark suite on the same ms7d25 system once it's running Coreboot.

**Comment by rafkoch** [comment]
Dear @macpijan (you open this issue), Dear @codewiz  (you are waiting for "the WSON8 probe to arrive and test the recovery process") the main goal of this issue is done - we have Dasharo port for MSI PRO Z690-A DDR5 variant. 
So I propose to close this issue. 
For any new issues (e.g. after tests with the WSON8 probe) there is possibility to open  new, dedicated issue.

**Comment by macpijan** [comment]
Since the DDR5 release is out there, it can be closed. If there are any specifc problems reported related to this release, we can track them in new tickets.

BTW @rafkoch it would be nice to link to the release notes of given release when you say something was release, so interested readers of this thread can have easier time finding it.

**Comment by miczyg1** [comment]
Can be closed I guess. Release notes:

https://docs.dasharo.com/variants/msi_z690/releases/#v110-2022-11-22

**Comment by rafkoch** [comment]
Nice. I move this issue to column DONE.
