### ISSUE TITLE
Dasharo does not preserve boot order after reboot and firmware update

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#23]
**Dasharo version**
 v0.2-rc3

**Dasharo variant**
Workstation

**Affected component(s) or functionality**
Boot order

**Brief summary**
Dasharo does not preserve boot order after reboot nor after firmware update.

**How reproducible**
Every boot.

**How to reproduce**

1. Boot Debian on Dasharo Workstation
2. Run: `sudo grub-install /dev/sda --target=x86_64-efi --efi-directory=/boot/efi`
3. Reboot
4. Confirm there is no debian in boot order

**Expected behavior**
Debian should be added as first boot option

**Actual behavior**
Entry is not added

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by miczyg1** [comment]
It worked for me, beats me what configuration you have that it doesn't work. Of course if you reflash the whole ROM with a firmware update you will loose the boot order, that's obvious. I recommend using `--fmap - i <REGION1> -i <REGION2>` parameter with flashrom to update only executable code, instead of all code and cached configuration like MRC or UEFI NVAR.

**Comment by pietrushnic** [comment]
@miczyg1 definitely `--fmap` was not used, but also we should have that information in the documentation. I will provide the config as soon I will have access to the hardware.

**Comment by miczyg1** [comment]
Well, it would be in the documentation if I had started writing one. :)

**Comment by macpijan** [comment]
@miczyg1 We were requested to use flashrom on boot.3mdeb.com from following fork:

```
SRC_URI = "git://github.com/pcengines/flashrom.git;branch=apu_support "
SRCREV = "092b1c28bf31dab170d2fc0dc09b6bee3fa68bfa"
```

Can you remember why and if this is still necessary?

**Comment by miczyg1** [comment]
If anything it may have something to do with dongle flashing and recovery.

**Comment by mkopec** [comment]
I believe this has been resolved in DTS, which can now preserve the SMMSTORE region across updates.
