### ISSUE TITLE
Suspend does not work correctly while a SATA disk is installed

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#230]
**Dasharo version**

v1.0.0

**Dasharo variant**

n/a

**Affected component(s) or functionality**

Suspend mode

**Brief summary**

When a SATA disk inserted into the SATA-compatible M.2 slot of the laptop, suspend
mode does not work fully. Even when SATA DIPM is enabled, entry into suspend is
blocked by the SATA controller. The CPU will enter Package C-state C10 but SLP_S0#
is never asserted.

**How reproducible**

100%, when a SATA disk is connected. Otherwise no sleep issues appear.

**How to reproduce**

1. Install a SATA M.2 SSD into the laptop
2. Boot Ubuntu 22.04
3. Put the laptop into suspend
4. Wait for a minute
5. Wake the laptop
6. Execute `sudo cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec`

**Expected behavior**

The command returns a non-zero value, indicating S0ix entry while suspended.

**Actual behavior**

The command always returns 0, which indicates that the laptop never entered S0ix.

**Screenshots**

n/a

**Additional context**

**Solutions you've tried**

- Try to enable all possible power savings in Ubuntu using `powertop --auto-tune`

**Comment by macpijan** [comment]
@mkopec IIRC we believe there is some soft of a hardware design problem there? Can we share a bit more information here?

**Comment by mkopec** [comment]
The problem is that the DEVSLP pin for SATA port 1 is wired to the DEVSLP0B pin on the PCH, which the PCH does not expect (it expects the DEVSLP1 or DEVSLP1B port to be used for SATA port 1 and DEVSLP0 or DEVSLP0B for SATA port 0). The board design crosses these pins instead

**Comment by wessel-novacustom** [comment]
NovaCustom officially does not support S-ATA M.2 disks. That being said, there is [this post installation step](https://docs.dasharo.com/unified/clevo/post-install/#suspend-fix-for-sata-disks_1) that should fix the issue.

The issue can therefore be closed.
