### ISSUE TITLE
Public cache for building meta-dts CE version

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#232]
**The problem you're addressing (if any)**

Expose meta-dts-ce cache publicly so everyone could use it in order to shorten the image build time.

**Describe the solution you'd like**

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by kotylamichal** [comment]
@pietrushnic subdomain `cache.dasharo.com` will be good for that? I am asking you about that because we need to create a task with that for the IT support team

**Comment by TomaszAIR** [comment]
@kotylamichal maybe let's use `cache.dasharo.com/yocto/dts-ce` so under yocto there will be future Yocto related projects.

**Comment by pietrushnic** [comment]
@kotylamichal in such situation asking @macpijan is good enough. I argee with his opinion.

**Comment by TomaszAIR** [comment]
@kotylamichal similar to https://github.com/Dasharo/dasharo-issues/issues/217#issuecomment-1294539534 also for cache please drop `-ce` from name

**Comment by kotylamichal** [comment]
@TomaszAIR done https://github.com/Dasharo/meta-dts-ce/pull/5/commits/16973da124252455bf3979b4a21ad6de321e2fde

**Comment by TomaszAIR** [comment]
Will close that issue now.
