### ISSUE TITLE
Initial deployment of Dasharo on supported hardware

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#233]
**The problem you're addressing (if any)**

It should be possible to use DTS CE in order to perform initial Dasharo deployment on supported platforms. Those are listed in official documentation. [1] Scripts for deployment should be public and available for everyone that would like to use Dasharo on theirs platforms as long as they are supported.

[1] https://docs.dasharo.com/#compatible-hardware

**Describe the solution you'd like**

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by TomaszAIR** [comment]
Using changes from https://github.com/Dasharo/meta-dts-ce/pull/14 we are able to perform initial deployment on ASUS KGPE-D16, Dell OptiPlex 7010/9010, NovaCustoms laptops (NV4x and NS5x) and MSI PRO Z690-A.

This is still wip as we need to add rest of platforms

**Comment by TomaszAIR** [comment]
Talos II needs flashing from BMC so there is not much we can do about it now. And for now we cannot ensure deployment on Protectli platforms so the initial deployment is added for

* ASUS KGPE-D16
* Dell OptiPlex 7010/9010
* MSI PRO Z690-A
* NV4x
* NS5x

**Comment by rafkoch** [comment]
I moved this issue (card) to DONE column in project "Nlnet October 2022", because its status is CLOSED.
Moreover PR is merged.
