### ISSUE TITLE
Dasharo Tools Suite test environment

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#234]
**The problem you're addressing (if any)**

Dasharo Tools Suite Community Edition should have a dedicated test suite. This test suite should consist of test cases that cover all of the dedicated functionalities of the DTS. 

Also, it would be good to create and maintain an automated test environment with documentation on how to prepare the testing stand to run the automated tests.

**Describe the solution you'd like**

1. Dasharo Tools Suite test suite documentation available on docs.dasharo.
2. Automated test environment based on the documentation mentioned in the 1st point.
3. Documentation on how to create the test stand and how to run the tests.

**Where is the value to a user, and who might that user be?**

Before each release community obtains information on the actual status of the declared functionalities (confirmed by the results of individual tests).

**Describe alternatives you've considered**

**Additional context**

**Comment by sulewskiprzemyslaw** [comment]
PR - DTS test cases documentation: https://github.com/Dasharo/docs/pull/340

PR - testing stand prepare documentation: https://github.com/Dasharo/docs/pull/354

Automated testing environment: https://github.com/Dasharo/open-source-firmware-validation

**Comment by rafkoch** [comment]
@sulewskiprzemyslaw what are we waiting for in this task, for about a month, before we move it to the CLOSED status?
Both PR's are merged but the question is: 
have these 3 points been done?

1. Dasharo Tools Suite test suite documentation available on docs.dasharo.
2. Automated test environment based on the documentation mentioned in the 1st point.
3. Documentation on how to create the test stand and how to run the tests.

What separates us from closing this task?

**Comment by sulewskiprzemyslaw** [comment]
@rafkoch full issue scope has been realized. With this fact in mind, I close the issue.

**Comment by rafkoch** [comment]
Thank You @sulewskiprzemyslaw for closing this task, so I move this task to DONE column in the project.
