### ISSUE TITLE
No video output via USB-C after shutdown if PowerDelivery (PD) is active NV40MZ

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#237]
**Dasharo version**

v1.3.0

**Dasharo variant**

NovaCustom NV40 Series (SKU: NV40MZ)

**Affected component(s) or functionality**

Video output via USB-C (Display Alt Mode)

**Brief summary**

If the laptop starts from a cold boot and PowerDelivery (PD; charging via USB-C) is active before pressing the power button, no video output is transmitted via USB-C. This requires users with a docking station to either restart their docking station after the boot, or to unplug and replug the docking station.

It seems to be related to PowerDelivery, as the bug doesn't happen when using a docking station without PowerDelivery. Once the PowerDelivery adaptor is connected, the bug happens.

This happens while running Debian 11 (Bullseye). I will try Ubuntu 22.04 LTS in a minute.

**How reproducible**

100%

**How to reproduce**

1. Connect the docking station with at least one external display via the dock.
2. Charge the laptop via USB-C, if not already.
3. Shutdown the laptop.
4. Start the laptop again.

**Expected behavior**

External screen display is active.

**Actual behavior**

External screen display is not active.

**Screenshots**

-

**Additional context**

-

**Solutions you've tried**

-

**Comment by wessel-novacustom** [comment]
I confirm: same problem for Ubuntu 22.04 LTS

**Comment by mkopec** [comment]
May be fixed by https://github.com/Dasharo/coreboot/pull/344 - with these changes I can coldboot and reboot with the display still being on. Also, if the lid is closed, the firmware splash and setup screens will be displayed on the external monitor (USB-C or HDMI). Should be helpful for docked use-cases.

**Comment by wessel-novacustom** [comment]
That'd be really great!

**Comment by Pokisiekk** [comment]
@wessel-novacustom Could you provide the model of the docking station affected by this issue, please?

**Comment by Pokisiekk** [comment]
@wessel-novacustom Could you provide the model of the docking station affected by this issue, please?

**Comment by wessel-novacustom** [comment]
WL-UMD05 Pro. I was not able to reproduce the problem at the latest Dasharo version.
