### ISSUE TITLE
ME neutering credits not given to Trammel Hudson at https://docs.dasharo.com/osf-trivia-list/me/

### ISSUE THREAD

**Issue by tlaurion** [Dasharo/dasharo-issues#238]
There is little history flaw that would benefit to be corrected at https://github.com/Dasharo/docs/blob/master/docs/osf-trivia-list/me.md
> Method discovered by Nicola Corna of the me\_cleaner project Removes all modules other than those required for platform init

Actually, Corna based his work on Trammel's. 

As noted under https://github.com/corna/me\_cleaner/wiki/How-does-it-work%3F#sources
> Our work started when we found, on the coreboot Mailing List, a message from Trammel Hudson in which he shared his recent discovers about Intel ME firmware. Then we tried by ourself and replicated the results: to make things simpler I created a Python script to modify the firmware automatically and we published it on the coreboot Mailing List and later on GitHub.

Might want to give Trammel the credit :)

Amazing work through https://docs.dasharo.com/osf-trivia-list/me/ :)

**Comment by miczyg1** [comment]
@pietrushnic I guess you are the author according to git history. Would you like to fix that?

**Comment by pietrushnic** [comment]
I will handle that. Thanks.

**Comment by wessel-novacustom** [comment]
@tlaurion Can you confirm it has been fixed and close the issue, please?

**Comment by tlaurion** [comment]
> Method discovered by Nicola Corna of the me_cleaner project Removes all modules other than those required for platform init

Correct story line

https://hardenedlinux.github.io/firmware/2016/11/17/neutralize_ME_firmware_on_sandybridge_and_ivybridge.html

**Comment by miczyg1** [comment]
https://github.com/Dasharo/docs/commit/13e5ed2e4d557558885b1dbede1c614e67eb62ab
