### ISSUE TITLE
Small esthetic improvement of the boot screen

### ISSUE THREAD

**Issue by renehoj** [Dasharo/dasharo-issues#239]
**Describe the solution you'd like**
If a second boot splash image was added to the ROM it would be possible to write the boot options using a true type font. 

First the Image without the text is shown, and when it's possible to use Del, Enter, F11 the second image is shown.

The second image is a copy of the first image with the boot instructions written with a true type font.

**Where is the value to a user, and who might that user be?**

It would make the boot screen look more clean, if the information text used a font the matches the text used in the Dasharo logo.

**Additional context**

![dasharo_sc](https://user-images.githubusercontent.com/108547507/197405953-a451a13b-68ee-4ebe-8980-6bd1084c0657.jpg)

**Comment by macpijan** [comment]
That would require crafting per-platform images, as the boot keys differ per platforms.
It also means replacing logo with a custom one would be more tricky, as you would need to include the boot keys information. It is unlikely we will go this path.

**Comment by mkopec** [comment]
Instead of changing the logo, we can draw other graphics on top of / next to it.

Ideally we'd have a truetype renderer in UEFI

**Comment by miczyg1** [comment]
> It would make the boot screen look more clean, if the information text used a font the matches the text used in the Dasharo logo.

The hotkeys are printed as strings with the built-in font inside EDK2. Adding a custom font is not that easy.

> The second image is a copy of the first image with the boot instructions written with a true type font.

This is even worse for reasons explained by @macpijan 

If those strings are such a PITA, then this should help: https://github.com/Dasharo/dasharo-issues/issues/116
