### ISSUE TITLE
Dasharo Workstation compilation documentation

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#24]
make distclean && cp configs/config.pcengines_apu2_grub_uefi .config && make olddefconfig && make V=1
**Dasharo version (if applicable)**
v0.2-rc3

**Dasharo variant (if applicable)**
Workstation

**Affected component(s) or functionality (if applicable)**
Documentation

**Brief summary**
Documentation should contain introductory material about compilation for new coming developers.

**Additional context**
In long run, we should have consistent compilation documentation for all Dasharo SKUs. Instructions should be
1. as simple as possible 
2. have a little bit of dependency as possible
3. build as close as possible result to 3mdeb public releases

**Comment by pietrushnic** [comment]
@BeataZdunczyk @macpijan, do we have plans to include this in an upcoming release?

**Comment by BeataZdunczyk** [comment]
Documentation has been added here: https://github.com/Dasharo/docs/pull/873, and it is already live: [Dasharo Documentation](https://docs.dasharo.com/variants/dell_optiplex/overview/). Closing issue.
