### ISSUE TITLE
Touchpad isn't work on Debian 11.3 

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#240]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS50/70PU

**Affected component(s) or functionality**
Touchpad

**Brief summary**
Touchpad isn't work on Debian 11.3 

**How reproducible**
100%

**How to reproduce**

1. Install Debian 11.3 on disk.
2. Boot to Debian 11.3.
3. Try to use the touchpad.

**Expected behavior**
Touchpad works properly.

**Actual behavior**
Touchpad isn't work.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by wessel-novacustom** [comment]
Maybe this is fixed once a newer Debian version is released? For instance with a Linux 6.0 kernel ...

We haven't seen any client using Debian yet on our Alder Lake machines. We are considering to change to Fedora for testing, as Debian is a pain to get everything compatible.

If anyone disagrees or has any comments, please comment.

**Comment by macpijan** [comment]
Debian is probably not the best target for the most recent hardware, indeed.
Unless you use [Debian unstable](https://wiki.debian.org/DebianUnstable) which is not something we use here and it is for more "advanced" users we can say, as it requires some more effort tu use Unstable (or Testing) than merely installing it.

We can simplify by saying that Ubuntu is using the latest Debian packages from Testing/Unstable repositories and makes it more easy to use for not advanced users.

**Comment by wessel-novacustom** [comment]
Exactly.

Fedora seems to be quite popular however. Maybe we can consider to switch from testing on Debian to Fedora Workstation (latest version, which is 37 IIRC), starting from new releases.

**Comment by macpijan** [comment]
If your users tend to use it, then yes, it may make more sense.

Note also that Fedora is a base for QubesOS (althoguh a bit older release, typically).

**Comment by wessel-novacustom** [comment]
Good to know! Then we definitively want to go in that direction.

**Comment by emvivre** [comment]
Indeed by default the touchpad is not recognized on debian 11, you need to recompile some kernel modules in order to make touchpad usable.

The touchpad is well detected on a ubuntu 22.04 LTS. With the help of some forum, and with the kernel log (dmesg) on buntu 22.04 LTS I deduce what kernel modules to initialize.

I initialize the following parameters : 
```
   Device Drivers -> I2C support -> I2C Hardware Bus support
        Intel 82801 (ICH/PCH)
        Synopsys DesignWare Slave
        Synopsys DesignWare Platform
        Synopsys DesignWare PCI
   Device Drivers -> HID support -> Special HID drivers -> HID Multitouch panels
   Device Drivers -> HID support -> Generic HID driver
   Device Drivers -> HID support -> I2C HID support -> HID over I2C transport layer ACPI driver
```

The compilation of the linux kernel is really straightforward : 
```
wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.2.10.tar.xz
tar xf linux-6.2.10.tar.xz
cd linux-6.2.10/
make olddefconfig
make menuconfig  
#   delete signature modules
#   Cryptographic API -> Certificates for signature checking -> () Additional X.509 keys for default system keyring
#          delete debian/certs/debian-uefi-certs.pem
make bindeb-pkg -j16
cd ../
sudo dpkg -i linux-headers-6.2.10_6.2.10-9_amd64.deb
sudo dpkg -i linux-image-6.2.10_6.2.10-9_amd64.deb
sudo reboot
```

**Comment by wessel-novacustom** [comment]
It works out of the box with Debian 12 (Bookworm). @Pokisiekk Can the issue be closed?
