### ISSUE TITLE
Booting from recovery not works

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#242]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS50/70PU

**Affected component(s) or functionality**
Verified boot

**Brief summary**
After flashing locally signed firmware the device didn't boot to BIOS

**How reproducible**
100%

**How to reproduce**

1. Flash the DUT with firmware with the wrong-signed vboot keys.
2. Turn off the DUT.
3. Turn on the DUT.

**Expected behavior**
The DUT boots

**Actual behavior**
The DUT doesn't boot, the LED lights up green briefly, you can hear the windmills, and so on every few seconds

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by wessel-novacustom** [comment]
What means DUT?

**Comment by pietrushnic** [comment]
Device Under Test

**Comment by Pokisiekk** [comment]
https://github.com/Dasharo/coreboot/pull/251 - tested, the fix worked and the problem no longer occurs
