### ISSUE TITLE
MSI PRO Z690-A WIFI DDR4 with two Video Cards (2x Radeon 5600XT) has issues related to MMIO resource allocation

### ISSUE THREAD

**Issue by zirblazer** [Dasharo/dasharo-issues#245]
**Dasharo version**
Dasharo v1.0.0 for MSI PRO Z690-A WIFI DDR4

**Affected component(s) or functionality**
MultiGPU support. Could potentially affect other cards that requires big MMIO allocation.

**Brief summary**
As a follow up to my previous issue: https://github.com/Dasharo/dasharo-issues/issues/181
Having two Video Cards installed simultaneously fails to work the way it should, causing Windows 11 to BSOD on boot with a DRIVER_VERIFIER_DMA_VIOLATION error if Radeon Drivers are installed, and some Linux Kernel versions reporting than amdgpu Driver failed to initialize the second card with a " [drm:amdgpu_device_init.cold [amdgpu]] ERROR sw_init of IP block <gmc_v10_0> failed -19 " error. This happens ONLY if I install 2x Radeon 5600XT in both PCI_E1 16x (Wired to Processor PCIe 5.0 16x Port) and PCI_E3 16x (Wired to Chipset PCIe 3.0 4x Port), it doesn't happen if only one is plugged in either slot.
I have no idea if it affects other Radeon series or GeForces.

**How reproducible**
100%

**Additional context**
There is a truckload of logs about this, and you NEED to understand the name convention I used to make sense of it.
It includes three different OSes: A 2 years Arch Linux install I call Arch Linux OLD, an Arch Linux LiveCD that I call Arch Linux NEW, and Ubuntu 22.04 LiveCD.

Arch Linux OLD					Linux 5.9.14
Ubuntu 22.04 (LiveCD)				Linux 5.15.0
Arch Linux NEW (LiveCD 2022.06.01)	Linux 5.18.1

Each of these three were tested with both Dasharo v1.0.0 and MSI 1.70. Dasharo has no options to modify, whereas in MSI I tested with both Above 4G MMIO Off and On (All with Resizeable BAR Off).
Note than I only attach Above 4G Off results with Arch Linux OLD because I later discovered than in newer Linux Kernel versions, amdgpu decides to force enable Above 4G and ReBAR Linux side EVEN if they are disabled on MSI Firmware (Dasharo has both effectively disabled), and this ironically fixes the problem in Dasharo since it is reallocating all PCI MMIO resources after boot. So 5.15.0 and 5.18.1 have identical results with Above 4G Off and On on MSI and Dasharo, and the GPUs ends up effectively with ReBAR On.

Dasharo		Arch Linux OLD					/	Ubuntu 22.04					/	Arch Linux NEW
MSI 1.70		Arch Linux OLD (Above 4G OFF & ON)	/	Ubuntu 22.04 (Above 4G ON)		/	Arch Linux NEW (Above 4G ON)

Finally, there is a dump of dmesg, dmesg | grep amdgpu, and lspci -vvv of each PCIe Root Port involved.
Note than modern Radeon cards had some strange PCI Topology where the card has both a built-in PCIe Upstream and Downstream Bridges, so the topology is something like this:
PCIe Root Port GPU 1 -> Radeon Upstream Bridge -> Radeon Downstream Bridge -> GPU 1 Device (Missed to lspci GPU HDMI Audio)
PCIe Root Port GPU 2 -> Radeon Upstream Bridge -> Radeon Downstream Bridge -> GPU 2 Device (Missed to lspci GPU HDMI Audio)

After analyzing the logs, the problem seems to be on how MMIO for the PCIe Root Ports are allocated. GPU 1 gets 258 MiB at the top PCIe Root Port whereas GPU 2 only gets 256 MiB, and this is not enough. Check Region 0 and 2 of GPU 1 and 2, then look at the PCIe Root Ports:

GPU 1 (Dasharo, Arch Linux OLD - dasharo__archlinuxold__lspci-vvv-gpu1-gpu.txt )
Region 0: Memory at 90000000 (64-bit, prefetchable) [size=256M]
Region 2: Memory at a0000000 (64-bit, prefetchable) [size=2M]
Region 4: I/O ports at 2000 [size=256]
Region 5: Memory at 80400000 (32-bit, non-prefetchable) [size=512K]
Expansion ROM at 80480000 [disabled] [size=128K]

PCIe Root Port 1 (Dasharo, Arch Linux OLD - dasharo__archlinuxold__lspci-vvv-gpu1-rootport.txt )
I/O behind bridge: 00002000-00002fff [size=4K]
Memory behind bridge: 80400000-805fffff [size=2M]
Prefetchable memory behind bridge: 0000000090000000-00000000a01fffff [size=258M]

GPU 2 (Dasharo, Arch Linux OLD - dasharo__archlinuxold__lspci-vvv-gpu2-gpu.txt )
Region 0: Memory at d0000000 (64-bit, prefetchable) [disabled] [size=256M]
Region 2: Memory at <ignored> (64-bit, prefetchable) [disabled]
Region 4: I/O ports at 3000 [size=256]
Region 5: Memory at 80800000 (32-bit, non-prefetchable) [disabled] [size=512K]
Expansion ROM at 80880000 [disabled] [size=128K]

PCIe Root Port 2 (Dasharo, Arch Linux OLD - dasharo__archlinuxold__lspci-vvv-gpu2-rootport.txt )
I/O behind bridge: 00003000-00003fff [size=4K]
Memory behind bridge: 80800000-809fffff [size=2M]
Prefetchable memory behind bridge: 00000000d0000000-00000000dfffffff [size=256M]

With cbmem logs (Check Issue 181 2x5600xt_twoslots_cbmem.log), it was discovered than Coreboot seems to be properly assigning 258 MiB to the second PCIe Root Port, but somehow Linux sees only 256 MiB. It was speculated than TianoCore/edk2 may be reconfiguring MMIO allocation in some other way, but no further troubleshooting was done.

As this are, the consequences of missing those 2 MiB MMIO seems to be reproducible only in Windows with the BSODs and old Linux versions that fail to initialize the second card because they don't reallocate PCI MMIO. So if it wasn't because I tested this on an old Arch Linux install, I wouldn't have catched it.

Check RESUME.txt, which pretty much resumes the important parts of the logs and file names.

**Solutions you've tried**
On Windows 11, Safe Mode (Which requires Windows to fail to boot a few times before presenting the magical menu) works, which allows me to enter Device Manager and disable the second Radeon 5600XT, which finally allows Windows to boot normally. Re-enabling it from Device Manager makes Windows to instantly BSOD.

[RESUME.txt](https://github.com/Dasharo/dasharo-issues/files/9872570/RESUME.txt)

![msi1-70__igp_2x-5600xt](https://user-images.githubusercontent.com/32025193/198104083-627ddafb-9ed3-45e4-bdd8-e2dd07fd10b1.png)

[dasharo__archlinuxold__dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/9872589/dasharo__archlinuxold__dmesg.txt)
[dasharo__archlinuxold__dmesg-amdgpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872590/dasharo__archlinuxold__dmesg-amdgpu.txt)
[dasharo__archlinuxold__lspci-vvv-gpu1-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872591/dasharo__archlinuxold__lspci-vvv-gpu1-bridgedownstream.txt)
[dasharo__archlinuxold__lspci-vvv-gpu1-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872592/dasharo__archlinuxold__lspci-vvv-gpu1-bridgeupstream.txt)
[dasharo__archlinuxold__lspci-vvv-gpu1-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872593/dasharo__archlinuxold__lspci-vvv-gpu1-gpu.txt)
[dasharo__archlinuxold__lspci-vvv-gpu1-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872594/dasharo__archlinuxold__lspci-vvv-gpu1-rootport.txt)
[dasharo__archlinuxold__lspci-vvv-gpu2-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872595/dasharo__archlinuxold__lspci-vvv-gpu2-bridgedownstream.txt)
[dasharo__archlinuxold__lspci-vvv-gpu2-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872596/dasharo__archlinuxold__lspci-vvv-gpu2-bridgeupstream.txt)
[dasharo__archlinuxold__lspci-vvv-gpu2-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872597/dasharo__archlinuxold__lspci-vvv-gpu2-gpu.txt)
[dasharo__archlinuxold__lspci-vvv-gpu2-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872598/dasharo__archlinuxold__lspci-vvv-gpu2-rootport.txt)

[dasharo__archlinuxnew__dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/9872577/dasharo__archlinuxnew__dmesg.txt)
[dasharo__archlinuxnew__dmesg-amdgpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872579/dasharo__archlinuxnew__dmesg-amdgpu.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu1-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872580/dasharo__archlinuxnew__lspci-vvv-gpu1-bridgedownstream.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu1-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872581/dasharo__archlinuxnew__lspci-vvv-gpu1-bridgeupstream.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu1-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872582/dasharo__archlinuxnew__lspci-vvv-gpu1-gpu.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu1-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872583/dasharo__archlinuxnew__lspci-vvv-gpu1-rootport.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu2-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872584/dasharo__archlinuxnew__lspci-vvv-gpu2-bridgedownstream.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu2-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872585/dasharo__archlinuxnew__lspci-vvv-gpu2-bridgeupstream.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu2-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872586/dasharo__archlinuxnew__lspci-vvv-gpu2-gpu.txt)
[dasharo__archlinuxnew__lspci-vvv-gpu2-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872587/dasharo__archlinuxnew__lspci-vvv-gpu2-rootport.txt)

[dasharo__ubuntu2204__dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/9872602/dasharo__ubuntu2204__dmesg.txt)
[dasharo__ubuntu2204__dmesg-amdgpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872603/dasharo__ubuntu2204__dmesg-amdgpu.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu1-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872604/dasharo__ubuntu2204__lspci-vvv-gpu1-bridgedownstream.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu1-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872605/dasharo__ubuntu2204__lspci-vvv-gpu1-bridgeupstream.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu1-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872606/dasharo__ubuntu2204__lspci-vvv-gpu1-gpu.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu1-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872607/dasharo__ubuntu2204__lspci-vvv-gpu1-rootport.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu2-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872608/dasharo__ubuntu2204__lspci-vvv-gpu2-bridgedownstream.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu2-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872609/dasharo__ubuntu2204__lspci-vvv-gpu2-bridgeupstream.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu2-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872610/dasharo__ubuntu2204__lspci-vvv-gpu2-gpu.txt)
[dasharo__ubuntu2204__lspci-vvv-gpu2-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872611/dasharo__ubuntu2204__lspci-vvv-gpu2-rootport.txt)

[msi1-70_above4g-off__archlinuxold__dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/9872612/msi1-70_above4g-off__archlinuxold__dmesg.txt)
[msi1-70_above4g-off__archlinuxold__dmesg-amdgpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872613/msi1-70_above4g-off__archlinuxold__dmesg-amdgpu.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872614/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-bridgedownstream.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872615/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-bridgeupstream.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872616/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-gpu.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872617/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu1-rootport.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872618/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-bridgedownstream.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872619/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-bridgeupstream.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872620/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-gpu.txt)
[msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872621/msi1-70_above4g-off__archlinuxold__lspci-vvv-gpu2-rootport.txt)

[msi1-70_above4g-on__archlinuxold__dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/9872635/msi1-70_above4g-on__archlinuxold__dmesg.txt)
[msi1-70_above4g-on__archlinuxold__dmesg-amdgpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872636/msi1-70_above4g-on__archlinuxold__dmesg-amdgpu.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872637/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-bridgedownstream.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872638/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-bridgeupstream.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872639/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-gpu.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872640/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu1-rootport.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872641/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-bridgedownstream.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872642/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-bridgeupstream.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872643/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-gpu.txt)
[msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872644/msi1-70_above4g-on__archlinuxold__lspci-vvv-gpu2-rootport.txt)

[msi1-70_above4g-on__archlinuxnew__dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/9872624/msi1-70_above4g-on__archlinuxnew__dmesg.txt)
[msi1-70_above4g-on__archlinuxnew__dmesg-amdgpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872625/msi1-70_above4g-on__archlinuxnew__dmesg-amdgpu.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872626/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-bridgedownstream.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872627/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-bridgeupstream.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872628/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-gpu.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872629/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu1-rootport.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872630/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-bridgedownstream.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872631/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-bridgeupstream.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872632/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-gpu.txt)
[msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872633/msi1-70_above4g-on__archlinuxnew__lspci-vvv-gpu2-rootport.txt)

[msi1-70_above4g-on__ubuntu2204__dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/9872650/msi1-70_above4g-on__ubuntu2204__dmesg.txt)
[msi1-70_above4g-on__ubuntu2204__dmesg-amdgpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872651/msi1-70_above4g-on__ubuntu2204__dmesg-amdgpu.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872652/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-bridgedownstream.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872653/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-bridgeupstream.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872654/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-gpu.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872655/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu1-rootport.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-bridgedownstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872656/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-bridgedownstream.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-bridgeupstream.txt](https://github.com/Dasharo/dasharo-issues/files/9872657/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-bridgeupstream.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-gpu.txt](https://github.com/Dasharo/dasharo-issues/files/9872658/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-gpu.txt)
[msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-rootport.txt](https://github.com/Dasharo/dasharo-issues/files/9872659/msi1-70_above4g-on__ubuntu2204__lspci-vvv-gpu2-rootport.txt)

**Comment by miczyg1** [comment]
Some patches that should fix the issues:

https://review.coreboot.org/c/coreboot/+/69948
https://review.coreboot.org/c/coreboot/+/69949
https://review.coreboot.org/c/coreboot/+/69950

**Comment by miczyg1** [comment]
This does not however fix the problem with not-fitting resources due to big BARs. I guess ReBAR will be needed here as allocation above 4G will need to be checked more thoroughly on coreboot side.

**Comment by zirblazer** [comment]
Nor Large BARs nor ReBAR are necessary for these to work. They worked fine with 256 MiB BARs in Windows. I can get you screenshots of W11 resources if you need them with Above 4G Off and On, and ReBAR Off and On (All the logs but a single screenshot are from Linux) on MSI Firmware.

There has to be something else...

**Comment by zirblazer** [comment]
Screenshots of W11 using the following 3 configurations on MSI 1.70:

Above 4G Decoding OFF

![msi1-70_above4g-off__devicemanager-memory](https://user-images.githubusercontent.com/32025193/203736560-56a06850-1c0c-4fb6-8be0-f3f5a13ebd40.png)


Above 4G Decoding ON / ReBAR OFF

![msi1-70_above4g-on_rebar-off__devicemanager-memory](https://user-images.githubusercontent.com/32025193/203736584-f5e3b022-db15-4389-8d5c-9c14dc3bf2fc.png)


Above 4G Decoding ON / ReBAR ON

![msi1-70_above4g-on_rebar-on__devicemanager-memory](https://user-images.githubusercontent.com/32025193/203736597-45332998-1174-47ef-aa33-b246c2eaf6f2.png)

**Comment by miczyg1** [comment]
I don't see any differences in resource allocation for the AMD GPUs, they still get the minimal resources allocates under 4G.

**Comment by zirblazer** [comment]
The point is, even without Above 4G, both GPUs works. On Dasharo v1.0.0/1.1.0 and the two test versions, I can boot to Windows only after disabling the second 5600XT from Device Manager, and enabling it again causes instant hang or BSOD. Not sure at this point if it was only a resource allocation issue, giving than the test versions seemed to work on Arch Linux OLD but continues to fail in Windows.

**Comment by zirblazer** [comment]
These logs were made with a testing binary, and are already a week old. Posting the reelevant data here to keep things better organized.

So far: Dasharo 1.1.1-rc3 FINALLY WORKS with 2x5600XT (Didn't tested behavior with a single one) in both Arch Linux OLD and Windows 11, which were the problem cases. Attached are the logs from Arch Linux OLD, Ubuntu 22.04.1, and some screenshots of Windows 11 showing CPU-Z, GPU-Z and Device Manager MMIO Ranges in "Resources by Connection" and "Resources by Type" modes (2 screenshots each, can't fit everything in a single one, and I'm not aware if this can be dumped to text file or I need to use a third party tool like HWinfo) as best as I could.

The important thing is that now both PCIe Root Ports 00:01.0 (Main PCI_E1 16x Slot) and 00:1c.4 (Second PCI_E3 16x Slot) reports 258 MiB, which is what is required for GPU BAR0 (256 MiB) and BAR1 (2 MiB). On MSI BIOS 1.70 both reported 384 MiB, but it is not required for them to be oversized.

Note than the current Dasharo settings are equivalent to Above 4G MMIO = OFF. There is still no equivalent to Above 4G ON + ReBar OFF, and Above 4G ON + ReBAR ON, but what matters is that basic functionality works. As a sidenote, Ubuntu 22.04.1 LiveCD failed to boot with an "out of memory error" with MSI BIOS 1.70 with Above 4G Disabled, whereas in Dasharo it worked (I recall than Ubuntu 22.04 LiveCD worked in MSI BIOS 1.70 on same conditions), most likely due to reserving a bit less MMIO (2x258 MiB vs 2x384 MiB).

Also further note than my 5600XTs have broken ReBAR Capabilities, they announce a 1 GiB max BAR0, whereas same-silicon 5700XTs could do 8 GiB. This was acknowledge as a bug by AMD itself but they only fixed it Linux side with a special case that forces a 8 GiB BAR0 if the PCI DeviceID matches 0x731F, most likely when amdgpu reconfigures MMIO. It has to be tested if this workaround can be used Firmware side to set the 8 GiB BAR0 before Windows boots and see if it works, given than AMD doesn't seem willing to fix the bug VBIOS side.

[dasharo-1-1-1-rc3_2x5600xt_cbmem.txt](https://github.com/Dasharo/dasharo-issues/files/10197063/dasharo-1-1-1-rc3_2x5600xt_cbmem.txt)

[dasharo-1-1-1-rc3_2x5600xt_archlinuxold_dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/10197061/dasharo-1-1-1-rc3_2x5600xt_archlinuxold_dmesg.txt)

[dasharo-1-1-1-rc3_2x5600xt_archlinuxold_lspci-vvvnnxxxx.txt](https://github.com/Dasharo/dasharo-issues/files/10197062/dasharo-1-1-1-rc3_2x5600xt_archlinuxold_lspci-vvvnnxxxx.txt)

[dasharo-1-1-1-rc3_2x5600xt_ubuntu-22-04-1_dmesg.txt](https://github.com/Dasharo/dasharo-issues/files/10197064/dasharo-1-1-1-rc3_2x5600xt_ubuntu-22-04-1_dmesg.txt)

[dasharo-1-1-1-rc3_2x5600xt_ubuntu-22-04-1_lspci-vvvnnxxxx.txt](https://github.com/Dasharo/dasharo-issues/files/10197065/dasharo-1-1-1-rc3_2x5600xt_ubuntu-22-04-1_lspci-vvvnnxxxx.txt)

![dasharo-1-1-1-rc3_2x5600xt_windows_cpu-z](https://user-images.githubusercontent.com/32025193/206764926-06fdbf5c-6f98-4df4-b843-6daf82801feb.png)

![dasharo-1-1-1-rc3_2x5600xt_windows_device-manager-connection1](https://user-images.githubusercontent.com/32025193/206764932-864c6ff7-c2d6-46ff-9e52-3494d359db3b.png)

![dasharo-1-1-1-rc3_2x5600xt_windows_device-manager-connection2](https://user-images.githubusercontent.com/32025193/206764934-256e3dff-557a-42fb-b4fb-06a0a48f0e86.png)

![dasharo-1-1-1-rc3_2x5600xt_windows_device-manager-type1](https://user-images.githubusercontent.com/32025193/206764937-2657c529-aae4-4a0d-b3d9-ce4a73751aa3.png)

![dasharo-1-1-1-rc3_2x5600xt_windows_device-manager-type2](https://user-images.githubusercontent.com/32025193/206764941-fc4a99f0-9255-4b3f-8bc2-c2fd59b6bc1e.png)

**Comment by miczyg1** [comment]
The solution to it is to make the below 4G MMIO space bigger to fit all big BARs for two GPUs: https://github.com/Dasharo/coreboot/commit/5b8f7b922d644e2d9bf599cb50152f0ae5bbcc55
Will be available in v1.1.1 release

**Comment by BeataZdunczyk** [comment]
Closing this issue as it has been resolved in the v1.1.1 release. Please refer to https://docs.dasharo.com/variants/msi_z690/releases/#v111-2023-02-23 for further details.
