### ISSUE TITLE
Support charge thresholds

### ISSUE THREAD

**Issue by bserem** [Dasharo/dasharo-issues#246]
**The problem you're addressing (if any)**

Laptop computers are often used as workstations, being always plugged into mains power supply. This leads to bad battery life, because lithium batteries should not be at 100% (or 0%) for prolonged periods of time.

**Describe the solution you'd like**

Add a setting that would not charge battery above 80% and won't start a charge if not below 40% (values are examples)

![thresholds](https://www.tuxedocomputers.com/store_files/1/images/content/faq/screenshot_flexicharger.jpg)

It is actually a killer feature, considering that a laptop should last 5 years, if not longer.

**Where is the value to a user, and who might that user be?**

Batteries will last longer and won't be damaged. It's environmentally good too.

**Describe alternatives you've considered**

Setting this from a utility would also be fine (see tlp), but a setting in coreboot is preferred.

**Additional context**

Dell and HP have a bios setting for this. ThinkPads can be configured through `tlp`.
Tuxedos call this [flexicharge](https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/How-can-I-extend-the-life-of-my-battery-.tuxedo) and Sony phones call it stamina.

**Comment by wessel-novacustom** [comment]
This [has been developed](https://docs.dasharo.com/unified/novacustom/battery-management/#charge-thresholds) now, I think the issue can be closed.

**Comment by wessel-novacustom** [comment]
@bserem The feature [has been integrated](https://docs.dasharo.com/unified/novacustom/battery-management/#charge-thresholds). Could you close the issue, please?
