### ISSUE TITLE
MSI PRO Z690-A non-WIFI DDR4 support

### ISSUE THREAD

**Issue by mseflek** [Dasharo/dasharo-issues#248]
**Dasharo version**
V 1.0

**Dasharo variant**

**Question text**
It seems from first glance that the only difference between the wifi and non-wifi versions of the board is the inclusion of the wifi chip in an m.2 e slot. Will there be any blockers trying to install the firmware on this board? I'm currently thinking of purchasing the board so apologies; I haven't had the resources to try it myself

**Comment by zirblazer** [comment]
The current v1.0.0 binary works, but the SMBIOS info is static and thus it reports it as the WIFI version. Is pretty much cosmetic.

**Comment by mseflek** [comment]
@pietrushnic to be perfectly honest this is more of a "oh cool, something to tinker with" type of project for me than something that is critical to my workload. I found out about this project through Phoronix.com.

What I'm most interested in from this project is more granular control over motherboard features (such as virtualization or power consumption related features), and hopefully longer term support of boards that, with the vendor BIOS, end up essentially EOL'ed once a new Intel/AMD platform is released. Really excited to start playing with this!

**Comment by pietrushnic** [comment]
> @pietrushnic to be perfectly honest this is more of a "oh cool, something to tinker with" type of project for me than something that is critical to my workload. I found out about this project through Phoronix.com.

Great that Phoronix.com spread the word about Dasharo and thanks to that we can grow community.

> What I'm most interested in from this project is more granular control over motherboard features (such as virtualization or power consumption related features), and hopefully longer term support of boards that, with the vendor BIOS, end up essentially EOL'ed once a new Intel/AMD platform is released. Really excited to start playing with this!

Long term maintenance is definitely our goal. Granular control over features is something we working on, but there is huge gap between EDKII and what IBV provide these days, so it means a lot of work to expose feature-rich setup menu. At least we are not going anywhere, so we will extend support gradually. Feel free to add your requests regarding new BIOS options, if anything important would be missing.
