### ISSUE TITLE
edk2 git log malformed

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#25]
**Dasharo version**
v0.2

**Dasharo variant**
Firewall

**Affected component(s) or functionality**
History of git is malformed

**Brief summary**

**How reproducible**
Always

**How to reproduce**
See `git log` of Dashar edk2 `firewall/master` branch:

```
* 1147cb4d62ee (HEAD -> firewall-v0.3-rc1, tag: firewall-v0.2, origin/firewall/master, firewall/master) UefiPayloadPkg: Fix build with TPM enabled
* 66e77bf08b0a UefiPayloadPkg: Drop custom Tcg implementation
* 761994664993 UefiPayloadPkg: Add NullVariable PEI implementation
* 677a77d8926a UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c: use ESC key to enter menu
* 44b2c015349a UefiPayloadPkg/Library/AmdSpiLib/AmdSpiLib.c: remove the constraints
* 9c72752b8707 UefiPayloadPkg/UefiPayloadPkg.fdf: correct the variable base address
* 0da82ea1edb5 UefiPayloadPkg/UefiPayloadPkgIa32X64.dsc: set timeout and boot menu key as in PCE
* 9ffc4373a04f UefiPayloadPkg/NetworkDrivers/ipxe.efi: fix duplicated serial output
* 636f037ba05d UefiPayloadPkg/UefiPayloadPkgIa32X64.dsc: fixes for 64b build
* 8aa9d18cc4ac parent f799169cf721f0b1ec9fb4812caef257c027eb08 author Igor Bagnucki <igor.bagnucki@3mdeb.com> 1600411347 +0200 committer Michał Żygowski <michal.zygowski@3mdeb.com> 1604865605 +0100 gpgsig -----BEGIN PGP SIGNATURE-----
* f799169cf721 UefiPayloadPkg/Library/CbSMMStoreLib/CorebootSMMStore.c: debug SMMSTORE init
* d73636dbbb3c UefiPayloadPkg/Library/PciHostBridgeLib/PciHostBridgeSupport.c: limit max bus number to 64
```

or [here](https://github.com/Dasharo/edk2/commit/8aa9d18cc4ac24b6fe491d793380708bf7821de0)

**Expected behavior**
There should be no such commit title like:
```
* 8aa9d18cc4ac parent f799169cf721f0b1ec9fb4812caef257c027eb08 author Igor Bagnucki <igor.bagnucki@3mdeb.com> 1600411347 +0200 committer Michał Żygowski <michal.zygowski@3mdeb.com> 1604865605 +0100 gpgsig -----BEGIN PGP SIGNATURE-----
```

**Actual behavior**
Clean git log output

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by pietrushnic** [comment]
I tried to fix that [here](https://github.com/Dasharo/edk2/commit/f05b212dbe9d4821c7b66b449d01a7145cc952aa) question to @miczyg1 and @IgorBagnucki, who is not in Dasharo group, if this is ok.

**Comment by IgorBagnucki** [comment]
For me it looks like just change in commit message was required. If that's true, the commit looks ok, but I would prefer @miczyg1 to look at this, since I am not fluent in edk2 nor Dasharo.

**Comment by miczyg1** [comment]
I did a cherry-pick, since a cherry-pick is like a standard commit, it asked me for GPG passphrase to sign it. And this is probably a result...

**Comment by pietrushnic** [comment]
@miczyg1 for me it never ends up like that doing cherry-pick, it looks like some key combination that moved commit title from the top to the bottom. Anyway, I think it should be fixed on whatever branch we plan to maintain longer.

**Comment by IgorBagnucki** [comment]
@pietrushnic @miczyg1 I have checked the current history of edk2 repository and couldn't find malformed commit that was mentioned. 
Can you confirm, that this issue is resolved and can be closed?

**Comment by miczyg1** [comment]
It's still there:
```
commit 8aa9d18cc4ac24b6fe491d793380708bf7821de0
Author: Igor Bagnucki <igor.bagnucki@3mdeb.com>
Date:   Fri Sep 18 08:42:27 2020 +0200

    parent f799169cf721f0b1ec9fb4812caef257c027eb08
    author Igor Bagnucki <igor.bagnucki@3mdeb.com> 1600411347 +0200
    committer Michał Żygowski <michal.zygowski@3mdeb.com> 1604865605 +0100
    gpgsig -----BEGIN PGP SIGNATURE-----
    
     iQIzBAABCAAdFiEEALiPsl/WN1vF/xlda1uiFNIfzrIFAl+oTkUACgkQa1uiFNIf
     zrLGmxAAkPyd/DPe9ZDonQ0orZKNs824hDeFgf8KHu8MF1b8E8PvgNdndVF7w4Kw
     C9Ccq0s8s+a3ZJGshKjafn9SX3ml7pN2x/Bst0CSTbRDiOXECYIN4BMtulFs2Kq4
     /hKdoaYyC/YzViC2ZUuATsgBF0B0puMuMIVgkKHHPNrq87OK2NTr2H5AW6sqw8m+
     Kw07S53slm86HRyIqbi2KRhwG0L+IQhFRBcakDkbim8ry5Bnmwp5rkKoJfvoDCKo
     BbnPQlNVCmmUYR3yIaHQcxlizIEOLmNNItY3H//vJiDCRS7savFIIuiz7dpt6o6R
     AViyCQCgt+ZoJKGZXqIXi79wYFFUyvRJrlcwaDQEHgZ4yviRVrYAlvwSitWDoYRA
     Q+Aelk7ospzK17YLAu5m4T4Z3P2G2xq7Ui7z9wv51tDIW1uT2VFcLzuiO0wmoOLp
     Z5pARVPJrPDphKEkTW73Qu0q2rFeQavFuDHDqkhvXnNvtWu1sQyhaRE4yL5rqN/3
     8BROaHzhMuW88TPFJ8fZmOXJ7WUgbZa1oc2vP3aUvT/c/pRhlSsweVH05K5XiLvl
     hqCuAG4CXwVMuWwv9alhAJsYPK1qqDCfty91muuGZIzqI97kIs1mq1fq2hjwEjXQ
     isb1nsvCSGqtpVvXVItLH9kkEsmAb6jTBbVmErBuZh8j+P2wrd8=
     =K4qO
     -----END PGP SIGNATURE-----
    
    UefiPayloadPkg/AmdSpiDxe: integrate AMD SPI driver
```

**Comment by macpijan** [comment]
@IgorBagnucki This is related to the PC Engines APU2 platform. We need to add that label. We also need to add documentation pages and rename `firewall/master` according to our documentation. This target may be missing proper release.

**Comment by macpijan** [comment]
Not applicable anymore
