### ISSUE TITLE
Add recipe for meinfo from coreboot/utils 

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#250]
**The problem you're addressing (if any)**

Add meinfo from coreboot/utils

**Describe the solution you'd like**

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

Issue copied from other repository which was related to DTS

**Comment by TomaszAIR** [comment]
It was created in https://github.com/Dasharo/meta-dts/issues/17, should `meinfo` be available from https://github.com/Dasharo/coreboot/tree/coreboot-utils/util ?

**Comment by macpijan** [comment]
There is no `meinfo` util as far as I can see. Maybe this one was meant here: https://github.com/Dasharo/coreboot/tree/coreboot-utils/util/intelmetool ?

**Comment by macpijan** [comment]
I'm not sure about the revision. It needs to be checked. It needs to support latest architectures and ME revisions, so maybe we should see what kind of patches landed there lately.

**Comment by TomaszAIR** [comment]
I think we could install intelmetool here. Basically in such kind of request it would be easier to close issues if we would provide SBoM of DTS with every release. This way we could prove that given utility is installed.

**Comment by pietrushnic** [comment]
Signed SBoM and attestation of it :star_struck:

**Comment by DaniilKl** [comment]
@TomaszAIR, I see [`intelmetool_git.bb`  recipe](https://github.com/Dasharo/meta-dts/blob/main/meta-dts-distro/recipes-bsp/coreboot-utils/intelmetool_git.bb) on latest `develop` branch and I am a bit lost why this issue is still open :thinking: ?

**Comment by DaniilKl** [comment]
@TomaszAIR, @macpijan  am a bit lost here, could you please clarify what did you mean?

**Comment by macpijan** [comment]
If you confirm it's there and it works, it should be closed.

**Comment by DaniilKl** [comment]
@TomaszAIR, I am not able to answer on that question. `intelmetool` origin is [`zamaudio/intelmetool`](https://github.com/zamaudio/intelmetool) repo which is now deprecated, latest commits can be found in [`coreboot`](https://github.com/coreboot/coreboot/commits/main/util/intelmetool) repo, though. There is no revision and architecture info neither in the `zamaudio` or `coreboot` repo (or its documentation).

**Comment by TomaszAIR** [comment]
> If you confirm it's there (intelmetool) and it works, it should be closed.

Based on this and comments from @DaniilKl I am closing this one.
