### ISSUE TITLE
Detect Intel fused platforms

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#252]
**The problem you're addressing (if any)**
Some platforms may come with a fused chipset and Enabled Boot Guard. DTS should be able to detect such platforms and warn that Dasharo cannot be installed on such devices.

**Describe the solution you'd like**
Currently, there is no utility in coreboot that will return the fuse state. intelmetool can only print Boot Guard execution status. One needs to parse ME HFSTS6 register to determine the fuse state and report it. intelmetool can be extended to do so and then included in DTS.

**Where is the value to a user, and who might that user be?**
Users will not accidentally brick devices and will get clear information on whether they can run open firmware.

**Describe alternatives you've considered**
Own complex utility for ME configuration and status reporting.

**Additional context**
None

**Comment by artur-rs** [comment]
@miczyg1 I wanted to refresh the request. Do we have any new tools/scripts related to the issue? Is there any more context to be added?

**Comment by PLangowski** [comment]
@miczyg1 I wrote a bash script that checks the fuse state and added it to `meta-dts` https://github.com/Dasharo/meta-dts/pull/138
