### ISSUE TITLE
The external headset connected to the jack slot doesn't work

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#254]
**Dasharo version**
v1.4.0

**Dasharo variant**
NV41PZ

**Affected component(s) or functionality**
The external headset,jack slot

**Brief summary**
The external headset connected to the jack slot doesn't work

**How reproducible**
100%

**How to reproduce**

1. Boot into Ubuntu 22.04.
2. Connect the external headset.

**Expected behavior**
A notification appears (selection of headphones / headset), In Settings -> Sound should be possibility to select connected device, and after clicking `Test`, the headphones should emit a sound, similar situation with the microphone

**Actual behavior**
The system doesn't recognize the headset

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment]
We have proposal for  a workaround here: https://github.com/Dasharo/docs/pull/379
Waiting for @Pokisiekk to report after retesting.

**Comment by Pokisiekk** [comment]
https://github.com/Dasharo/docs/pull/379 - I can confirm that this workaround makes the headset work properly.
