### ISSUE TITLE
MSI PRO Z690-A WIFI DDR4 has wrong Tau values for Turbo Boost

### ISSUE THREAD

**Issue by zirblazer** [Dasharo/dasharo-issues#256]
**Dasharo version**
v1.0.0 for MSI PRO Z690-A WIFI DDR4

**Affected component(s) or functionality**
Intel Turbo Boost duration

**Brief summary**
After casually checking Alder Lake Datasheet, I found out than the default values for Tau duration is supposed to be 56 seconds for at least my current Processor (Core i5 12600K, known as class 6+4 Core 125W on Datasheet): https://edc.intel.com/content/www/us/en/design/ipla/software-development-platforms/client/platforms/alder-lake-desktop/12th-generation-intel-core-processors-datasheet-volume-1-of-2/009/processor-line-thermal-and-power/

Dasharo defaults to 28 seconds instead according to Intel XTU: https://user-images.githubusercontent.com/32025193/179429963-72af60c2-d0ee-440a-9cba-384d5a6c62b6.png

Note than all 125W+ class Processors (12600K, 12700K, 12900K, 12900KS) has 56s Tau, whereas it seems that all other Alder Lake-S models (Basically, all non-K) has 28s Tau.

**How reproducible**
100%

**Additional context**
Based on chat comments, it seems to be related to this: https://github.com/coreboot/coreboot/blob/master/src/soc/intel/alderlake/systemagent.c#L186
DualTauBoost was also mentioned.

**Comment by miczyg1** [comment]
https://review.coreboot.org/c/coreboot/+/69217

**Comment by miczyg1** [comment]
Also cherry-picked it to the release branch in our fork, should appear in v1.1.0 release.
