### ISSUE TITLE
Password protection for Firmware setup

### ISSUE THREAD

**Issue by thePretendend** [Dasharo/dasharo-issues#257]
**The problem you're addressing (if any)**

There currently is no way to protect e.G. the secureboot state from tampering.

**Describe the solution you'd like**

An optional password prompt when entering the firmware setup at boot (pressing Esc when turning the unit on)

**Where is the value to a user, and who might that user be?**

Added security for any user by preventing unauthorized third parties to access security related settings or booting images without authorization.

**Describe alternatives you've considered**

There are none.

**Additional context**

When entering firmware setup, secure boot for example can be turned off without authentication. Also, the boot order can be modified without authentication.

**Comment by pietrushnic** [comment]
@thePretendend thanks for reporting, but it looks like duplicated of #120

**Comment by thePretendend** [comment]
Thank's for the reply, sorry for the deuplicate.
So this seems to be implemented, but not compiled into the preinstalled Version (v1.4.0) on my newly delivered novacustom ns51pu?

**Comment by pietrushnic** [comment]
@thePretendend correct. @wessel-novacustom cc

**Comment by thePretendend** [comment]
Can I somehow get this version as a precompiled binary? I'm not yet confident enought to compile this myself, since I do not have the adaptor for arduino for flashing the firmware externaly yet (in case of an error). Or can I just downgrade to v1.3.0 on an intel alderlake without major issues?

**Comment by wessel-novacustom** [comment]
@pietrushnic Are you sure that this functionality is in our latest Dasharo version implemented? I don't think that this is the case for NS51PU yet, right? :-)

@thePretendend Version 1.4.0 is currently the latest available firmware version. Also, you already have the latest open EC firmware. Newer versions will be easy to flash with Dasharo Tools Suite (DTS). We are working on documentation for that (https://docs.dasharo.com/). If you choose to get firmware update notifications while ordering your laptop, you will receive an email as soon as a new version has been released.

**Comment by thePretendend** [comment]
Thank's for the reply. I'm looking forward to this update, and hope password protection will be implemented there. Will upgrade as soon as I get the notification (which I think, I have chosen, else I'll subscribe to it on the dasharo.com website. afaik tou can do that right?)

**Comment by wessel-novacustom** [comment]
I hope so too, it would be a nice security feature. We'll discuss it with the team.

The Alder Lake version's documentation and news letter is still under construction. If you have chosen to be informed at firmware updates via our website while ordering, you should receive the right newsletter somewhere between December and February.

Otherwise, you can check in December again if the Alder Lake laptop you have has been added to docs.dasharo.com and sign up for the news letter there then.

**Comment by thePretendend** [comment]
Also, will there be a toutorial how to correctly compile this firmware using the docker container:
a) with podman as the container engine since fedora only supports podman?
b) with instructions how to correctly set manufacturer and serialnumber in SMBIOS?
Thank's

**Comment by pietrushnic** [comment]
> @pietrushnic Are you sure that this functionality is in our latest Dasharo version implemented? I don't think that this is the case for NS51PU yet, right? :-)

@wessel-novacustom I'm pretty sure it is not integrated since this is very new thing, we created it at the end of October. @macpijan can you elaborate about that?

> Also, will there be a toutorial how to correctly compile this firmware using the docker container:
> a) with podman as the container engine since fedora only supports podman?
> b) with instructions how to correctly set manufacturer and serialnumber in SMBIOS?

@macpijan let's consider this as feature request.

**Comment by thePretendend** [comment]
Should I create a new feature request for that, or will this here do?

**Comment by wessel-novacustom** [comment]
Sorry, we focus on Ubuntu and/or Debian for the build process. I don't know how easy it is to make this possible under Fedora, too. We will discuss this internally.

I believe that the requested security feature will be integrated into the new release, which will be available in a few months. It's up to @macpijan to confirm this.

Yes, please create separate tickets for separate feature requests.

**Comment by macpijan** [comment]
The password lock **is not** part of the 1.4.0 release, which is shipping with new units.

**Comment by macpijan** [comment]
Podman claims to be a drop-in replacement for Docker. So in theory, you should be able to replace `docker` with `podman` and it might work. Please create a separate ticket on supporting Fedora/podman build and report your results there if you wish.

**Comment by thePretendend** [comment]
Thank's, will do

**Comment by wessel-novacustom** [comment]
> The password lock **is not** part of the 1.4.0 release, which is shipping now with new units.
- Correct, but the question was if it will be part of a future release ;-) .

**Comment by macpijan** [comment]
It might be (and I think there is a good reason to be) along with some more features we implemented in October here: https://github.com/Dasharo/dasharo-issues/projects/5

We just need to agree the roadmap.

**Comment by wessel-novacustom** [comment]
Ok.

I think it is a good idea to implement this feature, yes.
