### ISSUE TITLE
FW6 Comet Lake graphics crashes in Linux

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#26]
**Dasharo version**
1.0.5-rc1

**Dasharo variant**
Firewall

**Affected component(s) or functionality**
Integrated Graphics

**Brief summary**
There is a problem with Intel graphics on a i5-10310u SoC ported to coreboot. I am using Debian 10 with 4.19.x kernel for testing, but it cannot start X session, because /dev/dri/card0 when installed in UEFI mode. When booted in legacy mode X session is starting and the platform is usable till the moment when the screen blanks due to inactivity, then the platform resets. coreboot logs show the PMC firmware requested global reset (from the global reset cause registers). So I suspect a problem with graphics initialization. Tried various scenarios:

Debian 10, kernel 4.19.x, legacy. Graphics initialized with VGA OROM. X is working until one gets the system occupied. When it goes inactive and screen blanks, then global reset happens
Debian 10, kernel 4.19.x, UEFI with TianoCore UEFI payload package. Graphics initialized with FSP GOP driver. X is not working, from the log I see /dev/dri/card0 is not found, but platform is stable.
Debian 10, kernel 5.10 installed from backports, UEFI with TianoCore UEFI payload package. Graphics initialized with FSP GOP driver. I noticed the i915 driver does not bind to graphics device in previous cases, so I upgraded the kernel, because Cometlake graphics is supported since Linux 5.2. Now the DRM is initialized and X starts, but the login prompt is shown only briefly, then the system crashes and displays some garbage on the screen and performs global reset after few seconds.
Ubuntu 20.04.2 has similar behaviour like Debian 10 with kernel 5.10.

Using public FSP for silicon initialization (Cometlake1 FSP to be precise). The original firmware from AMI has no problems with any of the above scenarios. Using OROM and VBT extracted from the original AMI firmware image.

**How reproducible**
Always

**How to reproduce**

1. Boot any of the configurations
2. Wait for login prompt and see garbage and the resets briefly if the firmware is UEFI
3. Wait idly until the system will blank the screen and observe the platform reboots.

**Expected behavior**
Graphics works correctly and the OS is usable. Screen blanking does not cause resets.

**Actual behavior**
Graphics crashes immediately after starting X with UEFI or after going idle and blanking screen on legacy. Platfomr performs global reset requested from PMC (probably graphics power management issue).

**Screenshots**
None

**Additional context**
None

**Solutions you've tried**
1. Try Windows 10 with UEFI firmware variant, in case it is Linux drivers fault. Windows 10 is able to install, but when it boots for the first time after installation it also resets and did not even display login prompt.
2. Try Linux commandline parameters `i915.enable_dc=0` and `consoleblank=0` to avoid the screen going idle and blanking. However it didn't work as well.

TODO: try with newer FSP from Intel and newer GOP driver.

**Comment by miczyg1** [comment]
I managed to launch the platform and get it working quite stable. What I did, is to add the "i915.enable_guc=3 i915.guc_firmware_path=i915/cml_guc_49.0.1.bin' parameters to the Linux kernel commandline. The i915 driver has failed with following messages:

```
[    5.423322] i915 0000:00:02.0: [drm] Incompatible option enable_guc=3 - HuC is not supported!                                              
[    5.432186] i915 0000:00:02.0: [drm] Incompatible option enable_guc=3 - GuC submission is N/A                                              
[    5.441492] i915 0000:00:02.0: [drm] VT-d active for gfx access                                                                            
[    5.447732] i915 0000:00:02.0: vgaarb: deactivate vga console                                                                              
[    5.519583] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem                                   
[    5.532095] i915 0000:00:02.0: firmware: direct-loading firmware i915/kbl_dmc_ver1_04.bin                                                  
[    5.546415] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/kbl_dmc_ver1_04.bin (v1.4)                                         
[    5.553281] i915 0000:00:02.0: firmware: failed to load i915/cml_guc_49.0.1.bin (-2)                                                       
[    5.585022] i915 0000:00:02.0: Direct firmware load for i915/cml_guc_49.0.1.bin failed with error -2                                       
[    5.594173] i915 0000:00:02.0: [drm] GuC firmware i915/cml_guc_49.0.1.bin: fetch failed with error -2                                      
[    5.609497] i915 0000:00:02.0: [drm] GuC firmware(s) can be downloaded from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux5
[    5.630517] i915 0000:00:02.0: GuC initialization failed -2                                                                                
[    5.639734] i915 0000:00:02.0: Enabling uc failed (-5)                                                                                     
[    5.656491] i915 0000:00:02.0: Failed to initialize GPU, declaring it wedged!                                                              
[    5.663919] i915 0000:00:02.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by intel_gt_init+0xa0/0x2d0 [i915]                             
[    5.796700] [drm] Initialized i915 1.6.0 20200917 for 0000:00:02.0 on minor 0                                                              
[    5.821827] fbcon: i915drmfb (fb0) is primary device                                                                                       
[    5.904358] i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device  
```

Somehow the graphics power management works, the screen can go blank on inactivity or when the screen is being locked. However, the issue with this approach is that the kernel must be fresh enough to probe the i915 driver and the cml_guc_49.0.1.bin must be present on the filesystem.

**Comment by pietrushnic** [comment]
@miczyg1 it would be great to have some pass/fail table since I'm not sure I'm getting what you achieved. What are the results for AMI CSM/UEFI and coreboot legacy and Tianocore payload?

TBH first release of coreboot should not have a Tianocore payload.

**Comment by miczyg1** [comment]
AMI works in every case, while Dasharo never worked until I passed the mentioned parameters to Linux when booting legacy Dasharo:

| Firmware / Test variant | Debian 10 kernel 4.19 | Debian 10 kernel 5.10 | Debian 10 kernel 5.10 with cmdline w/a | Windows 10 |
|--|--|--|--|
| AMI legacy mode with CSM | PASS | PASS | NOT TESTED | NOT TESTED |
| AMI legacy UEFI mode | PASS | PASS | NOT TESTED | PASS |
| Dasharo with legacy SeaBIOS | FAIL | FAIL | PASS | NOT TESTED |
| Dasharo with UEFI payload | FAIL | FAIL | NOT TESTED | FAIL |

**Comment by pietrushnic** [comment]
@miczyg1 that's great news, at least we can move forwards and proved this is not firmware-only issue.

**Comment by miczyg1** [comment]
@pietrushnic well, AMi firmware does not need a workaround. My concern is what will happen with distro installers. This Debian 10 was already installed and used backports repo to install the latest kernel and drivers. At least we know, that the i915 and DMC firmware binaries have some dependencies on the BIOS firmware settings. We only need to find which settings. I have also requested some more detailed document of graphics registers so that I could compare differences between FSP/VGA ROM and AMI firmware

**Comment by miczyg1** [comment]
Hmm something weird happens when the platform goes to Susped to Idle (modern S0 Idle):
```
[ 5895.170291] (NULL device *): firmware: direct-loading firmware i915/kbl_dmc_ver1_04.bin            <------------------                                        
[ 5895.179266] Freezing user space processes ... (elapsed 0.001 seconds) done.                                                                
[ 5895.188285] OOM killer disabled.                                                                                                           
[ 5895.191828] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.                                                           
[ 5895.201047] printk: Suspending console(s) (use no_console_suspend to debug)
```

**Comment by pietrushnic** [comment]
It can be easily checked how the kernel detects that. Maybe code has no way of correctly recognized hardware at this point or something is broken in that regard.

**Comment by miczyg1** [comment]
The board hit 20h uptime without reset.

**Comment by miczyg1** [comment]
Found FSP parameters that allow us to disable graphics power management. When disabled, the Linux works well with graphics and doesn't need any custom commandline parameters, but care should be taken when using kernels with i915 driver that do not yet support Cometlake graphics:
- S3 suspend/resume will not work, in some cases the OS may come back (tested with Linxu 4.9), but without graphics (as there is nothing that will re-initialize it after resume, SeaBIOS and VGA option ROM are skipped on S3 resume); in other cases the OS may crash (Linux 4.19)
- modern S0 idle (S0ix/s2idle) works well with kernels supporting s2idle. If one wishes to enable low power states, it is recommended to use s2idle: https://01.org/blogs/qwang59/2018/how-achieve-s0ix-states-linux

**Comment by miczyg1** [comment]
I have been testing the Ubuntu now to verify whether this workaround gives better results and now:

* Ubuntu 20.04.2 installer doesn't boot
* Ubuntu 21.04 installer boots and works ok
* Ubuntu 21.04 installed already, resets when starting X

Previous test were conducted on Debian 10 installed with the mentioned kernels, so Debian behaves better than Ubuntu. Something is still wrong with this power management stuff. I guess the option is to go for comparison of graphics power management registers AMI vs coreboot.

**Comment by miczyg1** [comment]
Update to the table of results:

| Firmware / Test variant | Debian 10 kernel 4.19 (i915 driver not probed) | Debian 10 kernel 5.10 | Debian 10 kernel 5.10 with GUC cmdline w/a | Ubuntu 20.04.2 installer (kernel 5.8) | Ubuntu 21.04 installer (kernel 5.11) | Ubuntu 21.04 installed (kernel 5.11) |
|--|--|--|--|--|
| AMI legacy mode with CSM | PASS | PASS | NOT TESTED | NOT TESTED | NOT TESTED | NOT TESTED |
| AMI legacy UEFI mode | PASS | PASS | NOT TESTED | NOT TESTED | NOT TESTED | NOT TESTED |
| Dasharo with legacy SeaBIOS | FAIL | FAIL | **PASS** | FAIL | PASS | FAIL |
| Dasharo with UEFI payload | FAIL | FAIL | NOT TESTED | NOT TESTED | NOT TESTED | NOT TESTED |

**Comment by miczyg1** [comment]
I have compared the dumps of MMIO registers of AMI firmware and coreboot+FSP, and the lower address registers which are programmed by FSP in power management initialization looks the same... No clues from this

**Comment by miczyg1** [comment]
Newer GOP behaves better than VBIOS, however it still has issues e.g with Debian 10 kernel 4.19.

 I also thought that the i915 driver may have problems with the VBT and OpRegion. And now the results are as follows:

Update to the table of results:

| Firmware / Test variant | Debian 10 kernel 4.19 (i915 driver not probed) | Debian 10 kernel 5.10 | Debian 10 kernel 5.10 with GUC cmdline w/a | Ubuntu 20.04.2 installer (kernel 5.8) | Ubuntu 21.04 installer (kernel 5.11) | Ubuntu 21.04 installed (kernel 5.11) | Debian 10 kernel 4.9 (i915 driver not probed) |
|--|--|--|--|--|--|--|--|
| AMI legacy mode with CSM | PASS | PASS | NOT TESTED | NOT TESTED | PASS | PASS | NOT TESTED |
| AMI UEFI mode | PASS | PASS | NOT TESTED | NOT TESTED | NOT TESTED | NOT TESTED | NOT TESTED |
| Dasharo with legacy SeaBIOS | FAIL | FAIL | **PASS** | FAIL | PASS | FAIL | PASS |
| Dasharo with UEFI payload | FAIL | FAIL | PASS | NOT TESTED | PASS | PASS | NOT TESTED |
| Dasharo with legacy SeaBIOS w/o VBT | FAIL | PASS | NOT TESTED | PASS | PASS | PASS | PASS |

Debian 10 fails with kernel 4.19 when the screen is being locked and goes blank, this however does not occur with 4.9 kernel and 5.10 kernel (here the driver is probed). I think we should not pay that much attention to issues on systems where the driver does not support the graphics device yet. It seems we have found a combination that gives consistent and good results across kernels that have the support for Cometlake graphics in i915 driver @pietrushnic

**Comment by miczyg1** [comment]
With the newer revision of hardware, the issue vanished and workarounds in the firmware are no longer needed. Status will be confirmed with v1.0.18 release.
