### ISSUE TITLE
The power LED is not always blinking while in sleep mode on Ubuntu 22.04

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#260]
**Dasharo version**
v.1.4.0

**Dasharo variant**
NV41PZ

**Affected component(s) or functionality**
The power LED, sleep mode

**Brief summary**
The power LED is permanently green during sleep mode on Ubuntu 22.04

**How reproducible**
After closing the lid - ~80%
After pressing `Fn+F12` or power button - ~50%

**How to reproduce**

1. Power on the DUT.
2. Boot into Ubuntu 22.04.
3. Close the lid or press `Fn+F12` or press power button.

**Expected behavior**
The DUT is in sleep mode, the power LED blinking green

**Actual behavior**
The power LED is permanently green.

**Screenshots**

**Additional context**
Sometimes the power LED only blinks a few times and then it is permanently green again.

**Solutions you've tried**

**Comment by macpijan** [comment]
So if you could link documentation fix here and @Pokisiekk confirms it helps, we might close the issue.

**Comment by mkopec** [comment]
Will do. Also worth mentioning, when testing s0ix, I've noticed that trying to put the laptop into suspend right after it wakes up rarely works, it's best to wait at least 20 seconds for things to calm down (some applications seem to be inhibiting sleep)

**Comment by mkopec** [comment]
@macpijan @Pokisiekk Pushed to novacustom-cleanup:

https://github.com/Dasharo/docs/pull/356/commits/e17c0fe08846133d85abc8e98266605ce5fce32c

**Comment by thePretendend** [comment]
My issue #261 seems similar (maybe the same). I'm running Linux 6.0.7 on a NS51 by Nova Custom. And suspend/sleep does not work at all when closing the lid. Also didn't work on Linux 5.19

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk fix for this bug has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)
