### ISSUE TITLE
The connected RJ45 cable to the Ethernet socket causes a hardware error on Windows 11

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#264]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS5x/7xPU

**Affected component(s) or functionality**
Ethernet connection, Ethernet socket

**Brief summary**
The connected RJ45 cable to the Ethernet socket causes a hardware error on Windows 11

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Windows 11.
3. Connect the RJ45 cable to the Ethernet socket.
4. Wait 1-5 minutes(sometimes up to 2 hours).

**Expected behavior**
The system works normally. The connected cable provides access to the Internet.

**Actual behavior**
The system stops due to the hardware error `WHEA_UNCORRECTABLE_ERROR`.

**Screenshots**
![D208CFA6-3F82-4A1A-BAD6-352285ABFAA4](https://user-images.githubusercontent.com/101700648/202137523-a8259e97-0d00-4f62-9bbd-ba71719b4feb.jpg)

**Additional context**
Basic and optional drivers and updates have been installed.

**Solutions you've tried**
The problem doesn't occur when the RJ45 cable is connected through the docking station.

**Comment by wessel-novacustom** [comment]
We have seen the same blue screen with:

NS51PU, running Windows 11 Pro that was restored from a disk image, that was initially created with a Tiger Lake machine.

Therefore, my question is if you encounter this problem with a clean installation from a USB pen drive?

A reinstallation with a USB pen drive solved the issue for us on that machine.

**Comment by Pokisiekk** [comment]
@wessel-novacustom I installed Windows using a USB drive as usual.

**Comment by wessel-novacustom** [comment]
Hmmm ok, just wanted to make sure :-)

Then we will await a firmware fix of the team.

**Comment by mkopec** [comment]
I enabled verbose BSOD error messages and the error code decodes to `An uncorrectable PCI Express error occurred`. I suspect AER needs to be disabled for that network card.

**Comment by mkopec** [comment]
I've observed the same on an NS5xPU after installing all available updates. Seems like on of the most recent updates started causing these BSODs. On the firmware side, I disabled PCIe AER for the network cards and it doesn't crash anymore, but I'll let it run some more time to confirm.

**Comment by PrzemyslawBanasiak13** [comment]
Reproduced this bug on updated Windows 11 on NS41PZ. 1-2 minutes after connecting the Ethernet cable device throws a blue screen and reboots. The cable has to be connected to the working switch for the bug to occur

**Comment by mkopec** [comment]
@PrzemyslawBanasiak13 Does it still happen on the latest version after we added a fix for this?

**Comment by PrzemyslawBanasiak13** [comment]
@mkopec On firmware including the fix, the problem doesn't occur

**Comment by mkopec** [comment]
Thanks

**Comment by Pokisiekk** [comment]
I am reopening the issue due to the same problem on NS5x/7xPU laptops

**Comment by Stojek139808** [comment]
I've tested https://github.com/Dasharo/coreboot/pull/266 on ns70pu and it seems to fix the problem there too. On the [release branch](https://github.com/Dasharo/coreboot/releases/tag/novacustom_ns5x_adl_v1.4.0) it crashed after 5min every time. After cherry-picking [this one commit](https://github.com/Dasharo/coreboot/commit/cd975d74ed0168b9f573dc3dd98a7f2ec9ac009e) on top of the release branch, the laptop lasted about 2 hours without issues. 
The issue will be fixed in the next release.

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/novacustom_ns5x_adl/releases/#v160-2023-04-07) are the binaries in version v.1.6.0 for NS5x/7x ADL, on which the issue does not occur
