### ISSUE TITLE
Buggy touchpad when charging via USB-C (NV40MZ)

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#265]
**Dasharo version**

v1.3.0 (open EC)

**Dasharo variant**

NovaCustom NV40MZ-i5

**Affected component(s) or functionality**

Touchpad

**Brief summary**

The touchpad shows weird behaviour when charging via USB-C.

**How reproducible**

100%

**How to reproduce**

1. Boot the laptop to Ubuntu 22.04 LTS.
2. Connect the USB-C PowerDelivery (PD) charger.
3. Use the laptop with the touchpad for at least 15 minutes.

**Expected behavior**

The touchpad is working normally, including two finger scrolling and right click by two fingers tapping.

**Actual behavior**

Two finger scrolling is not working and the speed of the touchpad changes constantly.

**Screenshots**

-

**Additional context**

This doesn't seem to happen on a docking station here, although we are not 100% sure as we haven't tested long enough yet.

Sometimes, the touchpad doesn’t respond at all any longer. Most of the time however, the cursor hangs sometimes or makes inaccurate moves when using the touchpad.

Unplugging the USB-C charger helps and brings the touchpad back to normal.

Blacklisting psmouse as we do with NS7x doesn’t help.

**Solutions you've tried**

None.

**Comment by wessel-novacustom** [comment]
This is related to the used USB-C charger. So far, we have tested that this problem only happens with 65W USB-C adaptors that we used to supply. NovaCustom customers who are experiencing this issue can [submit a warranty claim](https://configurelaptop.eu/service-centre/) to receive a USB-C adaptor replacement of 90W, which don't have this issue.

**Comment by wessel-novacustom** [comment]
Sorry, the issue is still present, for 90W+ adaptors as well but the problem seems less aggressive than with the 65W USB-C power adaptor.

**Comment by mkopec** [comment]
This is a common issue with ungrounded power supplies: https://electronics.stackexchange.com/questions/587678/effect-of-charger-on-laptop-touchpad

Some chargers produce noise that gets picked up by the capacitive touchpad. To confirm this is a grouding issue, you can connect a grounded peripheral to the laptop, like a monitor, and check if the problem persists.
