### ISSUE TITLE
Suspend mode not working under Qubes OS 4.1 (NV41PZ DUT)

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#266]
**Dasharo version**

v1.4.0 (DUT)

**Dasharo variant**

NV41PZ-i7 DUT

**Affected component(s) or functionality**

Suspend mode

**Brief summary**

The laptop does not reach the suspend state.

**How reproducible**

100%

**How to reproduce**

1. Boot the laptop to Qubes OS 4.1.
2. Trigger suspend mode with FN+F12 --> Suspend.

**Expected behavior**

The laptop reaches S0(i3) state: suspend state, with a blinking power LED, keyboard illumination powered off, fans powered off, etc.

**Actual behavior**

The screen display is black and showing a 'blinking cursor' (but in fact, it is not blinking).

**Screenshots**

![screendisplay](https://user-images.githubusercontent.com/100232604/202155121-1c46c573-4118-4df5-961b-0c82225b5258.jpg)

![led](https://user-images.githubusercontent.com/100232604/202155152-89dc8ca7-6c5c-4180-b46c-0666ec052e0a.jpg)

**Additional context**

Only a hard reset is possible, the laptop cannot get back to the normal state without that.

This problem might also occur with NS5x_7xPU.

This problem occurs with NV40MZ too, but no compatibility with Qubes OS is planned for that model.

We would like the firmware developer's team to make the ADL laptops compatible with Qubes OS starting from the second (or third in case of NS5x_NS7xPU) firmware release.

**Solutions you've tried**

Fully updating Qubes OS through Qubes Update (GUI).

**Comment by mkopec** [comment]
I believe this is related to this issue: https://github.com/QubesOS/qubes-issues/issues/6411

It looks like Xen hypervisor used in Qubes OS does not currently support s0ix suspend. S0ix requires cooperation of basically all device drivers, and passthrough of PCI devices from host to guest makes it even more difficult.

**Comment by wessel-novacustom** [comment]
Does this mean that the best way to solve this is to wait for Qubes OS S0ix support? Maybe in Qubes OS 5?

**Comment by wessel-novacustom** [comment]
And how easy is S3 integration? In case Qubes OS won't support S0ix for a long time, we might consider that as a workaround?

**Comment by mkopec** [comment]
We haven't tried S3 on Alder Lake laptops since it's officially unsupported since Tiger Lake. We can try but it's unlikely to work at all due to limitations of the ADL-P silicon itself

**Comment by wessel-novacustom** [comment]
Ok, so no other option than to wait for S0ix support in Qubes OS, I guess?

**Comment by miczyg1** [comment]
Maybe related to this: https://github.com/Dasharo/dasharo-issues/issues/267#issuecomment-1318636467
The display may not resume well without graphics driver support, but the whole OS may actually be resuming well. Although if Xen really doesn't support S0ix, then having the graphics driver won't necessarily help.

**Comment by wessel-novacustom** [comment]
Yes, so same answer:

Thank you. I will contact the Qubes team to see if we can get what we need, as we are willing to become a Qubes OS certified partner.

**Comment by marmarek** [comment]
> We haven't tried S3 on Alder Lake laptops since it's officially unsupported since Tiger Lake-U. We can try but it's unlikely to work at all due to limitations of the ADL-P platform itself. I'm not sure if the board is even wired for S3.

Some TGL-based systems do support S3, and it does work under Qubes OS in such case (for example tested on Framework with i7-1165G7). I haven't tested myself on any ADL system, but I think I've seen reports of it working too.

S0ix support is in development, but it will be about two more months.

**Comment by wessel-novacustom** [comment]
Good to know!

Good luck with the S0ix integration :-) . I will post here once it works.

**Comment by wessel-novacustom** [comment]
For suspend mode in Qubes OS, S3 is currently required.

As our customers and I personally prefer S3 suspend mode instead of S0ix modern standby and Qubes OS does not support S0ix currently, we will develop S3 suspend mode for our next firmware release. This will solve the suspend issue under Qubes OS. Once it has been released, I will close this topic.

**Comment by wessel-novacustom** [comment]
Working with certified hardware that has S3 enabled, provided that Qubes OS was installed with _kernel latest_ from the GRUB installation menu and that all Qubes OS updates have been installed.
