### ISSUE TITLE
Docking station under Qubes OS (NV41PZ)

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#267]
**Dasharo version**

v1.3.0 with open EC

**Dasharo variant**

NovaCustom NV41PZ-i7

**Affected component(s) or functionality**

Docking station

**Brief summary**

The docking station (Wavlink WL-UMD05 Pro) is not passing video signal at all.

**How reproducible**

100% reproducible.

**How to reproduce**

1. Boot the NV41PZ to Qubes OS (latest version, currently 4.1.1).
2. Plug in the docking station and make sure it is turned on.

**Expected behavior**

The two external screen displays that were connected via the docking station are active.

**Actual behavior**

The two external screen displays that were connected via the docking station are not active.

**Screenshots**

-

**Additional context**

Other docking station functionality (other than the screen displays) might be affected, too.

**Solutions you've tried**

Play around with blocked devices settings, but I have no experience with this ...

**Comment by miczyg1** [comment]
As far as I know, Qubes OS R4.1.1 does not contain AlderLake graphics support in the Intel graphics Linux driver. So basically the Dasharo firmware is only initializing primary display (LCD) and Qubes is utilizing the display framebuffer passed from the firmware. Thus only LCD works. Qubes OS has no means to enable any secondary display without a Linux driver support. An update to newer Linux kernel version in Qubes could help, but I am not sure if QUbes provides a kernel that contains Alder Lake graphics driver.

**Comment by wessel-novacustom** [comment]
Thank you. I will contact the Qubes team to see if we can get what we need, as we are willing to become a Qubes OS certified partner.

**Comment by wessel-novacustom** [comment]
Graphics acceleration for Alder Lake processors will have to be integrated by the Qubes OS team. This might be an issue of the current kernel. We will post an update as soon as this compatibility has been realised and then close the issue.

**Comment by Pokisiekk** [comment]
@wessel-novacustom fix for this bug for NV4x ADL has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)
