### ISSUE TITLE
The power LED is not blinking during sleep mode when the docking station is connected on Windows 11

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#268]
**Dasharo version**
v1.4.0

**Dasharo variant**
NV41PZ

**Affected component(s) or functionality**
power led, sleep mode

**Brief summary**
The power LED is not blinking during sleep mode when the docking station is connected

**How reproducible**
100%

**How to reproduce**

1. Power on the laptop.
2. Boot into Windows 11.
3. Connect the docking station.
4. Close the lid or press `Fn+F12` or press power button.

**Expected behavior**
The laptop is in sleep mode, the power LED blinking green

**Actual behavior**
The laptop is in sleep mode, the power LED is permanently green

**Screenshots**

**Additional context**
Disconnecting the docking station causes the power LED start blinking green.
Connecting the docking station during sleep, stops the power LED blinking and it is permanently green again.

**Solutions you've tried**

**Comment by PrzemyslawBanasiak13** [comment]
I've checked this issue and I confirm that the device behavior is as described in the `Actual Behavior` section. When in sleep mode docking station is connected LED instead of blinking is turned on continuously.

**Comment by macpijan** [comment]
Please extend the description with docking station details.

We are expecting a new one tomorrow, which will be a replacement to the existing model. We will need to retest that later on with a new station model.

**Comment by PrzemyslawBanasiak13** [comment]
https://github.com/Dasharo/dasharo-issues/issues/268#issuecomment-1318548729

Docking station I've used to reproduce described malfunction:
[**"USB-C Multi-function dock station"**](https://jiji.com.gh/achimota/accessories-and-supplies-for-electronics/usb-c-mulit-function-dock-station-8in1-4bwXswg6chVn9jxpVtB5FTfY.html)
Couldn't find the producer's name on the package and that's the only photo/information about it I could find.

**Comment by Pokisiekk** [comment]
Duplicate of https://github.com/Dasharo/dasharo-issues/issues/368
