### ISSUE TITLE
Suspend doesn't work in Qubes OS with v1.1.0

### ISSUE THREAD

**Issue by renehoj** [Dasharo/dasharo-issues#271]
**Dasharo version**
1.1.0

**Dasharo variant**
MSI Pro Z690-A DDR4 Wi-Fi

**Affected component(s) or functionality**
Suspend doesn't work with Qubes OS.

**Brief summary**
The system reboots when returning from suspend.

I have only tested it with Qubes OS 4.1.1

**How reproducible**
I have tested it twice and this system rebooted both times.

**How to reproduce**

1. Suspend the system
2. Wake up the system
3. The system reboots

**Comment by miczyg1** [comment]
suspend/resume might need driver support for Alder Lake devices to work properly, Current Qubes OS 4.1.1 lacks those.

**Comment by miczyg1** [comment]
Apparently the suspend breaking with v1.1.0 was our fault. Fixed by https://github.com/Dasharo/edk2/pull/40 and will be included in v1.1. release

**Comment by BeataZdunczyk** [comment]
Closing this issue as it has been resolved in the v1.1.1 release. Please refer to https://docs.dasharo.com/variants/msi_z690/releases/#v111-2023-02-23 for further details.
