### ISSUE TITLE
Option to erase all Secure Boot keys

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#279]
**The problem you're addressing (if any)**
Currently one has to enter custom mode and loop through all keys and delete one by one manually, which is tedious.

**Describe the solution you'd like**
An option to erase all installd keys in one sway, similarly like the reset keys option added recently.

**Where is the value to a user, and who might that user be?**
Better user experience and intuitive use of UEFI Secure Boot.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by macpijan** [comment]
It is there: https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration
