### ISSUE TITLE
Add documentation for the newest Dasharo features

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#281]
**The problem you're addressing (if any)**

Some of the newest Dasharo features don't have any documentation which makes it easier to understand how the whole mechanism works.

**Describe the solution you'd like**

The following newest Dasharo features should have documentation:
1. PS/2 Controller enable/disable option.
2. Chipset watchdog support during boot and watchdog configuration menu.
3. TCG2 TPM Physical Presence Interface support.
4. Early boot DMA protection.
5. Firmware setup password.
6. SED/OPAL disk password support.
7. SATA disk password.
8. Firmware performance reporting.
9. USB stack and mass storage enable/disable option.
10. Network Boot enable/disable option
11. SMM BIOS Write Protection support and enable/disable option
12. AcpiView command to UEFI Shell
13. Platform will beep 12 times and blink HDD led on critical firmware errors, e.g. if memory training failed
14. PCIe 5.0 firmware caching in flash which allows to disable ME without losing PCIe 5.0 port functionality
15. cbmem logging from UEFI Payload is now supported and one can check complete firmware logs from OS using coreboot's cbmem utility

**Where is the value to a user, and who might that user be?**

1. Users might use this documentation during owned device configuration procedure.
2. In case of a problem with the working of any above-described functionality users might easily compare the performance of their own platform to the assumed performance of its creators.

**Comment by miczyg1** [comment]
The documentation has been added:
https://github.com/Dasharo/docs/pull/419
https://github.com/Dasharo/docs/pull/429
https://github.com/Dasharo/docs/pull/430
https://github.com/Dasharo/docs/pull/431
https://github.com/Dasharo/docs/pull/432
https://github.com/Dasharo/docs/pull/423
