### ISSUE TITLE
sata-suspend-fixup.sh incompatible with immutable OSs.

### ISSUE THREAD

**Issue by thePretendend** [Dasharo/dasharo-issues#283]
**Dasharo version**

**Dasharo variant**

**Affected component(s) or functionality**

SATA suspend

**Brief summary**

The script to resolve an issue with the suspend of SATA SSDs does not work with immutable OSs like Fedora Silver Blue or Open Suse MicroOS because /usr is being mounted read-only. 

**How reproducible**

**How to reproduce**
Run script on an immutable Linux distribution.
1. Install an immutable Linux distribution.
2. Run script.
3. Observe output.

**Expected behavior**

(Without reading and understanding script) copy commandline from https://docs.dasharo.com/unified/clevo/post-install/#introduction and paste into terminal and have it return 0 / no error.

**Actual behavior**

Created symlink /etc/systemd/system/multi-user.target.wants/enable_dipm.service → /etc/systemd/system/enable_dipm.service.
Job for enable_dipm.service failed because the control process exited with error code.
See "systemctl status enable_dipm.service" and "journalctl -xeu enable_dipm.service" for details.

**Screenshots**

**Additional context**

Immutable OSs provide a lot of reliability and may be "the future" for the Linux Desktop. They should be supported whenever possible. 

**Solutions you've tried**

/usr/local/bin/ should be replaceable with /var/local/bin and I think the latter should be preferred anyway.

**Comment by macpijan** [comment]
Thanks for the report @thePretendend 
Right now the Fedora in general is supported in limited form. We just install the basic Fedora image.

Supporting immutable OS might be in fact important and we may look at this in the future.

**Comment by wessel-novacustom** [comment]
Hello,

I assume this fix is for any NovaCustom laptop.

Please note that SATA SSDs are officially not supported, but users can still use this workaround.

If there is anyone of the community who is willing to share his/her Fedora-adapted script, please feel free to share it here.

**Comment by thePretendend** [comment]
#!/bin/bash

# A script to install a service that enables SATA link power management on
# each boot.
# Enables suspend mode while a SATA SSD is attached to the system.

# Location to the script that shall be executed on each boot.
SCRIPT="/var/usrlocal/bin/enable_dipm.sh"
SERVICE="/etc/systemd/system/enable_dipm.service"

if [ "$EUID" -ne 0 ]
  then echo "This script needs to be executed as root."
  exit
fi

echo "#!/bin/bash

SCSI_HOST=/sys/class/scsi_host

if [ ! -d \$SCSI_HOST ]; then
		exit
fi

if [ -z '\$(ls -A \$SCSI_HOST)' ]; then
		exit
fi

for host in \$SCSI_HOST/host*; do
		echo 'med_power_with_dipm' > \$host/link_power_management_policy
done
" > $SCRIPT

chmod +x $SCRIPT

echo "
[Unit]
Description=Enable SATA DIPM
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/var/usrlocal/bin/enable_dipm.sh

[Install]
WantedBy=multi-user.target
" > $SERVICE

systemctl daemon-reload
systemctl enable --now enable_dipm.service

**Comment by thePretendend** [comment]
This might work.

**Comment by wessel-novacustom** [comment]
@thePretendend S-ATA disks are officially not supported by our laptops.

I'm not sure if the issue was for one of our laptops or not. Also, I don't know if it is still relevant. If it is no longer relevant, please consider to close the issue.
