### ISSUE TITLE
Improved visual comfort

### ISSUE THREAD

**Issue by micmarluc** [Dasharo/dasharo-issues#286]
**The problem you're addressing (if any)**
When you press F7 on startup, to choose a boot device, the selected element appears on a black background while the other elements are on a very dark blue background, and it's not easy to distinguish the selection compared to the other elements.

**Describe the solution you'd like**
Increase the contrast, for example keep the black for selection but with a lighter blue (or other) background...

**Where is the value to a user, and who might that user be?**
An improved visual comfort, especially for people with poor eyesight.

**Describe alternatives you've considered**

**Additional context**

**Comment by miczyg1** [comment]
@micmarluc I don't exactly see which colors are not contrasting enough:

![image](https://user-images.githubusercontent.com/30656491/207632860-b918ca8e-ec2e-4cb5-90cd-ace08210ec31.png)

**Comment by micmarluc** [comment]
@miczyg1 

In my opinion, there is a very low contrast between the black background of the selected element ("Sandisk Ultra Fit", in your example), and the very dark blue background of the pop up window.

My proposal looks like this, please see attachment, (blue color is an example) : the contrast is better between selected and not selected elements.
![boot_options](https://user-images.githubusercontent.com/105767098/208265114-77722a65-b057-4ee7-9e80-4c66ad227bcb.png)

Best regards
micmarluc

**Comment by miczyg1** [comment]
> In my opinion, there is a very low contrast between the black background of the selected element ("Sandisk Ultra Fit", in your example), and the very dark blue background of the pop up window.

I see now... Okay, we will consider making a better contrast here.

**Comment by miczyg1** [comment]
@micmarluc I have made my own vision of improved visual comfort. Let me know how do you like it (yellow hover plus moving arrow):

![image](https://user-images.githubusercontent.com/30656491/208740509-d61a52c8-e62d-4c07-99b0-344ad98e41c0.png)

**Comment by micmarluc** [comment]
It's OK for me : yellow color and moving arrow are very good ideas ! (blue might be less dark, but it’s a matter of personal taste).

**Comment by miczyg1** [comment]
PR: https://github.com/Dasharo/edk2/pull/42

**Comment by miczyg1** [comment]
My modification has landed on the main edk2 branch. It can be expected to be seen on the closest release to be published. Closing.
