### ISSUE TITLE
iPXE entry doesn't occur in setup menu

### ISSUE THREAD

**Issue by PrzemyslawBanasiak13** [Dasharo/dasharo-issues#289]
**Dasharo version**
v1.0.0

**Dasharo variant**
Protectli VP2420

**Affected component(s) or functionality**
iPXE boot entry

**Brief summary**
iPXE boot entry is not shown as it's supposed to do in the setup menu.

**How reproducible**
100%

**How to reproduce**

1. Boot the device
2. Press the boot menu key
3. Look for `Network boot and utilities` in the setup menu

**Expected behavior**
iPXE is shown in the setup menu.

**Actual behavior**
iPXE is NOT shown in the setup menu.

**Comment by miczyg1** [comment]
@PrzemyslawBanasiak13 also the procedure for reproduction is wrong. One should look for `Network boot and utilities`, iPXE word will never be found on Protectli Dasharo builds.

**Comment by PrzemyslawBanasiak13** [comment]
> @PrzemyslawBanasiak13 also the procedure for reproduction is wrong. One should look for `Network boot and utilities`, iPXE word will never be found on Protectli Dasharo builds.

@miczyg1 Corrected

**Comment by miczyg1** [comment]
Reproduction confirmed. Fixed it.

**Comment by sulewskiprzemyslaw** [comment]
@miczyg1 @PrzemyslawBanasiak13 new prepared release candidate binary contains the `Network boot and utilities` menu which contains all necessary options. Taking into account the above, I close the issue
