### ISSUE TITLE
Dasharo BIOS lock menu is missing on VP2420 v1.0.0

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#291]
**Dasharo version**
v1.0.0

**Dasharo variant**
VP2420

**Affected component(s) or functionality**
UEFI payload menu/Dasharo features menu

**Brief summary**
A menu to enable/disable BIOS lock is missing on VP2420 v1.0.0

**How reproducible**
100%

**How to reproduce**

1.  Power on the VP2420
2. Enter firmware setup
3. Enter Dasharo System Features
4. See there is no Dasharo Security Options submenu which should contain `Lock the BIOS boot medium` option.

**Expected behavior**
Dasharo Security Options submenu is present under Dasharo System Features and contains `Lock the BIOS boot medium` option.

**Actual behavior**
Dasharo Security Options submenu is NOT present under Dasharo System Features.

**Screenshots**
![image](https://user-images.githubusercontent.com/30656491/208470934-2eba7248-568c-4f53-a7c2-2699a28e0d81.png)

**Additional context**
None

**Solutions you've tried**
None

**Comment by Pokisiekk** [comment]
@miczyg1 On v1.0.1 it works as you described:
1. `Dasharo Security Options` is presented under `Dasharo System Features` and contain `Lock the BIOS boot medium` option.
2. There are no other submenus under `Dasharo System Features`
