### ISSUE TITLE
The Auto Boot time-out value is not respected

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#292]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS5x/7xPU, NV41PZ

**Affected component(s) or functionality**
`Auto Boot time-out` value in BIOS, booting time

**Brief summary**
The `Auto Boot time-out` value is not respected, when changing this value in the BIOS settings to X seconds, the `Auto Boot time-out` value is still 2 seconds

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Press `ESC` to enter the setup menu.
3. Select the `Boot Maintance Manager` option.
4. Set `Auto Boot Time-out` value to X seconds.
5. Press `F10` and `Y` to save changes.
6. Restart the DUT.

**Expected behavior**
The time between the appearance of the logo/BIOS entry keys and the start of auto-boot is X seconds.

**Actual behavior**
The time between the appearance of the logo/BIOS entry keys and the start of auto-boot is 2 seconds.

**Screenshots**

**Additional context**
After restarting and re-entering the settings, the `Auto Boot Time-out` value is always 2

**Solutions you've tried**

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/novacustom_ns5x_adl/releases/#v160-2023-04-07) are the binaries in version v.1.6.0 for NS5x/7x ADL, on which the issue does not occur

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk Fix for this bug for NV4x ADL has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)
