### ISSUE TITLE
ACPI boot errors during booting Ubuntu 22.04

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#293]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS5x/7xPU, NV41PZ

**Affected component(s) or functionality**
Booting Ubuntu 22.04

**Brief summary**
While booting Ubuntu 22.04, there are several ACPI errors on the screen.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot Ubuntu 22.04.

**Expected behavior**
Ubuntu boots without any errors displayed.

**Actual behavior**
ACPI errors are displayed during booting Ubuntu 22.04.

**Screenshots**

![Screenshot from 2022-12-20 07-15-48](https://user-images.githubusercontent.com/101700648/208598260-2dfecd87-815d-479b-82fa-93d6cf90559a.png)

**Comment by Pace17881** [comment]
Same here on my NovaCustom NV41 (nv4x_adl)
For me it appears on  my current system: debian bookworm (kernel 6.2.6)
Also other live distributions like linux mint 21.1 (kernel 5.19) or POPOS shows the
issue

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/novacustom_ns5x_adl/releases/#v160-2023-04-07) are the binaries in version v.1.6.0 for NS5x/7x ADL, on which the issue does not occur

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk Fix for this bug for NV4x ADL has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)
