### ISSUE TITLE
Windows update KB5012170 cannot be installed

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#294]
**Dasharo version**
v1.4.0, v1.3.0

**Dasharo variant**
NS5x/7xPU, NV41PZ, NS5x/7xMU

**Affected component(s) or functionality**
Windows update

**Brief summary**
Windows update KB5012170 cannot be installed

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot Windows 11.
3. Install all Windows updates.

**Expected behavior**

![win-update](https://user-images.githubusercontent.com/101700648/208599813-eea03a3b-301f-44e4-b9fd-19ec231ede77.png)

**Actual behavior**

![Screenshot from 2022-12-20 07-35-13](https://user-images.githubusercontent.com/101700648/208599858-f608951c-63ba-4a4b-8cb2-87f3a3b68a5a.png)

**Comment by Pokisiekk** [comment]
On NV4xMx with v1.4.0 dasharo firmware, issue does not occur

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/novacustom_ns5x_adl/releases/#v160-2023-04-07) are the binaries in version v.1.6.0 for NS5x/7x ADL, on which the issue does not occur

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk Fix for this bug for NV4x ADL has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)
