### ISSUE TITLE
Protectli VP4670 - windows crashes after installing updates

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#302]
**Dasharo version**
v1.0.19

**Dasharo variant**
Dasharo for Protectli VP4670

**Affected component(s) or functionality**
Windows 11 support

**Brief summary**

After installing all of the updates Windows 11 crashes immediately.

**How reproducible**

100%

**How to reproduce**

1. By using the USB installer install Windows 11.
2. Boot into the system.
3. By using the Windows Update app download and install all  available updates,
4. Reboot the device (some updates need a reboot of the system for working correctly).

**Expected behavior**

Windows 11 have not crashed after performing the update process.

**Actual behavior**

Windows 11 crashes after performing the update process. 

**Screenshots**

1.  Information about the Windows version:

![windows_version](https://user-images.githubusercontent.com/90184097/211318630-7ae720e5-11c4-4b43-bf01-fc697d70d2a7.jpg)

2. SMBIOS log:

![dmidecode](https://user-images.githubusercontent.com/90184097/211318796-e65739fd-d325-42dc-bb69-4ed1526f60cd.jpg)

3. List of the updates:

![updates_list](https://user-images.githubusercontent.com/90184097/211318941-21379835-04bc-4ca5-b16d-310933a0ab33.jpg)

4. Crash info:
 
![crash](https://user-images.githubusercontent.com/90184097/211318890-9ed34fcc-ef00-45fc-a89c-d4a5ec68e0e9.jpg)

**Additional context**

N/A

**Solutions you've tried**

1. Installing two Windows 11 versions: 22H2 (OS build 22621.525) and 21H2 (OS build 22000.318).
2. Blocking after installing the OS auto-updates (this one works).

**Comment by miczyg1** [comment]
Potential fixes: https://github.com/Dasharo/coreboot/pull/303

Tried installing and updating 3 times on VP4670. So far looks good, but probably we need much more testing

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/protectli_vp46xx/releases/#v110-2023-06-05) are the binaries in version v.1.1.0 for VP4670, on which the issue does not occur
