### ISSUE TITLE
Impossibility of pfSense/OPNsense console versions installation

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#309]
**Dasharo version**
v1.0.0

**Dasharo variant**
Protectli VP2420

**Affected component(s) or functionality**

1. pfSense support (console version)
2. OPNsense support (console version)

**Brief summary**

There's a lack of possibility for installing the two systems mentioned above on the VP2420. At some point during the installation, there are problems that stop the process (console output does not change, it seems like the platform hangs up).

**How reproducible**

100%

**How to reproduce**

1. Prepare pfSense/OPNsense installer on the USB.
2. Put the USB into the USB slot on the VP2420.
3. Start the installation process and wait for the hang-up.

**Expected behavior**

Installation of the above-mentioned systems ends successfully.

**Actual behavior**

Installation of the above-mentioned systems ends with failure.

**Screenshots**

N/A

**Additional context**

Log from pfSense installation process:
[pfsense-log.txt](https://github.com/Dasharo/dasharo-issues/files/10479783/pfsense-log.txt)

**Solutions you've tried**

1. Different versions of systems.

**Comment by mkopec** [comment]
Addressed in https://github.com/Dasharo/coreboot/pull/286

**Comment by Pokisiekk** [comment]
On v1.0.1 I was able to install both systems in serial versions
