### ISSUE TITLE
PS/2 keyboard nonfunctional in UEFI

### ISSUE THREAD

**Issue by unilock** [Dasharo/dasharo-issues#311]
**Dasharo version**
v1.1.1 RC3

**Dasharo variant**
msi_ms7d25

**Affected component(s) or functionality**
PS/2 functionality

**Brief summary**
My PS/2 keyboard works in the OS, but does not work in the UEFI. (nor the OS prior to the OS's drivers being loaded, i.e. a pre-boot environment provided by LUKS that asks for the disk encryption password)

**How reproducible**
Always

**How to reproduce**

1. Attach a PS/2 keyboard to the computer
1. Turn the computer on
2. Try to e.g. enter the UEFI settings by pressing the "DEL" key
3. The UEFI does not respond to the "DEL" key, and continues booting the OS

**Expected behavior**
The UEFI settings are entered after pressing the "DEL" key.

**Actual behavior**
The UEFI does not respond to the "DEL" key, and continues booting to the OS.

**Screenshots**
N/A

**Additional context**
I do have the PS/2 controller *enabled* in the UEFI settings.
A USB keyboard *does work* to enter the UEFI settings, or to use any other hotkey during boot.

The PS/2 keyboard used to work with Dasharo firmware versions prior to v1.0.0. It's possible this problem existed on v1.0.0, but I was never able to test due to coreboot failing to initialize my iGPU on said firmware. Nor was I able to test v1.1.0 - which may be relevant, as this version added the ability to toggle the PS/2 controller in the UEFI.

My PS/2 keyboard is a "Microsoft Natural Keyboard Elite".
(Notably, this keyboard original shipped with a passive "PS/2 to USB" adapter; maybe that's relevant? Note that I do not have said adapter, as I bought the keyboard pre-owned.)

**Solutions you've tried**
Disabling and re-enabling the PS/2 controller in the UEFI settings
...?

**Comment by miczyg1** [comment]
Here is the explanation why it doesn't work: https://github.com/Dasharo/dasharo-issues/issues/123#issuecomment-1402308580

**Comment by unilock** [comment]
Got it. I'll close this issue as a duplicate then.

**Comment by wessel-novacustom** [comment]
A workaround: turn off the laptop, unplug the power plug for about 2 seconds, plug it in again, start the laptop and the keyboard is working again.

**Comment by wessel-novacustom** [comment]
Or computer in this case, might be a workaround for that too? Not sure, just wanted to give a hint actually.

**Comment by wessel-novacustom** [comment]
@unilock Is this issue still present in the latest firmware version?

**Comment by miczyg1** [comment]
For MSI board this issue is still relevant.

**Comment by tlaurion** [comment]
Related even if not UEFI? https://ticket.coreboot.org/issues/515
