### ISSUE TITLE
DTS Release Notes should be precisely explain version of given tool

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#314]
**The problem you're addressing (if any)**

Right now change log of DTS v1.1.0 explain flashrom support in following way:

> Updated flashrom to version [dasharo-v1.2.2](https://github.com/Dasharo/flashrom/tree/dasharo-v1.2.2)

This doesn't say anything to user. Of course if developer wants to check feature set which exist behind the link she/he will figure out. But in most cases community want to use tool not hack on it.

DTS tools contain additional features and this is huge value for DTS which should be reach the market. Users should use our version of tool because it includes more and better features.

More to that I'm not sure if dasharo-v1.2.2 would be good versioning scheme. We should check what schemes are used in major distributions that deal with customized versions of packages for more than 30 years e.g. [Debian](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version)

**Describe the solution you'd like**

Precisely describe in DTS release notes what changes given component include.

**Where is the value to a user, and who might that user be?**

Better explanation of what is included in distribution.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by PLangowski** [comment]
How detailed do you think those explanations should be? Because finding out the exact changes for every tool between every past release is going to be very complicated. Unless you only want to introduce this in future releases without modifying the existing changelog notes.

**Comment by pietrushnic** [comment]
@PLangowski, I don't see a reason to introduce that for past releases. Having that information in all future releases is good enough for me.
