### ISSUE TITLE
SATA ports malfunction or Hot-Plug function disabled

### ISSUE THREAD

**Issue by collector-ynh** [Dasharo/dasharo-issues#315]
**Dasharo version**
1.1

**Dasharo variant**
MS-7D25

**Question text**

Hello, I would like to report a problem with the initialization of the SATA ports of the MSI PRO Z690-A DDR4 with Dasharo 1.1, 

I made several tests. The SATA ports work, but only if you connect a SATA device before starting Dasharo. This is the only way the connected SATA port will be initialized. Once the port is initialized, it is possible to disconnect the SATA device while the motherboard is running and reconnect another one without any problem, but the other SATA ports that were not connected to any device before Dasharo started are not initialized and do not work after the startup!

Maybe this is some kind of hot-plug related problem!

**Comment by miczyg1** [comment]
@collector-ynh as far as I understood, you are requesting the SATA hotplug to be enabled. In most cases SATA disks are statically connected before power on, so we didn't enable hot-plug by default. But if you consider it important, there is no problem with enabling that.

**Comment by collector-ynh** [comment]
@miczyg1 Yes, I would like to have the SATA hot-plug enabled. Are there any particular reasons why you would not want to enable the hot-plug by default, such as problems that could possibly be triggered? 
I think it's just an extra feature that shouldn't have any negative influence on Dasharo if it was enabled by default!

Personally I don't use the hot-plug on M2 slots, but only on SATA connectors

Do I have to recompile Dasharo to enable the SATA hot-plug function? Or is it possible to enable it directly via the configuration menu provided at Dasharo startup?

**Comment by miczyg1** [comment]
@collector-ynh we will enable it by default. Runtime option for that is not anticipated yet.

**Comment by collector-ynh** [comment]
@miczyg1 Thanks, I'm looking forward to using the hotplug on the MSI :)

**Comment by miczyg1** [comment]
PR enabling HP: https://github.com/Dasharo/coreboot/pull/288

**Comment by BeataZdunczyk** [comment]
Closing this issue as it has been resolved in the v1.1.1 release. Please refer to https://docs.dasharo.com/variants/msi_z690/releases/#prerequisites for further details.
