### ISSUE TITLE
DTS does not detect MSI platform correctly and allows to flash firmware unsupported on platform variant

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#317]
**Dasharo version**
Any

**Dasharo variant**
Dasharo compatible with MSI PRO Z690-A DDR4/DDR5

**Affected component(s) or functionality**
DTS

**Brief summary**
Currently DTS only support deployment of Dasharo v1.0.0 which is supported only on DDR4 variant. DDR5 variant is not supported. One of the users managed to deploy the Dasahro on MSI DDR5 variant and bricked the platform, issue reported via Matrix.

**How reproducible**
Always: https://github.com/Dasharo/meta-dts/blob/main/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy#L157

**Expected behavior**
DDR5 should be reported as unsupported unless the deployment is implemented in DTS.

**Actual behavior**
DDR4 and DDR5 variant have the same product name in the DMI type 1 System Information. Thus matching to MS-7D25 will cause flashing on any variant: https://github.com/Dasharo/meta-dts/blob/main/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy#L157

DTS should use baseboard product name (from DMI type 2)  which is as follows for DDR5:

```
Base Board Information
	Manufacturer: Micro-Star International Co., Ltd.
	Product Name: PRO Z690-A WIFI (MS-7D25)
```

If baseboard product name was used for MSI platform, there would be no mistake to flash DDR5 platform with unsupported Dasharo firmware.

**Comment by miczyg1** [comment]
DDR4 variants:

- PRO Z690-A WIFI DDR4(MS-7D25)
- PRO Z690-A DDR4(MS-7D25)

DDR5 variants:

- PRO Z690-A WIFI (MS-7D25)
- PRO Z690-A (MS-7D25)

**Comment by miczyg1** [comment]
@macpijan GUID is still an info from SMBIOS, not sure how that improves the situation. UEFI went with GUIDs for almost anything and most people hate it.

Here is a pull request that correctly handles MSI platforms:
https://github.com/Dasharo/meta-dts/pull/26 (needs verification on real hardware though)

**Comment by pietrushnic** [comment]
@miczyg1 from beginning scripts were treated as temporary deployment method fwupd is state of the art and whatever they choose we have to comply to. If you can argue GUIDs you should try convince Richard or UEFI Forum. We can't find industry standards even if we don't like those.

We can of course try to change industry standards but that means inventing superior implementation and make it de factor standard which will lead to elimination of GUIDs from UEFI and fwupd. It is not feasible.

Temporarily we have to maintain correct and strict parsing in DTS scripts, but ultimate target is fwupd ideally with attestation and TLS client authentication to our servers.

**Comment by miczyg1** [comment]
> Temporarily we have to maintain correct and strict parsing in DTS scripts, but ultimate target is fwupd ideally with attestation and TLS client authentication to our servers.

Until that really happens and Dasharo releases are deployed through fwupd, we should use raw SMBIOS data, not GUIDs. Whe new have fwupd support, all that GUID logic will be abstracted from DTS, because fwupd will handle that for us anyways.

**Comment by TomaszAIR** [comment]
Fixed in v1.1.1 DTS release https://docs.dasharo.com/dasharo-tools-suite/releases/#v111-2023-02-20, where we added additional check on MSI boards and used output of `dmidecode -s baseboard-product-name` to determine which firmware should be used. For DDR4 we are using https://docs.dasharo.com/variants/msi_z690/releases/#v100-2022-05-27 and for DDR5 https://docs.dasharo.com/variants/msi_z690/releases/#v110-2022-11-22

In the near future we plan to provide test results with every DTS release.

**Comment by pietrushnic** [comment]
@miczyg1 I'm not sure who should verify that. @artur-rs @BeataZdunczyk did DTS v1.1.1 was covered by validation? If yes, then questions is if it was verified this bug no longer exist.

**Comment by pietrushnic** [comment]
Same comment for #316

**Comment by pietrushnic** [comment]
@TomaszAIR in future I guess linking commit which fix this and #316 would be appreciated.

**Comment by Pokisiekk** [comment]
@pietrushnic DTS v1.1.1 detects MSI platform variant as described in https://github.com/Dasharo/dasharo-issues/issues/317#issuecomment-1438151885. I confirm that this mechanism works correctly.

**Comment by miczyg1** [comment]
if TAT has tested the procedure, there is no need for me to repeat it. Besides I have accidentally stumbled upon the midst of the validation process of this feature in the lab. So we can safely close the ticket.

**Comment by miczyg1** [comment]
if TAT has tested the procedure, there is no need for me to repeat it. Besides I have accidentally stumbled upon the midst of the validation process of this feature in the lab. So we can safely close the ticket.
