### ISSUE TITLE
pfSense boot time

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#318]
**Dasharo version**
v1.0.1

**Dasharo variant**
Protectli VP2420

**Affected component(s) or functionality**
pfSense boot time

**Brief summary**
the boot time is extended by 4/5 minutes.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot pfSense.

**Expected behavior**
pfSense boots at its standard time

**Actual behavior**
pfSense boots at its standard time + 4/5 minutes

**Screenshots**
```
Writing configuration...ahcich0: Timeout on slot 12 port 0
ahcich0: is 00000000 cs 00000000 ss 00001000 rs 00001000 tfd 50 serr 00000000 cmd 0000c617
(ada0:ahcich0:0:0:0): SEND_FPDMA_QUEUED DATA SET MANAGEMENT. ACB: 64 01 00 00 00 40 00 00 00 00 00 00
(ada0:ahcich0:0:0:0): CAM status: Command timeout
(ada0:ahcich0:0:0:0): Retrying command, 3 more tries remain
ugen0.2: <Logitech USB Optical Mouse> at usbus0 (disconnected)
ums0: at uhub0, port 3, addr 1 (disconnected)
ums0: detached
ugen0.2: <Logitech USB Optical Mouse> at usbus0
ums0 on uhub0
ums0: <Logitech USB Optical Mouse, class 0/0, rev 2.00/72.00, addr 4> on usbus0
ums0: 3 buttons and [XYZ] coordinates ID=0
ahcich0: Timeout on slot 13 port 0
ahcich0: is 00000000 cs 00000000 ss 00002000 rs 00002000 tfd 40 serr 00000000 cmd 0000cd17
(ada0:ahcich0:0:0:0): SEND_FPDMA_QUEUED DATA SET MANAGEMENT. ACB: 64 01 00 00 00 40 00 00 00 00 00 00
(ada0:ahcich0:0:0:0): CAM status: Command timeout
(ada0:ahcich0:0:0:0): Retrying command, 2 more tries remain
ahcich0: Timeout on slot 20 port 0
ahcich0: is 00000000 cs 00000000 ss 00100000 rs 00100000 tfd 40 serr 00000000 cmd 0000d417
(ada0:ahcich0:0:0:0): SEND_FPDMA_QUEUED DATA SET MANAGEMENT. ACB: 64 01 00 00 00 40 00 00 00 00 00 00
(ada0:ahcich0:0:0:0): CAM status: Command timeout
(ada0:ahcich0:0:0:0): Retrying command, 1 more tries remain
ugen0.2: <Logitech USB Optical Mouse> at usbus0 (disconnected)
ums0: at uhub0, port 3, addr 4 (disconnected)
ums0: detached
ugen0.2: <Logitech USB Optical Mouse> at usbus0
ums0 on uhub0
ums0: <Logitech USB Optical Mouse, class 0/0, rev 2.00/72.00, addr 5> on usbus0
ums0: 3 buttons and [XYZ] coordinates ID=0
ahcich0: Timeout on slot 27 port 0
ahcich0: is 00000000 cs 00000000 ss 08000000 rs 08000000 tfd 40 serr 00000000 cmd 0000db17
(ada0:ahcich0:0:0:0): SEND_FPDMA_QUEUED DATA SET MANAGEMENT. ACB: 64 01 00 00 00 40 00 00 00 00 00 00
(ada0:ahcich0:0:0:0): CAM status: Command timeout
(ada0:ahcich0:0:0:0): Retrying command, 0 more tries remain
```

**Additional context**
pfSense version = 2.6.0
kernel version = 12.3-STABLE
disk = SSDPR-CL100-240-g2

**Solutions you've tried**
Workaround:
1. Power on the DUT.
2. Boot pfSense.
3. Drop to Shell.
4. Run the following command: `echo "vfs.zfs.trim.enabled=0" >> /boot/loader.conf.local`
5. Reboot the DUT.

**Comment by macpijan** [comment]
Please provide the exact version of pfSense. It is important to relate it with FreeBSD release - and hence, the kernel version.

Relevant threads on this subject:
- https://www.xf.is/2021/02/20/send_fpdma_queued-cam-status-command-timeout-on-pfsense-zfs-install/
- https://forums.freebsd.org/threads/updating-bsd-from-10-to-11-ahci-ssd-issue.59923/

**Comment by macpijan** [comment]
Please also provide the disk model, as the problem seems to be related to the specific disks, that might require some workarounds.

**Comment by macpijan** [comment]
It was also **not** present on another disk? Can you also provide the model, which worked fine without workaround?

**Comment by Pokisiekk** [comment]
@macpijan After installing pfSense on the `Samsung 860 EVO M.2 NZ-N6E250 250GB SSD`, the problem doesn't occur

**Comment by macpijan** [comment]
This is more related to the BSD, not Dasharo firmware. We can reopen if we have another instance of this problem.
