### ISSUE TITLE
Add documentation to support Secure Boot path while deploying Dasharo on Dell OptiPlex

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#33]
**Dasharo version (if applicable)**
Dasharo Dell OptiPlex 7010/9010 v0.1

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

Just deployment documentation.

**Brief summary**

as in title

**Additional context**

**Comment by pietrushnic** [comment]
I made some progress here by testing UEFI Secure Boot on v0.1.0, this commit had working UEFI, but enablind/disabling Secure Boot was not stable it required couple tried to make it work: https://github.com/Dasharo/edk2/commit/17b0d5b1b2c80d865ff03dd8438ebf34d940114c

Some discussion was made during OptiPlex Tuesday on Matrix channel [here](https://matrix.to/#/!rsKWMJGPMsyPTTjXuh:matrix.org/$oUsUKLLEu_S6dnrIoiWwQeysRGuoPhK_R0_mdaGsqz8?via=matrix.org&via=invisiblethingslab.com&via=pikaviestin.fi)

**Comment by pietrushnic** [comment]
@BeataZdunczyk @macpijan, do we have plans to include this in an upcoming release?

**Comment by BeataZdunczyk** [comment]
@pietrushnic We have already tested Secure Boot. The results are available [here]( https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit?gid=1598054578#gid=1598054578).
The release is pending publication, but based on the test results, I am closing this issue.
