### ISSUE TITLE
Keyboard backlight turns on after resuming from sleep mode

### ISSUE THREAD

**Issue by MasterBootRecord-KML** [Dasharo/dasharo-issues#332]
**Dasharo version**
v1.3.0

**Dasharo variant**
NovaCustom NV40MZ (Tiger Lake variant) running GNOME and Arch Linux.

**Affected component(s) or functionality**
Computer's backlight keyboard

**Brief summary**
The keyboard's backlight lights up after resuming the computer from sleep while it was off before the operation. I noted it occurs also when you start the computer after it was shut down.

**How reproducible**
Occurs everytime the computer is resumed from sleep mode or when you start it after it was shut down.

**How to reproduce**
When in sleep mode :
1. The keyboard's backlight is off ;
2. Close the lid of the laptop ;
3. Open the lid of the laptop ;
4. The keyboard's backlight is on.

When shut down :
1. Shut down the computer ;
2. Start it up normally ;
3. The keyboard's backlight is on.

**Expected behavior**
The keyboard's backlight should lights up only if it was already on before putting the computer into sleep mode.

**Actual behavior**
The keyboard's backlight turns on when resuming the computer from sleep when it was off before the operation.

**Screenshots**
On the first picture : the keyboard state before putting the computer into sleep mode.
On the second picture : the keyboard state after resuming the computer from sleep mode.
![BeforeSleep](https://user-images.githubusercontent.com/117741516/218817867-428bf149-0560-4950-980f-95d539c7c991.jpg)
![AfterResume](https://user-images.githubusercontent.com/117741516/218817935-fcafa49a-3813-4110-b27e-aa8f13937125.jpg)

**Additional context**
Seems to be no related error when looking at journalctl after the computer has resumed from sleep mode.

**Solutions you've tried**
After the issue has occured, manually turn off the backlight, putting the computer back in sleep mode, waiting ten seconds and resume the computer : the backlight is back on.

Note : the backlight always turns on to "step 3" power in GNOME when resuming from sleep mode when it was off before the operation.

**Comment by miczyg1** [comment]
It is probably due to system76_acpi driver? @mkopec can you confirm?

**Comment by macpijan** [comment]
@mkopec This is supposed to be fixed by the v1.4.0?

**Comment by mkopec** [comment]
Unfortunately it isn't. Could be that the OS driver conflicts with the ACPI backlight restore functionality we've added recently

**Comment by XutaxKamay** [comment]
just a little bump to say that i couldn't reproduce the issue on nv41me (TGL), using gentoo with plasma, i'm not really sure why it's occuring for you

since the patterns seems to point on gnome, im thinking maybe to try a new DE?

**Comment by MasterBootRecord-KML** [comment]
@XutaxKamay aren't the NV41x series running newer 12th gen Intel CPUs (Alder Lake) ? Mine as well as others NV40x laptops are running Intel's 11th gen CPUs (Tiger Lake).
However, it's been a little while since I have seen this issue occuring on my laptop. I don't know if the v1.4.0 has fixed the issue on my precise model (NV40MZ) or if it was related to the DE or some software mechanism on Linux that has since been fixed (according to @macpijan, the issue couldn't be reproduced on Windows 11).

**Comment by XutaxKamay** [comment]
> @XutaxKamay aren't the NV41x series running newer 12th gen Intel CPUs (Alder Lake) ? Mine as well as others NV40x laptops are running Intel's 11th gen CPUs (Tiger Lake). However, it's been a little while since I have seen this issue occuring on my laptop. I don't know if the v1.4.0 has fixed the issue on my precise model (NV40MZ) or if it was related to the DE or some software mechanism on Linux that has since been fixed (according to @macpijan, the issue couldn't be reproduced on Windows 11).

Not really, I think TGL laptops are actually nv4*m* and ADL are like nv4*p* (the motherboard is actually based on a nv40, i don't know why it is nv41 probably some revision if i remember correctly)

so this can be closed i guess? (this is great cause i think then all issues related to this model are for now resolved when i watched all dasharo issues)

**Comment by MasterBootRecord-KML** [comment]
> so this can be closed i guess?
Yes, as the issue seems to have been addressed for every TGL models with the latest release (v1.4.0), I will close this issue as fixed.

> this is great cause i think then all issues related to this model are for now resolved when i watched all dasharo issues
There are still a few issues here and there that haven't been fixed (maybe for the future release of Dasharo for the NV4x TGL) : I opened an issue last month on ticket #453 but there don't seem to be anyone but me that have been affected by this issue...

**Comment by XutaxKamay** [comment]
> > so this can be closed i guess?
> 
> Yes, as the issue seems to have been addressed for every TGL models with the latest release (v1.4.0), I will close this issue as fixed.
> 
> > this is great cause i think then all issues related to this model are for now resolved when i watched all dasharo issues
> 
> There are still a few issues here and there that haven't been fixed (maybe for the future release of Dasharo for the NV4x TGL) : I opened an issue last month on ticket #453 but there don't seem to be anyone but me that have been affected by this issue...

I'll try to give a look soon
