### ISSUE TITLE
DTS image delivery with up-to-date tools versions (flashrom, ectool etc)

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#333]
**The problem you're addressing (if any)**

The development of tools that are used by DTS (e.g. flashrom, ectool) sometimes takes place outside the work performed when releasing the next version of the DTS image. It would be nice to have a way that automatically bumps the revisions of the utilities used with each release so we do not miss anything

**Describe the solution you'd like**

A script that automatically checks and upgrades the versions of tools that are used by DTS so that each subsequent DTS release has up-to-date revisions of this.

**Where is the value to a user, and who might that user be?**

Anyone using DTS will be able to use latest versions of such utilities.

**Describe alternatives you've considered**

**Additional context**

**Comment by artur-rs** [comment]
This is already addressed by: https://github.com/Dasharo/meta-dts/blob/main/scripts/update_components.sh
