### ISSUE TITLE
Non-functional ports on the docking station

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#336]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS70MU, NS51MU

**Affected component(s) or functionality**
docking station

**Brief summary**
Devices connected to USB 3.0 ports on the docking station are not recognized. Connecting the RJ45 cable to the Gigabit Ethernet port on the docking station does not result in obtaining an Internet connection.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into system Windows 11.
3. Plug in the docking station into Thunderbolt USB-c port.
4. Connect any device to USB 3.0 port and the RJ45 cable to the Gigabit Ethernet port on the docking station.

**Expected behavior**
USB devices are recognized and accessible, after a while the Internet connection is established

**Actual behavior**
USB devices are not recognized and accessible, the Internet connection isn't established

**Screenshots**

**Additional context**
Docking station: wavlink USB-C 4K@60Hz Triple Display Docking Station,  model: WL-UMD05

**Solutions you've tried**

**Comment by mkopec** [comment]
This was caused by using an incorrect power supply. With the correct 20V / 130W PSU, this issue does not occur. Tested on both NV4x / Ubuntu 22.04 and NS5x / Win11.
