### ISSUE TITLE
Make DTS documentation more user friendly

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#337]
The documentation for DTS provides lots of stuff like

* flashing
* building
* features description
* etc

Some of them are definitely not user friendly as using it needs some technical knowledge.

What we would like to achieve is to create docs by following principals similar to ones, described in Diataxis[1].

We could logically divide docs that are for users, developers, technicians etc.

[1] https://diataxis.fr/

**Comment by sulewskiprzemyslaw** [comment]
Issue mentioned in the latest DTS PR: https://github.com/Dasharo/docs/pull/369#discussion_r1111618509

**Comment by TomaszAIR** [comment]
As part of this task, we should carefully review the documentation and make sure that the usability part (downloading DTS, using it, deploying Dasharo, etc.) is described in a clear way, understandable to anyone who wants to try Dasharo. For example, commands like `grep`, `wget`, `cd` should be described in detail, in case they are read by someone who has never dealt with Linux or the terminal.

**Comment by macpijan** [comment]
As long as we require users to use commands such as `grep` or `wget` to update their firmware, it will never be user-friendly.

Teaching the Linux shell commands in documentation is not a good path forward.

**Comment by artur-rs** [comment]
Scheduled related issue: https://github.com/Dasharo/dasharo-issues/issues/352
This one will be closed as duplicate/based on the comment https://github.com/Dasharo/dasharo-issues/issues/337#issuecomment-1446048270
