### ISSUE TITLE
Add tests for DTS operating system

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#338]
The DTS documentation provides tests results made on couple platforms[1]. For those we use DTS to flash Dasharo firmware.

What we are missing are tests for the DTS itself. We could later post them with every new DTS release and place the results in the newsletter. The scope of these tests needs to be determine.

[1] https://docs.dasharo.com/dasharo-tools-suite/documentation/#supported-hardware

**Comment by TomaszAIR** [comment]
@sulewskiprzemyslaw maybe you could help with test suite? What and how we could test on DTS with every release.

**Comment by sulewskiprzemyslaw** [comment]
@TomaszAIR first 9 test cases for DTS might be found under this link: https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/326-dasharo-tools-suite/

Of course, we should review that list and, based on the changes in DTS, propose new test cases.

**Comment by TomaszAIR** [comment]
@sulewskiprzemyslaw how much effort do we need to test DTS Dasharo deploy on supported platforms?

**Comment by pietrushnic** [comment]
To boot DTS in QEMU:

* Create persistent storage for UEFI variables:
  ```shell
  cp /usr/share/OVMF/OVMF_VARS.fd /tmp/OVMF_VARS.fd
  ```
* Run QEMU
  ```shell
  qemu-system-x86_64 \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd \
  -drive if=pflash,format=raw,file=/tmp/OVMF_VARS.fd \
  -net nic,model=e1000 -net user \
  -nographic -m 1024
  ```
* Type `exit` in shell and go to `Boot Manager > UEFI PXEv4`
* Hit `Ctrl+B` while entering iPXE shell
* Get IP address using DHCP
   ```shell
   dhcp
   ```
* Chainload DTS
   ```shell
   chain http://boot.3mdeb.com/dts.ipxe
   ```

**Comment by macpijan** [comment]
> To boot DTS in QEMU:

(when developing DTS)

```
kas-container shell meta-dts/kas.yml
runqemu slirp nographic
```

**Comment by pietrushnic** [comment]
@macpijan I don't think having RF and Cukinia in parallel is a good idea. I had a discussion about that with @TomaszAIR and @artur-rs. 

For some reason, RF is used for OpenBMC. The community impact of RF is way way beyond Cukinia. Cukinia is simple and small, but do we really want to manage two sets of tests and frameworks in 3mdeb and Dasharo?

**Comment by macpijan** [comment]
> I don't think having RF and Cukinia in parallel is a good idea.

And here we are using nothing ¯\_(ツ)_/¯

I see cukinia more as a tool almost on a level of pre-commit check. It is **very quick** for a developer of distro, to just `build -> runqemu -> cukinia` and have some **very basic** guarantee that my image still contains what it was supposed to contain according to the requirements. Those tools are built in Yocto (no external setup required), and you edit both (specification and code) in one place.

You would still have to use RF for any more tests that require actual interaction with the DTS, or running on hardware. And you can also reuse cukinia test by running them as one of the RF suites, not bothering to implementing keyword for these checks.

**Comment by pietrushnic** [comment]
@artur-rs @TomaszAIR I guess we get back to this topic a little bit as part of UEFI Secure Boot compliance. Maybe we can push this issue forward?

**Comment by artur-rs** [comment]
CI workflow with tests has been added, closing with https://github.com/Dasharo/meta-dts/pull/193
