### ISSUE TITLE
Permanent keyboard illumination

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#339]
**The problem you're addressing (if any)**

Currently, the keyboard illumination shuts off when booting.

**Describe the solution you'd like**

We would like the keyboard illumination setting to be permanently saved every time the user changes it.
This means that the keyboard illumination setting must be the same after suspend, after a reboot and after a full shutdown.
This applies to all our machines.

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by macpijan** [comment]
Implemented in the v1.4.0 release for TGL devices.

**Comment by wessel-novacustom** [comment]
Will this be implemented in v1.5.x for ADL (NS5x/NS7x), too? And for other NovaCustom devices?

**Comment by macpijan** [comment]
> Will this be implemented in v1.5.x for ADL (NS5x/NS7x), too? And for other NovaCustom devices?

Yes - for all of them

**Comment by mkopec** [comment]
@sulewskiprzemyslaw @Pokisiekk This was implemented in v1.6.0, so this can be closed now, right?
