### ISSUE TITLE
No possibility to view and change Secure Boot status

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#340]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS70MU, NS51MU

**Affected component(s) or functionality**
SecureBoot

**Brief summary**
The status of secure boot is not visible in the BIOS Menu, the `Attempt secure boot` option cannot be enabled

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. While the DUT is booting, hold the `BIOS_SETUP_KEY`(F2) to enter the UEFI Setup Menu
3. In Setup menu select `Device Manager` -> `Secure Boot Configuration`.

**Expected behavior**
The `Current Secure Boot State` field should inform about current state of Secure Boot.
The `Attempt secure boot` option should be available, after using `Reset Secure Boot keys`. - [documentation](https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration)

**Actual behavior**
The `Current Secure Boot State`  field does not inform about the status of Secure Boot.
The `Attempt secure boot` option is not available, after using `Reset Secure Boot keys`.

**Screenshots**
![Screenshot from 2023-02-20 08-24-40](https://user-images.githubusercontent.com/101700648/220042301-e01acd66-6eb7-4828-a9c4-12b56ea34bb3.png)

**Additional context**

**Solutions you've tried**

**Comment by mkopec** [comment]
Fixed in https://github.com/Dasharo/edk2/pull/49
