### ISSUE TITLE
Missing information about cache

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#343]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS70MU, NS51MU

**Affected component(s) or functionality**
cache info

**Brief summary**
Several values ​​are missing in the output from the `getconf -a | grep CACHE` command

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Ubuntu 22.04.
3. Open the terminal and run the following command: `getconf -a | grep CACHE`

**Expected behavior**
The output of the command should contain information about all cache levels, their size and association.
Example output:
```
LEVEL1_ICACHE_SIZE                 32768
LEVEL1_ICACHE_ASSOC                32
LEVEL1_ICACHE_LINESIZE             128
LEVEL1_DCACHE_SIZE                 32768
LEVEL1_DCACHE_ASSOC                32
LEVEL1_DCACHE_LINESIZE             128
LEVEL2_CACHE_SIZE                  524288
LEVEL2_CACHE_ASSOC                 2048
LEVEL2_CACHE_LINESIZE              32
LEVEL3_CACHE_SIZE                  10485760
LEVEL3_CACHE_ASSOC                 40960
LEVEL3_CACHE_LINESIZE              32
LEVEL4_CACHE_SIZE                  0
LEVEL4_CACHE_ASSOC                 0
LEVEL4_CACHE_LINESIZE              0
```

**Actual behavior**
Missing information: `LEVEL1_ICACHE_ASSOC`, `LEVEL4_CACHE_ASSOC`, `LEVEL4_CACHE_LINESIZE`
```
LEVEL1_ICACHE_SIZE                 32768
LEVEL1_ICACHE_ASSOC                
LEVEL1_ICACHE_LINESIZE             64
LEVEL1_DCACHE_SIZE                 49152
LEVEL1_DCACHE_ASSOC                12
LEVEL1_DCACHE_LINESIZE             64
LEVEL2_CACHE_SIZE                  1310720
LEVEL2_CACHE_ASSOC                 20
LEVEL2_CACHE_LINESIZE              64
LEVEL3_CACHE_SIZE                  8388608
LEVEL3_CACHE_ASSOC                 8
LEVEL3_CACHE_LINESIZE              64
LEVEL4_CACHE_SIZE                  0
LEVEL4_CACHE_ASSOC                 
LEVEL4_CACHE_LINESIZE 
```        

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment]
@mkopec Is this an issue?

**Comment by mkopec** [comment]
I would guess this is a result of different OS versions being used between tests.

**Comment by macpijan** [comment]
@Pokisiekk Please link to the test procedures and explain what was expected here. This does not look like a firmware bug.

**Comment by Pokisiekk** [comment]
@macpijan https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31T-cpu-status/#cpu002001-cpu-cache-enabled-ubuntu-2204 - The output of the `getconf -a | grep CACHE` command should contain information about all cache levels, their size and association. Three values ​​were missing so I thought this should be reported.

**Comment by pietrushnic** [comment]
@macpijan @BeataZdunczyk, here we have another issue with the same problem I described [here](https://github.com/Dasharo/dasharo-issues/issues/356#issuecomment-1798259088)

**Comment by pietrushnic** [comment]
8 months no response

**Comment by macpijan** [comment]
It does not belong to heads milestone at all.
Also, it is not a functional issue at all, rather not the best test design on our side.
