### ISSUE TITLE
The keyboard illumination does not turn off during suspend

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#344]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS51MU, NS70MU

**Affected component(s) or functionality**
The keyboard illumination

**Brief summary**
The keyboard illumination does not turn off during suspend.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Windows 11.
3. Press `Fn` + `F12` or power button to suspend the DUT.

**Expected behavior**
The keyboard illumination should turn off during suspend.

**Actual behavior**
The keyboard backlight stays on during suspend.

**Screenshots**

**Additional context**
It works properly on Ubuntu 22.04.

**Solutions you've tried**

**Comment by mkopec** [comment]
Can be fixed in EC FW by checking if the lid is open, instead of relying on ACPI / OS to do the right thing here.

**Comment by mkopec** [comment]
Fixes went in https://github.com/Dasharo/ec/pull/26 and https://github.com/Dasharo/coreboot/pull/300, let's keep this open until confirmation

**Comment by Pokisiekk** [comment]
I confirm that after applying the above fixes, the problem no longer occurs
