### ISSUE TITLE
EC flashing errors report

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#345]
**Error 1**
```
Buffer size: 128
ID: FF7F VER: 127
thread 'main' panicked at 'Unknown ID: FF7F', examples/isp.rs:822:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
```
**Solution**
Correcting the connections, press the keyboard connector on the laptop with your finger

**Comment by wessel-novacustom** [comment]
@Pokisiekk I believe this is not a firmware bug and the solution has been provided. It can be related to issue #183, which is actually solved, too. Could you please close the issue?
