### ISSUE TITLE
The docking station turns off when connected

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#348]
**Dasharo version**
v1.4.0

**Dasharo variant**
NV41MZ

**Affected component(s) or functionality**
Docking station, port Thunderbolt USB-c

**Brief summary**
Connecting the docking station to the Thunderbolt USB-c port turns off it

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Windows 11/Ubuntu 22.04.
3. Connect the docking station to Thunderbolt USB-c port using USB-c - USB-c cable.

**Expected behavior**
The docking station starts charging the DUT and the devices connected to it are available in the system.

**Actual behavior**
The docking station shuts down and does not offer any functionality

**Screenshots**

**Additional context**
Docking station: wavlink USB-C 4K@60Hz Triple Display Docking Station, model: WL-UMD05

**Solutions you've tried**

**Comment by mkopec** [comment]
Wrong power supply was used.

**Comment by macpijan** [comment]
@mkopec Please elaborate more on what the correct PS should be, for the sake of completness.

**Comment by mkopec** [comment]
20V / 130W, the one with the `NovaCustom Docking Station` sticker on it
