### ISSUE TITLE
Keyboard backlight not working after restart

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#349]
**Dasharo version**
v1.4.0

**Dasharo variant**
NV41MZ, NV41MB

**Affected component(s) or functionality**
Keyboard backlight

**Brief summary**
Keyboard backlight not working after restart, the hotkey to control backlight also does not work

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Windows 11.
3. Turn on keyword backlight using `Fn` + `F4`.
4. Restart the system.
5.  Boot into Windows 11.

**Expected behavior**
The keyboard backlight is turned on with the intensity set before the system restart, with `Fn` + `F4` it is possible to change the intensity of the keyboard backlight.

**Actual behavior**
The keyboard backlight is turned off and cannot be turned on using `Fn` + `F4`

**Screenshots**

**Additional context**
Windows 11 22H2

**Solutions you've tried**
Turning off the computer completely and turning it back on restores the function of the `Fn` + `F4` hotkey.

**Comment by macpijan** [comment]
On my `NV40MB 1`:

1. Power on
2. Boot into Windows 11
3. Set keyboard backlight to 3/5
4. Shut down via Windows GUI
5. Boot into Windows 11

At this point there is no keyboard backlight at all. I also cannot change it via a hotkey.

**Comment by mkopec** [comment]
https://github.com/Dasharo/coreboot/pull/302 fixes this, tested on NS5x and NV4x.

**Comment by macpijan** [comment]
Just confirmed on `NV40MB 1`. Keyboard illumination is preserved on Windows 11 in all cases:
- suspend
- reboot
- poweroff

**Comment by Pokisiekk** [comment]
I'm re-opening the issue due to the identical problem noted on the NV41PZ, except that the `Fn` + `F4` key combination works fine all the time, it's just that the keyboard backlight settings are not restored after a restart.

**Comment by Pokisiekk** [comment]
I reproduced the issue on the NS50PU with Dasharo firmware v1.6.0, but not in 100%.
Keyboard backlight works after:
* reboot 3/8 (three times it worked on eight checks)
* poweroff 4/5
* coldboot 5/5
* suspend 5/5

I was always able to control the keyboard backlight.

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk Fix for this bug for NV4x ADL has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)

**Comment by mkopec** [comment]
I guess this issue can be closed then.
