### ISSUE TITLE
Function key display on/off does not completely blank the screen

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#354]
**Dasharo version**

v1.5.0

**Dasharo variant**

NovaCustom NV4x PZ

**Affected component(s) or functionality**

Functional keys

**Brief summary**

Clicking on the function key `Display on/off` (F2) does not wholly blank the screen.

**How reproducible**

100%

**How to reproduce**

1. Boot into the system.
2. Click on the F2 key to blank the screen.
3. Observe the screen. 

**Expected behavior**

The screen should blank completely. 

**Actual behavior**

The screen does not blank completely.

**Screenshots**

The laptop screen after clicking on F2:

![20230227_113138](https://user-images.githubusercontent.com/90184097/221556427-3dfcb967-3067-4fc8-979e-130666d76c3d.jpg)

**Additional context**

**Solutions you've tried**

**Comment by Pokisiekk** [comment]
I reproduced the issue on Windows 11, 22H2

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk fix for this bug has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)
