### ISSUE TITLE
Connecting the RJ45 cable to the Gigabit Ethernet port on the docking station does not result in obtaining an Internet connection

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#356]
**Dasharo version**
v1.4.0

**Dasharo variant**
NS51MU, NS70MU

**Affected component(s) or functionality**
Gigabit Ethernet port on the docking station

**Brief summary**
Connecting the RJ45 cable to the Gigabit Ethernet port on the docking station does not result in obtaining an Internet connection

**How reproducible**
~50%

**How to reproduce**

1. Power on the DUT.
2. Boot into Windows 11.
3. Plug in the docking station into Thunderbolt USB-c port.
4. Connect the RJ45 cable to the Gigabit Ethernet port on the docking station.

**Expected behavior**
After a while the Internet connection is established

**Actual behavior**
The Internet connection isn't established

**Screenshots**

**Additional context**
Windows 11 21h2
Docking station: wavlink USB-C 4K@60Hz Triple Display Docking Station, model: WL-UMD05

**Solutions you've tried**

**Comment by macpijan** [comment]
Could you please always provide a model of the station?
We've had reports related to stations in the past, but I'm pretty sure we have another model already: https://github.com/Dasharo/dasharo-issues/issues/264

**Comment by mkopec** [comment]
@macpijan That issue was for the integrated GbE controller.

@Pokisiekk I saw this issue when the wrong spec power supply was used, but I'm assuming you're using the 20V / 130W power supply that came with the station?

**Comment by Pokisiekk** [comment]
I reproduced the issue on NV41PZ with v1.5.0 Dasharo firmware on Windows 11, 22H2

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk fix for this bug for NV4x ADL has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)

**Comment by pietrushnic** [comment]
@macpijan @BeataZdunczyk this issue was reported in v1.4.0 for NS5x 11th Gen and is linked in our test results spreadsheet.

**Comment by wessel-novacustom** [comment]
@pietrushnic Docks have been extensively tested by us and confirmed to be no longer an issue starting from v1.5.2 (TGL) and v1.7.2 (ADL). I believe the issue should be closed, @Pokisiekk.
