### ISSUE TITLE
Store EC firmware in main SPI Flash

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#359]
**The problem you're addressing (if any)**

The EC firmware is currently stored in a separate SPI flash that is not easily accessible from x86 and makes flashing complicated. It is also not possible to include this firmware in TPM measurements.

**Describe the solution you'd like**

The IT5570 EC supports eSPI Flash Sharing. In this scenario the EC firmware is located in main SPI flash that stores the x86 boot firmware and ME. The chipset allows the EC to access the firmware via eSPI Flash Access Channel.

**Where is the value to a user, and who might that user be?**

- Simpler update procedure - only one flashing is needed for both EC and BIOS
- Only one binary is required
- Unbricking is easier using the same flashing method as the BIOS
- EC FW can be measured to the TPM and the measurements can be used to seal secrets
- Remove the need for complicated EC transition procedure

**Describe alternatives you've considered**

n/a

**Additional context**

- IT5570 datasheet
- eSPI MAFS specification
- StarLabs Merlin EC code in coreboot

**Comment by macpijan** [comment]
Code from our experiments so far:
- https://github.com/Dasharo/ec/commits/espi_mafs
- https://github.com/Dasharo/coreboot/pull/369
- https://github.com/Dasharo/novacustom-blobs/pull/4

**Comment by wessel-novacustom** [comment]
I believe we have discussed that we won't store the EC firmware in the main SPI flash as it is not feasible. However, for Capsule Updates (#423), we will need to update the EC from firmware. Since that is part of the other ticket, I would suggest to close the issue.

**Comment by miczyg1** [comment]
As an alternative we have put the EC FW into coreboot's CBFS and coreboot will handle updating the EC firmware, in case it has a different version than expected:

https://github.com/Dasharo/coreboot/pull/481

**Comment by miczyg1** [comment]
Capsule updates would handle it as well, but the timeline for Capsuel Update is not yet clear.

**Comment by miczyg1** [comment]
Closing this issue, because MAFS is not feasible, indeed.
