### ISSUE TITLE
Unable to wake up from suspend

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#362]
**Dasharo version**
v1.5.0

**Dasharo variant**
NV41PZ

**Affected component(s) or functionality**
Suspend, Windows 11

**Brief summary**
After entering the suspend state, there is no way to wake up the computer, a manual restart is required

**How reproducible**
Described in `Actual behavior` section

**How to reproduce**

1. Power on the DUT.
2. Boot into Windows 11.
3. Close the lid or press `Fn` + `F12` or press power button.
4. Try to wake up the DUT in any way.

**Expected behavior**
The DUT wakes up.

**Actual behavior**
First test on Windows 11, 21H2 - the system was installed before flashing to v1.5.0
With each iteration of suspend it was not possible to wake up the device, always required a manual restart

A second test on Windows 11, 22H2 - the system was installed after flashing to v1.5.0
After installing all the updates, no problems occur.
After a few tests other things and maybe 5 reboots, the problem came back and when it comes back it occurs in every iteration of trying to get out of suspend.

When I click the button on the keyboard, i.e. the standard way to exit the suspend: the power LED stops blinking and lights permanently green, the keyboard backlight is turned on, the screen changes shades of black from time to time, and sometimes even the mouse cursor appears, but it cannot be moved

**Screenshots**

**Additional context**
After one of the reboots, the operating system entries in the BIOS MENU disappear, I don't know if it can be related

**Solutions you've tried**

**Comment by macpijan** [comment]
I confirmed this as well on NV4xPU with 1.5.0.

I could run a cycle of ~5 suspend/resume cycles with pwrtest.exe until machine rebooted.
Until then, even a single S3 operation causes the device to appear as `unable to wake up from screen`. In reality, it reboots after a few minutes in my case.

**Comment by mkopec** [comment]
Fixed by:
- https://github.com/Dasharo/coreboot/pull/310
- https://github.com/Dasharo/ec/pull/27

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk fix for this bug has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)
