### ISSUE TITLE
Nvidia RTX 3060 does not spawn HDA device in Device Manager

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#364]
**Dasharo version**
Any

**Dasharo variant**
MSI PRO Z690-A

**Affected component(s) or functionality**
GPU HD Audio

**Brief summary**
When Dasahro firmware is installed, Windows 11 does not spawn Nvidia HDAudio device when RTX 3060 is plugged. As a result a monitor with speakers is not working with Dasharo under Windows 11.

**How reproducible**
Always

**How to reproduce**

1. Boot Windows 11 with Dasahro on MSI PRO Z690-A and RTX 3060 plugged to x16 port 
2. Install Nvidia drivers (GeForce Experience and the graphics driver)
3. Open Device Manager and expand `Sound, video and game controllers`. Check if `Nvidia High Definition Audio` is on the expanded list.

**Expected behavior**
`Nvidia High Definition Audio` is on the list and one can configure audio output to the monitor.

**Actual behavior**
`Nvidia High Definition Audio` is missing in Device Manager and thus it is impossible to set the output to the monitor.

**Screenshots**
None

**Additional context**
MSI v1.70 tested and works, spawns Nvidia HD Audio device and output works on monitor. 

Dasharo v1.1.1 and Nvidia HD Audio works under Ubuntu 22.04. 

**Solutions you've tried**
Windows had a lot of PCI AER errors in the event log with Dasharo. Tried disabling AER on the respective root ports to match MSI firmware, but it did not help.

**Comment by miczyg1** [comment]
Cause: interrupts form HD Audio device are not serviced. Git blame: https://github.com/Dasharo/coreboot/commit/5e9de1d923538db1a80c551d176ade79e0cce514

**Comment by miczyg1** [comment]
Fix: https://github.com/Dasharo/coreboot/pull/306

Tested by booting Ubuntu with `pci=nomsi` that caused to use INTx for all devices. Although the NVMe disks can not work properly and force-disable INTx (have to add `irqpoll` to boot actually). Besides that Nvidia driver complained on not being able to enable MSI interrupts.

Now the Nvidia audio works under Windows.

**Comment by zirblazer** [comment]
Is there any relationship between this bug and this one? https://github.com/Dasharo/dasharo-issues/issues/411

He reported that passthorough of the PCIe Cards with the USB Controllers worked on MSI but not on Dasharo, and since he teseted with v1.1.1, this bug came to my mind.

**Comment by miczyg1** [comment]
Dunno. This issue only affects CPU PCIe ports, not PCH PCIe ports

**Comment by miczyg1** [comment]
Flashed the soon- to be released v1.1.2 and issue is not present

**Comment by BeataZdunczyk** [comment]
Closing this issue as it has been resolved in the [v1.1.2 release](https://docs.dasharo.com/variants/msi_z690/releases/#v112-2023-09-06).
