### ISSUE TITLE
Unwanted reset of BIOS settings

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#365]
**Dasharo version**
v1.5.0

**Dasharo variant**
NV41PZ

**Affected component(s) or functionality**
BIOS settings

**Brief summary**
BIOS settings reset themselves

**How reproducible**
This has happened to me about 5 times

**How to reproduce**
There are several scenarios after which the problem occurred:

1. After not being able to wake up from sleep on Windows 11, I turned off the DUT with the power button and restarted it.
2. After the `reboot` command executed in the terminal on Ubuntu 22.04.
3. After changing settings in `Dasharo System Features` in Setup Menu and using `Reset` option.

**Expected behavior**
The DUT will boot with the settings before turning it off.

**Actual behavior**
BIOS settings return to default/initial:
1. Fan profile: `Silent`
2. Intel ME mode: `Enabled`
3. The operating system entries like `ubuntu` disappear from the boot menu.

**Screenshots**

**Additional context**
I have the impression that before this settings reset, the DUT always took longer to boot

**Solutions you've tried**

**Comment by Pokisiekk** [comment]
@macpijan I started looking more closely at each boot iteration and noted two situations like this:

1. Shutdown via Windows GUI.
2. Turn on the DUT using the power button.
3. The screen changed shade of black, the power LED is permanently green - nothing else happens
4. Turn off and turn on the DUT again using the power button.
5. The platform starts but the BIOS settings return to default/initialt as described in the issue.

**Comment by Pokisiekk** [comment]
I experienced the same behavior as described in this issue on a VP4670 platform with Dasharo firmware v1.0.20-rc1. The rest of the BIOS settings was mainly after a failed boot to the system and a forced coldboot.

**Comment by macpijan** [comment]
The issue has not been replicated since the last year.
