### ISSUE TITLE
Laptop not suspending while connected to a USB-C docking station

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#368]
**Dasharo version**

v1.4.0

**Dasharo variant**

NovaCustom NV4x ADL

**Affected component(s) or functionality**

USB4 port / Power management

**Brief summary**

The laptop fails to go to sleep while connected to a USB-C docking station (Lenovo ThinkPad USB-C Dock Gen2, DP Alt mode). Additionally, fans go to 100% speed while it's trying to go to sleep.

Sleep mode doesn't work after disconnecting the dock either, need to reboot to have it work again.

**How reproducible**

100%

**How to reproduce**

1. Connect USB-C dock to left USB-C port on the device
2. Put the laptop to sleep

**Expected behavior**

Laptop goes to sleep successfully

**Actual behavior**

Laptop does not enter sleep successfully

**Screenshots**

n/a

**Additional context**

Will probably be fixed once S3 support rolls out.

**Solutions you've tried**

None

**Comment by Pokisiekk** [comment]
I reproduced the issue on NV41PZ with Dasharo firmware v1.6.0, but only on Windows 11 22H2. On Ubuntu 22.04 sleep works fine with connected docking station.

**Comment by Pokisiekk** [comment]
I reproduced the issue on NS5x/7xPU with v1.6.0 Dasharo firmware on Windows 11 22H2.

**Comment by mkopec** [comment]
Works on the unit I tested, both with and without a monitor attached to the docking station.

**Comment by mkopec** [comment]
Marking as resolved as of the v1.7.2
