### ISSUE TITLE
Booting problems with Ubuntu 22.04

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#370]
**Dasharo version**
v1.0.20-rc1

**Dasharo variant**
VP4670

**Affected component(s) or functionality**
Booting Ubuntu 22.04

**Brief summary**
Ubuntu 22.04 does not boot after using the command `sudo apt upgrade`

**How reproducible**
100% - 4/4

**How to reproduce**

1. Install Ubuntu 22.04 form USB stick.
2. Boot into system.
3. Open the terminal and run the following commands: `sudo apt update` and then `sudo apt upgrade`
4. Power off and power on the platform OR reboot.
5. Try to boot Ubuntu 22.04.

**Expected behavior**
Ubuntu should boot correctly.

**Actual behavior**
Ubuntu does not boot, the system could be selected in the GRUB menu and then nothing happens.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by Pokisiekk** [comment]
Ubuntu server 20.04.05 does not boot, not even once right after installation.

**Comment by Pokisiekk** [comment]
I noticed a case that Ubuntu 22.04 stopped booting without using the `sudo apt upgrade` command. It happened after about 30 bootups.

**Comment by miczyg1** [comment]
The problem seems to be lying in the early microcode update in Linux kernel. As a workaround one may boot with the `dis_ucode_ldr` in kernel commandline and it will work. In the next version we will bump the microcode revision In Dasahro which fixes the issue completely

**Comment by Pokisiekk** [comment]
[Here](https://docs.dasharo.com/variants/protectli_vp46xx/releases/#v110-2023-06-05) are the binaries in version v.1.1.0 for VP4670, on which the issue does not occur
