### ISSUE TITLE
Dasharo compatible with Dell OptiPlex 7010/9010 v0.1.0 - Validation

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#372]
**Dasharo version (if applicable)**
v0.1.0

**Dasharo variant (if applicable)**
Dasharo compatible with Dell OptiPlex 7010/9010

**Brief summary**

Perform v0.1.0 firmware validation

**Comment by pietrushnic** [comment]
@BeataZdunczyk @macpijan, do we have plans to include this in an upcoming release?

**Comment by BeataZdunczyk** [comment]
Of course, validation is crucial with every Dasharo release. We have finished testing, and the results are available [here](https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit?gid=1598054578#gid=1598054578). We will also link the test results in the release notes once they are published.
