### ISSUE TITLE
"GPU" fan runs too fast

### ISSUE THREAD

**Issue by MasterBootRecord32** [Dasharo/dasharo-issues#388]
**Dasharo version**
v1.4.0

**Dasharo variant**
 NovaCustom NV40MZ (Tiger Lake variant) running GNOME and Arch Linux.

**Question text**
I don't know if it is a bug or if this is deliberate : 
After upgrading my NovaCustom NV40MZ, I noted that the computer's fans were louder than before, even by using the "silent mode" in the setup. When the CPU temperature is around 30°C : while the CPU fan is reported to run at around 1300RPM, the GPU fan run at around 2100RPM even though I don't have the Nvidia GPU on my model.

Is it a bug (can I make a bug request) or is it completely normal ?
If it is normal, I will create a feature request to ask to lower the fan speed on NV40MZ models that does not have the GPU. 

**Screenshot of the problem**
Here's a screenshot of the values (temp in the headerbar == CPU temp) with Vitals :
![FanSpeed](https://user-images.githubusercontent.com/117741516/226182648-37e15372-9447-4adf-8a25-20c5bb62a7a9.png)

**Comment by macpijan** [comment]
Before we dive any deeper into that, one of the features introduced in this release was to select the fan curve profile in setup menu:
- https://docs.dasharo.com/variants/novacustom_nv4x_tgl/releases/
- https://docs.dasharo.com/unified/novacustom/fan-profiles/

So you could see if the other one works for you.

**Comment by mkopec** [comment]
@MasterBootRecord-KML I believe in one of the past releases we set the fans to always spin at the lowest speed possible, because we received complaints that the fans make noise while spinning up and stopping.

In your case where you don't have discrete graphics, the fans are both set to the same speed value. The problem is that they seem to respond differently to the same setting. I think we should tweak the fan curves so that the actual fan speeds match.

**Comment by wessel-novacustom** [comment]
Yes; I think this should be improved for the next firmware release for this device.

**Comment by wessel-novacustom** [comment]
@MasterBootRecord32 The fan policy has been updated since the last update (v1.5.2 for 11th Gen NovaCustom laptops). Could you please check this and close the issue?

**Comment by MasterBootRecord32** [comment]
As I can't read fan state from the OS anymore, I can't verify the exact fan speed. However, they are clearly less audible than on the past release by using the "silent" profile so I will close this issue as fixed.
