### ISSUE TITLE
Laptop cannot output video via the Tunderbolt 4 USB Type-C port

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#39]
*Issue moved from GitLab*

**Dasharo version**

v0.4.0

**Hardware details**

Clevo NV41MB

**Operating system**

1. Windows 10N 
2. Ubuntu 20.04 LTS

**Affected component(s) or functionality**

Thunderbolt 4 USB Type-C port and its ability to output video

**Brief summary**

The laptop can not output video to a display connected via the Thunderbolt 4 USB Type-C port. The display is not recognized, despite it being connected through the HDMI --> DVI-D cable and USB Hub to the laptop.

The same connection, using the same media was checked on a laptop model NV41MZ. In that case, it works properly. 

**How reproducible**

Always

**How to reproduce**

1. Turn on the laptop and boot into one of the above-mentioned systems.
2. Set the connection: Display -> HDMI --> DVI-D cable -> USB hub -> laptop.
3. Determine if the second display is available by using the F7 button or by changing settings in the display menu.

**Expected behavior**

The laptop can output video to a display via the Thunderbolt 4 USB Type-C port

**Actual behavior**

The laptop cannot output video to a display via the Thunderbolt 4 USB Type-C port

**Screenshots**

**Additional context**

**Solutions you've tried**

/cc @macpijan

**Comment by macpijan** [comment]
The workaround via documentation updated was applied and it was decided this is enough for us: https://gitlab.com/novacustom/dasharo-compatibility/-/issues/1#note_810992892
