### ISSUE TITLE
fatal: clone of 'https://github.com/Dasharo/blobs.git'

### ISSUE THREAD

**Issue by Pace17881** [Dasharo/dasharo-issues#395]
I tried to build current bios 1.6.0 for nova custom nv41 adl. But after pulling  https://github.com/Dasharo/coreboot.git and fetching the submodules the above error appeard. Seems that the repo is deleted or hidden.

**Comment by miczyg1** [comment]
@Pace17881 yes it is a private repo intentionally. It contains non-redistributable blobs.

It should be possible to build the binaries without access to the private repo. Moreover, the clevo/release branch, which is used to build release novacustom images does not use the Dasharo/blobs repo, but the public coreboot/blobs repo:
https://github.com/Dasharo/coreboot/blob/clevo/release/.gitmodules#L3

So I suspect something in your tree is outdated. Try this:

```bash
git submodule sync
git submodule update --init --checkout
```

**Comment by Pace17881** [comment]
Thank you. Issue solved
