### ISSUE TITLE
VP2420 memory issues and incorrectly reported memory capacity

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#397]
**Dasharo version**
v1.0.1

**Dasharo variant**
Protectli VP2420

**Affected component(s) or functionality**
Memory HCL

**Brief summary**
An issue was brought up on a [Reddit post](https://www.reddit.com/r/OPNsenseFirewall/comments/11cv4tj/psa_for_protectli_vp2420_users_possible_crucial/) that indicated a VP2420 with coreboot and 16 GB of Crucial DRAM had problems. Then a couple more people mentioned similar issues.

Initially it was thought to be an incompatibility issue between coreboot on the VP2420 and specific Crucial 16 GB DRAM. 

Upon further testing, it was discovered that sometimes when a DRAM module was initialized successfully and subsequently a module of a different size replaced the original size, the unit had memory issues.

Further testing revealed that sometimes the unit would not recognize the new DRAM and resize incorrectly. For example, when initializing with an 8G DRAM, then replacing it with a 16G module, the coreboot BIOS menu still displayed 8G and the unit had memory errors or would crash.

**How reproducible**
100%

**How to reproduce**

1. Boot the platform with one memory module.
2. Power off the platform.
3. Change the memory module to one with different capacity.
4.  Boot the platform and observe the memory capacity has not changed.

**Expected behavior**
The setup menu or OS detected the actual memory capacity.

**Actual behavior**
The OS and firmware setup menu shows the first module memory capacity.

**Screenshots**
None

**Additional context**
None

**Solutions you've tried**
None

**Comment by miczyg1** [comment]
Fixed by https://github.com/Dasharo/coreboot/pull/319

**Comment by Pokisiekk** [comment]
fix for this bug for Vp2420 has been added in firmware [v1.1.0](https://docs.dasharo.com/variants/protectli_vp2420/releases/#v110-2023-04-20)
