### ISSUE TITLE
Setup menu does not issue a reset, resulting in saved but unapplied settings

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#398]
**Dasharo version**

Any

**Dasharo variant**

Any

**Affected component(s) or functionality**

Setup menu settings

**Brief summary**

Saving settings that require a reset, doesn't force a reset after exiting the setup menu

**How reproducible**

100%

**How to reproduce**
- Enter setup menu
- Make a change to a setting, e.g. SMM BIOS write protection
- Save
- Select `Continue` to boot into OS

**Expected behavior**

Settings are applied. If a setting requires a reboot, then reboot and don't depend on the user to know when to reboot end when not to.

**Actual behavior**

Some settings are  not applied after a reboot

**Screenshots**

n/a

**Additional context**

Conventional BIOSes have two options, e.g. `Save and reset` and `Discard and exit` which are self-explanatory.
Since users are likely to already be accustomed to these, maybe they could be implemented in Dasharo too.

**Solutions you've tried**

None

**Comment by miczyg1** [comment]
https://github.com/Dasharo/DasharoModulePkg/pull/19

**Comment by miczyg1** [comment]
The fix has been merged. Also tested on latest MSI releases. Closing.
