### ISSUE TITLE
The docking station is not detected after cold-boot, warm-boot and reboot

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#404]
**Dasharo version**
v1.6.0

**Dasharo variant**
NS50PU, NS70PU

**Affected component(s) or functionality**
The docking station

**Brief summary**
On both models, the docking station is not detected in system after cold-boot. On NS5x ADL it's also not detected on warm-boot and reboot. Tested with Ubuntu 22.04 on USB-C and Thunderbolt port.

**How reproducible**
100%

**How to reproduce**

1. [Thunderbolt docking station](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/350-thunderbolt-docking-station/)
AND
2. [USB-C docking station](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/321-docking-station-usb-c/)

**Expected behavior**
The docking station is detected after cold-boot, warm-boot and reboot.

**Actual behavior**
The docking station is not detected after cold-boot and warm-boot while connected to USB-C port.
The docking station is not detected after cold-boot, warm-boot and reboot while connected to Thunderbolt port.

**Screenshots**

**Additional context**
The docking station is charging the DUT while connected to Thunderbolt port despite not being detected.
Docking station: wavlink USB-C 4K@60Hz Triple Display Docking Station, model: WL-UMD05

**Solutions you've tried**

**Comment by wessel-novacustom** [comment]
Please check for NV41-ADL as well, it might have the same problem.

**Comment by Pokisiekk** [comment]
@wessel-novacustom I checked it on NV41PZ with v1.6.0 Dasharo firmware and and the dock is detected properly on one of the USB-c ports (not Thunderbolt) after warmboot and coldboot.

**Comment by wessel-novacustom** [comment]
Ok. What about the Thunderbolt port?

**Comment by Pokisiekk** [comment]
The docking station is not detected by the `lsusb` command, but battery is being charged.

**Comment by wessel-novacustom** [comment]
Ok, so NV4-ADL label should be added as well, I think. The docking station should work on both ports on both laptops, except PowerDelivery, which is only expected to be working on one port.

**Comment by mkopec** [comment]
Displays will also not work on the non-Thunderbolt port as it does not have DisplayPort lanes routed to it. But USB peripherals, networking and audio should work.

**Comment by wessel-novacustom** [comment]
Ah okay. Well, then it should at least work on the same port as the PowerDelivery port.

**Comment by Pokisiekk** [comment]
I detailed the issue description and did some tests with USB-C Multi-function dock station:
1. This docking station is detected after cold-boot, warm-boot and reboot while connected to USB-C port. 
2. This docking station is not detected after cold-boot, warm-boot and reboot while connected to Thunderbolt port.

**Comment by mkopec** [comment]
Would be good to check if this is still present in v1.7.0 ADL / v1.5.0 TGL

**Comment by johanes2115** [comment]
@mkopec the issue still occurs after coldboot on ns70 ADL using Dasharo v1.7.0 fw.

**Comment by wessel-novacustom** [comment]
This is considered to be a priority issue.

**Comment by mkopec** [comment]
The issue appears to have been fixed in the latest firmware. There were problems regarding display connection to the docking station. Re-tested on v1.7.1 on NS5x ADL. NV4x ADL also works.

**Comment by wessel-novacustom** [comment]
That's great! :+1:

**Comment by mkopec** [comment]
To clarify a bit more:

There can sometimes be an issue with display init when multiple displays are connected to the dock using the dock's builtin DP MST hub. It can get into a weird state and need a re-plug to the laptop to work well again. The issue seems exclusive to this specific dock and only if plugged in at boot. Perhaps the OS does some sort of DP reset to get the MST hub into a good state again.

The issue never appears if:
- only one monitor is connected to the dock
- multiple monitors are connected via a separate MST hub (for example I have 2 daisy-chained DP monitors connected via a single cable to the dock)
- Other docks are used - I personally use a CableMatters triple display travel hub for work everyday with my NV4x ADL and it works perfectly every time - I've successfully done ca. 20 reboot cycles with both models and I get the firmware bootsplash / menu on both monitors

**Comment by wessel-novacustom** [comment]
Yes please check if it can be fixed with laptop firmware.

**Comment by mkopec** [comment]
Continued in https://github.com/Dasharo/dasharo-issues/issues/560
