### ISSUE TITLE
Charging indicator if power adapter was unplugged while in sleep mode

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#41]
*Issue moved from GitLab*

**Dasharo version**
NovaCustom Dasharo v0.4.0

**Hardware details**
NV41MZ

**Affected component(s) or functionality**
Sleep mode in combination with battery indicator

**Brief summary**
The battery plugged-in state / battery mode state is not being updated on wake-up.

**How reproducible**

100% reproducible (so far)

**How to reproduce**

1. Put laptop to sleep mode (for instance, FN+F12 shortcut) while having the power adapter attached.
2. Remove the power adapter as soon as the laptop is in sleep mode (blinking power LED).
3. Wake from sleep by hitting a button on the keyboard (or on/off button).

**Expected behavior**
Laptop indicates that the power adapter is not attached.

**Actual behavior**
Laptop indicates that the power adapter is attached.

**Screenshots**
-

**Additional context**
-

**Solutions you've tried**
-

/cc @macpijan

**Comment by wessel-novacustom** [comment]
This issue seems to be fixed in v1.0.1. :+1:

**Comment by mkopec** [comment]
Good to hear, I'll close this issue then.
