### ISSUE TITLE
Chipset Watchdog timeout value does not change actual watchdog trigger time

### ISSUE THREAD

**Issue by verygreen** [Dasharo/dasharo-issues#413]
**Dasharo version**

1.1.1

**Dasharo variant**

MSI Z390A DDR5

**Affected component(s) or functionality**

dasharo chipset settings

**Brief summary**

Increasing the watchdog timeout value in chipset settings has no effect on actual timeout settimg, only the display of the value.
Booting a (self built) version clearly demonstrates the problem
![wdt-timeout](https://user-images.githubusercontent.com/625925/232993294-6cf51172-7cbe-4a17-b1f5-98a5fd1b0122.jpg)
```
Found variable with state 3c and GUID: 8be4df61-93ca-11d2-aa0d00e098032b8c
Found variable with state 3c and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3f and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3f and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3f and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3f and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3f and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3f and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3c and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
Found variable with state 3f and GUID: d15b327e-ff2d-4fc1-abf6c12bd08c1359
EFIVARS: No Firmware Volume header present
EFIVARS: Failed to validate firmware header
Watchdog: reload and start timer (timeout 120s)
Watchdog: WDT enabled
```
So at bootup the efivar cannot be read even though it's definitely there based on the uuid just before.

**How reproducible**

100%

**How to reproduce**

1. Set the timeout value 
2. press F10 / Y and save
3. restart
4. 
**Expected behavior**

Expected the timeout to change as directed. Changing CONFIG_SOC_INTEL_COMMON_OC_WDT_TIMEOUT and recompiling works as expected.

**Actual behavior**

the timeout actually set for the watchdog remains at the compile time default (CONFIG_SOC_INTEL_COMMON_OC_WDT_TIMEOUT) 120

**Additional context**

This setting is important on DDR5 boards because 128G Ram takes longer to MRC-train than the 120 second timeout (on my board takes 4.5 minutes)

**Solutions you've tried**

Self-building with CONFIG_SOC_INTEL_COMMON_OC_WDT_TIMEOUT set to desired value works.

**Comment by zirblazer** [comment]
> This setting is important on DDR5 boards because 128G Ram takes longer to MRC-train than the 120 second timeout (on my board takes 4.5 minutes)

Does this means than your system goes into an infinite boot loop with it enabled? If I recall correctly, the Watchdog comes enabled by default so there is a chance than even 64 GiB users encounter this issue.

**Comment by verygreen** [comment]
yes, as soon as I plug 128G RAM into this board, the system enters a bootloop rebooting every two minutes as it cannot complete the memory training in the alotted time. 64G works by a hair.

**Comment by verygreen** [comment]
here's the two iterations of the bootloop on a debug build with loglevel set to 8 (produced by @miczyg1 ): https://pastebin.com/3wMa2FvM
v1.1.1 from download site does not produce any serial output at all.

**Comment by verygreen** [comment]
[myrom1-128G.txt](https://github.com/Dasharo/dasharo-issues/files/11277092/myrom1-128G.txt)
And here's debug output from my own build with the timeout increased at compile time to 300. Note that another bug hits (in all versions I tried) - after memory training the WDT is never disabled so if you enter the bios menu right after - the WDT hits and the boards reboots on the timeout boundary. that's why there are again two reboots visible in this log

**Comment by miczyg1** [comment]
> [myrom1-128G.txt](https://github.com/Dasharo/dasharo-issues/files/11277092/myrom1-128G.txt) And here's debug output from my own build with the timeout increased at compile time to 300. Note that another bug hits (in all versions I tried) - after memory training the WDT is never disabled so if you enter the bios menu right after - the WDT hits and the boards reboots on the timeout boundary. that's why there are again two reboots visible in this log

The watchdog is still working indeed, but we have periodic SMI that reloads the watchdog. `Feed the watchdog using periodic SMI` in the chipset coreboot menuconfig. This must be something else like I said on matrix.

**Comment by verygreen** [comment]
> `Feed the watchdog using periodic SMI` in the chipset coreboot menuconfig must be selected, otherwise you will get resets

I use the default config, so it's there, right?  `CONFIG_SOC_INTEL_COMMON_OC_WDT_RELOAD_IN_PERIODIC_SMI=y` jsut verified.

I also verified that even if I am quick and able to start the OS boot after MRC training, it still resets. But only just that one time, subsequent boots where MRC training is not done work just fine, so must be related to that somehow.

**Comment by miczyg1** [comment]
@verygreen yes it resets if you have an Ubuntu or something like that installed. The thing is that if you flash the BIOS region, you lose the UEFI boot options. Ubuntu restores the boot option if you execute EFI/BOOT/BOOTX64.EFI, but also resets the platform after the option is restored (you can quickly see Reset System in the top left corner of the screen). This is not firmware fault. Although we work on adding the support to scan the filesystems to look for known OSes and boot the OS bootloader directly: https://github.com/Dasharo/dasharo-issues/issues/94

**Comment by verygreen** [comment]
No, that's definitely not it. I don't have an OS installed even.

Basically it's like this:
1. memory trained, watch it like a hawk, press del to enter the menu, muck about in the menu, reset (at the boundary of the original WDT)
2. memory trained, watch it like a hawk, press del to enter the menu, quickly navigate to one time boot, select usbstick with semthing (e.g. memtest), memtest starts loading -> reset as the boundary of WDT is reached
3. I think the same happens even when menu is not entered but was not paying as much conscious attention

**Comment by miczyg1** [comment]
Ok, I will look again at that log to see if there is something suspicious...

**Comment by verygreen** [comment]
thanks. Also it's very reproduceable for me (even on your test build) - wipe training data (usually by bios flashing, I guess, so might be related to some other data missing, not training data?) power the system on, it undergoes memory training, enter bios setup, the system reboots as the wdt timer about of time is reached.

I can file a separate issue if you want.

**Comment by miczyg1** [comment]
There was a problem in reading the variables on coreboot's side: https://github.com/Dasharo/coreboot/commit/bb12ff970391cf90b987761a090d2b4d2df21fad

With v1.1.2 the problem should be gone.

**Comment by miczyg1** [comment]
V1.1.2 has been released and the issue does not occur, so closing the issue.
