### ISSUE TITLE
User does not belong to the docker group

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#42]
*Issue moved from GitLab*

**Dasharo version**

v0.5.0

**Hardware details**

NV40MZ

**Affected component(s) or functionality**

While building: docker

**Brief summary**

Permission denied error when using the docker application.

**How reproducible**

Always on every new installation until the solution is applied.

**How to reproduce**

Run docker as a standard non-admin user, for example:
docker run hello-world

A permission denied message will show up.

**Expected behavior**

Docker shows a message and exits.

**Actual behavior**

Docker shows a message with permission denied.

**Screenshots**

![Bildschirmfoto_vom_2021-12-10_13-08-25](/uploads/debf95b5bd32d3d1a129218fbcb511b1/Bildschirmfoto_vom_2021-12-10_13-08-25.png)

**Additional context**

The solution should be implemented in the documentation.

**Solutions you've tried**

Run the following two commands in a terminal:

- sudo usermod -aG docker $USER
- newgrp docker

This solves the issue.

/cc @macpijan

**Comment by macpijan** [comment]
This was already fixed. Please see: https://gitlab.com/novacustom/dasharo-compatibility/-/issues/11#note_806623896
