### ISSUE TITLE
Useless information in Dasharo newslettter

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#420]
`Dasharo coreboot fork based on 1a8eb6c02103727431ac1ea23f4f507e49f3cde7 revision ae10b20f` it is an awful way of providing information and for 99.9% of community useless.  Why can't something a little bit meaningful, e.g., a version of the upstream project we are based on and some information about the measure of the amount of differences we introduced diverging from that version (I'm not insisting on that information, this is just an example to avoid completely useless and time-wasting information in correct newsletter template).

**Comment by pietrushnic** [comment]
This happens again in Protectli Vault VP2420 Dasharo Release v1.1.0:

```
Components:

    coreboot based on c86c926 revision e36a117d
    edk2 based on 7f90b9cd revision 19bf14b4
```

**Comment by macpijan** [comment]
@pietrushnic In upcoming NovaCustom release we have:

```
[Dasharo coreboot fork based on 4.21 revision 36032e55](https://github.com/Dasharo/coreboot/tree/36032e55)
 [Dasharo EDKII fork based on edk2-stable202002 revision b68e46b0](https://github.com/Dasharo/edk2/tree/b68e46b0)
 ```
    
 In the previous MSI release, we had similar: https://docs.dasharo.com/variants/msi_z690/releases/#v112-2023-09-06
    
    
```
[Dasharo coreboot fork based on 4.18 revision 197229de](https://github.com/Dasharo/coreboot/tree/197229de)
[Dasharo EDKII fork based on edk2-stable202002 revision 94f562a7](https://github.com/Dasharo/edk2/tree/94f562a7)
```

**Comment by pietrushnic** [comment]
@macpijan Thank you, I love it. Did we manage to change some templates or guides for release note creation so we can be sure we will not get back to the previous useless format?

Also, I think in the release notes, we should clearly say that we update the given framework version.

**Comment by macpijan** [comment]
>  Did we manage to change some templates or guides for release note creation so we can be sure we will not get back to the previous useless format?

It is not automated, but for new releases we reuse the previous YAML as a base, so this should be preserved. I belive it could be automated still, though.

> Also, I think in the release notes, we should clearly say that we update the given framework version.

It is in `changed` section for this release.

**Comment by miczyg1** [comment]
@pietrushnic please close the issue if you feel it has been addressed.

**Comment by miczyg1** [comment]
> Did we manage to change some templates or guides for release note creation so we can be sure we will not get back to the previous useless format?

At least in the repository with templates we have a following description for the version field in the README:

```
version - the latest upstream tag which the release is based from, should be a meaningful value, cannot be a hash (unless the upstream repository does not provide tags)
```

**Comment by pietrushnic** [comment]
Yes, I'm closing it based on manual verification of `Dasharo Entry Subscription for Network Appliance release for PC Engines v0.9.0` where correct reference versions are implemented.
