### ISSUE TITLE
Change boot order menu is confusing

### ISSUE THREAD

**Issue by verygreen** [Dasharo/dasharo-issues#422]
**Dasharo version**
v1.1.1

**Dasharo variant**
MSI Z690A DDR5 (and DDR4 too)

**Affected component(s) or functionality**
boot maintenance -> change boot order screen is confusing

**Brief summary**
Unlike what we see in the documentation: https://docs.dasharo.com/dasharo-menu-docs/boot-maintenance-mgr/#change-boot-order
The actual screen looks very confusing with an empty list:
![PXL_20230424_030332680](https://user-images.githubusercontent.com/625925/233891387-840e47d7-1e05-43ec-992c-25b1a42fc63a.jpg)
If you then press enter on this empty screen with nothing highlighted, you get a menu to change boot order of stuff. When you press enter later you get back to this screen.
But if you just move the cursor with keyboard arrows all you see is commit/discard changes selecting creating an illusion nothing could be done on this screen.

**How reproducible**
100%

**Comment by verygreen** [comment]
I tested on 1080p and it does show up there indeed.

**Comment by miczyg1** [comment]
Fix: https://github.com/Dasharo/edk2/pull/74

**Comment by BeataZdunczyk** [comment]
Closing this issue as the changes have been merged. We are currently completing testing for the release, and further updates will be provided on testing issues https://github.com/Dasharo/dasharo-issues/issues/612 and https://github.com/Dasharo/dasharo-issues/issues/613.
