### ISSUE TITLE
Fan curve adjustable from OS (Linux)

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#424]
**The problem you're addressing (if any)**

The fan curve is not adjustable from OS level. It requires recompliation of EC firmware, or selecting one of the profiles ine the firmware menu: https://docs.dasharo.com/unified/novacustom/fan-profiles/

**Describe the solution you'd like**

I'd like that the fan curve can be configured from Linux, so I can use sysfs programming interface in my scripts, or GUI applications, to control the fan curve.

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

None

**Additional context**

Some work was already done here by community contributor: https://github.com/pop-os/system76-acpi-dkms/issues/9#issuecomment-1281232866
It seems it lacked testing and review, and maybe we could step in here with some support.

**Comment by wessel-novacustom** [comment]
No need from our side for this feature. Users can set the fan curve they like in the UEFI firmware settings. Moreover, they can temporarily switch to 100% fan speed with the shortcut `Fn + 1`. I think that is enough :-)

**Comment by tlaurion** [comment]
@wessel-novacustom but if not exposed through kernel (again system76_acpi driver I guess) then Heads will not be able to permit to tweak those settings?

**Comment by wessel-novacustom** [comment]
> @wessel-novacustom but if not exposed through kernel (again system76_acpi driver I guess) then Heads will not be able to permit to tweak those settings?

I think that is correct. Ping @macpijan 

So we need #820

**Comment by macpijan** [comment]
Yes, please see my comment here: https://github.com/Dasharo/dasharo-issues/issues/820#issuecomment-2076652413

It is challenging to please Linux, Windows, and now also heads users with a single firmware base. We were aware of the fact, that some features implemented in the edk2 (UEFI firmware variant) will not be available in the heads firmware variant.

**Comment by Atrate** [comment]
> No need from our side for this feature. Users can set the fan curve they like in the UEFI firmware settings. Moreover, they can temporarily switch to 100% fan speed with the shortcut Fn + 1. I think that is enough :-)

I personally would appreciate if this feature was added. Both of the fan curves in Dasharo are not good for my use-case, so I'd like to be able to set it from the OS itself.
