### ISSUE TITLE
Allow to toggle camera ON/OFF

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#425]
**The problem you're addressing (if any)**

Currently, camera is always ON.

**Describe the solution you'd like**

I'd like to be able to switch camera OFF.

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

None

**Additional context**

EC could control the camera state, and we could export that via ACPI driver to the OS.

**Comment by zollerd** [comment]
Would love to see this feature come to fruition eventually.

**Comment by mkopec** [comment]
Implemented in https://github.com/Dasharo/coreboot/pull/389

@macpijan do we keep this issue open until the release is out?

**Comment by wessel-novacustom** [comment]
This has been implemented in the UEFI firmware settings and can be closed, right?
