### ISSUE TITLE
Selectable performance profiles

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#426]
**The problem you're addressing (if any)**

With Dasharo firmware, I cannot set the performance profiles as with the Clevo Control Center

**Describe the solution you'd like**

Clevo Control Center allows 4 profiles to be set:
- Quiet
- Power Saving
- Entertainment
- Performance

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by macpijan** [comment]
NovaCustom is not planning to add support for this

**Comment by wessel-novacustom** [comment]
Correct, not for Clevo WMI ACPI tables. So the issue can be closed.
