### ISSUE TITLE
Power delivery compatibility

### ISSUE THREAD

**Issue by Pace17881** [Dasharo/dasharo-issues#431]
### The problem you're addressing (if any)

I'm using a novacustom_nv4x_adl

If I use a 60W PD charger, the charger gets reseted periodically every second. If I use a 90W Charger it works.

### Describe the solution you'd like

Is it possible to improve the compatibility to weaker chargers, without losing advantages of better chargers?

### Where is the value to a user, and who might that user be?

Typical situation could be, that you don't have a 90W charger available and another person has a 60W Charger...

**Comment by mkopec** [comment]
This is a known problem actually, we're tracking adding better support for USB-PD supplies here: https://github.com/Dasharo/dasharo-issues/issues/236 .

**Comment by mkopec** [comment]
This issue is fixed in upcoming release v1.7.0 for NV4x ADL.
