### ISSUE TITLE
[edk2 rebase - task 2] Verify if commits with concerns should be applied or not

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#433]
Here is a list containing a diff against the upstream edk2:
https://paste.dasharo.com/?15d7c69a16f148ca#HA1yxMydgvQtGa7pac1RwitbZFGcahyNdHRig6x67cty)

I have marked each commit (on the begining of the line) with a symbol:

- `+` means a commit that has to be cherry-picked onto a rebased edk2 branch (to be migrated)
- `-` measn a commit has to be skipped/dropped
- `?+` means a commit that SHOULD be cherry-picked onto a rebased edk2 branch (to be migrated), however there are some concerns which have to be checked first before deciding (the concerns are at the end of the line in parentheses) 
- `?-` means a commit that SHOULD be skipped/dropped, however there are some concerns which have to be checked first before deciding (the concerns are at the end of the line in parentheses) 
- `U` means upstreamable fix to edk2-devel ML

There are also commits marked for quashing or to be migrated to DasharoModulePkg to make future rebases easier.

Next (second) task is to check the items makred with `?+` and `?-` and verify whether the concerns to those commits apply, or if we change some suspicious part of given commit, it will stil lwork as expected or even fix some bugs. The test should be done on the current code base. The goal is to determine whether given commit:

- `?-` can be really dropped or needs some work to be fixed and then applied
- `?+` is still needed (if not can be dropped) or needs some work to be fixed and then applied

The action to be taken is really dependent on the given commit and the concerns it has. Concerns should be tested on separate branches. If there are any positive results, a PR should be created. Then we should add new commits to paste created in [task 1](https://github.com/Dasharo/dasharo-issues/issues/432) and mark them for squashing with the commit it relates to, giving a `+` sybmol to it and removing the concern in parentheses. It will allow us to reduce the number of unneeded commits and clean up the list of unsure commits.

**Comment by miczyg1** [comment]
```
?- 56313ac56f MdeModulePkg/Usb/Keyboard.c: don't request protocol before setting
?- 143d9fea48 MdeModulePkg/Usb/Keyboard.c: remove Get/SetConfig calls
```

Are actually correct... They help with USB USB transfer timeouts. ALso the drivers support only the boot protocol, so trying anything else is pointless in edk2.

**Comment by miczyg1** [comment]
Updated diff: https://paste.dasharo.com/?778383f1dc1e8819#6gyZdKvzfAToYscQj9HTh4GLweBnzQZMLPSRL75SAy6w

**Comment by SergiiDmytruk** [comment]
Done: https://github.com/Dasharo/edk2/pull/129#issuecomment-2461829498
