### ISSUE TITLE
[edk2 rebase - task 3] Migrating commit to a fresh edk2 branch

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#434]
Here is a list containing a diff against the upstream edk2:
https://paste.dasharo.com/?15d7c69a16f148ca#HA1yxMydgvQtGa7pac1RwitbZFGcahyNdHRig6x67cty)

I have marked each commit (on the begining of the line) with a symbol:

- `+` means a commit that has to be cherry-picked onto a rebased edk2 branch (to be migrated)
- `-` measn a commit has to be skipped/dropped
- `?+` means a commit that SHOULD be cherry-picked onto a rebased edk2 branch (to be migrated), however there are some concerns which have to be checked first before deciding (the concerns are at the end of the line in parentheses) 
- `?-` means a commit that SHOULD be skipped/dropped, however there are some concerns which have to be checked first before deciding (the concerns are at the end of the line in parentheses) 
- `U` means upstreamable fix to edk2-devel ML

There are also commits marked for quashing or to be migrated to DasharoModulePkg to make future rebases easier.

Third task bases on the paste created in [task 2](https://github.com/Dasharo/dasharo-issues/issues/433) which will already contain a complete list of commits that are 100% known to be dropped or migrated. One has to create a new branch based on the upstream edk2 and start applying/cherry-picking the commits (with squashing if needed) to the new branch. Of course git conflicts will appear and they must be solved with utmost care. The task ends if all commits marked with `+` are migrated (one may likely need also some code from the commits marked with `-`, be sure to check it if git has major problems) and the images are buildable.

**Comment by krystian-hebel** [comment]
@miczyg1 I suggest starting with building clean edk2 before rebasing. There were some changes to the toolchain requirements, Docker images we're using may no longer be able to build it.

**Comment by miczyg1** [comment]
Updated diff https://paste.dasharo.com/?778383f1dc1e8819#6gyZdKvzfAToYscQj9HTh4GLweBnzQZMLPSRL75SAy6w

**Comment by miczyg1** [comment]
> @miczyg1 I suggest starting with building clean edk2 before rebasing. There were some changes to the toolchain requirements, Docker images we're using may no longer be able to build it.

Upstream edk2 checked and it builds with the newest coreboot-sdk. Moreover it boots Linux

**Comment by SergiiDmytruk** [comment]
Done: https://github.com/Dasharo/edk2/pull/129#issuecomment-2461829498
