### ISSUE TITLE
[edk2 rebase - task 4] Regression testing all of the features after edk2 rebase

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#435]
Using the branch created in [task 3](https://github.com/Dasharo/dasharo-issues/issues/434) one should produce fully featured Dasharo images to undergo the full validation cycle and detect all possible errors. The cooperation of the validation team and development team is inevitable and crucial in this task. If there is any need to change the documentation on docs.dasharo.com page, it should be done now. The task ends if all features' tests PASS.

Suggested platforms for use, that can cover all features: NovaCustom ADL laptops and MSI Z690-A desktops. For serial console testing, Protectli VP46xx platforms may be used.

**Comment by SergiiDmytruk** [comment]
Done: https://github.com/Dasharo/edk2/pull/129#issuecomment-2461829498
