### ISSUE TITLE
No text rendered in Dasharo UEFI firmware on GTX660ti

### ISSUE THREAD

**Issue by BrettLMiller** [Dasharo/dasharo-issues#438]
**Dasharo version**
dmesg reports: DMI: Micro-Star International Co., Ltd. MS-7D25/PRO Z690-A WIFI (MS-7D25), BIOS Dasharo (coreboot+UEFI) v1.1.0 11/15/2022
dmidecode reports: Dasharo (coreboot+UEFI) v1.1.0

But I used DTS to update to v1.1.1

**Dasharo variant**
no variant

**Affected component(s) or functionality**
The UEFI firmware UX/UI.
The hands-off boot process is fine.

**Brief summary**
There is NO text shown by Dasharo firmware during the normal boot process.
After attempting to enter interactive mode, some graphical characters are drawn in rectangular box shapes.
Boot process works fine.

**How reproducible**
100% reproducible

**How to reproduce**
Do nothing special..

**Expected behavior**
The same video card & same computer works fine* with original MSI UEFI-BIOS.
The same video card works fine* in Asus Z87 in UEFI mode (modified BIOS for NVMe)
The same video card works fine* in Intel DP55WG UEFI mode.
*works- fine == BIOS interactive UI/UX & normal boot process

**Actual behavior**
No text in UEFI firmware
An underscore character shows in top left corner of a white screen.
Blind navigation of Dasharo firmware seems possible.
Blind navigation in Boot Manager to DTS to shell is possible.
DTS works fine
Text is displayed in the launched shell.
I use efibootmgr to be able to run DTS.

Until several days ago I did not realize there was any Dasharo UI/UX operating mode!

**Additional context**
The video card GPU is a Nvidia GTX660ti GK104 with modified VBIOS to allow UEFI boot.
VBIOS has UEFI GOP added using python tool GOPupd.py.
Monitor is 4K connected by displayport.
Monitor is 100% percent reliable with Windows10 PC connected by displayport.

**Solutions you've tried**
I imagine changing video card will fix this & is in future plans..

**Comment by zirblazer** [comment]
Do you have a Processor with IGP? Tried plugging the Monitor to it (Motherboard ports)?
Were the other Motherboards you tested it in pure UEFI mode (CSM disabled), to guarantee than they're actually using UEFI GOP and not VBIOS?
Also try with a 1920 x 1080 resolution Monitor instead of a 4K one if you can.

If you can get Firmware video output in any other way, can you check if you have either Secure Boot and [Early boot DMA protection](https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/) enabled (Both should be disabled by default, but better check)? The last one caused a white screen on POST with Radeon Polaris cards (RX 470/480/570/580).

**Comment by BrettLMiller** [comment]
This issue is not causing any problems here until I break grub/OS boot process.
I managed to get DTS running (USB stck without using efibootmgr) & then a shell so can be done again..

CPU = Intel 12400F so no IGP.
This is a domestic environment so there is no cache of stuff to experiment with.
All the other mobos tested, including msi-z690 (with msi bios/fw), were booted in UEFI mode and NO secure boot.
The whole point of adding GOP to VBIOS was to get full UEFI boot from NVMe & to avoid scrapping yet another video card.
The Intel DP55WG mobo was one of the first with UEFI BIOS & is very very picky with CSM settings.

GTX660ti works really well with nouveau until it crashes (hard & often).
But I suspect that the problem could be in that VBIOS modding process.
AFAIK Linux Nvidia proprietary driver does not work with secure boot so it must be off..
Note that now I am not using any NVidia driver but nouveau & llvmpipe (to stop GLX crashing). 

So a white initial Dasharo POST screen is not normal ?
The "exiting UEFI FW" Dasharo logo splash screen is displayed in 4K (AFAICT).

If the Intel Arc A380 was in stock locally, I'd have already tried it!

**Comment by miczyg1** [comment]
> So a white initial Dasharo POST screen is not normal ?

It is not normal. It should be pitch black background with white Dasharo logo.

The issue looks like the VBIOS problems we had with other cards, VBIOS seems to be buggy (does not account for IOMMU DMA protection in its code) and the white screen is a cause of this.

What is worrying is that the update to v1.1.1 did not succeed. I suspect the flash protection were still on when updating and the firmware booted in recovery mode. What we can do now is to boot DTS again and:

1. Enter the Shell in DTS (option 9)
2. Download the v1.1.1 binary by typing `wget https://dl.3mdeb.com/open-source-firmware/Dasharo/msi_ms7d25/v1.1.1/msi_ms7d25_v1.1.1_ddr5.rom` (your board is DDR5 judging from the board name from the issue description, right?)
3. Use flashrom to update again, but we will also erase the UEFI settings:

```
flashrom -p internal -w msi_ms7d25_v1.1.1_ddr5.rom --fmap -i RW_SECTION_A -i RW_SECTION_B -i SMMSTORE -i RW_NVRAM
```

4. If flashrom reports the operation as VERIFIED, type `poweroff` to shut the machine down.
5. Unplug the AC power cord.
6. Remove the CMOS coin cell battery from the mobo and leave it for 30 seconds.
7. Plug the battery and the AC power cord back.
8. Power on the machine and check if dmidecode shows v1.1.1 now.

If it shows v1.1.1 the DMA protection should be disabled by default now and hopefully the Nvidia card will allow you to browse firmware UI

**Comment by BrettLMiller** [comment]
That fixed it..
Glad you spotted the FW version in the dmidecode / dmesg reports..
I just assumed the DTS flash process did not update those fields with right data.

I downloaded the firmware with browser & copied it to the DTS USB stick.
Thanks very much.

**Comment by miczyg1** [comment]
You are welcome :)
