### ISSUE TITLE
z690-A WIFI reboot loop

### ISSUE THREAD

**Issue by inoperable** [Dasharo/dasharo-issues#439]
**Dasharo version**

Booted DTS over ipxe, v1.1.1

**Dasharo variant**

MSI z690-A pro ddr4 wifi

**Question text**

DTS procedure successfully completed,
Flashed and rebooted. HDD led blinked, then the board shutdown and it keeps rebooting o.O in a loop.

13700k and rtx 3080, what do I do? 
Tried to reshuffle ram, reduced to one 8gb stick in a2 slot - no go.
Connected iGPU through DP and HDMI, dGPU with HDMI - blank screen, reboot loop. Recovery isn't a issue, got a hw programmer with tons of clips and cables (and the movie has a pretty common winbond chip) but I want to make it work and not revert :-)

All suggestions appreciated.

**Comment by pietrushnic** [comment]
@inoperable, why are you trying Dasharo on 13th Gen? If there is misleading information somewhere, please point us to that before others brick their hardware.

There is no 13th Gen on the CPU compatibility list: https://docs.dasharo.com/variants/msi_z690/cpu-hcl/#network-appliance

There are also issues with supporting 13th Gen https://github.com/Dasharo/dasharo-issues/issues/263 https://github.com/Dasharo/dasharo-issues/issues/130

**Comment by inoperable** [comment]
Huh, there is nothing about not using dasharo on 13th gen, only a notice about ddr5 version a d coreboot mainline not supporting 13th gen. Either this or im didn't rtfmed enough.

Consider adding a simple bash script to waern dumbasses like me to not proceed if /dev/cpuinfo contains "13th" :-)

Damn, so ch341a for me...

**Comment by inoperable** [comment]
Aside of the obvious, why is it doing the reboot loop? Seems some parts get initialized. You got my HCL submitted so you can take a closer look on the HW if there is sny point at it now.

**Comment by inoperable** [comment]
And thanks for your fast response! Are all of the 12th gen CPUs good, I got a pentium 12th gen ar hand so before I start unfold the clippers it would be easier to swap the CPU ;-)

**Comment by miczyg1** [comment]
> And thanks for your fast response! Are all of the 12th gen CPUs good, I got a pentium something 12th gen at hand so before I start unfold the clippers it would be easier to swap the CPU ;-)

Should be fine IMO. Also plugging a 12th gen CPU won't do any more harm :)

**Comment by miczyg1** [comment]
> Aside of the obvious, why is it doing the reboot loop? Seems some parts get initialized. You got my HCL submitted so you can take a closer look on the HW if there is sny point at it now.

No idea. We haven't been plugging 13th gen CPUs yet, so we don't know the possible bootloop reasons.

**Comment by inoperable** [comment]
Will commit some considerations to be put into the docs. Explicitly allowed stuff does not implicitly constraints people from doing ~experimental, umm research~ :-)

**Comment by miczyg1** [comment]
This one can be closed, because is caused by #440
