### ISSUE TITLE
Dasharo Supporters Releases (DSRs) support in DTS

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#441]
We need to discuss and establish a road map for adding support for upgrades and deployments of future DSRs in DTS.

It is worth going back to https://docs.dasharo.com/dev-proc/versioning/#dasharo-supporters-releases and considering whether such a division between DSRs and DCRs (Dasharo Community Releases) is still valid.

**Comment by TomaszAIR** [comment]
https://github.com/Dasharo/docs/pull/541#discussion_r1193205125

**Comment by pietrushnic** [comment]
> It is worth going back to https://docs.dasharo.com/dev-proc/versioning/#dasharo-supporters-releases and considering whether such a division between DSRs and DCRs (Dasharo Community Releases) is still valid.

The description has to be improved. I created a branch to move forward documentation, based on which we can discuss the impact on the DTS update process.

**Comment by miczyg1** [comment]
The support has been added with recent MSI release. Proof from changelog: https://github.com/Dasharo/meta-dts/blob/main/CHANGELOG.md#v127---2023-09-05
