### ISSUE TITLE
RW firmware unable to verify keyblock

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#442]
**Dasharo version**

v1.1.1

**Dasharo variant**

MSI Z690-A DDR4

**Affected component(s) or functionality**

Boot process, security?

**Brief summary**

Since the update from v1.1.0 to v1.1.1 through DTS v1.2.0 option `5) Update`, I'm getting the warning `RW firmware unable to verify keyblock.`

**How reproducible**

100%

**How to reproduce**

Update from v1.1.0 to v1.1.1  using DTS v1.2.0 update option?

**Expected behavior**

Boot without warning.

**Actual behavior**

The boot process should complete without warning.

**Screenshots**

![dasharo_v1 2 0_warning](https://github.com/Dasharo/dasharo-issues/assets/1071894/56f5f73d-29af-42ac-8fa6-6c4298ebf08b)

**Additional context**

None.

**Solutions you've tried**

None.

**Comment by pietrushnic** [comment]
Duplicate of #269 ?

**Comment by pietrushnic** [comment]
@miczyg1 @TomaszAIR so what is happening here? I just did a regular update using the most recent DTS.

**Comment by miczyg1** [comment]
No idea for now. I will try to reproduce it to see what happened

**Comment by pietrushnic** [comment]
@miczyg1 IMHO, this is critical, how we can live with a firmware update after which the platform indicates it was tempered? @artur-rs @BeataZdunczyk @macpijan, do we have this on any roadmap?

**Comment by pietrushnic** [comment]
It is fixed for me after updating to v1.1.2, but there are users reporting similar problem but with error `0x03` on Dasharo Primer Support.

**Comment by miczyg1** [comment]
I think the BIOS lock was not disabled during an update and as a result, the vboot error is displayed. Not sure if DTS has al checks in place already, but some checks for locks have been addded.

**Comment by pietrushnic** [comment]
@miczyg1 but how to fix that state? Force update again?

**Comment by miczyg1** [comment]
> @miczyg1 but how to fix that state? Force update again?

If it is still bootign from recovery it should expose the older firmware version in SMBIOS, so DTS should still try to update. The answer is yes, disable the protection and try again with DTS.,

**Comment by pietrushnic** [comment]
@miczyg1 so I guess we need that in documentation and I'm fine with closing this issue.

**Comment by miczyg1** [comment]
@pietrushnic it is there for a very long time: https://docs.dasharo.com/dasharo-tools-suite/documentation/ (see requirements)

**Comment by pietrushnic** [comment]
@miczyg1, we are getting to very convoluted logic here. There are requirements for disabling locks to which we can't even link directly, but there is no word on what will potentially happen if you message and how to get back on track.

Security features not covering all detection, protection, and recovery possibilities are poorly designed and/or implemented. We can recover, but there is no word about the signature of the detection event (hence the scary screen during boot). What is more, what we get is so scary that the user has no idea if it was compromised or a user mistake during the update process. We advise users to update from a potentially compromised system. Someone concerned about security may be picky here. Partially applied updates are always PITA; we should have a mechanism to avoid that. Finally, if we detect an issue, we should provide a reliable path for recovery, even if that path would assume some not ideal threat model.

**Comment by miczyg1** [comment]
Well, DTS is still lacking in all of the above terms (handling errors and checking preconditions). We just have added the checks for (yet not all) protections in latest DTS release. The Firmware Update Mode is ought to solve those problems (and simplify things for DTS)

**Comment by miczyg1** [comment]
@pietrushnic this issue is something else and is rather subject for closing already, not extending its scope and mixing with DTS. IF anything it should be a separate issue created for that.

**Comment by pietrushnic** [comment]
@miczyg1 No problem, if you need that bureaucracy https://github.com/Dasharo/dasharo-issues/issues/489

**Comment by miczyg1** [comment]
@pietrushnic not bureaucracy. I just hate never ending stories which lead to never decreasing number of issues.
