### ISSUE TITLE
Add hwprobe to DTS HCL report generation

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#449]
### The problem you're addressing (if any)

Improving the value of HCL reports ending users. Currently, HCL reports are dumped into the 3mdeb cloud, and nobody has time to process those. There is already state of the art database for hardware configurations supported by Linux and BSD:

https://linux-hardware.org
https://bsd-hardware.info/

Why not use it for spreading information about 3mdeb and Dasharo's market share and hardware support?

### Describe the solution you'd like

In addition to the generation of every HCL report hwprobe should be triggered and uploaded to linux-hardware database.

The side effect would be reporting about DTS usage.

### Where is the value to a user, and who might that user be?

Users can easily find if their hardware is supported and we can spread information about Dasharo market share.

### Additional context

This topic is closely related with the redesign of the HCL report: https://github.com/Dasharo/docs/pull/463

**Comment by artur-rs** [comment]
The [changes](https://github.com/Dasharo/meta-dts/pull/103/files) are now in the testing/review phase.
