### ISSUE TITLE
Custom fan curve after suspend

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#45]
**Dasharo version**

v1.0.1

**Dasharo variant**

Clevo NV41MZ

**Affected component(s) or functionality**

Custom fan curve.

**Brief summary**

The custom fan curve is not active after a system suspend state (S3).

**How reproducible**

100% reproducible.

**How to reproduce**

1. Boot the laptop to Ubuntu 20.04.4.
2. Install the packages `stress` and `xsensors` using the command `sudo apt install -y stress xsensors` in a terminal window.
3. Start a video on YouTube using a web browser. Alongside, start the xsensors application and the next command in a terminal window: `stress --cpu 8 --io 4 --vm 2 --vm-bytes 128M --timeout 120s`.
4. Observe the CPU temperature and notice that the fan behavior is working properly (barely noticeable at 51 degrees C) in a quiet environment.
5. Put the laptop into sleep mode (for instance with the shortcut FN+F12) and bring it back to normal state (S0) as soon as the sleep mode is active, which can be noticed by a blinking green power LED.
6. Observe the CPU temperature and notice that the fan behavior is not working properly (very noticeable at 51 degrees C) in a quiet environment.

**Expected behavior**

The CPU fan to be barely noticeable in step 6 (after suspend).

**Actual behavior**

The CPU fan to be quite noticeable in step 6 (after suspend).

**Screenshots**

**Additional context**

This issue has not been confirmed nor been noticed in older firmware versions.

I have not tried to flash EC version 1.07.08 as this EC version does not support the custom fan curve at all.

Using EC version 1.07.05, the used laptop has no revised motherboard.

**Solutions you've tried**

Restarting the laptop. This brings back the expected behavior until the laptop goes in sleep mode (suspend, S3) again.
Reflashing the EC firmware internally and then performing a CMOS reset. This did not affect the issue.

**Comment by macpijan** [comment]
@wessel-novacustom 
We have spend a little bit on analyzing this issue. What we found out is that the EC firmware resets the fan curve some time after suspend (after we set it ourselves, so our custom one is overriden). It is not clear why and where it happens. Some more analysis of the EC firmware would need to be required, unfortunately.

**Comment by wessel-novacustom** [comment]
All right! Please keep me up to date about it. Many thanks!

**Comment by mkopec** [comment]
This has been fixed by switching to open-source EC firmware
