### ISSUE TITLE
NV40MZ's touchpad does not work after waking up from sleep mode

### ISSUE THREAD

**Issue by MasterBootRecord32** [Dasharo/dasharo-issues#453]
**Dasharo version**
v1.4.0

**Dasharo variant**
 NovaCustom NV40MZ (Tiger Lake variant) running GNOME and Arch Linux.

**Affected component(s) or functionality**
Laptop's internal pointing device (touchpad).

**Brief summary**
Sometimes, when the laptop wakes up from sleep mode, the internal touchpad does not click anymore : when using "tap to click" but also when pushing to click (physical click).

**How reproducible**
The issue seem to appear on a completely random basis.

**How to reproduce**

1. Put the laptop in sleep mode using the GUI and closing the lid of the laptop or by pressing "Super + L" and closing the lid ;
2. Open the lid of the laptop and enter the password for the session ;
3. Either the click works or not.

**Expected behavior**
The touchpad should click even after the computer has been woken up from deep sleep mode.

**Actual behavior**
Sometimes, the touchpad does not click anymore (see workarounds to see how I fix the issue when this happen).

**Screenshots**
Issue after waking up from sleep mode : 
https://github.com/Dasharo/dasharo-issues/assets/117741516/38bd600d-8d08-4eac-bd67-2c9380e210fb

**Additional context**
Please note that only the click function does not work : sliding on the touchpad to move the cursor actually still works. 

**Solutions you've tried**
Works : Rebooting the laptop by only using its internal keyboard : "Ctrl + Alt + F3" or "Fn + Ctrl + Alt + F3" (if function lock is enabled) to switch to TTY3, login to your user account, sudo systemctl reboot.
Works : Closing the lid of the laptop again to put it back in sleep mode and waking it back up.

**Comment by MasterBootRecord32** [comment]
Since v1.5.0, this issue does not seem to appear anymore.
It happened directly after waking up the laptop from suspend mode, with no delay.

I'm using a rolling release so kernel v6.6.1-arch1-1.
I had no logs about this issue in journalctl.

I think maybe we can close this issue as fixed.

**Comment by wessel-novacustom** [comment]
All right, yes, please mark it as closed.
