### ISSUE TITLE
 F9 key feature in Dasharo System Features is not documented (basic navigation and hotkeys documentation)

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#459]
**Brief summary**

Using the F9 key resets the settings in each of the submenus in Dasharo System Features, which is not documented.

**Comment by miczyg1** [comment]
The F9 hotkey is always displayed on the bottom of the setup page when browsing a form. I don't get what is missing. What expectations did you have WRT to F9 key? Reset only a part of the settings? Every BIOS has a settings reset option that works globally.

**Comment by Pokisiekk** [comment]
Will every potential user know that this option resets the settings globally? It wasn't obvious to me.

The F9 hotkey only appears after entering one of the submenus in Dasharo System Features. Let's assume that someone, wanting to restore fan settings, chooses the F9 option while also enabling ME and disabling BIOS lock, which is not visible on the screen. Without being aware of such changes, they are exposed to unintended results of their actions.

A brief note in the documentation wouldn't hurt to avoid any unwanted scenarios.

**Comment by miczyg1** [comment]
> Will every potential user know that this option resets the settings globally? It wasn't obvious to me.

it is obvious to me, because every BIOS I have seen have a reset that works globally.

> The F9 hotkey only appears after entering one of the submenus in Dasharo System Features. Let's assume that someone, wanting to restore fan settings, chooses the F9 option while also enabling ME and disabling BIOS lock, which is not visible on the screen. Without being aware of such changes, they are exposed to unintended results of their actions.

I shows on every form you browse, not only Dasharo menu. Simply check the TCG2 Configuration or Secure Boto Configuration in our docs...

> A brief note in the documentation wouldn't hurt to avoid any unwanted scenarios.

If it is that simple, feel free to submit PR and I can review it :)

**Comment by mkopec** [comment]
Reset do defaults behavior has been changed in https://github.com/Dasharo/edk2/pull/109 - the hotkey is always available and always resets all settings (all forms) to their default values regardless where the user invokes the reset. Same goes for F10 (Save) hotkey.

**Comment by macpijan** [comment]
I think we could still add section on the very basics, such as navigation keys and global hotkeys. Example: https://www.dell.com/support/manuals/en-us/latitude-14-5440-laptop/latitude-5440-owners-manual/navigation-keys?guid=guid-f448dd64-1b07-4857-a446-42e313a39cc8&lang=en-us

**Comment by filipleple** [comment]
Resolved by [docs PR #709](https://github.com/Dasharo/docs/pull/709)
