### ISSUE TITLE
/usr/sbin/dasharo-hcl-report: unary operator expected

### ISSUE THREAD

**Issue by zsrv** [Dasharo/dasharo-issues#467]
**Dasharo version**

Dasharo Tools Suite v1.2.0

**Dasharo variant**

Dasharo is not installed, I only booted into Dasharo Tools Suite

**Affected component(s) or functionality**

Dasharo HCL report generator

**Brief summary**

I generated an HCL report through Dasharo Tools Suite running on a PC Engines apu2e4. Two error messages appeared during the report generation (full output: [pc_engines_apu2e4_dts_hcl_report.log](https://github.com/Dasharo/dasharo-issues/files/12040355/pc_engines_apu2e4_dts_hcl_report.log)):

```
[...]
Getting hardware information. It will take a few minutes...
Sound card files are missing!                                      |
CRITICAL ERROR: cannot dump firmware                               |
/usr/sbin/dasharo-hcl-report: line 67: [: -ne: unary operator expected
/usr/sbin/dasharo-hcl-report: line 69: [: -eq: unary operator expected
###################################################################|

[OK]            PCI configuration space and topology
[...]
```

I do not know if these errors can be safely ignored or not.

**How reproducible**

I did not attempt to reproduce. I can try this again if requested.

**How to reproduce**

1. Prepare a USB stick with the USB bootable DTS v1.2.0 image from https://docs.dasharo.com/dasharo-tools-suite/releases/#features
2. Boot into the USB stick on a PC Engines apu2e4
3. Select the option to generate a Dasharo HCL report and upload the logs to Dasharo

**Expected behavior**

I did not expect to see an error message.

**Actual behavior**

I saw the error message pasted in the "Brief summary" section above.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment]
The PC Engines might have not been supported back then.
For sure, the latest v1.2.23 version can dump HCL report correctly.
