### ISSUE TITLE
DTS does not expose /sys/firmware/acpi/bgrt

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#470]
### The problem you're addressing (if any)

There is no  `/sys/firmware/acpi/bgrt` despite BGRT ACPI table is present.

### Describe the solution you'd like

Include necessary options in Linux kernel  to expose the entry

### Where is the value to a user, and who might that user be?

Unified testing of features in Dasahro validation, especially custom logo

**Comment by macpijan** [comment]
@TomaszAIR @artur-rs can we enable this option in the next DTS release?

**Comment by macpijan** [comment]
Maybe we will handle it in the next 3 days we will be working on the hotfix releases. This feature would be useful for testing the boot logo feature.

**Comment by macpijan** [comment]
Should be fixed in: https://github.com/Dasharo/meta-dts/pull/57

**Comment by pietrushnic** [comment]
@miczyg1 @macpijan I guess someone has to prove it was verified, and the issue should be closed. I'm not sure part of which release it was, but can't see information in [CHANGELOG](https://github.com/Dasharo/meta-dts/blob/main/CHANGELOG.md) nor reference to this issue.

**Comment by miczyg1** [comment]
v1.2.13-rc2 booted over iPXE  exposes `/sys/firmware/acpi/bgrt` so probably can be closed, but no idea which version enabled it

**Comment by macpijan** [comment]
None yet, we are still waiting for this release, which should happen the latest with the novacustom fixes (we will need to bump compatible versions for laptops as well).

**Comment by mkopec** [comment]
@macpijan v1.7.2 has been released, so I believe this issue can be closed, can you confirm?
