### ISSUE TITLE
Cannot build QEMU

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#472]
**Dasharo version**

https://docs.dasharo.com/variants/qemu_q35/building-manual/#procedure

**Dasharo variant**

QEMU

**Affected component(s) or functionality**

https://docs.dasharo.com/variants/qemu_q35/building-manual/#procedure

**Brief summary**

**How reproducible**

100%

**How to reproduce**

Follow linked build documentation

**Expected behavior**

Build succeds

**Actual behavior**

1. `git clone https://github.com/Dasharo/edk2-platforms.git -b 3323ed481d35096fb6a7eae7b49f35eff00f86cf` fails - there is no such revision (I just used default clone, without branch specification, instead)
2. Following the build instructions ends with: `/home/coreboot/coreboot/OvmfPkg/OvmfPkgX64.dsc(621): error F001: Pcd (gEfiMdeModulePkgTokenSpaceGuid.PcdPropertiesTableEnable) defined in DSC is not declared in DEC files referenced in INF files in FDF. Arch: ['X64']`

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by miczyg1** [comment]
Fixed in this PR: https://github.com/Dasharo/edk2/pull/70/files
