### ISSUE TITLE
Disabling early Boot DMA Protection doesn't work untill full shutdown 

### ISSUE THREAD

**Issue by Mixss** [Dasharo/dasharo-issues#473]
**Dasharo version**

msi_7d25_v1.1.1_serial

**Dasharo variant**

msi_7d25_v1.1.1_serial

**Affected component(s) or functionality**

Early Boot DMA Protection 

**Brief summary**

Changing early Boot DMA Protection option to disable and reseting doesn't affect the machine. Full power off and then power on after changing this option does.

**How reproducible**

probably always

**How to reproduce**

Basically this test: https://docs.dasharo.com/unified-test-documentation/dasharo-security/20L-early-boot-dma-protection/#edp002001-disable-early-boot-dma-protection-support
1. Have early Boot DMA Protection enabled
2. Go into the BIOS and disable early Boot DMA Protection.
3. Save changes and select *Reset* in main menu
4. Boot to ubuntu and run `cbmem -1 | grep DMA` 

**Expected behavior**

The output of the script doesn't contain `Successfully enabled VT-d PMR DMA protection`

**Actual behavior**

The output of the script contains `Successfully enabled VT-d PMR DMA protection`

**Screenshots**

**Additional context**

This was tested on [msi_z690](http://snipeit/hardware/289).
You can reset continuously, but it will still show that dma protection is enabled. This message will disappear after full shutdown and powering on 

**Solutions you've tried**
<!--(If applicable, any solutions or workarounds you've already

**Comment by miczyg1** [comment]
And what is the output of `cbmem -1 | grep DMA`?

**Comment by Mixss** [comment]
https://cloud.3mdeb.com/index.php/s/gMX8o3iZL9ir83B

**Comment by pietrushnic** [comment]
I wonder if such a test as grepping logs is sufficient. We at least should have a plan for extending tests with real hardware-based validation. @macpijan how do we plan to track bugs and feature requests in OSFV?

**Comment by macpijan** [comment]
@miczyg1 Have you tried with the most recent cbmem from upsteam perhaps?

**Comment by miczyg1** [comment]
> I wonder if such a test as grepping logs is sufficient. We at least should have a plan for extending tests with real hardware-based validation. @macpijan how do we plan to track bugs and feature requests in OSFV?

@pietrushnic Currently, we have no better way to investigate the firmware flow. In case of DMA the option only controls the behavior during firmware execution. The OS gives us no clue how and when VT-d was set up in firmware, because it reconfigures it per its own needs, so inspecting the VT-d registers will not confirm anything. Investigating coreboot logs is the best what we can do as of now.

> Have you tried with the most recent cbmem from upsteam perhaps?

@macpijan I have tried it just now and it seems to consistently return the logs from current boot. No wonder I haven't seen this issue before, because I was always compiling upstream cbmem...

**Comment by miczyg1** [comment]
Check on latest v1.1.2 and cbmem built from upstream, it works now. Closing
