### ISSUE TITLE
CI on PR to test changes

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#476]
### Describe the solution you'd like

CI workflow that would build a DTS image on pushed PR

### Where is the value to a user, and who might that user be?

Anyone working with DTS that could test the changes that are provided in given PR.

**Comment by artur-rs** [comment]
Linking related PR:
* https://github.com/Dasharo/meta-dts/pull/41

**Comment by artur-rs** [comment]
@TomaszAIR to be confirmed, that changes introduced here: https://github.com/Dasharo/meta-dts/blob/main/scripts/update_components.sh resolve the issue.

**Comment by TomaszAIR** [comment]
@artur-rs script mentioned by you rather resolve this issue https://github.com/Dasharo/dasharo-issues/issues/333

Here we provided documentation on how to produce image from `develop` branch that can be used for testing https://github.com/Dasharo/meta-dts/?tab=readme-ov-file#how-to-publish-a-develop-release

It may not do 100% what is described in this issue but maybe this is good enough?

**Comment by artur-rs** [comment]
@TomaszAIR Thanks. The documentation is clear and should be sufficient. As for CI tests on PR, this should be resolved here: https://github.com/Dasharo/dasharo-issues/issues/720

Closing.
