### ISSUE TITLE
Errors when trying to install Windows 11 on Z790 + RPL platform

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#480]
**Dasharo version**
v0.9.0

**Dasharo variant**
MSI Z-790 RPL

**Affected component(s) or functionality**
Windows 11 installation

**Brief summary**
Trying to install Windows 11 on MSI z790 + RPL platform ends with errors (screenshots), both manual and automatic installation. Tried multiple USB sticks, SSD drives and drive slots. The problem occurs both on Dasharo and newest official MSI firmware. Windows 11 is able to boot from drive on which it was previously installed on different platform on MSI firmware, but when the platform is flashed with Dasharo firmware Windows 11 refuses to boot and gives "inaccesible boot device" error (screenshot).

**How reproducible**
100%

**How to reproduce**

1.  Plug in bootable USB stick with Windows 11
2.  Power on the machine
3.  Enter boot menu and select previously plugged in USB drive

**Expected behavior**
Windows 11 installation should start without errors.

**Actual behavior**
After partitioning the drive, trying to install the OS ends with an error message.

**Screenshots**
![Screenshot from 2023-08-08 18-45-53](https://github.com/Dasharo/dasharo-issues/assets/43601433/cc0e0ed0-f02a-4126-b53d-46cdffd1d327)
![Screenshot from 2023-08-18 14-48-00](https://github.com/Dasharo/dasharo-issues/assets/43601433/b0a1e81e-2161-41ea-a770-0f3ae998e20c)
![image-20230810-110346](https://github.com/Dasharo/dasharo-issues/assets/43601433/5348e912-3394-4f3f-a088-070ba6148b1c)
![image-20230810-105844](https://github.com/Dasharo/dasharo-issues/assets/43601433/48d2c95b-13ef-456e-8166-8a3deab1b962)
![Screenshot from 2023-08-24 10-37-51](https://github.com/Dasharo/dasharo-issues/assets/43601433/80d5e510-d698-48d6-a29b-fd6a10457b81)

**Comment by miczyg1** [comment]
https://github.com/Dasharo/coreboot/pull/380/files
