### ISSUE TITLE
No audio playback on Ubuntu and Windows 11 on MSI Z690-a ddr4 board

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#483]
**Dasharo version**
v1.1.2

**Dasharo variant**
MSI Z690-a ddr4

**Affected component(s) or functionality**
Audio

**Brief summary**
No audio playback on Ubuntu and Windows 11. Tested on two different pairs of headsets. System does recognize that the device is plugged into the audio jack.

**How reproducible**
100%

**How to reproduce**

1. Plug the headset in
2. Play audio

**Expected behavior**
Audio plays through the headset

**Actual behavior**
Output is silent.

**Comment by miczyg1** [comment]
I have already flashed v1.1.2 on m hoem machine and couldn't reproduce the bug on Windows 11. Only Ubuntu actually didn't give any audio output on the rear and front audio jacks (mic did work though).

**Comment by miczyg1** [comment]
Small update:

When I tested Windows and it worked, I have booted straight to Ubuntu after a reboot.

But when I powered off, powred on and then booted straight to Ubuntu, audio playback worked on both front and read audio jacks.

So the issue seems to be reproducible after reboot only and probably from different OSes (one OS driver does something what second OS driver doesn't like). Not sure if we can fix that in the firmware, but maybe...

**Comment by miczyg1** [comment]
Maybe this will help somehow: https://github.com/Dasharo/coreboot/pull/388 (we can test it later and eventually release as v1.1.3 if it works)

**Comment by miczyg1** [comment]
Nah, resetting the codec does not help. Also no errors in dmesg whatsoever.

I noticed that Ubuntu doesn't get the playback sound when rebooted from Windows to Ubuntu. Vice versa may not trigger the bug though.

**Comment by miczyg1** [comment]
I had to look for the audio verbs in the vendor BIOS images. It seems only the pin configs are extractable from Linux, some vendor widget verbs cannot be obtained that way...

Now it works on my MSI PRO Z690-A DDR4 no matter how many reboots between Windows and Ubuntu I do.

**Comment by zirblazer** [comment]
I recall that for the original 1.0.0 release a year ago or so I found this exact same issue about headphones not working after a reboot and mentioned it in chat but failed to reproduce, so I never formally reported it. I didn't thought about the possibility of it happening not while rebooting the same OS, but when rebooting system and switching OS. Is likely that I had no sound after rebooting from one OS to other and completely missed that detail when trying to reproduce. Congratulations on the find and fix, I recall being frustrated about not being able to figure out this one.

**Comment by miczyg1** [comment]
> I recall being frustrated about not being able to figure out this one.

Happens to the best of us :)

**Comment by filipleple** [comment]
currently on z790p v0.9.1 audio capture doesn't work, neither for mic in nor line in, for both Ubuntu and Windows

**Comment by miczyg1** [comment]
Checked z690-ddr4-adl on Windows and Qubes OS, bot hare working as intended. But one thing that Windows gives is a pop-up from Realtek Audio driver that tells you to choose which device you plugged in, when hot plugging the mic/headphones. But when pressed OK on these pop-ups, the audio input and output appeared and I did a mic test online with a playback and it worked. For Qubes it also worked.

Thus I consider these test results invalid and subject to recheck

**Comment by miczyg1** [comment]
Also checked Z790-P to be sure and both Windows and Ubuntu work. Window has those pop-ups mentioned before. Ubuntu has no such problems, except one case: hotplugging the jacks does not make Ubuntu detect the input and output automatically on latest kernel (6.6.x) and in this case it doesn't work after hotplugging, on stock kernel (6.2.x) it is working automatically. Such results on latest kernel can happen, test should not be conducted on Ubuntu using latest kernel, unless it is absolutely necessary, like in case of fTPM bug. But the kernel latest should be used only for TPM test in such case, not for everything.

**Comment by zirblazer** [comment]
> Also checked Z790-P to be sure and both Windows and Ubuntu work. Window has those pop-ups mentioned before. Ubuntu has no such problems, except one case: hotplugging the jacks does not make Ubuntu detect the input and output automatically on latest kernel (6.6.x) and in this case it doesn't work after hotplugging, on stock kernel (6.2.x) it is working automatically.

Sounds (Pun intended) like a regression to me. Isn't this the type of thing that should be reported to the Linux Kernel guys?
Also, it could, or not, be a Firmware issue depending on whenever this is reproducible on MSI. But even if confirmed to be reproducible thus 100% a Kernel issue, then you get to the whole git bisect thing to see at which commit things went bad...

**Comment by mkopec** [comment]
Could also be a Ubuntu patch, they tend to maintain their fixes downstream, so a mainline kernel won't have them

**Comment by miczyg1** [comment]
> Sounds (Pun intended) like a regression to me. Isn't this the type of thing that should be reported to the Linux Kernel guys?

The kernel latest is not an officially supported kernel by Canonical, so they probably won't care. It also isn't clear why it doesn't work. Maybe some options which should be selected, weren't selected in this particular kernel build.., No idea.

**Comment by macpijan** [comment]
@BeataZdunczyk This one should be closed, if it does not happen on Ubuntu release kernel.
