### ISSUE TITLE
IME HAP disable doesn't work with Z790

### ISSUE THREAD

**Issue by renehoj** [Dasharo/dasharo-issues#487]
**Dasharo version**
v0.9.0

**Dasharo variant**
Workstation

**Affected component(s) or functionality**
The IME HAP disable option 

**Brief summary**
With IME HAP disable option selected the mei0 device is available to the OS.

**How reproducible**
100% reproducibility

**How to reproduce**

1. Select the IME HAP disable option in the UEFI menu
2. load the OS
3. check /sys/class/mei/mei0

**Expected behavior**
/sys/class/mei wouldn't exist or be empty.

**Comment by renehoj** [comment]
I noticed that IME was updated, does the new version has the same HAP offset as the old version?

Is the Z690 working with v16.1.30.2255?

**Comment by miczyg1** [comment]
@renehoj both Z690 and Z790 have been tested with HAP disable and it worked.

Check with cbmem if the coreboot log does not contain the following: `Host doesn't have write access to Descriptor Region`. If it does, then your flash descriptor is locked. It could happen when you used DTS to perform initial deployment. MSI seems to have started to lock the descriptor and DTS has no way to deal with it, so it couldn't flash our unlocked descriptor. Try to use the FLashBIOS button with our release image and then retry to set the HAP bit via setup.

**Comment by renehoj** [comment]
@miczyg1 Yes, I used the DTS for the initial deployment, and you are also right about the log error.

Using the bios flash solved the issue.

**Comment by mlario** [comment]
> @renehoj both Z690 and Z790 have been tested with HAP disable and it worked.
> 
> Check with cbmem if the coreboot log does not contain the following: `Host doesn't have write access to Descriptor Region`. If it does, then your flash descriptor is locked. It could happen when you used DTS to perform initial deployment. MSI seems to have started to lock the descriptor and DTS has no way to deal with it, so it couldn't flash our unlocked descriptor. Try to use the FLashBIOS button with our release image and then retry to set the HAP bit via setup.

Hi. Have same issue. Could you please give more detail about flashing with FlashBIOS? 

By release image you meant Dasharo tools USB image as found here: https://github.com/Dasharo/meta-dts/releases


Or you meant to somehow extract actual bios ROM and write it down on fat32 formatted USB and rename it to MSI.ROM and then run FlashBIOS?

If so where to get actual bios ROM for MSI Z790-P DDR5 WIFI?

I tried simply inserting DTS usb and running flashBios and LED is blinking already for 1 hour without finishing....

**Comment by renehoj** [comment]
You need to use the usb port and the button on the back panel marked for firmware flashing.

From: https://docs.dasharo.com/unified/msi/recovery/#intro
Format an empty USB drive with FAT32 filesystem.
Place Dasharo release binary or official MSI binary on the drive's root directory and name it MSI.ROM.
Put the drive in the rear USB 2.0 port marked as FlashBIOS.
Be sure that your machine is powered off (ATX supply must be still connected).
Press the FlashBIOS button near the FlashBIOS port.
After a few seconds the machine should power on the ATX supply and begin flashing (the red diode will be blinking).
Wait approximately 5 minutes for the process to finish. The board will automatically restart and boot.

Here is a video: https://www.youtube.com/watch?v=iTkXunUAriE

**Comment by mlario** [comment]
> Dasharo release binary

Thanks.

Sorry for stupid question, but where do I get Dasharo release binary?

Previously I used DTS usb to flash the bios. It uses my purchased keys to get up-to-date bios and from my understanding this binary is deleted after successful bios flash

Is there repository where I can dasharo binaries for my motherboard?

**Comment by renehoj** [comment]
I only think the v0.9.0 release is available for user with a paid subscription, I think v1.0 is the going to be the public release.

If you have a subscription, you should have gotten an e-mail with download links, else try and contact support about how to get the rom file.

**Comment by mlario** [comment]
> I only think the v0.9.0 release is available for user with a paid subscription, I think v1.0 is the going to be the public release.
> 
> If you have a subscription, you should have gotten an e-mail with download links, else try and contact support about how to get the rom file.

OK, will contact support for binary rom

Thanks!

**Comment by pietrushnic** [comment]
@mlario, your binary will, and any other subscriber will be password protected behind this link.`https://cloud.3mdeb.com/index.php/s/{download_key}`. If you buy a subscription, you should have both `download_key` and `password` in your inbox.

**Comment by mlario** [comment]
> @mlario, your binary will, and any other subscriber will be password protected behind this link.`https://cloud.3mdeb.com/index.php/s/{download_key}`. If you buy a subscription, you should have both `download_key` and `password` in your inbox.

great, thanks!

**Comment by mlario** [comment]
OK, I can confirm that on MSI z790-p flashing using FlashBios option works well and allows successful deactivation of intel me with hap bit
