### ISSUE TITLE
Documentation and DTS Enhancements to Address Flashing with Locks and Facilitate Secure Recovery

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#489]
**Dasharo version**

v1.1.1 (issue initially observed), also relevant to other versions where flashing with locks is possible.

**Dasharo variant**

MSI Z690A DDR4

**Affected component(s) or functionality**

- Documentation regarding flashing procedures
- DTS functionality allowing flashing with locks enabled
- Recovery path post flashing with locks enabled

**Brief summary**

Users updating to Dasharo version v1.1.1 and v1.1.2 through DTS v1.2.0 and 1.2.6 have encountered a warning message during the boot process, indicating "RW firmware unable to verify keyblock." with various errors 0x3, 0x13. This issue has brought to light the gaps in our documentation concerning the flashing process with locks enabled and the lack of a reliable recovery path (refer to #442 ).

**How reproducible**

100% ?

**How to reproduce**

Steps to reproduce the behavior (hypothesis best on #442 ):

1. Update Dasharo to version v1.1.2 using DTS v1.2.6 Without disabling the BIOS lock.
2. Reboot the system post-update.
3. Observe the warning message during the boot process.

**Expected behavior**

Users should be able to update Dasharo without encountering warning messages during the boot process. The documentation should provide clear guidelines on disabling locks before flashing, and DTS should prevent flashing when locks are enabled to ensure a smooth and secure update process.

**Actual behavior**

The update process does not inhibit flashing with locks enabled, leading to a warning message during the boot process and potentially leaving the system in a compromised state. The existing documentation does not offer sufficient guidance on the consequences of flashing with locks and the recovery process.

**Screenshots**

![](https://user-images.githubusercontent.com/1071894/238950366-56f5f73d-29af-42ac-8fa6-6c4298ebf08b.jpg)

**Additional context**

This issue has raised concerns about the security implications and the user experience, emphasizing the need for a robust recovery guide and enhanced DTS functionalities to prevent such occurrences in the future.

**Solutions you've tried**

* Updating to a newer Dasharo version (v1.12) has resolved some users' issues, but it is not a universal solution.
* Discussions have been initiated to enhance the DTS, prevent flashing with locks enabled, and develop comprehensive documentation to guide users appropriately.

**Comment by macpijan** [comment]
> Update Dasharo to version v1.1.2 using DTS v1.2.6 Without disabling the BIOS lock.

Maybe we should focus on that aspect, why are we using older DTS to upgrade to this v1.1.2 release and move documentation and DTS in this direction. 

This problem of locks is already addressed in the latest DTS (1.2.8: https://docs.dasharo.com/dasharo-tools-suite/releases/#v128-2023-09-06)

**Comment by pietrushnic** [comment]
@macpijan I wrote that from a memory person who reported that Dasharo Primer Support used the most recent one, which was 1.2.8. Please read #442 why this issue was even created.

**Comment by DaniilKl** [comment]
Just have been analyzing the situation and got to following conclusions:
* Newest DTS does have features to prevent flashing firmware and it works just fine;
* Some section in Dasharo is needed for those who are using old DTS or flashing it manuaolly via `flashrom` and got this problem, so they will be able to cope with it.
Just looking for an appropriate section in docs.

**Comment by DaniilKl** [comment]
Ok, seems like in [Deployment section](https://docs.dasharo.com/osf-trivia-list/deployment/#flashrom)  similar topics are being explained. Put this note there then.

**Comment by pietrushnic** [comment]
> Some section in Dasharo is needed for those who are using old DTS or flashing it manuaolly via flashrom and got this problem, so they will be able to cope with it.

There should be a clear statement that old releases are not supported.

**Comment by Firminator** [comment]
However at that point in time when the issue was reported I think DTS v1.1.1 was the latest available DTS version for non-Dasharo subscribers. The solution would be to raise the non-subscriber version to a newer version that has this issue fixed, AND implement a warning that older versions are not supported anymore.

**Comment by TomaszAIR** [comment]
@pietrushnic do you think that changes from https://github.com/Dasharo/docs/pull/793/files correctly address this issue? 

> There should be a clear statement that old releases are not supported.

This is already done in https://docs.dasharo.com/dasharo-tools-suite/releases/

**Comment by TomaszAIR** [comment]
@pietrushnic maybe we should just leave only button for latest release then? https://docs.dasharo.com/dasharo-tools-suite/releases/ And add info that using older versions is not recommended as it may lead to bricking device, e.g. by using version without checks on flash lock?

@DaniilKl could you please add needed changes to

**Comment by pietrushnic** [comment]
> @pietrushnic maybe we should just leave only button for latest release then? https://docs.dasharo.com/dasharo-tools-suite/releases/ And add info that using older versions is not recommended as it may lead to bricking device, e.g. by using version without checks on flash lock?

That would be the solution IMHO. We then can see what will happen. Hopefully, it will not confuse users even more.

**Comment by TomaszAIR** [comment]
@DaniilKl please, let's do that

**Comment by DaniilKl** [comment]
@TomaszAIR, @pietrushnic added changes here 89be95e61e5c1be633dfa44e57dad488f62269d6, check please the commit and verify whether I have understood you right.
