### ISSUE TITLE
Missing picture to KGPE-D16 TPM header

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#49]
**Dasharo version**

N/A

**Dasharo variant**

N/A

**Affected component(s) or functionality**

Documentation

**Brief summary**

TPM header picture is not in documentation tree.

**How reproducible**

Always

**How to reproduce**

Check https://docs.dasharo.com/variants/asus_kgpe_d16/setup/#tpm and compare to [code](https://github.com/Dasharo/docs/blob/master/docs/variants/asus_kgpe_d16/setup.md?plain=1#L104)

**Expected behavior**

Missing picture should be visible in documentation

**Actual behavior**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Solutions you've tried**

N/A

**Comment by miczyg1** [comment]
https://github.com/Dasharo/docs/pull/90
