### ISSUE TITLE
The DTS just hang, without stop, if I choose option 1 or 2. MSI PRO Z690-A Wifi (DDR4) and MSI PRO Z790-P WIFI 

### ISSUE THREAD

**Issue by dhajdu83** [Dasharo/dasharo-issues#491]

**Comment by zirblazer** [comment]
You said that you tried with both Ubuntu 22.04 and 20.04. However, DTS is a LiveCD and is intended to be used that way. So what did you tried Ubuntu for, then? To write DTS to an USB Flash Drive? The way you explained it makes me thing that you tried to execute it from within Ubuntu, which would be wrong.

Also, are you already running Dasharo v1.1.1, or were you trying to install it?

**Comment by dhajdu83** [comment]
> You said that you tried with both Ubuntu 22.04 and 20.04. However, DTS is a LiveCD and is intended to be used that way. So what did you tried Ubuntu for, then? To write DTS to an USB Flash Drive? The way you explained it makes me thing that you tried to execute it from within Ubuntu, which would be wrong.
> 
> Also, are you already running Dasharo v1.1.1, or were you trying to install it?

Thanks for your message.
I fleshed the downloaded image onto a 32GB USB stick. I fleshed 1 time with Etcher and more times with the dd command. 
```
gzip -cdk dts-base-image-v1.2.8.wic.gz | \
sudo dd of=/dev/sda bs=16M status=progress conv=fdatasync
```
After I inserted the USB stick into the (FLASH BIOS) USB slot, in my device. After I booted from the USB stick.


![20230917_085405](https://github.com/Dasharo/dasharo-issues/assets/29186365/e72e5ef4-3d47-4ead-b111-6cca9cd959cf)

**Comment by dhajdu83** [comment]
I have a MSI P790-A (with a Intel i7) too. I have there exactly same problem. (I updated the original text.)

**Comment by miczyg1** [comment]
@dhajdu83 could you also share the `/var/local/dts-err.log` from the DTS stick when the above issue occurs?

**Comment by miczyg1** [comment]
I hope so. If not, then hard shutdown and put the DTS stick to another machine, mount it and grab the files

**Comment by miczyg1** [comment]
Ahh no matter what I do I cannot reproduce it... for me it takes maybe 2 minutes for the HCL to finish

**Comment by pietrushnic** [comment]
Please note following procedure is based on report from [Dwizzzle on Twitter](https://twitter.com/dwizzzleMSFT/status/1715186314080043463):

![F82Q3KlbAAAq6i0](https://github.com/Dasharo/dasharo-issues/assets/1071894/fada9375-02e0-4aa7-9ebd-a8d9c8bd2b67)

Okay, to summarize the approach that we may have to debug this problem:
- try what @miczyg1 mentioned on Twitter:  `/bin/bash -x dasharo-hcl-report`
- after hand, try Ctrl+C and look for: `/var/local/dts-err.log`, `logs/acpidump.log` and `logs/acpidump.err.log`
- if the above doesn't work, reboot and enable SSH before, then start the procedure, and if it hangs ssh to the machine and retrieves logs

Correct debugging steps depend on the step at which DTS is. The initial report for this problem has much more advanced progress, so it may be something different going on.

**Comment by miczyg1** [comment]
The logs can be also access hopefully on the stick mounted in another device (without booting DTS). THey should be placed in `/logs` and the `dts-root` partition. Analogically with `/var/local/dts-err.log`

**Comment by pietrushnic** [comment]
This bug is straightforward to fix. As reported by @WiktorG351 problem is [here](https://github.com/Dasharo/meta-dts/blob/develop/meta-dts-distro/recipes-dts/reports/dasharo-hcl-report/dasharo-hcl-report#L300), there should be `|` instead of `&&`. polymechanos confirmed on the matrix that this solved the issue of hanging.

**Comment by WiktorG351** [comment]
@pietrushnic I think this is something different, because in this issue the script hangs well before trying to remove the mac adress from the logs. Also, I checked on the `1.2.8` version and the script doesn't contain the `&&` instead of `|` mistake (it somehow must have found its way into the `develop` branch of `meta-dts`).

I am trying to reproduce this issue, but no success so far - might try with an older firmware version...

**Comment by pietrushnic** [comment]
@WiktorG351, at least the fix you suggested helped someone on the Dasharo matrix, but as you said, it really may be a different bug.

**Comment by WiktorG351** [comment]
@dhajdu83 hi, I've been trying to reproduce this issue, but have had no success so far:
```
Last login: Thu Mar 21 14:34:57 2024 from 192.168.4.158
root@DasharoToolsSuite:~# cd /
root@DasharoToolsSuite:/# cat /usr/lib/os-release 
ID=dts-distro
NAME="Dasharo Tools Suite"
VERSION="1.2.8 (kirkstone)"
VERSION_ID=1.2.8
PRETTY_NAME="Dasharo Tools Suite 1.2.8 (kirkstone)"
DISTRO_CODENAME="kirkstone"
root@DasharoToolsSuite:/# ./usr/sbin/dasharo-hcl-report
./usr/sbin/dasharo-hcl-report: line 61: [: =: unary operator expected
./usr/sbin/dasharo-hcl-report: line 143: [: =: unary operator expected
###################################################################|

./usr/sbin/dasharo-hcl-report: line 256: [: =: unary operator expected
./usr/sbin/dasharo-hcl-report: line 281: [: =: unary operator expected
./usr/sbin/dasharo-hcl-report: line 291: [: =: unary operator expected
root@DasharoToolsSuite:/# tar -xzf logs.tar.gz 
root@DasharoToolsSuite:/# ls logs
 acpi		      biosdecode.log	 cpuinfo.log	        dmidecode.log	        gpio_cnl.h	     intelmetool.err.log   ioports.err.log   msrtool.err.log	 result		       tpm_version.err.log
 acpidump.err.log     cbmem.err.log	 decode-dimms.err.log   ectool.err.log	        gpio_lbg.h	     intelmetool.log	   ioports.log	     msrtool.log	 rom.bin	       tpm_version.log
 acpidump.log	      cbmem.log		 decode-dimms.log       ectool.log	        gpio_snr.h	     intelp2m.err.log	   lspci.err.log     nvramtool.err.log	 superiotool.err.log
 amt-check.err.log   'codec#*'		 dmesg.err.log	        flashrom_read.err.log   i2cdetect.err.log    intelp2m.log	   lspci.log	     nvramtool.log	 superiotool.log
 amt-check.log	     'codec#*.err.log'	 dmesg.log	        flashrom_read.log       i2cdetect.log	     inteltool.err.log	   lsusb.err.log    'pin_hw*'		 touchpad.err.log
 biosdecode.err.log   cpuinfo.err.log	 dmidecode.err.log      gpio_apl.h	        input_bustypes.log   inteltool.log	   lsusb.log	    'pin_hw*.err.log'	 touchpad.log
root@DasharoToolsSuite:/# 
```
i have tried with a couple versions of firmware, and the report always completes. Have You tried using a newer version of DTS?

**Comment by artur-rs** [comment]
No response in a long time, closing
