### ISSUE TITLE
Extending Subscription expiration date / cancelation for DES

### ISSUE THREAD

**Issue by Stanislaw-bnk** [Dasharo/dasharo-issues#494]
### The problem you're addressing (if any)

A request to implement a feature that would allow us to easily extend a subscription's expiration date for our subscribers or cancel it.

### Describe the solution you'd like

Expand the script to read the spreadsheet and extend the validity of the links on cloud.

**Comment by macpijan** [comment]
@TomaszAIR Does it belong here, or request is tracked in the tool's repo and shall be closed here? If this is the case, please close it here.

**Comment by TomaszAIR** [comment]
Request was tracked internally. This should be closed
