### ISSUE TITLE
Inability to install Windows 11 on Protectli VP4650

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#495]
**Dasharo version**
v1.0.19

**Dasharo variant**
Protectli

**Affected component(s) or functionality**
Windows 11 installation

**Brief summary**
After installation, Windows 11 does not boot, but instead the recovery popup appears. After restarting the machine, the OS tries to repair itself, but then goes into recovery again. Tested on both manual and automatic installation.

**How reproducible**
100%

**How to reproduce**

1. Plug bootable USB stick with Windows 11 into the DUT
2. Perform the installation

**Expected behavior**
Windows 11 boots normally after installation.

**Actual behavior**
Recovery popup appears after installation.

**Screenshots**
![Screenshot from 2023-08-30 14-22-51](https://github.com/Dasharo/dasharo-issues/assets/43601433/bf782853-5d7b-4f77-8e93-3fdbe803f056)

**Solutions you've tried**
Multiple drives and USB sticks, bot automatic and manual installation.

**Comment by macpijan** [comment]
We've been able to install Windows 11 23H2 with 1.2.0 release.
