### ISSUE TITLE
Some RPL-S CPUs ( 0xB06F2 (RPL-S C0) or 0xB06F5 (RPL-S H0)) have problem with booting on v1.1.2

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#496]
**Dasharo version**

v1.1.2

**Dasharo variant**

Desktop MSI PRO Z690-A

**Affected component(s) or functionality**

Boot process

**Brief summary**

If the platform does not boot with RPL-S CPU and the CPUID of the CPU is either 0xB06F2 (RPL-S C0) or 0xB06F5 (RPL-S H0, datasheet has a bug), then it needs new version, v1.1.3 that will contain the fix.
(https://edc.intel.com/content/www/us/en/design/products/platforms/details/raptor-lake-s/13th-generation-core-processors-datasheet-volume-1-of-2/005/cpuid/)

**How reproducible**

100%

**How to reproduce**

Boot platform

**Expected behavior**

Platform booting without issues.

**Actual behavior**

Boot process hang.

**Screenshots**

**Additional context**

Dasharo Primer Support member reported the problem.

**Solutions you've tried**

**Comment by miczyg1** [comment]
Most likely Z790-P will also be affected.

**Comment by miczyg1** [comment]
New release will be based on 4.21 which does not have this issue.
