### ISSUE TITLE
Controlling keyboard illumination (brightess and on/off) does not work

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#498]
**Dasharo version**
v1.7.0

**Dasharo variant**
Novacustom ns5x/7x ADL

**Affected component(s) or functionality**
Keyboard illumination

**Brief summary**
Trying to set keyboard brightness level or turning it on/off does not affect the actual illumination, despite correct values being displayed in the OS. The funcionality is affected on Ubuntu 22.04, it works fine under Windows 11.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Ubuntu 22.04.
3. Try to set keyboard brightness level or turn the illumination on/off using keyboards shortcuts.

**Expected behavior**
Brightness level changes, keyboard illumination turns on/off.

**Actual behavior**
Keyboard illumination brightness level stays the same and can not be turned on/off.

**Comment by mkopec** [comment]
I guess https://github.com/Dasharo/ec/pull/49/files will help here. I need to test on hardware.

**Comment by mkopec** [comment]
reworked the backlight code in:
-  https://github.com/Dasharo/ec/pull/50
- https://github.com/Dasharo/coreboot/pull/419

**Comment by macpijan** [comment]
Fixed in 1.5.1/1.7.1

**Comment by Pace17881** [comment]
Does not work for me. Using:
* NV41PZ with current firmware/ec 1.7.1
* Debian trixie
* current kernel 6.6.3
* kde
![keyboardillu](https://github.com/Dasharo/dasharo-issues/assets/24521835/3795fcf9-21c0-4a15-88e6-3413b7446470)
See screenshot: Missing keyboard control
