### ISSUE TITLE
Reset by F9 sets battery thresholds to 0

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#499]
**Dasharo version**
v1.7.0

**Dasharo variant**
Novacustom nv41 ADL

**Affected component(s) or functionality**
Reset to defaults by F9 in the firmware

**Brief summary**
Resetting power settings to default by using the F9 key results in battery thresholds set to 0 (should be 95 and 98). With thresholds set to 0, the laptop can not be charged.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT
2. Enter BIOS setup
3. Go into Dasharo System Features -> Power Management Options
4. Press F9 key to reset the settings to default

**Expected behavior**
Battery thresholds are set to 95 and 98.

**Actual behavior**
Battery thresholds are set to 0.

**Comment by mkopec** [comment]
https://github.com/Dasharo/DasharoModulePkg/pull/35

**Comment by johanes2115** [comment]
@mkopec the issue does not occur in the newest binaries.
