### ISSUE TITLE
Power button suspend not working as expected

### ISSUE THREAD

**Issue by Mixss** [Dasharo/dasharo-issues#500]
**Dasharo version**
v1.5.0

**Dasharo variant**

Novacustom ns70mu tgl

**Affected component(s) or functionality**

Keyboard lighting

**Brief summary**
(Ubuntu 22.04): After clicking the power button screen goes dark, but the keyboard stays lit up. For comparison, when the lid is closed keyboard goes dark

**How reproducible**
100%

**How to reproduce**

1. Boot Ubuntu and log in
2. Press power button

**Expected behavior**
Laptop goes fully to suspend

**Actual behavior**
Keyboard stays lit up

**Comment by mkopec** [comment]
what is the power button configured to do in Ubuntu?

**Comment by Mixss** [comment]
Power button is set to suspend.

**Comment by Mixss** [comment]
btw I think #504 also covers this issue

**Comment by mkopec** [comment]
Yes, I think this is a duplicate of https://github.com/Dasharo/dasharo-issues/issues/504 . Closing.
