### ISSUE TITLE
Permanent keyboard illumination after cold boot fails: keyboard light level is not saved correctly

### ISSUE THREAD

**Issue by Mixss** [Dasharo/dasharo-issues#501]
**Dasharo version**

v1.5.0

**Dasharo variant**
Novacustom nv41mz tgl

**Affected component(s) or functionality**

Keyboard illumination

**Brief summary**
ermanent keyboard illumination after cold boot fails: keyboard light level is not saved correctly

**How reproducible**

100%

**How to reproduce**

1.  Set the level of keyboard light level
2.  Disconnect the battery
3.  Boot

**Expected behavior**

After booting up the keyboard light level is the same as before battery disconnection.

**Actual behavior**

After booting up the keyboard light level is different

**Comment by mkopec** [comment]
I guess we disabled the CMOS option backend, so coreboot can't restore the values from CMOS @miczyg1 

The proper solution is to store these values in the EC flash.

**Comment by Mixss** [comment]
> Which battery is disconnected?

Laptop's battery

**Comment by macpijan** [comment]
Fixed in 1.5.1/1.7.1

**Comment by macpijan** [comment]
Fixed in 1.5.1/1.7.1
