### ISSUE TITLE
DTS on network boot fails to boot

### ISSUE THREAD

**Issue by Mixss** [Dasharo/dasharo-issues#502]
**Dasharo version**

v1.5.0

**Dasharo variant**

Novacustom ns70mu tgl

**Affected component(s) or functionality**

DTS network boot

**Brief summary**

After selecting DTS in Dasharo Network Boot Menu, it seems that it is being downloaded, but it stops at ~50% and then it goes back to the Network Boot Menu

**How reproducible**

100%

**How to reproduce**

1.  Go into Network Boot Menu
2.  Select DTS

**Expected behavior**

DTS boots

**Actual behavior**

DTS seems that it is being downloaded, but it stops at ~50% and then it goes back to the Network Boot Menu

**Comment by mkopec** [comment]
works on my end

**Comment by mkopec** [comment]
@johanes2115 it would be great if you could confirm if this issue still occurs on the latest bins.

**Comment by macpijan** [comment]
We've not been able to replicate this issue anymore since then.
