### ISSUE TITLE
system76_ectool in DTS fails to flash

### ISSUE THREAD

**Issue by Ferenc-** [Dasharo/dasharo-issues#503]
**Dasharo version**
`1.4.0` on NS 51 TGL. Latest DTS booted via iPXE

**Dasharo variant**
`1.4.0` on NS 51 TGL.

**Affected component(s) or functionality**
`system76_ectool`

**Brief summary**
In a experimental attempt to fix the annoying constant fan crackling, attemting to downgrade the ec firmware, to the official v1.3.0.

**How reproducible**
Currently all the time, but interestingly this has worked before.

**How to reproduce**

1. Boot into DTS.
2. Enter shell `9`
3. Download 1.3.0 EC firmware with `wget https://3mdeb.com/open-source-firmware/Dasharo/novacustom_ns5x/v1.3.0/novacustom_ns5x_v1.3.0_ec.rom`
4. `system76_ectool flash novacustom_ns5x_v1.3.0_ec.rom`

**Expected behavior**
Flashing works.

**Actual behavior**
```
thread 'main' panicked at 'called `Option::unwrap()`on a `None` value', src/main.rs:145:50
```

**Screenshots**
![image](https://github.com/Dasharo/dasharo-issues/assets/6553695/703732cd-2505-4c28-ad03-ac70047f3981)

**Additional context**
There were times when this downgrading worked. Might be related to https://github.com/Dasharo/dasharo-issues/issues/333?

**Solutions you've tried**
The exact same thing worked before. So something here is nondeterministic.

**Comment by miczyg1** [comment]
The system76_ectool underwent some changes which makes it incompatible with older EC firmware builds IIRC. YOu would have to use an older DTS version to flash old EC versions. @mkopec please confirm

**Comment by mkopec** [comment]
@miczyg1 no, it looks like parsing the binary looking for board / version magic strings fails. Need to reproduce on actual hardware.

**Comment by miczyg1** [comment]
@Ferenc-  possibly still on proprietary EC firmware?

**Comment by mkopec** [comment]
@Ferenc- Could not reproduce on an NS51MU unit. Where did you obtain the v1.4.0 EC binary you are trying to downgrade from?

**Comment by Ferenc-** [comment]
> @Ferenc- Could not reproduce on an NS51MU unit. Where did you obtain the v1.4.0 EC binary you are trying to downgrade from?

It's from here: https://3mdeb.com/open-source-firmware/Dasharo/novacustom_ns5x_tgl/v1.4.0/novacustom_ns5x_tgl_ec_v1.4.0.rom

And at first it worked (non-reproducible), but now it doesn't work anymore (reproducible), so it might take a number of back-and-forth?

**Comment by Ferenc-** [comment]
But in any case if I boot into DTS and try to now down, but upgrade then it tells me that there is no update, so that should mean that I am on the latest, plus `system76_ectool info` also says so.

**Comment by mkopec** [comment]
hmm that is the same firmware I tested downgrading from. I am wondering if the `wget` command is failing silently on your device for some reason, though it works on my side. Can you run `sha256sum novacustom_ns5x_v1.3.0_ec.rom` after the `wget` and post the result here?

**Comment by Ferenc-** [comment]
Now it's non-reproducible again. In any case next time it is I will check the `sha256sum` for sure.
I think this can be closed for the time being and re-open when resurfaces.
Perhaps as a future improvement idea is to add some basic integrity check on the input, if the input rom can easily get corrupted?
