### ISSUE TITLE
Auto Boot Time-out do not show error for `-` value

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#505]
**Dasharo version**
v1.1.0

**Dasharo variant**
protectli_vp4670

**Affected component(s) or functionality**

`Auto Boot Time-out` in Dasharo Menu

**Brief summary**

If we press a key with a value that is not a digit, two red exclamation marks `!!` appear at the bottom of the window. It is still waiting for a numerical value.

If we press `-`, it exits the value entry, does not wait for the number to be entered.
In addition, I do not ask whether to save the value, even if we have previously changed it to another numerical value.

**How reproducible**

Always

**How to reproduce**

Press `-` where you enter the `Auto Boot Time-out` value. 

**Expected behavior**

If we press `-`, two red exclamation marks `!!` appear at the bottom of the window. It is still waiting for a numerical value. 

**Actual behavior**

If we press `-`, it exits the value entry, does not wait for the number to be entered.
In addition, I do not ask whether to save the value, even if we have previously changed it to another numerical value.

**Screenshots**

![image](https://github.com/Dasharo/dasharo-issues/assets/14311655/43b65b8b-41a3-4fe9-9365-6063c2af34ff)
If we press a key with a value that is not a digit (and not `-` because of a bug), two red exclamation marks `!!` appear at the bottom of the window. It is still waiting for a numerical value.

**Comment by mkopec** [comment]
i guess the `-` is treated as a negative sign? Question is how to enforce positive integers in the form

**Comment by filipleple** [comment]
@mkopec if I understand correctly, positive integers are enforced by making the opcode numeric and forcing range between 0 and 65535 in BootMaintenanceManagerCustomizedUiSupport.c here
```
BmmCreateTimeOutMenu (
  IN EFI_HII_HANDLE              HiiHandle,
  IN VOID                        *StartOpCodeHandle
  )
{
  HiiCreateNumericOpCode (
    StartOpCodeHandle,
    (EFI_QUESTION_ID) FORM_TIME_OUT_ID,
    VARSTORE_ID_BOOT_MAINT,
    BOOT_TIME_OUT_VAR_OFFSET,
    STRING_TOKEN(STR_NUM_AUTO_BOOT),
    STRING_TOKEN(STR_HLP_AUTO_BOOT),
    EFI_IFR_FLAG_CALLBACK,
    EFI_IFR_NUMERIC_SIZE_2 | EFI_IFR_DISPLAY_UINT_DEC,
    0,
    65535,
    0,
    NULL
    );
}
```
So this what makes the form exit from entering value upon pressing the `-`, and I should remove it and add a nosubmitif clause to the .vfr instead?

**Comment by miczyg1** [comment]
> @mkopec if I understand correctly, positive integers are enforced by making the opcode numeric and forcing range between 0 and 65535 in BootMaintenanceManagerCustomizedUiSupport.c here
> 
> ```
> BmmCreateTimeOutMenu (
>   IN EFI_HII_HANDLE              HiiHandle,
>   IN VOID                        *StartOpCodeHandle
>   )
> {
>   HiiCreateNumericOpCode (
>     StartOpCodeHandle,
>     (EFI_QUESTION_ID) FORM_TIME_OUT_ID,
>     VARSTORE_ID_BOOT_MAINT,
>     BOOT_TIME_OUT_VAR_OFFSET,
>     STRING_TOKEN(STR_NUM_AUTO_BOOT),
>     STRING_TOKEN(STR_HLP_AUTO_BOOT),
>     EFI_IFR_FLAG_CALLBACK,
>     EFI_IFR_NUMERIC_SIZE_2 | EFI_IFR_DISPLAY_UINT_DEC,
>     0,
>     65535,
>     0,
>     NULL
>     );
> }
> ```
> 
> So this what makes the form exit from entering value upon pressing the `-`, and I should remove it and add a nosubmitif clause to the .vfr instead?

EFI_IFR_DISPLAY_UINT_DEC causes the logic to treat input as unsigned. `EFI_IFR_DISPLAY_INT_DEC` is for signed integers. Note that this is dynamically generated opcode, there is no `.vfr` entry for that. You would have to create an opcode with nosubmitif and pass it to `HiiCreateNumericOpCode` last argument like I did with timeout default value here https://github.com/Dasharo/edk2/pull/96/files. But since I already occupy the last argument with the default value, you would have to find a way to append another opcode for nosubmitif. TBH no idea how it can be done

**Comment by filipleple** [comment]
@miczyg1 shouldn't simply changing the type to `EFI_IFR_DISPLAY_INT_DEC` and enforcing the range afterwards work as expected in the issue, and as demonstrated [here](https://github.com/Kostr/UEFI-Lessons/tree/master/Lessons/Lesson_65#numeric) ?  Instead, it ignores any input whatsoever and just displays the exclamation marks. I can only enter the `-`.
![image](https://github.com/Dasharo/dasharo-issues/assets/143995184/5c44a540-3415-4d9e-9887-33e7b005f092)
![image](https://github.com/Dasharo/dasharo-issues/assets/143995184/07d5a726-2817-478b-ab87-ea9df53d40c9)

**Comment by miczyg1** [comment]
> @miczyg1 @mkopec so shouldn't simply changing the type to `EFI_IFR_DISPLAY_INT_DEC` and enforcing the range afterwards work as expected in the issue, and as demonstrated [here](https://github.com/Kostr/UEFI-Lessons/tree/master/Lessons/Lesson_65#numeric) ? Instead, it ignores any input whatsoever and just displays the exclamation marks. I can only enter the `-`. ![image](https://user-images.githubusercontent.com/143995184/277588370-5c44a540-3415-4d9e-9887-33e7b005f092.png) ![image](https://user-images.githubusercontent.com/143995184/277588466-07d5a726-2817-478b-ab87-ea9df53d40c9.png)

And how that solves our problem? This way you only allow to enter `-` and that's all. Of course it addresses the expected behavior: `If we press -, two red exclamation marks !! appear at the bottom of the window. It is still waiting for a numerical value.`

But that's incorrectly set expectation. If you changed a BIOS setting on your PC and tried to put invalid value, what would you expect from the BIOS to do? Allow to input negative value in this case? Show some barely visible exclamation marks? Or rather show something more user-friendly like `invalid value` instead of those exclamation marks?

**Comment by Psotas** [comment]
Test added in https://github.com/Dasharo/open-source-firmware-validation/pull/107
Where can I find the firmware after fix to run tests?

**Comment by macpijan** [comment]
it's been confirmed with each Protectli release since then
