### ISSUE TITLE
Firmware Update Mode does not automatically boot into DTS

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#506]
**Dasharo version**
v1.7.0

**Dasharo variant**
Novacustom

**Affected component(s) or functionality**
Firmware update

**Brief summary**
After selecting Firmware Update Mode in BIOS, the PC should automatically boot into DTS after reboot, but it boots into the OS instead.

**How reproducible**
100%

**How to reproduce**

1. Power on the device
2. Go into BIOS setup
3. Enter Dasharo System Features -> Security Options -> Firmware Update Mode

**Expected behavior**
The device automatically boots into DTS after  reboot.

**Actual behavior**
The device boots into the installed OS after reboot.

**Comment by miczyg1** [comment]
Added a commit to ensure the direct DTS boot from iPXE: https://github.com/Dasharo/coreboot/pull/419/commits/676bf1980872c7637d299da94d8ba2dc78a9539f

@johanes2115 did the firmware try the iPXE boot?

**Comment by johanes2115** [comment]
@miczyg1 yes, it selected autoboot and then booten into the OS.

**Comment by miczyg1** [comment]
Allright, so the link to the commit should fix this. We just need a new build well we locate all bugs in this iteration

**Comment by johanes2115** [comment]
@miczyg1 same problem still occurs on the newest binaries.

**Comment by miczyg1** [comment]
Not sure what is wrong then. @mkopec ?

**Comment by mkopec** [comment]
@miczyg1 https://github.com/Dasharo/coreboot/pull/393/commits/c7fe020eb949c3f5480a0a6fe254a64809deadd7 another commit lost in the rebase...

**Comment by mkopec** [comment]
fix: https://github.com/Dasharo/coreboot/pull/422

**Comment by johanes2115** [comment]
Everything works fine on the newest binaries.
