### ISSUE TITLE
After waking up from suspend, keyboard illumination does not automatically turn on and can not be turned on manually (windows 11)

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#507]
**Dasharo version**
v1.7.0

**Dasharo variant**
Novacustom

**Affected component(s) or functionality**
Keyboard illumination

**Brief summary**
Keyboard illumination does not automatically turn on and can not be turned on manually after waking up from suspend on Windows 11.

**How reproducible**
100%

**How to reproduce**

1. Power on the device
2. Boot into Windows 11
3. Turn on keyboard backlight
4. Suspend the device
5. Wake the device up from suspend

**Expected behavior**
Keyboard illumination turns back on after waking up from suspend.

**Actual behavior**
Keyboard illumination does not turn back on after waking up ftom suspend and can not be turned on manually until reboot.

**Comment by miczyg1** [comment]
This commit should fix this: https://github.com/Dasharo/coreboot/pull/419/commits/96f735e7629fe611011718e9e79065cfe678ca77 but it wasn't probably confirmed yet

**Comment by mkopec** [comment]
can confirm https://github.com/Dasharo/coreboot/commit/96f735e7629fe611011718e9e79065cfe678ca77 fixes this issue

**Comment by mkopec** [comment]
reworked the backlight code in:
-  https://github.com/Dasharo/ec/pull/50
- https://github.com/Dasharo/coreboot/pull/419

**Comment by johanes2115** [comment]
@mkopec I can confirm that the issue no longer occurs.
