### ISSUE TITLE
No USB-C display output on Windows 11

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#509]
### Device

Novacustom ns70 ADL

### Dasharo version

v1.7.0

### Affected component(s) or functionality

USB-C display output

### Brief summary

USB-C display output does not work on Windows 11, both with the screen connected directly and through the docking station (HDMI and Display Port).

### How reproducible

100%

### How to reproduce

1. Power on the device
2. Boot into Windows 11
3. Connect a display through USB-C  port

### Expected behavior

The display should get output.

### Actual behavior

No image on the display.

**Comment by mkopec** [comment]
I'm getting video out via USB-C on my end, on an NV4x ADL unit. Dual daisy-chained DP monitors via simple USB-C to DP dongle.

Just needed to let all drivers install from Windows Update and reboot a couple of times until WU could not find any mode updates.

**Comment by mkopec** [comment]
NS5x ADL confirmed to work as well on my side.

**Comment by johanes2115** [comment]
@mkopec I will try updating and post the results.

**Comment by mkopec** [comment]
As we discussed offline, on a clean install, WU will install drivers automatically, but on an existing install it may not, in that case https://www.intel.com/content/www/us/en/support/detect.html is needed to install the missing drivers.

**Comment by johanes2115** [comment]
@mkopec works after sorting out the drivers.
