### ISSUE TITLE
No HDMI audio on Windows 11

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#511]
### Device

Novacustom ns70 ADL

### Dasharo version

v1.7.0

### Affected component(s) or functionality

HDMI audio playback

### Brief summary

HDMI audio recognition and playback does not work on Windows 11.

### How reproducible

100%

### How to reproduce

1. Power on the device
2. Boot into Windows 11
3. Connect the display to HDMI port
4. Connect headphones to 3.5 mm audio jack built into the display
5. In audio settings, try to set audio output to HDMI

### Expected behavior

HDMI audio should be able to be set as primary output and audio playback should work through headphones connected to the display.

### Actual behavior

HDMI audio is not recognised in the OS.

**Comment by mkopec** [comment]
As we discussed offline, on a clean install, WU will install drivers automatically, but on an existing install it may not, in that case https://www.intel.com/content/www/us/en/support/detect.html is needed to install the missing drivers.

**Comment by johanes2115** [comment]
@mkopec everything works after sorting out the drivers.
