### ISSUE TITLE
Auto Boot Time-out: If we press F9 (reset to default value) is reset to 0

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#513]
### Device

protectli_vp4670

### Dasharo version

v1.1.0

### Affected component(s) or functionality

Auto Boot Time-out in Dasharo Menu

### Brief summary

If we press F9 (reset to default value) Auto Boot Time-out is reset to 0

### How reproducible

100%

### How to reproduce

Press F9 for Auto Boot Time-out

### Expected behavior

6(?) seconds.

### Actual behavior

0 second.

**Comment by miczyg1** [comment]
Yes, but the boot maintenance manager creates the form dynamically and the callback doesn't handle the restore defaults action at all (return unsupported immediately). Just a matter of adding it to the code.

**Comment by Psotas** [comment]
Test on VP4670 v2:
I think we do not have default values set for the variables tested by `reset-to-defaults.robot` tests (Failed + probably skiped).
[reset-to-defaults_log.zip](https://github.com/Dasharo/dasharo-issues/files/12914762/reset-to-defaults_log.zip)

**Comment by filipleple** [comment]
Solved by [Pull Request #96](https://github.com/Dasharo/edk2/pull/96)

**Comment by macpijan** [comment]
The automatic test (https://github.com/Dasharo/open-source-firmware-validation/blob/configs-rework/dasharo-compatibility/auto-boot-time-out.robot) passes on v1.2.0 VP46X0 series
