### ISSUE TITLE
Permanent keyboard illumination after reboot/warm boot/cold boot not working in  Ubuntu 22.04

### ISSUE THREAD

**Issue by Mixss** [Dasharo/dasharo-issues#517]
### Device

novacustom ns70mu

### Dasharo version

v1.5.0

### Affected component(s) or functionality

RGB keyboard

### Brief summary

After reboot/warm boot/cold boot keyboard illumination does not save its setting

### How reproducible

always

### How to reproduce

1. Boot into ubuntu
2. Change settings of RGB keyboard illumination
3. Reboot into ubuntu

### Expected behavior

After booting into ubuntu the settings should be the same as set earlier

### Actual behavior

Keyboard's illumination settings stays the same until booting into ubuntu, then it changes to white color.

**Comment by mkopec** [comment]
reworked the backlight code in:
-  https://github.com/Dasharo/ec/pull/50
- https://github.com/Dasharo/coreboot/pull/419
