### ISSUE TITLE
Default branch for Dasharo/coreboot

### ISSUE THREAD

**Issue by ShalokShalom** [Dasharo/dasharo-issues#525]
### Device

-

### Dasharo version

-

### Brief summary

The default branch is confusing

### How to reproduce

If you look at the [dasharo/coreboot](https://github.com/dasharo/coreboot) website, you see that there is no commit since February. 

This deludes the actual effort that is put into the project since [the release tree](https://github.com/Dasharo/coreboot/tree/dasharo/release) has over 2000 more commits. 

### Expected behavior

I suggest that the active repo be the default one. 

### Actual behavior

Actively maintained repo is very well hidden.

**Comment by pietrushnic** [comment]
@ShalokShalom, this is a valid point, the key question is which branch we should choose as the active one since we have multiple active ones. I guess this is part of our activity of unifying and improving branch structure. I wonder what @macpijan @miczyg1 and @krystian-hebel think about that.

**Comment by miczyg1** [comment]
As we move to unification of all platforms on a single branch, I have set `dasharo` as the default one.
