### ISSUE TITLE
TPM not detected by VP4670 v2

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#528]
### Device

VP4670 v2 

### Dasharo version

v1.1.0

### Affected component(s) or functionality

full logs:
[tpm-support_log.zip](https://github.com/Dasharo/dasharo-issues/files/12915650/tpm-support_log.zip)

Note:  Additional testing may be necessary to be sure this is not a TPM problem.

ex.
Under windows:
Execute: `get-tpm`
```
return:TpmPresent                : False
TpmReady                  : False
TpmEnabled                : False
TpmActivated              : False
TpmOwned                  : False
RestartPending           ...
```
Execute: `tpmtool getdeviceinformation` 
```
return: 'Failed to get information.\r\nCommand failed with 0x800710df - The device is not ready for use.'
```

Under ubuntu 22.04:
`Arguments: [ 'cat /sys/class/tpm/tpm0/ppi/version' | strip_prompt=True ]` return: `cat: /sys/class/tpm/tpm0/ppi/version: No such file or directory`

### Brief summary

TPM not detected by VP4670 v2

### How to reproduce

Run the tests:
https://docs.dasharo.com/unified-test-documentation/dasharo-security/200-tpm-support/

### Expected behavior

TPM Support

### Actual behavior

TPM not detected

**Comment by macpijan** [comment]
This is not the case on v1.2.0. Modules have been detected on all units. Some TPM boards have been broken, this could also be the case here.
