### ISSUE TITLE
Raptor Lake Refresh Support

### ISSUE THREAD

**Issue by jonahnm** [Dasharo/dasharo-issues#534]
### The problem you're addressing (if any)

Not supporting Raptor Lake Refresh (haven't tested yet though).

### Describe the solution you'd like

Implementation of Raptor Lake Refresh support.

### Where is the value to a user, and who might that user be?

Any user interested in the higher performance but also wants to use an open source firmware.

### Describe alternatives you've considered

None.

**Comment by zirblazer** [comment]
This depends on Intel: https://github.com/intel/FSP/issues/96
Is completely unknown if Raptor Lake Refresh works with currently available binary blobs and a field test cost 300-600 U$D for a 14600K/14700K/14900K.

**Comment by miczyg1** [comment]
![Uploading image-8e5k5m93s7dhdxpk3666jseu6y.png…]()

**Comment by miczyg1** [comment]
<img width="667" alt="image-8e5k5m93s7dhdxpk3666jseu6y" src="https://github.com/Dasharo/dasharo-issues/assets/30656491/3718eb74-da41-4bbc-9c4d-536bc5fe6437">

**Comment by jonahnm** [comment]
Ah ok, cool.

**Comment by miczyg1** [comment]
Reopening for the purpose of validation of newest release on i7-14700K we ordered to confirm 14th gen support. Will be closed if not issues are detected.

**Comment by dushankw** [comment]
https://github.com/Dasharo/dasharo-issues/issues/534#issuecomment-1827632803

Do we have an update on this please?

**Comment by BeataZdunczyk** [comment]
> any idea why it hasn't been closed?

It wasn't added to the release [milestone](https://github.com/Dasharo/dasharo-issues/milestone/8) I guess @miczyg1 

> Do we have an update on this please?

Closing this one, as we have published a release with RPL support for Z690 [here](https://docs.dasharo.com/variants/msi_z690/releases/#v113-2024-01-22). We managed to merge the patch to coreboot with RPL support [here](https://review.coreboot.org/c/coreboot/+/69798), and even wrote a [blog post](https://blog.3mdeb.com/2024/2024-02-13-msi_z690-a_v1.1.3_release/) about release details, which I recommend everyone to read if curious about our recent MSI releases. @dushankw

**Comment by miczyg1** [comment]
> > any idea why it hasn't been closed?
> 
> It wasn't added to the release [milestone](https://github.com/Dasharo/dasharo-issues/milestone/8) I guess @miczyg1
> 

Ohh, okay. But strangely we had that in the changelog in docs and newsletter
