### ISSUE TITLE
Improve the documentation quality, make sure it actually works by copy-paste commands

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#541]

**Comment by pietrushnic** [comment]
@macpijan what else would be expected here to complete this task?

**Comment by macpijan** [comment]
@pietrushnic I should be able to build and run QEMU with all v0.1.0 features by using docs publicly available in docs.dasharo.com

The iPXE has been added, for instance, but the docs.dasharo.com does not support it yet, as there are some additional actions required to build iPXE first.

Some of it is here: https://github.com/Dasharo/docs/pull/678/files ?

**Comment by pietrushnic** [comment]
@macpijan yes, @miczyg1 merged my improvements to your branch. That was intentional, as I thought you would develop your branch further to support more stuff related to v0.1.0. There are also no conversations there. This release was developed by many people without much coordination, so it's no surprise we have a little mess. I just want to clean things that were confirmed to work or know another strategy for getting closer to release v0.1.0 if we have one. Some items on the roadmap are essentially Pandora's box, which, after opening, generates more and more work (e.g. OS installation from netboot.xyz).

**Comment by macpijan** [comment]
- tested build from:  https://github.com/Dasharo/docs/pull/678/files
- added link to validation use-case: [71c716c441773500fac72a3f39a3a06ec280fb90](https://github.com/Dasharo/docs/pull/678/commits/71c716c441773500fac72a3f39a3a06ec280fb90)
- proposed how to show which feautures are just menu front, which **should** work: https://github.com/Dasharo/docs/pull/678/commits/45e294d357c78168eac9c27ddd09818f09dc4794#r1386471963

**Comment by pietrushnic** [comment]
@macpijan thank you.
