### ISSUE TITLE
Dasharo compatible with Dell OptiPlex 7010/9010 v0.1.0 - rebase

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#547]
**Dasharo version (if applicable)**

v0.1.0

**Dasharo variant (if applicable)**

Dell OptiPlex 7010/9010

**Affected component(s) or functionality (if applicable)**

coreboot, edk2

**Brief summary**

coreboot and edk2 components shall be updated as shown in the roadmap: https://github.com/Dasharo/presentations/blob/main/dasharo_roadmap.md#dasharo-desktop-dell-roadmap

**Additional context**

Connected tasks:
- https://github.com/Dasharo/dasharo-issues/issues/546
- https://github.com/Dasharo/dasharo-issues/issues/545

**Comment by pietrushnic** [comment]
@BeataZdunczyk @macpijan, do we have plans to include this in an upcoming release?

**Comment by BeataZdunczyk** [comment]
Yes, we did. @filipleple will provide a summary of the work done here.

**Comment by filipleple** [comment]
I've managed to build OptiPlex 9010/7010 FW (edk2 and SeaBIOS) from our newest branches (coreboot/dasharo and edk2/rebased) with minor changes in https://github.com/Dasharo/coreboot/pull/541, so I think we can consider it to be rebased

**Comment by pietrushnic** [comment]
@filipleple great; I guess first you have to address the review, and then when it is merged, we can close this issue.

**Comment by pietrushnic** [comment]
@BeataZdunczyk @filipleple what is missing here?

**Comment by BeataZdunczyk** [comment]
> what is missing here?

@pietrushnic  I am closing the issue as PR has been merged: https://github.com/Dasharo/coreboot/pull/541
