### ISSUE TITLE
Adjust QEMU start scripts so OS (Ubuntu 22.04) installation is possible nad prove that by performing installation - the more automated the process is, the better

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#551]

**Comment by macpijan** [comment]
This has been implemented here (OS installation, but manual): https://github.com/Dasharo/open-source-firmware-validation/pull/116 and part of the v0.1.0 release https://docs.dasharo.com/variants/qemu_q35/releases/
