### ISSUE TITLE
Add DTS to netboot.xyz

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#552]
### The problem you're addressing (if any)

We should try to reach as many users as possible. netboot.xyz has huge community and we should try to give access to DTS with various open-source firmware-related tools to those users.

### Describe the solution you'd like

Contribute DTS entry to Tools > Utilities (UEFI) section.

### Where is the value to a user, and who might that user be?

More users easily can access DTS features

**Comment by PLangowski** [comment]
This PR introduces DTS to upstream netboot: https://github.com/netbootxyz/netboot.xyz/pull/1525

**Comment by Firminator** [comment]
Awesome. Thanks for implementing this feature request from last year.
