### ISSUE TITLE
The CPU frequency sometimes increases above max frequency on MSI® PRO Z690-A on Windows

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#558]
### Device

MSI® PRO Z690-A DDR4

### Dasharo version

v1.1.3

### Brief summary

The CPU frequency sometimes increases above max frequency on MSI® PRO Z690-A on Windows

### How to reproduce

5 times per hour

### Expected behavior

0 times per hour above max frequency

### Actual behavior

5 times per hour above max frequency:
1) '3700.0 > 3740.72038567493' should be true.

2) '3700.0 > 3713.43360313084' should be true.

3) '3700.0 > 3702.64962227633' should be true.

4) '3700.0 > 3979.57581501137' should be true.

5) '3700.0 > 4021.59659052624' should be true.

### Screenshots

[cpu-frequency_log.zip](https://github.com/Dasharo/dasharo-issues/files/13238631/cpu-frequency_log.zip)

**Comment by mkopec** [comment]
is 3.7GHz the actual max boost frequency, or is that the base clock frequency? 

As we discussed in https://github.com/Dasharo/dasharo-issues/issues/522, `(Get-CimInstance CIM_Processor).MaxClockSpeed` returns the base clock instead of max boost clock. May need to update tests to fix retrieving max boost value.

**Comment by Psotas** [comment]
> is 3.7GHz the actual max boost frequency, or is that the base clock frequency?

As I understand it, this is the base frequency.
https://docs.dasharo.com/variants/msi_z690/hardware-matrix/

> As we discussed in https://github.com/Dasharo/dasharo-issues/issues/522, (Get-CimInstance CIM_Processor).MaxClockSpeed returns the base clock instead of max boost clock. May need to update tests to fix retrieving max boost value.

Yes, it looks the same because we use the command in our tests:
`(Get-CimInstance CIM_Processor).MaxClockSpeed*((Get-Counter -Counter "\\Processor Information(_Total)\\% Processor Performance").CounterSamples.CookedValue)/100`

I'm closing the issue because it's a duplicate for #552

**Comment by miczyg1** [comment]
https://ark.intel.com/content/www/us/en/ark/products/134589/intel-core-i512600k-processor-20m-cache-up-to-4-90-ghz.html

3.7GHz is the base frequency of the performance core. The max frequency actually is 4.9GHz
