### ISSUE TITLE
ACPI error during boot (system76_acpi::kbd_backlight)

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#559]
### Device

NovaCustom NV4x-TGL

### Dasharo version

v1.5.0 (coreboot+EDK II)

### Affected component(s) or functionality

Normal boot without worrying errors

### Brief summary

A harmless ACPI error is showing up during boot

### How reproducible

100% reproducible

### How to reproduce

1. Boot to Ubuntu
2. Notice the boot log during boot

### Expected behavior

No errors during boot

### Actual behavior

An error showing up during boot:
`15:58:27 kernel: leds system76_acpi::kbd_backlight: Setting an LED's brightness failed (-1)`

### Additional context

This issue is not present in version v1.4.0.

**Comment by mkopec** [comment]
Wwe broke compatibility with the system76_acpi driver's handling of keyboard backlight, so it reports an error. Note that the driver is still used for the touchpad toggle hotkey and reading the fan speed. For this reason it remains enabled for now. The warning is entirely harmless.

**Comment by rapenne-s** [comment]
I updated my NV41 to 1.7.1, before it was running 1.5.0 (I'm not sure though), since the update, GNOME on Fedora 39 can't control the backlight anymore while it was working with the previous firmware.

**Comment by wessel-novacustom** [comment]
@rapenne-s Thank you for your contribution. The laptop was delivered with Dasharo v1.6.0 before it was updated.

I will discuss the options with my team soon, maybe we can get the keyboard backlight control back in graphical environments like GNOME and Cinnamon somehow.

**Comment by macpijan** [comment]
At first, we will hide the ACPI error for the upcoming hotfix release.
We will also look into what can be done to keep the graphical popups and control available in the future, but this is not planned for not. Unfortunately, we most likely cannot provide the compatibility with both Windows and Linux at the same time at the desired level, as the Linux driver is not under our control, and Windows has no driver, so the features (like keyboard backlight restore) are implemented in EC firmware mostly.

We will update this ticket once we have more concrete information.

**Comment by mkopec** [comment]
Fixed by commit https://github.com/Dasharo/coreboot/commit/1cc24c9c75aba9196d76361fe346e5a90bd9cf80

With each release we move further away from upstream, which introduces breakage. We changed the device HID to stop the driver from loading.
