### ISSUE TITLE
USB4 Root Device Router device displays an error in Windows 11 Device Manager

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#56]
*Issue moved from GitLab*

**Dasharo version**

v1.0.0

**Hardware details**

Clevo NV41MZ, Clevo NV41MB

**Affected component(s) or functionality**

USB4 Root Device Router

**Brief summary**

The USB4 Root Device Router device displays an error message in the Device Manager in Windows 11.

**How reproducible**

100%

**How to reproduce**

1. Boot Windows 11 without an USB-C device plugged in
2. Open Device Manager
3. Scroll down to the USB4 Root Device Router device

**Expected behavior**

The USB4 Root Device Router should not display an error in the Device Manager

**Actual behavior**

The USB4 Root Device Router displays an error in the Device Manager

**Screenshots**

Windows 11 Device Manager:

![devmgmt](https://user-images.githubusercontent.com/3678707/157429373-496cb992-1384-4e29-9b4b-cdb24ceb953f.png)

**Additional context**

The issue does not seem to impact any functionality. Plugging in USB-C peripherals like a USB stick or a HDMI adapter still works as expected.

**Solutions you've tried**

Plugging in a USB-C device like a HDMI adapter temporarily causes the device to stop displaying an error.

/cc @macpijan

**Comment by Pokisiekk** [comment]
The problem does not occur on the latest firmware version:

NV4xMZ/MB - [firmware v1.3.0](https://docs.dasharo.com/variants/novacustom_nv4x_tgl/releases/#v130-2022-10-18)
NS5x/7xMU - [firmware v1.3.0](https://docs.dasharo.com/variants/novacustom_ns5x_tgl/releases/#v130-2022-09-01)
