### ISSUE TITLE
Video on USB-C docks sometimes fails to initialize

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#560]
### Device

NovaCustom *

### Dasharo version

v1.5.1 TGL, v1.7.1 ADL

### Affected component(s) or functionality

Video initialization

Initialization of the dock may sometimes fail. The dock needs to be re-started to work around this issue.

### Brief summary

USB-C

### How reproducible

50%

### How to reproduce

power on laptop
connect and disconnect dock repeated

### Expected behavior

Monitors light up

### Actual behavior

Monitors do not display anything

### Additional context

The issue does not appear when one display is connected to the dock, or multiple monitors are connected to the dock via a downstream DP MST hub.
The issue also does not appear with:
- CableMatters triple display travel hub with DP, HDMI and VGA (P/N 201431-BLK)
- Lenovo ThinkPad USB-C Dock Gen2 (P/N 40AS)

Might also be fixed in updated firmware for the docking station.

**Comment by mkopec** [comment]
Updated the description. I can also reproduce the issue with other devices (Samsung Galaxy S23, Clevo L140MU running Insyde firmware). It does not seem to be tied to whether the dock is plugged in before or after boot. It just seems like an issue with the DP MST hub inside the docking station.

I can also see some severe graphics artifacts on the monitor for a couple of frames when disconnecting the dock from the laptop. Does not happen when the hub is working in SST mode.

**Comment by wessel-novacustom** [comment]
Thank you. I contacted WAVLINK from who we purchased directly. Hopefully, they can provide a firmware update.

**Comment by wessel-novacustom** [comment]
It seems that I have another revision, version Rev. E, here as well. I will now try to reproduce the problem on this revision.

**Comment by wessel-novacustom** [comment]
Running Windows 11. Rev. E has the same problem on NS5x-ADL v1.6.0. However, after the NS5x-ADL v1.7.1, that revision does no longer have this problem (tried once). However, a new problem occurred: the laptop does no longer power off when the docking station is attached.

Honestly, I do not see why the laptop's firmware hasn't been programmed in a way that it works for the delivered docking station, even if the dock's firmware isn't perfect.

**Comment by wessel-novacustom** [comment]
I made a new issue for that one: https://github.com/Dasharo/dasharo-issues/issues/562

Apart from that, we haven't seen the issue yet with the new laptop's firmware. We will do some more testing now and we will also do this under GNU/Linux instead of Windows 11.

**Comment by mkopec** [comment]
Looks to be fixed on NV4x ADL by commit https://github.com/Dasharo/ec/pull/53/commits/0c7ff80e1a0e1f3f25ab6d113666d53f8be56bb3
