### ISSUE TITLE
CPUs blocked at minimum frequency when laptop start unplugged

### ISSUE THREAD

**Issue by patrick-g** [Dasharo/dasharo-issues#561]
### Device

Novacustom NS51

### Dasharo version

1.7.0

### Affected component(s) or functionality

CPUs frequency

### Brief summary

CPUs blocked at minimum frequency when laptop start unplugged

### How reproducible

100%

### How to reproduce

Since the update to Dasharo firmware 1.7.0 for my Novacustom NS51 laptop, the CPUs frequency is not managed properly.
When laptop is booted with AC plugged everything is normal.
When the laptop is booted with AC unplugged the CPUs are blocked at the minimum frequency (400 MHz). If you plug the laptop the CPUs are not blocked anymore. And if you unplug it again the CPUs are not blocked either.
So the bug is ONLY if the laptop is booted when unplugged and the bug solve itself as soon as the AC power is plugged.

See the attached screenshots (plugged and unplugged) of command "watch -n1 "grep Hz /proc/cpuinfo" when I launch a very heavy encoding. We can see the CPUs are blocked at 400 MHz in the unplugged situation.

### Expected behavior

CPUs not blocked at the minimal frequency when you start it unplugged from AC power.

### Actual behavior

CPUs blocked at minimum frequency when laptop start unplugged from AC power.

### Screenshots

![plugged](https://github.com/Dasharo/dasharo-issues/assets/396194/88d007b7-0c39-4ae9-a3ff-ee428e5a7a06)
![unplugged](https://github.com/Dasharo/dasharo-issues/assets/396194/c40d8e52-0ea7-442e-878b-c95ce9007e1c)

### Additional context

CPU : Intel i7-1260p
Distro : Arch Linux
Current kernel : 6.5.9

### Solutions you've tried

I tried to enable and disable the Intel Management Engine (IME) in the Dasharo firmware but there is no impact on the bug.

**Comment by mkopec** [comment]
@patrick-g Please see issue https://github.com/Dasharo/dasharo-issues/issues/555
We are aiming to publish v1.7.1 very soon to fix this issue. It was caused by improper application of power limits in the new USB-PD driver code, which was meant to improve compatibility with various wattage USB-C chargers. It slipped during testing, but we're adding test cases for this specifically to avoid any such issues in the future.

**Comment by patrick-g** [comment]
Ah OK, sorry about the duplicate.

**Comment by patrick-g** [comment]
I updated from firmware 1.7.0 to the latest 1.7.1 version and I confirm this bug is solved.
