### ISSUE TITLE
Laptop doesn't power off in Windows

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#562]
### Device

NovaCustom NS5x-ADL (SKU: NS51PU-i5)

### Dasharo version

v1.7.1 (coreboot+EDK II)

### Affected component(s) or functionality

Powering off.

### Brief summary

The laptop does not power off if PowerDelivery (PD) is active

### How reproducible

100%

### How to reproduce

1. Boot the laptop to Windows 11 Pro.
2. Make sure that the laptop is charging via USB-C, either by a PD docking station or a regular USB-C PD charger.
3. Shutdown the laptop

### Expected behavior

The laptop will indicate that it is shutting down, then the screen display should turn off, the keyboard illumination should turn off and the power LED should change from green (on) to yellow (off during charging).

### Actual behavior

The laptop is indicating that it is shutting down, then the screen display turns off. But the keyboard illumination stays on and the power LED stays green, indicating that the laptop hasn't actually turned off.

### Additional context

I didn't try on GNU/Linux yet.

**Comment by mkopec** [comment]
Appears to shut down correctly on NS5x and NV4x ADL units for me, both in Windows 11 Pro and Ubuntu 22.04, with the Wavlink Dock and with a regular USB-PD power supply

**Comment by wessel-novacustom** [comment]
Would it possibly help to reinstall Windows 11 Pro?

**Comment by rapenne-s** [comment]
On a with NV4x-ADL with Dasharo 1.7.1, I got a similar issue multiple times.

In my case, in addition to OP description, the two fans were still spinning.

It happened when using Qubes OS, but I've not been able to figure a reproducer so far. I don't think I was using PowerDelivery at all.

**Comment by wessel-novacustom** [comment]
Doesn't seem to be exclusively related to PowerDelivery. This also just happened under Windows on the same device while using the default AC charger.

**Comment by wessel-novacustom** [comment]
The problem is also existing on battery mode, so it doesn't seem to be related to the power state at all.

**Comment by rapenne-s** [comment]
I might have a different problem then, I found what happened exactly and how to reproduce.

On qubes OS 4.2-RC4, suspend the system, then resume, then reboot. The system seems shut down but the fans are spinning and the LED is still green, and after a few minutes the screen is still black and I need to force the poweroff.

**Comment by wessel-novacustom** [comment]
Thank you @rapenne-s . @miczyg1 is investigating this as we speak.

**Comment by miczyg1** [comment]
Powering off when S3 is enabled (works):
```
[13:30:25.325] VWCTRL1 4
[13:30:25.329] VWIDX7 17
[13:30:25.329] VW_HOST_RST_ACK = 11
[13:30:25.333] VWCTRL1 4
[13:30:25.333] VWIDX7 16
[13:30:25.333] VW_HOST_RST_ACK = 10
[13:30:25.345] VWCTRL1 1B
[13:30:25.345] VWIDX2 70
[13:30:25.345] VWIDX3 30
[13:30:25.345] ESPI PLTRST# 10
[13:30:25.349] VWIDX41 B3
[13:30:25.349] VWCTRL1 1B
[13:30:25.353] VWIDX2 70
[13:30:25.353] VWIDX3 30
[13:30:25.353] VWIDX41 B3
[13:30:25.358] POWER_STATE_S5
[13:30:25.358] BA: ALL_SYS_PWRGD de-asserted
[13:30:25.361] PCH_PWROK_EC = false
[13:30:25.362] BA: power_off
[13:30:25.365] PCH_PWROK_EC = false
[13:30:25.370] EC_EN = false
[13:30:25.370] EC_RSMRST_N = false
[13:30:25.374] DD_ON = false
[13:30:25.374] VA_EC_EN = false
[13:30:25.378] PCH_DPWROK_EC = false
[13:30:25.382] POWER_STATE_OFF
[13:30:25.382] ESGCTRL0 E0
[13:30:25.386] BD: PLT_RST# asserted
[13:30:25.386] BD: SLP_SUS# asserted
```
Powering off when S0ix is enabled (doesn't work):

```
[13:38:21.279] VWCTRL1 4
[13:38:21.283] VWIDX7 17
[13:38:21.283] VW_HOST_RST_ACK = 11
[13:38:21.287] VWCTRL1 4
[13:38:21.287] VWIDX7 16
[13:38:21.287] VW_HOST_RST_ACK = 10
[13:38:26.219] FIXME: PMC HACK
```

So there is some problem here indeed.

**Comment by macpijan** [comment]
@wessel-novacustom The binaries for testing will be there: https://github.com/Dasharo/coreboot/actions/runs/6865457469

**Comment by wessel-novacustom** [comment]
With the provided test binaries above, the problem no longer occurs. Tested with both NV4x 12th gen and NS5x 12th gen.

**Comment by wessel-novacustom** [comment]
I could not reproduce the problem on Dasharo v1.7.2-rc1.
