### ISSUE TITLE
Thunderbolt Controller fails to start and shows yellow sign in Device Manager

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#563]
### Device

NovaCustom NS5x-ADL (SKU: NS51PU-i5)

### Dasharo version

v1.7.1 (coreboot+EDK II)

### Affected component(s) or functionality

Thunderbolt

### Brief summary

Thunderbolt Controller fails to start and shows yellow sign in Device Manager

### How reproducible

100%

### How to reproduce

1. Install Windows 11 Pro.
2. Upgrade the laptop from Dasharo v1.6.0 to Dasharo v1.7.1.
3. Open Device Manager.

### Expected behavior

No devices report an error.

### Actual behavior

The Thunderbolt Controller reports an error and doesn't start.

### Screenshots

![WhatsApp Image 2023-11-07 at 10 03 49](https://github.com/Dasharo/dasharo-issues/assets/100232604/99f5a194-6fc9-443b-a46c-90ba3ff27d63)

### Solutions you've tried

Remove the driver and install it manually from Intel's website. It didn't solve the problem.

**Comment by mkopec** [comment]
https://github.com/Dasharo/coreboot/pull/433

**Comment by macpijan** [comment]
@wessel-novacustom If you can, please provide comments under: https://github.com/Dasharo/coreboot/pull/433 what was tested on your side

**Comment by wessel-novacustom** [comment]
This particular issue will be solved when publishing the new version with that fix.

**Comment by wessel-novacustom** [comment]
While the problem has gone, the Thunderbolt Controller randomly disappears.

**Comment by wessel-novacustom** [comment]
We could no longer reproduce this issue with the latest test binaries.

Otherwise, one should follow [these steps](https://docs.dasharo.com/unified/clevo/post-install/#unrecognized-usb-controller-device-in-device-manager).
