### ISSUE TITLE
Sleep mode not working on Windows 11

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#564]
### Device

NovaCustom NS5x-ADL (SKU: NS51PU-i5)

### Dasharo version

v1.7.1 (coreboot+EDK II)

### Affected component(s) or functionality

Sleep mode (S0ix modern standby)

### Brief summary

Sleep mode not working

### How reproducible

100%

### How to reproduce

1. Install Windows 11 Pro
2. Upgrade from Dasharo v1.6.0 to v1.7.1
3. Boot to Windows 11 Pro
4. Enter sleep mode (Start menu --> Power icon --> Sleep)

### Expected behavior

Screen display turns off, keyboard illumination turns off, power LED will start blinking.

### Actual behavior

Screen display turns off, keyboard illumination remains on, power LED remains green (not blinking).

**Comment by mkopec** [comment]
https://github.com/Dasharo/coreboot/pull/433

**Comment by mkopec** [comment]
https://github.com/Dasharo/ec/pull/52

**Comment by wessel-novacustom** [comment]
The problem doesn't happen anymore with these test binaries.
