### ISSUE TITLE
MSI PRO Z790 WIFI DD5 Dasharo (Coreboot), ReBar for Intel Arc A750 GPU needs CONFIG_PCIEXP_DEFAULT_MAX_RESIZABLE_BAR_BITS > 29

### ISSUE THREAD

**Issue by xlfe** [Dasharo/dasharo-issues#565]
### Device

MSI PRO Z790 WIFI DD5

### Dasharo version

0.9.1

### Affected component(s) or functionality

ReBAR

### Brief summary

ReBAR does not work for this GPU

### How reproducible

100%

### How to reproduce

I saw the 0.9.1 ROM was already on the release server and used DTS to flash it to my system (I updated the version reference in http://dts-function.sh from 0.9.0 to 0.9.1).

Once I had 0.9.1 installed, I enabled Re BAR in the Dasharo BIOS configuration menu and booted into Linux.

Using cbmem I get the following output

```
[DEBUG]  found VGA at PCI: 03:00.0
[DEBUG]  Setting up VGA for PCI: 03:00.0
[DEBUG]  Setting PCI_BRIDGE_CTL_VGA for bridge PCI: 02:01.0
[DEBUG]  Setting PCI_BRIDGE_CTL_VGA for bridge PCI: 01:00.0
[DEBUG]  Setting PCI_BRIDGE_CTL_VGA for bridge PCI: 00:01.0
[DEBUG]  Setting PCI_BRIDGE_CTL_VGA for bridge DOMAIN: 0000
[DEBUG]  Setting PCI_BRIDGE_CTL_VGA for bridge Root Device
[INFO ]  Allocating resources...
[INFO ]  Reading resources...
[DEBUG]  PCI: 00:00.0 register 1c(20000000), read-only ignoring it
[DEBUG]  SA MMIO resource: MCHBAR   ->  base = 0xfedc0000, size = 0x00020000
[DEBUG]  SA MMIO resource: DMIBAR   ->  base = 0xfeda0000, size = 0x00001000
[DEBUG]  SA MMIO resource: EPBAR    ->  base = 0xfeda1000, size = 0x00001000
[DEBUG]  SA MMIO resource: REGBAR   ->  base = 0xfb000000, size = 0x00001000
[DEBUG]  SA MMIO resource: EDRAMBAR ->  base = 0xfed80000, size = 0x00004000
[DEBUG]  SA MMIO resource: CRAB_ABORT ->  base = 0xfeb00000, size = 0x00080000
[DEBUG]  SA MMIO resource: TPM      ->  base = 0xfed40000, size = 0x00010000
[DEBUG]  SA MMIO resource: LT_SECURITY ->  base = 0xfed50000, size = 0x00020000
[DEBUG]  SA MMIO resource: APIC     ->  base = 0xfec00000, size = 0x00100000
[DEBUG]  SA MMIO resource: PCH_RESERVED ->  base = 0xfc800000, size = 0x02000000
[DEBUG]  SA MMIO resource: GFXVTBAR ->  base = 0xfed90000, size = 0x00001000
[DEBUG]  SA MMIO resource: IPUVTBAR ->  base = 0xfed92000, size = 0x00001000
[DEBUG]  SA MMIO resource: TBT0BAR  ->  base = 0xfed84000, size = 0x00001000
[DEBUG]  SA MMIO resource: TBT1BAR  ->  base = 0xfed85000, size = 0x00001000
[DEBUG]  SA MMIO resource: TBT2BAR  ->  base = 0xfed86000, size = 0x00001000
[DEBUG]  SA MMIO resource: TBT3BAR  ->  base = 0xfed87000, size = 0x00001000
[DEBUG]  SA MMIO resource: VTVC0BAR ->  base = 0xfed91000, size = 0x00001000
[DEBUG]  SA MMIO resource: MMCONF   ->  base = 0xc0000000, size = 0x10000000
[DEBUG]  SA MMIO resource: DSM      ->  base = 0x4c800000, size = 0x03c00000
[DEBUG]  SA MMIO resource: TSEG     ->  base = 0x4b800000, size = 0x00800000
[DEBUG]  SA MMIO resource: GSM      ->  base = 0x4c000000, size = 0x00800000
[INFO ]  Available memory above 4GB: 64252M
[WARN ]  Device PCI: 03:00.0 requests a BAR with 33 bits of address space, which coreboot is not configured to hand out, truncating to 29 bits
[INFO ]  PCI: 03:00.0: Adjusting resource index 24: base: 0 size: 20000000 align: 29 gran: 29 limit: ffffffffffffffff
[INFO ]  Done reading resources.
```

### Expected behavior

ReBAR is enabled for the Intel ARC A750 GPU

### Actual behavior

ReBAR is not enabled for the Intel ARC A750 GPU

### Solutions you've tried

I've tried rebuilding the bios while setting 
CONFIG_PCIEXP_DEFAULT_MAX_RESIZABLE_BAR_BITS=33 and also to 36, both times the result of flashing that and then enablling rebar resulted in a garbled screen and no boot output.

I surmise that ReBar is attempting to be enabled by the GPU OPROM, but that has some incompatibility with Coreboot. I will file a separate issue for that.

**Comment by xlfe** [comment]
When I disable all Option ROMs in the bios, the system boots normally, but I get the same result as if ReBar is disabled (even though it was enabled in the bios).

**Comment by arthurrasmusson** [comment]
I'm not sure which OS you're using (depending on when this failure occurs in the boot chain it might have something to do with how the platform wants to pass these option ROMs to the GPU or perhaps how the GPU is communicating with the CPU - there are a few exotic interfaces it uses on Intel CPUs - some are the GuC talking to Intel CSME). I left a comment in your other thread where I recommended some flags in GRUB - can you also try installing this driver?
https://dgpu-docs.intel.com/driver/installation.html

I have a few debugging tools I can help you with as well - it's possible that the gFSP (GPU Firmware Support Package) on your GPU is not up to date - if that's the case this should be pretty easy to fix.

I'm going to think this over for awhile - if you can produce those logs and try that driver it could help. The GPU might be complaining about something interesting there.

**Comment by xlfe** [comment]
> I'm going to think this over for awhile - if you can produce those logs and try that driver it could help. The GPU might be complaining about something interesting there.

Sorry haven't had a chance to do this yet - hoping to get to it later this coming week, I have added a bunch of logs to the other issue as it looks like it might be a MMIO alignment issue from Coreboot.

**Comment by miczyg1** [comment]
Should be fixed with: https://github.com/Dasharo/coreboot/pull/439
tested on my RTX3060Ti

**Comment by miczyg1** [comment]
Also the ReBARs are broken in upstream coreboot and to begin with, they never worked as they are now.

**Comment by xlfe** [comment]
Fixed with #584

**Comment by miczyg1** [comment]
Same as here: https://github.com/Dasharo/dasharo-issues/issues/584#issuecomment-1827629488

**Comment by BeataZdunczyk** [comment]
Closing this issue as the changes have been merged. We are currently completing testing for the release, and further updates will be provided on testing issues https://github.com/Dasharo/dasharo-issues/issues/612 and https://github.com/Dasharo/dasharo-issues/issues/613.
