### ISSUE TITLE
Production binaries to allow automated deployment again

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#574]
**Dasharo version and variant**

NovaCustom TGL devices with Dasharo > v1.4.0 and NovaCustom ADL devices with Dasharo > v1.6.0

**Affected component(s) or functionality (if applicable)**

Semi-automated deployment of the open EC firmware and the automated deployment of the operating system using Clonezilla Server (via iPXE).

**Brief summary**

We use internal iPXE boot scripts with the iPXE autoboot functionality. Since Dasharo v1.5.0 and higher, some new mechanisms such as _BIOS boot medium lock_ and _SMM BIOS write protection_ have been introduced that are created to improve the end user's security. However, with the default UEFI firmware settings, the laptop no longer autoboots with iPXE when no operating system is installed. It drops to an UEFI shell instead, preventing us to semi-automatically flash the open EC firmware and deploy the operating system.

We would like to have production binaries which have these settings disabled and which boots to iPXE autoboot automatically like it used to be.

It would also be sufficient if we could get instructions on how to create these production binaries ourselves. If the UEFI firmware settings are stored in the main SPI, I can imagine that it would be possible to read them from a current device and to apply them to an existing binary.

**Additional context**

Of course we will always flash the non-production-binary as the last step before we send any laptop to our customers.

**Comment by macpijan** [comment]
> It drops to an UEFI shell instead, preventing us to semi-automatically flash the open EC firmware and deploy the operating system.

I assume the network boot is disabled, that is why it boots into UEFI shell, not iPXE: https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#networking-options ?

The boot order or iPXE option availability should not be related to the mentioned security lock options.

Is enabling network boot a viable solution? If not (as it adds a few manual steps), we will discuss further.

**Comment by macpijan** [comment]
> If the UEFI firmware settings are stored in the main SPI, I can imagine that it would be possible to read them from a current device and to apply them to an existing binary.

Yes, that is one of the options to overcome this. And actually, we need that as well for testing automation for another release, and already looking into a solution.

Ideally, to have a tool that allows to (offline) change BIOS settings in the specific firmware binary.

**Comment by wessel-novacustom** [comment]
Correct, I forgot to mention that. So yes it works when we enable network booting.

But the whole point is: we need a binary for temporary production use that we flash initially that doesn't require us to disable security mechanisms and/or enable network boot. This will help us avoiding manual steps in our production.

**Comment by macpijan** [comment]
At the same time, we should keep the secure default values for the customers when shipping hardware to them.

I believe the mentioned tool could help. In that a way we could automated the following process:
- take the public release binary (with sane security defaults),
- configure whatever is needed for manufacturing,
- install/configure the OS,
- configure back the sane security defaults,
- ship the hardware to the customer.

**Comment by pietrushnic** [comment]
> configure whatever is needed for manufacturing,

Dasharo Manufacturing Mode

> configure back the sane security defaults

In an ideal world, it would boil down to calling DTS to provision some security certification level, e.g. [HSI 5](https://fwupd.github.io/libfwupdplugin/hsi.html#hsi-level5)

**Comment by wessel-novacustom** [comment]
> At the same time, we should keep the secure default values for the customers when shipping hardware to them.
I absolutely realise that.

> I believe the mentioned tool could help. In that a way we could automate the following process:
>
>    take the public release binary (with sane security defaults),
    configure whatever is needed for manufacturing,
    install/configure the OS,
    configure back the sane security defaults,
    ship the hardware to the customer.
>
> Would such scenario work for your case?

This is how I imagined it:

- Initially flash the alternative binary which has some security settings turned off to allow easy flash/deployment of the Embedded Controller (EC), operating system and to flash back the public binary (BIOS region) which then restores the default secure settings.

I will probably build the firmware myself with different settings for internal use and then apply the method as described above. If that's the way to go, please let me know and I will close the issue.

The key point is that you can boot to **iPXE autoboot automatically and flash and deploy without needing to change firmware settings**.

**Comment by macpijan** [comment]
Another idea that would allow to keep using the same manufacturing method right now with no additional effort: since we want to reflash the binary anyway after manufacturing, we might just as well use older release (such as v1.6.0 - where this method worked)  and flash the most recent version afterwards?

**Comment by macpijan** [comment]
Agreed with @wessel-novacustom that right now we will stick to the above idea, but for the future releases, we should make sure that we have the ability to produce a "manufacturing" variant based on the release binary.

**Comment by wessel-novacustom** [comment]
For now, we will use Dasharo v1.4.0 for TGL (11th Gen) devices and Dasharo v1.6.0 for ADL (12th Gen) devices and then flash v1.5.2 and v.1.7.2 respectively once this hotfix release has been published.

I think I will be just using custom builds with different settings for the future. Most likely, we can this by ourselves. If not, we will re-open this issue.
