### ISSUE TITLE
PC Engines Dasharo v0.9.0 - release preparation - test infrastructure

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#576]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

- [x] Make sure hardware is available for testing
- [x] Create/update test matrix and results sheet for the given release
- [x] Create/update HW matrix / HCL
- [x] Make sure that peripherals in the DUT are connected according to HW matrix / HCL

**Additional context**

**Comment by mkopec** [comment]
apu2,3,4,6 have been added to the test environment. Tentative results for -rc1 are available here: https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit#gid=1670191276
