### ISSUE TITLE
PC Engines apu3 v0.9.0 - testing

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#578]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

- [x] Add platform config for the new platform in https://github.com/Dasharo/open-source-firmware-validation
- [x] Perform testing according to test matrix (https://github.com/Dasharo/dasharo-issues/issues/576)
- [x] Fill in the test results in the spreadsheet (https://github.com/Dasharo/dasharo-issues/issues/576)

**Additional context**

**Comment by pkubaj** [comment]
Done, but is there a point in duplicating Jira tasks here? Testing task is not exactly an issue in Dasharo, which, I believe, this repo is intended for.

**Comment by BeataZdunczyk** [comment]
The release v0.9.0 has been published, and the release notes can be found [here](https://docs.dasharo.com/variants/pc_engines/releases_uefi/#v090-2024-04-02). Test results for this platform are available [here](https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit#gid=1670191276).
