### ISSUE TITLE
Fix TPM detection with the newest Intel ME firmware (>15.0.10.1447)

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#58]
**Dasharo version**

v1.0.1

**Dasharo variant**

Clevo NV4xMB,MZ

**Affected component(s) or functionality**

TPM detection

**Brief summary**

When the Intel ME binary is updated to version newer than >15.0.10.1447 (e.g. 15.0.30.1776), the discrete TPM is no longer detected. The problem is caused by the newer ME distributed by Clevo having enabled Intel PTT fTPM which collides with the dTPM and causes neither TPM to be detected.

**How reproducible**

100%

**How to reproduce**

1. Flash ME v15.0.30.1776 from Clevo
2. Boot into Ubuntu 20.04
3. Check that there is no TPM entry in `/sys/class/tpm`

**Expected behavior**

Discrete TPM is discoverable and operable.

**Actual behavior**

Discrete TPM is not detected.

**Screenshots**

**Additional context**

One possible solution without modifying the ME blob is to send a HECI message from coreboot that will instruct the ME
to disable the PTT functionality.

**Solutions you've tried**

**Comment by Pokisiekk** [comment]
@mkopec Does the problem still occur? Are we planning to do something with it?

**Comment by mkopec** [comment]
@Pokisiekk Thanks for the ping, this was fixed by buiding ME binaries with PTT disabled. Can be closed now.

**Comment by macpijan** [comment]
Fixed when and how? Please be more specific and link relevant changelog (version) and maybe also changelog entry.

**Comment by mkopec** [comment]
@macpijan We don't have changelogs for the ME blobs as we don't publish the binaries. The fix was distributed directly to NovaCustom
