### ISSUE TITLE
NovaCustom NV4x (coreboot + heads) v0.9.0 - release preparation - firmware

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#580]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

- [ ] Consult with Thierry how the code should be added to: https://github.com/linuxboot/heads
- [ ] Use https://github.com/Dasharo/heads/pull/1 as a base to submit MR to https://github.com/linuxboot/heads
- [ ] Use the coreboot base from 1.7.2 release

**Additional context**

**Comment by tlaurion** [comment]
See:
- https://github.com/linuxboot/heads/pull/1522#issuecomment-1852539760
- https://github.com/linuxboot/heads/pull/1554#issue-2044890390
- https://github.com/Nitrokey/heads/issues/31#issuecomment-1859033376

Goal would be to not end up with multiple nv41/ns50 under Heads, where rebranding should be applied. 
Nk 2.4 firmware release based on Heads should now be possible. No idea of when and how, things have been messy for retracted 2.3 and people use 2.1/2.2 for the moment.

**Comment by jans23** [comment]
This issue is related to NovaCustom's device and Dasharo firmware. I don't see how this is related to Nitrokey's firmware. Maybe it would help to keep these two things separate.

**Comment by pietrushnic** [comment]
> PS: in future please tag @tlaurion so I receive notifications.

@tlaurion, we didn't tag you because we had no intention of bothering you with our preparation. The ball is on our side. We know how to reach out to you if we need your attention.

I agree with @jans23 that your message @tlaurion mixes issues. We should split those as commits, one logical issue per ticket. Under the Dasharo organization, I would be fine to discuss Dasharo-related issues and upstream-related stuff, but I would like to avoid commenting on other forks. Dasharo should be a place for cooperation, not competition.

Please give us some time to jump on this topic. The current release target for Dasharo (coreboot+Heads) v0.9.0 for Novacustom NV4x is 25.01.2024. Please note that there is no plan to support NS5x.

**Comment by mkopec** [comment]
I propose we follow a similar approach as ChromeOS devices for EC updates, where the EC firmware is updated by coreboot if coreboot finds a version mismatch. This solves a couple of problems:
- Single binary to distribute, download, verify and flash
- Can't mismatch coreboot and EC versions
- No need to distribute additional tool for updates
- EC FW is measured and verified by coreboot
- EC update interface can be locked down before passing control to payload, so nobody can flash malicious FW to it

This basically requires porting the EC update protocol from system76_ectool to coreboot, I got some basics working and running on Clevo NV40MZ: https://github.com/Dasharo/coreboot/pull/456

I've tested comparing version and board model so far, need to test reading FW tomorrow, once reading is working well, writing should be easy to add.

Related issue: https://github.com/Dasharo/dasharo-issues/issues/660

**Comment by mkopec** [comment]
For the EC update we went with DTS for this release. EC FW sync may be explored at some point in a future release.

The code in https://github.com/Dasharo/heads/pull/2 can now be built. With @miczyg1 's help I fixed an issue where the platform wouldn't boot after rebasing coreboot on latest Dasharo code, and centered the logo in the middle of the screen, without scaling.

**Comment by mkopec** [comment]
Resolved problems with building binaries in CI (in freshly cloned repos in general): https://github.com/linuxboot/heads/pull/1614

**Comment by mkopec** [comment]
I've tagged release v0.9.0: https://github.com/Dasharo/heads/releases/tag/novacustom_nv4x_adl_v0.9.0 - same rev as what we've tested previously. Binaries have been uploaded to cloud in preparation for DES release.

**Comment by BeataZdunczyk** [comment]
Closing this issue as the release notes has been published: https://docs.dasharo.com/variants/novacustom_nv4x_adl/heads/#v090-2024-02-29
