### ISSUE TITLE
 NovaCustom NV4x (coreboot + heads) v0.9.0 - release preparation - test infrastructure

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#581]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

- [x]  Make sure hardware is available for testing
- [x]  Create/update test matrix and results sheet for the given release
- [x]  Create/update HW matrix / HCL
- [x]  Make sure that peripherals in the DUT are connected according to HW matrix / HCL

**Additional context**

**Comment by mkopec** [comment]
Testing was completed and results are available here: https://github.com/Dasharo/dasharo-issues/issues/581

The initial release was tested fully manually. I'll update the HW matrix accordingly, but as per the documentation, current matrix applies, with the addition of a Nitrokey 3A Mini for testing Heads.
