### ISSUE TITLE
 NovaCustom NV4x (coreboot + heads) v0.9.0 - documentation

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#582]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

Following documentation pages shall be created:

- [x]  Overview page
- [x]  Building manual
- [x]  Initial deployment
- [x]  Firmware Update
- [x]  Recovery

**Additional context**

**Comment by BeataZdunczyk** [comment]
We have published a general overview for Dasharo (coreboot + Heads) firmware variant for NV4XPZ [here](https://docs.dasharo.com/unified/novacustom/overview/#dasharo-coreboot--heads), and documentation [here](https://docs.dasharo.com/variants/novacustom_nv4x_adl/heads/). Closing this issue.
