### ISSUE TITLE
 NovaCustom NV4x (coreboot + heads) v0.9.0 - testing

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#583]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

- [ ] Perform automated/manual testing of the v0.9.0 release as specified in the test matrix created in https://github.com/Dasharo/dasharo-issues/issues/581
- [ ] Fill in the test results in the spreadsheet created in https://github.com/Dasharo/dasharo-issues/issues/581
- [ ] Create bug reports on the dasharo-issues repository for detected defects

**Additional context**

**Comment by mkopec** [comment]
I've completed testing release v0.9.0 , results are available here: https://docs.google.com/spreadsheets/d/1yWZ--zFPIsQhXZByf7nJIrasQYuRSf1yCi60lY_RGsQ/edit#gid=2042954457
