### ISSUE TITLE
Firmware update should not be possible on battery mode

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#585]
**Dasharo version (if applicable)**

*

**Dasharo variant (if applicable)**

NovaCustom *

**Affected component(s) or functionality (if applicable)**

Firmware update

**Brief summary**

Currently, a firmware update can be executed on battery mode (without AC adaptor connected).

**Additional context**

There is a chance that the battery runs out during the firmware flash process, resulting in a bricked device for the end user. Most end users do not have external recovery kits to fix this and warranty service is required if this happens.

**Proposed solution**

Block firmware updates by returning an error with description if the power adaptor is not connected.

**Comment by macpijan** [comment]
Should be fixed with: https://github.com/Dasharo/meta-dts/pull/56

**Comment by wessel-novacustom** [comment]
A fix has been applied and verified on the NV4x-TGL, we are now awaiting more tests of today and finally the publication of the new Dasharo Tools Suite version.

**Comment by wessel-novacustom** [comment]
Solved in upcoming DTS version.
