### ISSUE TITLE
Boot logo not persistent after firmware update

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#586]
### Device

NovaCustom NS5x-ADL (SKU: NS70PU-i7)

### Dasharo version

v1.6.0 --> v1.7.1 (coreboot+EDK II)

### Affected component(s) or functionality

Currently, the firmware update causes the firmware boot splash logo to be restored to the NovaCustom BIOS logo.

A firmware update should not override the boot logo, though.

### Brief summary

A firmware update can be executed on battery mode

### How reproducible

100%

### How to reproduce

Make sure you have a custom boot logo. Then update the firmware from Dasharo v1.6.0 to v1.7.1.

### Expected behavior

The boot logo remains the custom logo set by the user when a previous Dasharo firmware version was installed.

### Actual behavior

The logo gets overwritten by the default NovaCustom boot splash.

### Additional context

A workaround might be applied in Dasharo Tools Suite by storing the BOOTSPLASH region before updating and restoring this region after the update.

### Solutions you've tried

Set the custom boot logo again is something I will try now, which will most likely work, but cannot be considered as a solution for the bug.

**Comment by constantine-gavrilov** [comment]
Model NV4xPZ (novacustom). I confirm the issue.

And I am not able to flash the custom boot logo either.  After update, I have dumped the ROM. The boot logo section is present, but is empty (no added files).

I tried adding the boot logo using DCU/cbfstool and flashing the image (or just boot logo section) -- no boot logo is displayed.

Flashing back the "empty" boot logo section reverts to default (non-customized) logo.

Novacustom flashed the logo originally for me (this is how the laptop was ordered), so I am not aware of the format/resolution limitations. I have tried various resolutions for the original image, using BMP3 conversion (as DCU tool does), but I could not get the logo to display.

**Comment by wessel-novacustom** [comment]
@constantine-gavrilov Thank you for confirming the issue.

You can contact the [NovaCustom support](https://configurelaptop.eu/contact/) directly for a fix to get the boot logo back that you used to have.

Meanwhile, @macpijan has created a solution for the problem by reading the bootsplash region before applying an update and flashing that region again after the update, which is waiting to be released. This solves the problem for further releases.

**Comment by wessel-novacustom** [comment]
Solved in upcoming DTS version.
