### ISSUE TITLE
Sometimes the hash of downloaded binary is not displayed in the DTS and the firmware update fails

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#588]
### Device

NovaCustom (all models)

### Dasharo version

DTS v1.2.12 and before

### Brief summary

Sometimes the hash of downloaded binary is not displayed in the DTS and the firmware update fails

### How reproducible

May depend on the location and Internet connectivity.
It was reported to be ~50% by some users.

### How to reproduce

Boot into DTS and select `Firmware Upgrade` option

### Expected behavior

Firmware upgrades normally

### Actual behavior

No hash is displayed for either EC, BIOS firmware, or both.

### Screenshots

![WhatsApp Image 2023-11-07 at 09 04 15(2)](https://github.com/Dasharo/dasharo-issues/assets/19353650/0ff62543-8516-4c24-954d-8ccadd4fbd04)
![bios](https://github.com/Dasharo/dasharo-issues/assets/19353650/875ed3dc-0c04-44e4-a395-84266dd160aa)

**Comment by macpijan** [comment]
Was able to reproduced the problem only when disconnected the Ethernet cable from the device, once the DTS has been booted already. Here is the log from this scenario: https://paste.dasharo.com/?1d2021a027d9814b#G258gtZc5S3bnQUnsECZQf989tJcguXWo4UkUKAoUUBS

**Comment by macpijan** [comment]
Improved some network failure errors and added waiting for network to be up before calling update: https://github.com/Dasharo/meta-dts/pull/58/files

**Comment by macpijan** [comment]
With the implemented checking for network connection, I am not able to reproduce the problem with missing hash anymore right now.

**Comment by wessel-novacustom** [comment]
@macpijan Which version has the `checking for network connection` functionality? I still had this problem today but with Dasharo Tools Suite version 1.2.11.

**Comment by macpijan** [comment]
@wessel-novacustom We aim to release this version along with more improvements together with the version bump to v1.7.2.
This is being worked on here: https://github.com/Dasharo/meta-dts/commits/develop/

**Comment by mkopec** [comment]
@macpijan We've already released v1.7.2 with improvements for this issue, so it can be closed I think?
