### ISSUE TITLE
Implement Clevo WMI ACPI interface to support Clevo Control Center

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#59]
**The problem you're addressing (if any)**

Clevo Control Center / TUXEDO Control Center do not currently work on coreboot. They use Clevo's WMI interface which is missing from our ACPI tables.

**Describe the solution you'd like**

Implement a functional Clevo WMI interface for compatibiliy with existing utilities.

**Where is the value to a user, and who might that user be?**

Compatibility with existing userspace tools makes it easier to change firmware settings such as the fan curve or power profiles.

**Describe alternatives you've considered**

**Additional context**

**Comment by macpijan** [comment]
Rather than implementing the WMI interface in open-source firmware (which is close to infeasible), we propose to enumerate the features Clevo Control Center provides, and provide alternative interfaces (implemented in open-source projects) to use these fetures.

- [ ] Fan curve control
- [ ] Webcam toggle
- [ ] Performance profiles selection

**Comment by wessel-novacustom** [comment]
> Rather than implementing the WMI interface in open-source firmware (which is close to infeasible), we propose to enumerate the features Clevo Control Center provides, and provide alternative interfaces (implemented in open-source projects) to use these fetures.
> 
>     * [X]  [Fan curve control](https://github.com/Dasharo/dasharo-issues/issues/424)
> 
>     * [X]  [Webcam toggle](https://github.com/Dasharo/dasharo-issues/issues/425)
> 
>     * [X]  [Performance profiles selection](https://github.com/Dasharo/dasharo-issues/issues/426)

These have been realised, so the issue can be closed :-)

We don't need CLEVO WMI ACPI compatibility. Rather not, actually.
