### ISSUE TITLE
Initial Deployment/Recovery processes for NovaCustom are not clear.

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#594]
### The problem you're addressing (if any)

The documentation is not simple, there are fragments of useful information in various places:
The pins are described in the Remote Testing Environmen section https://docs.dasharo.com/transparent-validation/rte/v1.1.0/flashing-guide/#ns5x7x-12th-generation
Pictures are only for 11th generation(TGL) https://docs.dasharo.com/unified/novacustom/initial-deployment/#installing-dasharo
The programmer itself is partially described in https://docs.dasharo.com/unified/msi/recovery/#ch341a

### Describe the solution you'd like

One concise process where you can switch between platforms to load the appropriate photos and differences in steps, if any.

**Comment by macpijan** [comment]
@BeataZdunczyk I think I saw a task like this in progress, let's make sure we address this issue as well.

**Comment by BeataZdunczyk** [comment]
We have simplified the process in https://github.com/Dasharo/docs/pull/829, and added photos for different models. Live updated documentation is here: https://docs.dasharo.com/unified/novacustom/recovery/.
