### ISSUE TITLE
 No WiFi device found on Ubuntu - ath10k has crashed during init

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#595]
### Device

Protectli VP4650

### Dasharo version

protectli_vault_cml_v1.1.0_vp46xx (coreboot 4.21 rebase)

### Affected component(s) or functionality

WiFi scanning

### Brief summary

`nmcli device wifi rescan` returns `Error: No Wi-Fi device found.`. The network controller is however listed in lspci (Qualcomm Atheros)

### How reproducible

100%

### How to reproduce

Boot Ubuntu and log in via SSH
Execute nmcli device wifi rescan

### Expected behavior

It should do a WiFi scan and return found networks

### Actual behavior

Error: No Wi-Fi device found.

### Screenshots

```
root@3mdeb:/home/ubuntu# nmcli device wifi rescan
Error: No Wi-Fi device found.

root@3mdeb:/home/ubuntu# lspci | grep "Network controller:"
07:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 30)

root@3mdeb:/home/ubuntu# dmesg | grep ath
[    3.496439] usbcore: registered new interface driver ath3k
[    3.573298] ath10k_pci 0000:07:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
[    3.847564] ath10k_pci 0000:07:00.0: qca6174 hw3.0 target 0x05020000 chip_id 0x003409ff sub 168c:3361
[    3.847568] ath10k_pci 0000:07:00.0: kconfig debug 0 debugfs 1 tracing 1 dfs 0 testmode 0
[    3.847937] ath10k_pci 0000:07:00.0: firmware ver WLAN.RM.4.4.1-00157-QCARMSWPZ-1 api 6 features wowlan,ignore-otp,mfp crc32 90eebefb
[    3.917880] ath10k_pci 0000:07:00.0: board_file api 2 bmi_id N/A crc32 706c395e
[    5.980960] ath10k_pci 0000:07:00.0: PCIe Bus Error: severity=Corrected, type=Physical Layer, (Receiver ID)
[    5.980962] ath10k_pci 0000:07:00.0:   device [168c:003e] error status/mask=00000001/00006000
[    5.980965] ath10k_pci 0000:07:00.0:    [ 0] RxErr                 
[   11.098547] ath10k_pci 0000:07:00.0: wmi unified ready event not received
[   11.148567] ath10k_pci 0000:07:00.0: device has crashed during init
[   11.176535] ath10k_pci 0000:07:00.0: device has crashed during init
[   11.176539] ath10k_pci 0000:07:00.0: failed to wait for target init: -70
[   11.177684] ath10k_pci 0000:07:00.0: could not init core (-110)
[   11.177711] ath10k_pci 0000:07:00.0: could not probe fw (-110)


```

**Comment by filipleple** [comment]
also occurs on VP4670, same binary:

```
ubuntu@3mdeb:~$ sudo dmesg | grep ath
[sudo] password for ubuntu: 
[    4.615047] usbcore: registered new interface driver ath3k
[    4.634742] ath10k_pci 0000:07:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
[    4.917748] ath10k_pci 0000:07:00.0: qca6174 hw3.0 target 0x05020000 chip_id 0x003409ff sub 168c:3361
[    4.917753] ath10k_pci 0000:07:00.0: kconfig debug 0 debugfs 1 tracing 1 dfs 0 testmode 0
[    4.918089] ath10k_pci 0000:07:00.0: firmware ver WLAN.RM.4.4.1-00157-QCARMSWPZ-1 api 6 features wowlan,ignore-otp,mfp crc32 90eebefb
[    4.989288] ath10k_pci 0000:07:00.0: board_file api 2 bmi_id N/A crc32 706c395e
[   12.090718] ath10k_pci 0000:07:00.0: wmi unified ready event not received
[   12.140748] ath10k_pci 0000:07:00.0: device has crashed during init
[   12.168778] ath10k_pci 0000:07:00.0: device has crashed during init
[   12.168789] ath10k_pci 0000:07:00.0: failed to wait for target init: -70
[   12.171673] ath10k_pci 0000:07:00.0: could not init core (-110)
[   12.171722] ath10k_pci 0000:07:00.0: could not probe fw (-110)

```

**Comment by mkopec** [comment]
> ```
> [    5.980960] ath10k_pci 0000:07:00.0: PCIe Bus Error: severity=Corrected, type=Physical Layer, (Receiver ID)
> [    5.980962] ath10k_pci 0000:07:00.0:   device [168c:003e] error status/mask=00000001/00006000
> [    5.980965] ath10k_pci 0000:07:00.0:    [ 0] RxErr   
> ```

Could be that AER for that slot has to be disabled. I also saw similar issues on M900 Tiny, had to disable PCIe ASPM substates to get the wifi card to work: https://github.com/Dasharo/coreboot/pull/402#issuecomment-1742168202

**Comment by miczyg1** [comment]
Okay, so buggy cards...

**Comment by macpijan** [comment]
> Okay, so buggy cards...

@miczyg1 @mkopec Do you mean this specific unit to be buggy, or the card model / chip in general? Can replacing to another unit help?

I am afraid we need this card to work, it comes with the kit sold by Protectli: https://eu.protectli.com/product/m2-wifi/

**Comment by macpijan** [comment]
@filipleple 

> protectli_vault_cml_v1.1.0_vp46xx (coreboot 4.21 rebase)

Have you checked if it worked before rebase, so on the previous release?

**Comment by mkopec** [comment]
> Do you mean this specific unit to be buggy, or the card model / chip in general? Can replacing to another unit help?

The card model most likely

> an you point to the specific change needed to test out this hypothesis? Ideally as PR, so we can use binaries from CI for testing.

https://github.com/Dasharo/coreboot/pull/469 CI should produce binaries for both changes, so they can be both tested

**Comment by macpijan** [comment]
Thanks, let's await tests results from @pkubaj

**Comment by pkubaj** [comment]
I first tried to compile myself with only one of the commits applied at the time - no change in behaviour.
Then I tried the CI-built image, also no change.

**Comment by pkubaj** [comment]
Downgrading the firmware as described in https://kb.protectli.com/kb/wifi-on-the-vault/ causes the Wifi card to work.

**Comment by macpijan** [comment]
At a very least we need to document it in dasharo docs to avoid in the future. Similar steps for other platforms have been documented like: https://docs.dasharo.com/unified/clevo/post-install/#linux

**Comment by miczyg1** [comment]
I would check if the FW is not broken: https://kb.protectli.com/kb/wifi-on-the-vault/
The page says that QCA6174-based WiFI cards need a firmware fix/workaround

**Comment by miczyg1** [comment]
There is also some thread related to the broken FW: https://lore.kernel.org/all/87zg7m8mt2.fsf@kernel.org/#t

**Comment by macpijan** [comment]
@pkubaj can you please document it as suggested here: https://github.com/Dasharo/dasharo-issues/issues/595#issuecomment-1988535950 ? Then we can close this one.

**Comment by pkubaj** [comment]
Please see https://github.com/Dasharo/docs/pull/782

**Comment by macpijan** [comment]
Thanks, @pkubaj left one comment there.
