### ISSUE TITLE
Touchpad enable/displable Fn shortcut no longer working

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#597]
### Device

NovaCustom NV4x-TGL (SKU: NV40MZ-i5)

### Dasharo version

v1.5.2-rc1

### Affected component(s) or functionality

Touchpad enable/disable Fn shortcut

### Brief summary

The touchpad enable/disable Fn shortcut is no longer working

### How reproducible

100% reproducible.

### How to reproduce

1. Start the laptop with the mentioned firmware version and related EC binary flashed.
2. Boot to either Ubuntu ~~or Windows~~ (not tested on Windows yet).
3. Hold the Fn key and press the F1 key.

### Expected behavior

The touchpad disables.

### Actual behavior

The touchpad is still working after triggering this shortcut.

### Additional context

In GNOME, there is no indicator of the shortcut like it used to be.
This is possibly related to the switch to an own version of the Embedded Controller? Also see https://github.com/Dasharo/dasharo-issues/issues/559. Maybe we need to hard switch the Touchpad like turning off the power when the Fn shortcut is triggered?

**Comment by wessel-novacustom** [comment]
Requires the [Touchpad hotkey enablement](https://docs.dasharo.com/unified/clevo/post-install/#touchpad-hotkey-enablement).

**Comment by mkopec** [comment]
Note that this is distro-dependent, systemd verions 253 and newer include this fix so it'll work OOTB on distros that ship it: https://github.com/systemd/systemd/commit/cb8d22fa8490ea19e82117b1e1ea794e3c0a4c98
