### ISSUE TITLE
Docking station ethernet support in iPXE

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#599]
### The problem you're addressing (if any)

Some Wavlink docks come with ASIX AX88179 Ethernet adapters. iPXE supports it with the `axge` driver, but we currently do not build with it enabled.

### Describe the solution you'd like

Build iPXE with the `axge` driver

### Where is the value to a user, and who might that user be?

Dasharo Tools Suite / PXE boot accessible via dock Ethernet, not just builtin ethernet.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by miczyg1** [comment]
@mkopec what makes you think that axge driver is not built into iPXE? 
As far as I can see all sources are included for EFI SB build:
`SRCDIRS		+= drivers/net` AXGE is in `src/drivers/net/axge.c`
`SRCS	+= $(wildcard $(patsubst %,%/*.c,$(SRCDIRS)))`
except:
```
SRCDIRS_INSEC	+= net/oncrpc
SRCDIRS_INSEC	+= net/80211
SRCDIRS_INSEC	+= drivers/net/rtl818x
SRCDIRS_INSEC	+= drivers/net/ath
SRCDIRS_INSEC	+= drivers/net/ath/ath5k
SRCDIRS_INSEC	+= drivers/net/ath/ath9k
```

**Comment by miczyg1** [comment]
Hmm, the `src/config/defaults/efi.h` contains all the things needed:

```
#define	USB_HCD_XHCI		/* xHCI USB host controller */
#define	USB_HCD_EHCI		/* EHCI USB host controller */
#define	USB_HCD_UHCI		/* UHCI USB host controller */
#define	USB_EFI			/* Provide EFI_USB_IO_PROTOCOL interface */
#define USB_BLOCK		/* USB block devices */
```

But what you may really be missing is the actual enumeration of the devices behind TBT port and that would probably require using FW CM (so sending connect topology command == setting FSPS UPD ITbtConnectTopologyTimeoutInMs to non-zero and causing quite big boot delay). Have you checked in the UEFI Shell that all devices of the dock are seen in the device list?

**Comment by mkopec** [comment]
@miczyg1 it's a DP Alt mode dock so video and USB work fine in firmware (keyboard and USB sticks are detected in UEFI). Tried in the "dumb" port but there's no difference

Also tried another dock with a Realtek NIC, no difference either. Still only net0 is enumerated in iPXE.

**Comment by miczyg1** [comment]
> @miczyg1 it's a DP Alt mode dock so video and USB work fine in firmware (keyboard and USB sticks are detected in UEFI). Tried in the "dumb" port but there's no difference
> 
> Also tried another dock with a Realtek NIC, no difference either. Still only net0 is enumerated in iPXE.

Okay... Then I have no idea and some iPXE debugging would be needed.

**Comment by mkopec** [comment]
according to https://forum.ipxe.org/showthread.php?tid=10777 the EFI target disables USB drivers by default, I built and chainloaded `bin-x86_64-efi/realtek--axge--ncm--ecm.efi` which works with USB dongles, but now I can't get back to the setup menu / boot menu when exiting iPXE. I don't know if it's a worthwile tradeoff to make

**Comment by macpijan** [comment]
@mkopec  Should this issue be renamed? Is it related to ncm laptops - do we need some labels?

**Comment by mkopec** [comment]
It's related to USB-C docking stations with ASIX ethernet adapters. Adding some labels now, and changing the name to reflect on the goal and not implementation detail.

Another way we could go about this is to add a UEFI SNP driver from https://github.com/tianocore/edk2-platforms/tree/master/Drivers/ASIX , which should work with iPXE and not break going back to the setup menu

**Comment by wessel-novacustom** [comment]
Honestly, we don't expect iPXE to work with the Ethernet port of the docking station. I would close this issue and state that iPXE is only supported for the Ethernet port of the laptop itself, not of external devices.
