### ISSUE TITLE
Why we don't publish hashes and signatures for DES delivered binaries?

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#600]
**Dasharo version**

v0.9.0

**Dasharo variant**

MSI PRO Z790-P (WIFI) (DDR4)

**Question text**

I'm not sure if we made a decision somewhere and I cannot find it, so why we don't publish hashes, so those who compile code themselves can check if they reproduced the same build?

**Comment by miczyg1** [comment]
@pietrushnic there was no decision IIRC. We just have to adjust our scripts and templates to upload hashes and signatures as it would be a regular public release. And publish the hashes of previous DES releases

**Comment by pietrushnic** [comment]
@miczyg1 does it interfere in any way with the vboot strategy of signing DES images? I guess it may add work if we continue to sign with dev keys.

**Comment by miczyg1** [comment]
Well, the binaries produced  are signed with vboot dev keys, so we have to publish hashes of the binaries which are devi signed.

Vboot signing is reversible, so taking Dasharo signed binary and resigning it with vboot dev keys results in dev_signed binary of the same hash as genuine build with dev keys signing.

**Comment by pietrushnic** [comment]
Great. I guess this issue should be addressed with some documentation and publication of hashes and signatures for DES releases, so in the future users could be sent to certain sections in docs.dasharo.com

**Comment by miczyg1** [comment]
Implemented the logic in the script to include the hash and signature in relnotes with links to FTP as well as upload these artifacts to FTP regardless of DES or not (only the firmware binary is not uploaded). No link to the respective MR/PR, because those are private repos.

**Comment by macpijan** [comment]
We do publish. Example: https://docs.dasharo.com/variants/msi_z790/releases/#v091-2024-01-22
