### ISSUE TITLE
dts-lib: rework flashing method

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#606]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

In `lib/dts-lib.robot`, there is a keyword called `Flash Firmware In DTS` for flashing that forces flashing with the internal programmer. It needs to be replaced with the more generic keyword that we already have developed in `keys-and-keywords/flashrom.robot`.

**Additional context**

**Comment by macpijan** [comment]
@Psotas Have you done some cleanup in this are in one of your MRs already?

**Comment by Psotas** [comment]
@macpijan Today I will synchronize with @filipleple regarding two PRs:
https://github.com/Dasharo/open-source-firmware-validation/pull/122/
https://github.com/Dasharo/open-source-firmware-validation/pull/130/

**Comment by Psotas** [comment]
@macpijan Should we post issues regarding the test environment here?
Or maybe in these issues: https://github.com/Dasharo/open-source-firmware-validation/pulls

**Comment by macpijan** [comment]
@Psotas @filipleple We do it here: https://github.com/Dasharo/open-source-firmware-validation/pulls

**Comment by macpijan** [comment]
I would appreciate it being moved @filipleple 
Please also provide links to files rather just names, if possible.

**Comment by filipleple** [comment]
moved to [osfv](https://github.com/Dasharo/open-source-firmware-validation/issues/141)
