### ISSUE TITLE
VP4650 DP display not detected on Windows

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#607]
### Device

Protectli VP4650

### Dasharo version

protectli_vault_cml_v1.1.0_vp46xx (coreboot 4.21 rebase)

### Brief summary

`Get-WmiObject WmiMonitorConnectionParams -Namespace root/wmi` always lists `VideoOutputTechnology : 5`, even if HDMI is detached and only DP attached

### How reproducible

100%

### How to reproduce

Boot into windows, attach DP dongle, run `Get-WmiObject WmiMonitorConnectionParams -Namespace root/wmi` to check video outputs

### Expected behavior

The command should list `VideoOutputTechnology : 10` or `VideoOutputTechnology : 11`, adequately to DP being attached

### Actual behavior

It always lists `VideoOutputTechnology : 5`

**Comment by mkopec** [comment]
I guess it can be used for testing DP++ functionality at least, if it's worth testing at all
