### ISSUE TITLE
VP4650 DP display not detected on Ubuntu

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#608]
### Device

Protectli VP4650

### Dasharo version

protectli_vault_cml_v1.1.0_vp46xx (coreboot 4.21 rebase)

### Brief summary

`cat /sys/class/drm/card0-DP-1/status` returns `disconnected`

### How reproducible

100%

### How to reproduce

Boot into ubuntu, attach DP dongle, execute `cat /sys/class/drm/card0-DP-1/status`

### Expected behavior

It should not return `disconnected` if it is, in fact, connected

### Actual behavior

It does return `disconnected`

**Comment by Psotas** [comment]
@filipleple 
Same like https://github.com/Dasharo/dasharo-issues/issues/607#issuecomment-1835906804
This means that DP dummy cannot be used in tests, at least not from this manufacturer.
