### ISSUE TITLE
eMMC support test Ubuntu - unrecognised disk label

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#609]
### Device

Protectli VP4650

### Dasharo version

protectli_vault_cml_v1.1.0_vp46xx (coreboot 4.21 rebase)

### Brief summary

Checking EMMC module via `parted /dev/mmcblk0 -- print` returns `Error: /dev/mmcblk0: unrecognised disk label`

### How reproducible

100%

### How to reproduce

Run test `MMC001.001`

### Expected behavior

Checking EMMC module via the `parted /dev/mmcblk0 -- print` command should succeed

### Actual behavior

It returns `Error: /dev/mmcblk0: unrecognised disk label` and doesn't contain the gpt flag

### Screenshots

![Pasted image](https://github.com/Dasharo/dasharo-issues/assets/143995184/91a9242e-e526-4f4e-956f-b0dc2d81abec)

**Comment by macpijan** [comment]
This is not perfect check. The eMMC may simply be not partitioned, and the test would fail, as it fails here.

**Comment by mkopec** [comment]
Yes, I guess `lsblk | grep mmcblk0` would be more reliable if we only want to test if the OS can see the EMMC at all

**Comment by macpijan** [comment]
Improved in: https://github.com/Dasharo/open-source-firmware-validation/pull/140
