### ISSUE TITLE
Fix Thunderbolt functionality on NV41MB

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#61]
**The problem you're addressing (if any)**

The Thunderbolt 4 capable USB-C port on the NV41MB does not currently work under coreboot. Plugging in peripherals (USB 2.0, USB 3.0, DP Alt mode) results in no detection at best and GPU errors at worst.

**Describe the solution you'd like**

Thunderbolt 4 functionality should work correctly on NV41MB, as it does on NV41MZ and NS51MU.

**Where is the value to a user, and who might that user be?**

Full Thunderbolt functionality is expected from the TB port.

**Describe alternatives you've considered**

**Additional context**

The same laptop exhibits the same issues under original Insyde firmware, so a hardware defect is possible.

**Comment by wessel-novacustom** [comment]
> The same laptop exhibits the same issues under original Insyde firmware, so a hardware defect is possible.
- I disagree. The NV40MB with the latest Insyde firmware doesn't have this problem.
![usbcvideooutput](https://user-images.githubusercontent.com/100232604/158415935-8dda55bd-c083-4426-9bd7-5a65b482a56b.jpg)

Please check the latest NV40MB delivery batch with revision code D02A for further investigation.
