### ISSUE TITLE
Cannot establish SSH connections from DTS on a read-only system

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#617]
### Device

-

### Dasharo version

-

### Affected component(s) or functionality

outgoing SSH connections from DTS

### Brief summary

If DTS is booted from a read only file system, e.g. on PiKVM, it is impossible to establish an outgoing SSH connection - each try fails with error `Connection reset by peer`.

### How reproducible

100%

### How to reproduce

Mount a DTS ISO as a read-only file system and try to connect to any device via SSH

### Expected behavior

A successful SSH connection

### Actual behavior

`Connection reset by peer`

**Comment by filipleple** [comment]
moved to meta-dts [issue 64](https://github.com/Dasharo/meta-dts/issues/64)

**Comment by pietrushnic** [comment]
> Issues for DTS are created here: https://github.com/Dasharo/meta-dts/issues

I'm not sure why.

* https://docs.dasharo.com/dasharo-tools-suite/overview/#reporting-issues
* https://github.com/Dasharo/dasharo-issues/issues?q=is%3Aopen+is%3Aissue+label%3ADasharoToolsSuite
* Here I request migration of issues from meta-dts to this repo: https://github.com/Dasharo/dasharo-issues/issues/301#issuecomment-1845250941

I would like to understand the logic behind your decision and how you plan to communicate that to DTS users.
