### ISSUE TITLE
Keyboard backlight does not turn off immediately when going to sleep

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#623]
### Device

NovaCustom *

### Dasharo version

v1.5.1 TGL, v1,7,1 ADL

### Affected component(s) or functionality

Keyboard backlight, sleep management

### Brief summary

When putting the laptop to sleep, the keyboard backlight does not turn off immediately

### How reproducible

100% on Windows 11 with AC adapter connected

### How to reproduce

- Power on laptop
- Ensure sleep mode is s0ix
- Put laptop to sleep via hotkey or OS

### Expected behavior

Keyboard backlight turns off immediately

### Actual behavior

Keyboard stays on until the SoC actually enters S0ix, this may take several minutes on Windows when AC is connected (Connected Standby)

### Additional context

Instead of depending on the SoC to actually go to sleep reasonably quickly, let's just use the PEP hooks, as presumably many other EC FWs do.

**Comment by mkopec** [comment]
Fixed by commit https://github.com/Dasharo/ec/commit/ebfc6b41d319569df91c61550995d6615a20c353

**Comment by wessel-novacustom** [comment]
I think this has been solved and should therefore be closed.
