### ISSUE TITLE
Audio/mic port on USB-C docking station NV41MZ

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#63]
**Dasharo version**

v1.0.1
EC: 1.07.05

**Dasharo variant**

Clevo NV41MZ

**Affected component(s) or functionality**

Audio/mic via USB-C while running Ubuntu 20.04.4 LTS

**Brief summary**

While using a USB-C docking station with an audio/mic port, the port doesn't work: no audio signal seems to be transmitted to the attached headset.

**How reproducible**

100% reproducible

**How to reproduce**

1. Boot the laptop to Ubuntu 20.04.4 LTS.
2. Insert the USB-C docking station including the headset.
3. Try to play audio via the USB-C docking station to the attached headset.

**Expected behavior**

The audio is transmitted correctly.

**Actual behavior**

The audio on the headset remains silent.

**Screenshots**

N/A

**Additional context**

The problem does not exist on the latest NV40MB laptop with Insyde firmware while running Windows 11.

I am not sure if this problem is related to the operating system or the firmware.

**Solutions you've tried**

Tried another docking station.
Please let me know if there is anything else I can try.

**Comment by macpijan** [comment]
@wessel-novacustom Which docking stations were tested? I have to check if we have any.

**Comment by wessel-novacustom** [comment]
@macpijan You will receive the laptop as well as two of the affected docking station tomorrow, so you can test this out :-) . I did not try another model docking station, but another one of the exact same model.

**Comment by Pokisiekk** [comment]
https://github.com/Dasharo/dasharo-issues/issues/89 - I have experienced similar issue but we have concluded that this is due to the docking station specification and a VGA cable must be connected to get sound through the headset. I tested laptops with a different docking station for a period of time and the audio worked fine.
