### ISSUE TITLE
Some devices on dock are not detected after warmboot or reboot

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#632]
### Device

NovaCustom *

### Dasharo version

v1.5.1 TGL, v1.7.1 ADL

### Affected component(s) or functionality

USB, TCSS

### Brief summary

Some devices on dock are lost after reboot (no longer visible in lsusb)

### How reproducible

~100%? @Psotas can clarify

### How to reproduce

- Connect power supply
- Boot laptop
- Connect dock (WL-UG69PD2)
- run lsusb
- power off
- power on
- run lsusb again

### Expected behavior

All devices that worked before shutdown should keep working after warmboot.

### Actual behavior

These are lost:

```
Fresco Logic USB3.0 Hub
Genesys Logic, Inc. USB3.1 Hub
Realtek Semiconductor Corp. USB3.0 Card Reader
```

### Additional context

Discovered by @Psotas , seems to only affect WL-UG69PD2

**Comment by wessel-novacustom** [comment]
Happens on NS70MU in Windows as well. Only the DisplayLink docking station seems to be affected.

**Comment by mkopec** [comment]
Seems to affect warmboot and reboot, and reproducibility isn't 100%, I've just re-run automatic tests and both reboot and warmboot cases passed on NS51PU

**Comment by wessel-novacustom** [comment]
Docks have been extensively tested by us and confirmed to be no longer an issue starting from v1.5.2 (TGL) and v1.7.2 (ADL). I believe the issue should be closed, @mkopec.

**Comment by macpijan** [comment]
Correct
