### ISSUE TITLE
CPU not running on expected frequency and usage NS50MU

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#64]
**Dasharo version**

v1.0.0

**Dasharo variant**

NS50_70MU (i5-1135G7)

**Affected component(s) or functionality**

Overall performance (CPU)

**Brief summary**

The CPU performance seems to be limited. The CPU frequency is (way) below the base frequency. The CPU frequency doesn't seem to become above the base frequency at all, even not when stress testing. The CPU usage when stress testing is limited by 50%. OS: Windows 11 Pro.

**How reproducible**

100% reproducible.

**How to reproduce**

1. Boot the laptop to Windows 11.
2. Start a CPU stress test, for instance prime95. 
3. Start task manager to monitor the CPU usage and frequency.

**Expected behavior**

- CPU is running at Turbo frequency, later throttled down to its base frequency when it becomes too hot.
- CPU usage at 100%.

**Actual behavior**

- CPU is running at lower frequencies, below its base frequency.
- CPU usage at about 50%.

**Screenshots**

N/A

**Additional context**

The problem seems to be worse in battery mode (without power adapter attached).

**Solutions you've tried**

None.

**Comment by macpijan** [comment]
@mkopec Isn't it a matter of adjusting the limits in the firmware?

**Comment by wessel-novacustom** [comment]
The problem also occurs under GNU/Linux. It is a serious issue.

**Comment by wessel-novacustom** [comment]
CPU frequency behaviour has been adjusted in the last release, but we are not sure if the problem is still there and how serious the problem is.

So if there is anyone having CPU frequency behaviour problems, please comment below.

**Comment by macpijan** [comment]
This was resolved in the [1.2.0 release](https://docs.dasharo.com/variants/novacustom_ns5x_tgl/releases/#v120-2022-05-26), and there were no reports since then, so we should go ahead and close this one.
