### ISSUE TITLE
How can installed firmware be trusted if the DTS is booted via iPXE?

### ISSUE THREAD

**Issue by jeltsch** [Dasharo/dasharo-issues#642]
**Dasharo version**

I plan to use a recent NovaCustom NV41 laptop. Currently, I don’t know which version of Dasharo such a laptop is running.

**Dasharo variant**

This will be the variant used on NovaCustom NV41 laptops.

**Question text**

The documentation of the Dasharo Tools Suite recommends starting the DTS via iPXE, causing it to be loaded via the internet. From the tutorial video at https://www.youtube.com/watch?v=WJHWbt_FNGA, it is visible that the DTS is fetched via unencrypted HTTP. According to the DTS documentation, Secure Boot has to be switched off for starting the DTS.

Doesn’t this mean that anyone capable of launching a man-in-the-middle attack could deploy a DTS version infected with malware to your machine and ultimately install malware-infected firmware?

**Comment by macpijan** [comment]
Thank you for bringing this up @jeltsch !

We already have an issue regarding this, so let's continue discussion there: https://github.com/Dasharo/dasharo-issues/issues/450

**Comment by pietrushnic** [comment]
@macpijan @jeltsch we should close this as duplicate IMHO.

**Comment by jeltsch** [comment]
I looked at this issue and am shocked that it is really the case that the recommended way of running the DTS is not tampering-resistant at all. I’ve commented there: https://github.com/Dasharo/dasharo-issues/issues/450#issuecomment-1864560185.

**Comment by pietrushnic** [comment]
Closing as confirmed duplicate.
