### ISSUE TITLE
Powering off NV41 with power button resets Fn-Lock state to default (i.e. turns it off)

### ISSUE THREAD

**Issue by serpack** [Dasharo/dasharo-issues#644]
### Device

novacustom NV41 Intel 12Gen

### Dasharo version

1.7.2 beta

### Affected component(s) or functionality

power button, Fn fuctions

### Brief summary

Powering off NV41 with power button resets Fn-Lock state to default (i.e. turns it off)

### How reproducible

100% of times

### How to reproduce

1) Enable Fn-Lock
2) Power off the System by pressing 5sec power button
3) Power on the system
4) Fn-Lock is disabled

### Expected behavior

The state of Fn-Lock should not change

### Actual behavior

Powering off NV41 with power button resets Fn-Lock state to default (i.e. turns it off)

**Comment by wessel-novacustom** [comment]
Thank you for your report! I think we will postpone this to a next release as we would like to focus on our coreboot+Heads version for the NV41 Series first.

**Comment by macpijan** [comment]
This enhancement was already requested, so maybe we close this as a duplicate: https://github.com/Dasharo/dasharo-issues/issues/308 ?
We already have #308 in our board in Backlog: https://github.com/orgs/Dasharo/projects/5/views/2?layout=board

**Comment by serpack** [comment]
hm... "Fn+Caps Lock" works as Fn-Lock fine for me, except the mentioned problem. I found it already in backlog as #458.

I will close this issue ad duplicate
