### ISSUE TITLE
Human readable UEFI Secure Boot key enrollment menu

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#645]
### The problem you're addressing (if any)

Right now the menu listing the DB certs contains a list of GUIDs, and with the default keys all 4 of them are the same. I don't know which one to remove if I want to disallow MS 3rd party CA, for example.

### Describe the solution you'd like

Human readable entries in the menu

TODO upload photo from my T14

### Where is the value to a user, and who might that user be?

Easier menu navigation, better UX

### Describe alternatives you've considered

Need to check how other vendors do it

**Comment by macpijan** [comment]
@BeataZdunczyk That would be also interesting for our customers and should not be that difficult to implement

**Comment by zirblazer** [comment]
I recall having posted months ago in the chat channels a TXT with a sort of specification about how I'm expecting UEFI Secure Boot to behave. I suppose that no one looked at it. Want me to repost it as a ticket here? Is a rather complete overhaul of the interface.

**Comment by mkopec** [comment]
Sure @zirblazer , I think it may be useful to post it here

**Comment by zirblazer** [comment]
https://github.com/Dasharo/dasharo-issues/issues/929
Have fun. This ticket is point 4 on mine.

**Comment by philipanda** [comment]
The screens for deleting DB and KEK certs are human readable on NV41PZ Dasharo v1.8.0-rc8.
![Image](https://github.com/user-attachments/assets/91ede7d0-6acf-42d6-ac92-4340ec014659)
![Image](https://github.com/user-attachments/assets/7c70c573-9050-472c-b7f9-90943268a0e0)
