### ISSUE TITLE
Propose password policy based on current standards

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#646]
### The problem you're addressing (if any)

The current password requirements are very strict and won't allow someone to use passphrases (because you need uppercase, lowercase, special, numeric, symbol(?) characters

It has been shown that strict password requirements cause people to re-use their passwords or use shorter ones because they simply can't remember so many complex strings of text, making their overall security *lower*: https://www.enzoic.com/blog/the-benefits-and-drawbacks-of-password-complexity-rules/

### Describe the solution you'd like

Remove or loosen the password requirements

### Where is the value to a user, and who might that user be?

People who use passphrases
People who are okay with using less secure passwords

### Describe alternatives you've considered

FIDO2 auth in setup menu?

### Additional context

https://neal.fun/password-game/

The password requirement code was imported completely from edk2-platforms without much thought if we want to actually have these requirements

**Comment by macpijan** [comment]
Mandatory XKCD: https://xkcd.com/936/

**Comment by miczyg1** [comment]
Not understanding the value of security, or being lazy, should never be a reason to weaken the security.

Personally, to make the password more memorable, I use `$` instead of `S` or `3` instead of `E` or `@` instead of `a` in casual words.

**Comment by mkopec** [comment]
And now we know which characters to include in the dictionary when bruteforcing your passwords ;)

**Comment by macpijan** [comment]
I hope it is a bait I missed

**Comment by miczyg1** [comment]
> And now we know which characters to include in the dictionary when bruteforcing your passwords ;)

Good luck. Except that I mainly use the generated passphrases from bitwarden-like apps

But in case like these where you need to memorize something, It may be good. And I just gave a few examples. There are more symbol I use, not necessarily in place of regular characters in words

**Comment by mkopec** [comment]
I guess I'll need to look for peer-reviewed studies showing the impact of password requirements here to show my point.

**Comment by macpijan** [comment]
Password policy is very common topic, we should just look at existing standards, here are some references: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls

Maybe we should change the title  of the issue to less-triggerring one, like "Propose password policy based on current standards" ;)

**Comment by pietrushnic** [comment]
> Not understanding the value of security, or being lazy, should never be a reason to weaken the security.

https://en.wikipedia.org/wiki/False_consensus_effect

**Comment by miczyg1** [comment]
> > Not understanding the value of security, or being lazy, should never be a reason to weaken the security.
> 
> https://en.wikipedia.org/wiki/False_consensus_effect

Sounds like something that can be applied to anything. So be it.

**Comment by miczyg1** [comment]
Just for reference, AMI:

![image](https://github.com/Dasharo/dasharo-issues/assets/30656491/de1b644b-9f6c-44d9-b6b9-63533dc4a9fc)

**Comment by pietrushnic** [comment]
I guess this is an antipattern we should not follow.

**Comment by rafkoch** [comment]
When is this issue planned to be implemented, i.e. when will Dasharo accept passphrases as USER or ADMIN password?

**Comment by macpijan** [comment]
@BeataZdunczyk That should be not that difficult change, can we plan to include in the next releases?

**Comment by philipandag** [comment]
Working on the issue here:
https://github.com/Dasharo/edk2/pull/152

**Comment by philipandag** [comment]
https://github.com/Dasharo/edk2/pull/152
https://github.com/Dasharo/docs/pull/857
PRs are merged, closing the issue.

**Comment by rafkoch** [comment]
I do not understand whether DASHARO supports or does not support PASSPHRASES, because the screenshot mentions the old requirements (lowercase, uppercase, aplhabetic, number,...) while under this screenshot in the description it already mentions the requirement of lowercase letters only.

1. screenshot on docs. dasharo.com [link1](https://docs.dasharo.com/dasharo-menu-docs/overview/#user-password-management:~:text=of%20your%20platform.-,User%20Password%20Management,-User%20Password%20Management):
![image](https://github.com/user-attachments/assets/227b45f4-c3a1-4237-8468-e30361cd5fed)

2. description under this screenshot [link2](https://docs.dasharo.com/dasharo-menu-docs/overview/#dasharo-menu-guides:~:text=setup%20admin%20password%3A-,The%20password%20requirements%20are%20compliant%20to%20modern%20standards.%20See%20Appendix%20A,current%20status%20of%20Admin%20Password%20if%20it%20is%20provisioned%20or%20not.,-To%20disable%20the):
![image](https://github.com/user-attachments/assets/c6ed9673-74da-45d1-939e-8d436b8b3d0c)

**Comment by mkopec** [comment]
Screenshot wasn't updated, but password requirements were loosened to allow for passphrases

**Comment by rafkoch** [comment]
So. I'm waiting to replace the screenshot until it is consistent with the description under it.

**Comment by rafkoch** [comment]
@BeataZdunczyk @mkopec we are still waiting for replacement the screenshot until it is consistent with the description under it.

**Comment by wiktormowinski** [comment]
my bad, @rafkoch https://github.com/Dasharo/docs/pull/942

**Comment by mkopec** [comment]
https://www.engadget.com/2017-08-08-nist-new-password-guidelines.html

**Comment by philipanda** [comment]
New password policy is present on NV41PZ Dasharo v1.8.0-rc8

<img width="1920" height="1440" alt="Image" src="https://github.com/user-attachments/assets/905f365d-96b3-48b3-badc-1792925e480d" />
