### ISSUE TITLE
Loss of logo when updating firmware using a USB memory stick?

### ISSUE THREAD

**Issue by jeltsch** [Dasharo/dasharo-issues#652]
**Dasharo version**

The current one

**Dasharo variant**

The one for NV4x 12th Gen

**Question text**

Somewhere in the Dasharo documentation I read that, when building certain firmware updating software from source, updating the firmware will result in the loss of the logo (right now I can’t find the place where I read this, as the Dasharo documentation is somewhat convoluted with its many little bits and lots of cross links). My question is whether the logo is lost also when updating the firmware using a USB memory stick with an image from https://github.com/Dasharo/meta-dts/releases.

**Comment by pietrushnic** [comment]
> the Dasharo documentation is somewhat convoluted with its many little bits and lots of cross links

As always, the contribution is welcome. Feel free to suggest improvements as separate issues or contribute to https://github.com/Dasharo/docs

Please point us to high-quality documentation examples that you feel are easy to work with. I doubt competing open-source firmware or BIOS documentation exists, but I can easily be wrong here.

> The current one

Please be precise; we have no idea what is `The current one` for you at that moment in time, and that information may change over time if this question is not be answered.

@macpijan @BeataZdunczyk I'm looking in test cases and see that despite being automated, `LCM004.001: Custom logo persists after firmware update` was not tested against any existing version for NV4x 12th Gen

**Comment by wessel-novacustom** [comment]
This is a [known issue](https://github.com/Dasharo/dasharo-issues/issues/586) that will be solved with the next release of Dasharo Tools Suite, @macpijan can possibly confirm. Hence, I believe this is a duplicate and the issue should be closed.

If needed, we can [provide assistance](https://novacustom.com/contact/) to replace the boot logo, or you can change the boot logo by following [this documentation](https://docs.dasharo.com/guides/logo-customization/).

**Comment by jeltsch** [comment]
> > the Dasharo documentation is somewhat convoluted with its many little bits and lots of cross links
> 
> As always, the contribution is welcome. Feel free to suggest improvements as separate issues or contribute to https://github.com/Dasharo/docs

It would already help to have the following:
* A single document with numbered sections, subsections, etc. (of which a multi-web-page version can exist as well, of course)
* A structure that is not so deeply nested (something like Document » Section » Subsection, with the latter being optional)
* Consistency between the entries in the table of contents on the left and the actual headlines
* URLs also for documents and parts of documents that are further divided into parts (Currently, clicking on the respective menu entries just unfolds the submenus. No URLs for the whole collections exist, which makes it impossible to bookmark them or link to them from other documents.)

> > The current one
> 
> Please be precise; we have no idea what is `The current one` for you at that moment in time, and that information may change over time if this question is not be answered.

At the moment, I’m not yet using Dasharo firmware; so there is none that I currently use. I meant the one currently offered by you. I understood GitHub issues in this category to be questions that are answered soon, so that the problem of changing versions isn’t really present.

**Comment by jeltsch** [comment]
I just wanted to turn my suggestions for documentation improvement above into a dedicated issue. Then I had to see that the format of feature requests forces such requests to be very extensive, containing such specific things as “Where is the value to a user, and who might that user be?”. Should I really explain the value of properly structured documentation?

@pietrushnic, it has happened repeatedly now that I pointed out problems and in response you asked me to do (part of) the work. That’s maybe the open-source (not the free-software) approach. I suggest to follow a more classical approach: strive more to deliver top-quality output in the first place, not to deliver substandard output and then have users point out problems. Certain knowledge, like how to better structure documentation or why to use TLS for delivering machine code that is to be executed with ring-0 privileges, can be obtain on one’s own initiative, without help from users.

**Comment by jeltsch** [comment]
> This is a [known issue](https://github.com/Dasharo/dasharo-issues/issues/586) that will be solved with the next release of Dasharo Tools Suite, @macpijan can possibly confirm.

I just looked at the issue description. I understand that upon firmware update the logo doesn’t disappear but is instead reset to the NovaCustom logo. Well, that’s not an issue for me, since I have a laptop with the NovaCustom logo.

> Hence, I believe this is a duplicate and the issue should be closed.

It’s not really meant to be an issue, as it doesn’t point out a problem or deficiency I’ve spotted. I just wanted to ask the Dasharo team a question, and they use GitHub issues for questions also. That said, I think I’ve indirectly received my answer through you pointing to #586, and thus this present “issue” can probably really be closed.

**Comment by jeltsch** [comment]
> @pietrushnic, it has happened repeatedly now that I pointed out problems and in response you asked me to do (part of) the work. That’s maybe the open-source (not the free-software) approach. I suggest to follow a more classical approach: strive more to deliver top-quality output in the first place, not to deliver substandard output and then have users point out problems. Certain knowledge, like how to better structure documentation or why to use TLS for delivering machine code that is to be executed with ring-0 privileges, can be obtain on one’s own initiative, without help from users.

Sorry for this response being somewhat harsh. However, it *really* feels bad to repeatedly get the impression that 3mdeb wants to shield itself from criticism and is telling people who point out problems that they first have to do some unpaid work for 3mdeb before 3mdeb will take their criticism serious. That’s certainly not the feeling of being treated as a customer. Well, I’m not directly 3mdeb’s customer. Maybe that’s my problem. However, I understand that as a customer of one of 3mdeb’s customers, I still should ask certain questions to 3mdeb directly, especially if they directly concern the Dasharo documentation.
