### ISSUE TITLE
QubesOS set rtc wake alarm failed

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#655]
### Device

MSI Z690-A WiFi DDR4 ADL

### Dasharo version

v1.1.3

### Brief summary

`rtcwake --mode no --seconds 60` returns `rtcwake: set rtc wake alarm failed: Invalid argument`

### How reproducible

100%

### How to reproduce

Execute `rtcwake --mode no --seconds 60`  as specified in [Platform suspend test](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31M-platform-suspend-and-resume/#susp001003-platform-suspend-and-resume-qubesos-wakeup-flag)

### Expected behavior

The RTC timer wake alarm should get set

### Actual behavior

Error message gets displayed

**Comment by miczyg1** [comment]
https://github.com/Dasharo/dasharo-issues/issues/484 duplicate
