### ISSUE TITLE
CPU frequency not displayed for i7-14700K

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#662]
### Device

MSI Z690-A DDR4

### Dasharo version

v1.1.3

### Affected component(s) or functionality

SMBIOS information, setup front page information

### Brief summary

The CPU frequency is 0GHZ for i7-14700K when looking at the setup front page. The same goes for SMBIOS type 4 current speed.

### How reproducible

Always

### How to reproduce

1. Enter setup and notice CPU frequency is 0 GHz

### Expected behavior

CPU frequency displays a valid value.

### Actual behavior

Frequency is 0 GHz

### Screenshots

![image](https://github.com/Dasharo/dasharo-issues/assets/30656491/df587770-2291-4725-b83d-a9d419bef66f)

**Comment by miczyg1** [comment]
The CPU frequency is taken from CPUID leaf 0x16: https://github.com/Dasharo/coreboot/blob/dasharo/src/arch/x86/smbios.c#L166

However, when `cpuid_eax(0x16);` is called inside the loop, the value returned is zero (despite it was NOT zero in the IF condition). Surprisingly, `cpuid_ecx(0x16);` returns a correct value of 100MHz when assigned to `t->external_clock`. Could it be that when  `cpuid_eax(0x16);` is called, ECX is not zero and ucode returns some weird result?

@andyhhp maybe you have some insights on this weird behavior.

**Comment by miczyg1** [comment]
Changing the code to something like this of course helps:

```
	if (cpu_have_cpuid() && cpuid_get_max_func() >= 0x16) {
		res = cpuid(0x16);
		if (res.eax != 0 && res.ecx != 0) {
			t->current_speed = res.eax; /* base frequency */
			t->external_clock = res.ecx;
		} else {
			t->current_speed = smbios_cpu_get_current_speed_mhz();
			t->external_clock = smbios_processor_external_clock();
		}
	} else {
		t->current_speed = smbios_cpu_get_current_speed_mhz();
		t->external_clock = smbios_processor_external_clock();
	}
```

Now both values are retrieved in one CPUID call and it works. But behavior described in the issue is rather unexpected.+

**Comment by andyhhp** [comment]
So yeah, suffice it to say that Intel's first attempts at populating leaf 0x15/0x16 weren't so great.

This has been documented around in the SDM (Vol 3, 20.7.3 "Determining the Processor Base Frequency") with some numbers to fill in in place of 0's.

I also suggest reading `arch/x86/kernel/tsc_msr.c` and parts of `tsc.c` (latter, for this specific case) which cover all of the stupidities that I'm aware of in this area.

**Comment by miczyg1** [comment]
Ohh the problem is the same for i5-13600K... Possibly a bug in microcode? Because previous Dasharo version did not show this behavior,

**Comment by renehoj** [comment]
My i9-13900K is displaying the correct 3 GHz base clock speed.

**Comment by renehoj** [comment]
No, I'm using the old version, my bad.

**Comment by andyhhp** [comment]
> Ohh the problem is the same for i5-13600K... Possibly a bug in microcode? Because previous Dasharo version did not show this behavior,

Here's a silly question...  Are the data returned from leaf 15/16 unstable if you sample them repeatedly?  I've just re-read your original description, and assuming there's no bad `asm()` for the CPUID primitive itself (it looks fine at a glance), getting different results like that is weird.

For a SoC, it will be a sideband access, (See [SRBDS](https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/technical-documentation/special-register-buffer-data-sampling.html) and the follow-on [MMIO Sampling](https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/advisory-guidance/processor-mmio-stale-data-vulnerabilities.html))

The old code was making four requests back-to-back to get half of 1 replies worth of data.  I wonder if there's some synchronisation behind the scenes which doesn't work properly with back-to-back accesses.

CPUID instructions themselves are very expensive in general (and two orders of magnitude worse under virt) so leaves should only ever be gotten once, and then spilled onto the stack.  The newer code is definitely better, although
```c
	if (cpu_have_cpuid() && cpuid_get_max_func() >= 0x16 &&
	    (res = cpuid(0x16), res.eax && res.ecx)) {
		t->current_speed = res.eax; /* base frequency */
		t->external_clock = res.ecx;
	} else {
		t->current_speed = smbios_cpu_get_current_speed_mhz();
		t->external_clock = smbios_processor_external_clock();
	}
```
would reduce the complexity further, but you still really want to cache `cpuid_get_max_func()` once and read it out of a variable.

**Comment by miczyg1** [comment]
>  (res = cpuid(0x16), res.eax && res.ecx)

I dislike this kind of syntax, reminds me of decompilers :) Harder to read the conditions.

> Here's a silly question... Are the data returned from leaf 15/16 unstable if you sample them repeatedly?

The silly answer is... No. If I call the cpuid repeatedly from UEFI Shell or Linux terminal, nothing bad happens, results are consistent.

> I've just re-read your original description, and assuming there's no bad asm() for the CPUID primitive itself (it looks fine at a glance), getting different results like that is weird.

My asm-fu is not so good, so I suspected there might be some trivial bug there... This is the one: https://github.com/Dasharo/coreboot/blob/dasharo/src/arch/x86/include/arch/cpuid.h

> For a SoC, it will be a sideband access, (See [SRBDS](https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/technical-documentation/special-register-buffer-data-sampling.html) and the follow-on [MMIO Sampling](https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/advisory-guidance/processor-mmio-stale-data-vulnerabilities.html))

These are desktop platforms with discrete chipset and CPU socket.

> CPUID instructions themselves are very expensive in general (and two orders of magnitude worse under virt) so leaves should only ever be gotten once, and then spilled onto the stack.

Good to know. Thanks. There are a lot of inefficiencies in CPUID regard in coreboot then.

**Comment by miczyg1** [comment]
This is what I also suspected in my earlier comment:

> Could it be that when cpuid_eax(0x16); is called, ECX is not zero and ucode returns some weird result?

But haven't looked at disassembled code via objdump.

**Comment by andyhhp** [comment]
If some leaves that are documented as not taking a subleaf input really are sensitive to `%ecx` then that's something that Intel needs to fix.

**Comment by miczyg1** [comment]
Also present on 12th gen:
![image](https://github.com/Dasharo/dasharo-issues/assets/30656491/50d17d88-3e13-4611-b55f-189b343d17a3)

And on the [most recent microcode](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20231114)

**Comment by andyhhp** [comment]
Found it.  It's a real inline asm error.  `cpuid_e[bcd]x()` don't mark eax as clobbered.  (cpuid_eax does, because of the "+" constraint).

Notice how `%eax` isn't realoaded from `%esi` between:
```asm
 402b429:	0f a2                	cpuid  
 402b42b:	85 c9                	test   %ecx,%ecx
 402b42d:	74 0f                	je     402b43e <smbios_write_type4+0x279>
 402b42f:	0f a2                	cpuid  
```

So you're invoking CPUID with garbage input, and for Intel, that means (return the data from max leaf), not something helpful like all zeros...

**Comment by andyhhp** [comment]
Seems it was broken by https://github.com/Dasharo/coreboot/commit/516eff01e61155a681a4f684515ae7924b9bff0d

**Comment by andyhhp** [comment]
Fixed by https://review.coreboot.org/c/coreboot/+/78192 by the looks of things

**Comment by andyhhp** [comment]
but you should definitely swap the 4xCPUID for a single CPUID irrespective

**Comment by pietrushnic** [comment]
@krystian-hebel I'm not sure if you are aware of this discussion.

**Comment by miczyg1** [comment]
@andyhhp thanks for looking into that such extensively. Will try cherry-picking this patch and see if it helps.

**Comment by krystian-hebel** [comment]
> @krystian-hebel I'm not sure if you are aware of this discussion.

I am now, was wondering about which issue discussion on Matrix was about.

> but you should definitely swap the 4xCPUID for a single CPUID irrespective

Agreed, CPUID messes up the pipeline by serializing the execution, not something that is needed in this case.

**Comment by andyhhp** [comment]
Sorry for the confusion.  Yes, this was the same issue that I was discussing on Matrix.  (And thankyou @krystian-hebel for the gerrit link in the first place).

I'd also recommend turning `cpu_has_cpuid` into a build time constant (It only needs to be variable when you're targeting a 486 platform.  Anything newer is compile time `true` and anything older is compile time `false`.

Also cache `cpuid_get_max_func()` once at the start of day (after clobbering the NT-4 compatibility hack which limits max_leaf to 3 on appropriate platforms), because it doesn't change after that.

You will probably be able to measure an improvement in boot performance, and the compiled result will definitely be smaller.

**Comment by macpijan** [comment]
@miczyg1 wasn't this improved? I see no linked PRs

**Comment by miczyg1** [comment]
@macpijan it was cherry-picked to dasharo-4.21: https://github.com/Dasharo/coreboot/commit/2c5426c38f0f8a4ec75fc9e4b9642c4eb5ff009a
