### ISSUE TITLE
Throttling temperature as UEFI setting

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#663]
### The problem you're addressing (if any)

Multiple people have different preferences when it comes to thermal throttling. Some prefer the laptop to be absolutely silent, while others prefer maximum performance.

### Describe the solution you'd like

I would like to have a UEFI setting where you can set the throttling temperature. I am not sure about the settings one should be able to set, but I was thinking about 70/75/80 (default)/85/90.

### Where is the value to a user, and who might that user be?

Users can choose between better performance by selecting a higher throttling temperature and a more silent computer by selecting a lower throttling temperature.

### Describe alternatives you've considered

A software solution, but this doesn't seem to be a decent solution for me.
A custom build with , but this is hard to get for regular end users that don't have much experience with firmware building.

### Additional context

It looks like the throttling temperature can easily be set in GNU/Linux:

https://github.com/Dasharo/dasharo-issues/issues/596#issuecomment-1884657279

I'm not sure though how persistent this would be?

**Comment by ubuntushopdoteu** [comment]
i can set this permanent with a systemd service, but what are the parameters? 
echo 25 | sudo tee /sys/class/thermal/cooling_device18/cur_state is less fan
default on the nv40 notebook is 20 (and too loud)
25 is better, but what about 30?
I do not find a link between these numbers(20,25,30,,,) and the temp.

**Comment by miczyg1** [comment]
@ubuntushopdoteu these values are just an offset from TJmax temperature (or critical temperature when we refer to ACPI cooling devices) when the CPU should start throttling. TJmax is the junction temperatures, product-specific. E.g. if TJMax=100 Celsius degrees, an offset of 20 would mean the throttling start temperature would be 80 Celsius degrees.

**Comment by mkopec** [comment]
You can also use `turbostat -T [temperature]` to set the desired temperature directly.

**Comment by wessel-novacustom** [comment]
> You can also use `turbostat -T [temperature]` to set the desired temperature directly.

Is that possible in Qubes OS, too?

**Comment by renehoj** [comment]
In Qubes OS, you don't have access to the physical CPU. You can't change the speed, without using the xenpm util, you also can't read the core temperature.

**Comment by mkopec** [comment]
The first release with this feature is scheduled for release today. Closing as completed.
