### ISSUE TITLE
asus_kgpe-d16: hardware write protection not works

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#67]
**Dasharo version**
asus_kgpe-d16_v0.3.0

**Dasharo variant**
ASUS KGPE-D16

**Affected component(s) or functionality**
Write Protection Mechanism

**Brief summary**
Write Protection Mechanism does not work on the platform ASUS KGPE-D16 with 16MB flash chip.

**How reproducible**
Always

**How to reproduce**

1.  Build flashrom in accordance with the following documentation: https://docs.dasharo.com/variants/asus_kgpe_d16/spi-wp/ 
2.  Try to use any of described in the above-mentioned documentation commands to set or read WP.

**Expected behavior**
Hardware Write protection works on ASUS KGPE-D16 with 16MB flash chip.

**Actual behavior**
Hardware Write protection does not work on ASUS KGPE-D16 with 16MB flash chip.

**Screenshots**

```
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
coreboot table found at 0xbfd56000.
Found chipset "AMD SB7x0/SB8x0/SB9x0".
Enabling flash write... OK.
Error accessing GD25Q256D, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip GD25Q256D at 0x00000000fe000000.
Error accessing IS25LP256, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip IS25LP256 at 0x00000000fe000000.
Error accessing IS25WP256, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip IS25WP256 at 0x00000000fe000000.
Error accessing MX25L25635F/MX25L25645G, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip MX25L25635F/MX25L25645G at 0x00000000fe000000.
Error accessing MX25U25635F, 0x2000000 bytes at 0x00000000fe000000
    [ Message content over the limit has been removed. ]
/dev/mem mmap failed: Operation not permitted
Could not map flash chip W25Q256JV_M at 0x00000000fe000000.
Error accessing W25Q256.W, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip W25Q256.W at 0x00000000fe000000.
Error accessing W25Q256JW_DTR, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip W25Q256JW_DTR at 0x00000000fe000000.
Error accessing W25Q512JV, 0x4000000 bytes at 0x00000000fc000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip W25Q512JV at 0x00000000fc000000.
Error accessing XM25QH256C, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip XM25QH256C at 0x00000000fe000000.
Error accessing XM25QU256C, 0x2000000 bytes at 0x00000000fe000000
/dev/mem mmap failed: Operation not permitted
Could not map flash chip XM25QU256C at 0x00000000fe000000.
Error: write protect support is not implemented for this flash chip.
```

**Additional context**

**Solutions you've tried**
1. Rebuild the flashrom tool.

**Comment by SergiiDmytruk** [comment]
`Error: write protect support is not implemented for this flash chip.` means that the chip was identified, but code lacks implementation of WP for it.

The code used for testing was still in review and has changed before landing in `master`. In particular WP metadata wasn't specified for `W25Q128.V..M` at the time, but it there now. Testing with current `master` should work for this variation of `W25Q128FV`.

**Comment by PrzemyslawBanasiak13** [comment]
I've built `flashrom` from [this branch](https://github.com/Dasharo/flashrom/pull/7/files), and write protection works properly

**Comment by Pokisiekk** [comment]
Work also with flashrom built from [this branch](https://github.com/3mdeb/flashrom/tree/wp-for-more-chips)
