### ISSUE TITLE
OS-level access to CBMEM

### ISSUE THREAD

**Issue by krystian-hebel** [Dasharo/dasharo-issues#69]
**The problem you're addressing (if any)**
After fixing memory reservation in the device tree generation code, CBMEM is no longer accessible from operating system. Previously it was marked as usable, non-reserved RAM and could be read as long as nothing overwrote it.

**Describe the solution you'd like**
It is mainly required by `cbmem` util from coreboot. This utility should be able to access CBMEM region either by `mmap`ing it directly or by accessing some file exposed by kernel.

**Where is the value to a user, and who might that user be?**
CBMEM holds various pieces of information about firmware, like console log or timestamps.

**Describe alternatives you've considered**
- it may be possible to mark this range as “reserved but `mmap`able” memory in device tree (note that skiboot, skiroot and final OS' kernel may modify it)
- Creating new kernel driver
- Enabling [Google’s driver](https://github.com/torvalds/linux/blob/master/drivers/firmware/google/Kconfig#L22) for other platforms, additional changes may be required

**Comment by sulewskiprzemyslaw** [comment]
@SergiiDmytruk I see, that CBMEM currently works on the platform flashed with v0.6.0 binary. I have one question: if the coreboot timestamps should be available?

When I execute the following command:

`
./git/coreboot/util/cbmem/cbmem -T
`

In the output I see:
`
No timestamps found in coreboot table
`

**Comment by SergiiDmytruk** [comment]
@sulewskiprzemyslaw No, timestamps aren't enabled. `.config` has this line:
```
# CONFIG_COLLECT_TIMESTAMPS is not set
```

**Comment by sulewskiprzemyslaw** [comment]
@SergiiDmytruk ok, thank you for the information.

**Comment by tlaurion** [comment]
CONFIG_COLLECT_TIMESTAMPS=y

Should be set otherwise speed comparison will not be possible.

**Comment by miczyg1** [comment]
Definition from Kconfig:
```
config COLLECT_TIMESTAMPS
	bool "Create a table of timestamps collected during boot"
	default y if ARCH_X86
```

So all x86 boards will have it. Is there a reason why POWER would not select it?

**Comment by krystian-hebel** [comment]
I don't know if QEMU would support timer in current state, this would need testing. Other than that, we can enable it.

**Comment by miczyg1** [comment]
We can either make it read-write and not reserve it or reserve it and do not let any access. Possible ideas

1. Adding some entry in DT
2. Modifying skiboot

**Comment by SergiiDmytruk** [comment]
https://github.com/Dasharo/coreboot/pull/197 was fixing this, but it's still open.

**Comment by tlaurion** [comment]
I think a different approach was taken since then? Confused but I think its now correctly exposed in read only now

**Comment by SergiiDmytruk** [comment]
The commit that excludes cbmem from available memory is there, so it basically works the same.  Endianness and DT stuff is done differently, but looks like the kernel can now see TPM log which used to cause issues.

**Comment by krystian-hebel** [comment]
> [Dasharo/coreboot#197](https://github.com/Dasharo/coreboot/pull/197) was fixing this (although not in `.../develop`), but it's still open.

@SergiiDmytruk you are correct. For some reason I think I saw it just added entries to FDT "memreserve" fields instead of creating DT "/reserved-memory/coreboot@%llx" nodes, in which case Skiboot wouldn't mark it as reserved and OS would be allowed to overwrite it. Maybe it was on `develop` :thinking:

**Comment by SergiiDmytruk** [comment]
> but looks like the kernel can now see TPM log which used to cause issues.

Nope, the necessary changes seem to be there, some commits just got squashed.

**Comment by miczyg1** [comment]
Awaiting for the automated tests to be ready to close the issue

**Comment by BeataZdunczyk** [comment]
This issue is fixed with https://github.com/linuxboot/heads/pull/1313 and is part of the 0.7.0 release, which was published here: https://docs.dasharo.com/variants/talos_2/releases/#v070-2023-07-26
