### ISSUE TITLE
Wrong path to the grub.cfg for DTS

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#691]
![dts-issue](https://github.com/Dasharo/dasharo-issues/assets/46576094/aa489754-fdaf-4d3b-9595-c69a5482f1f8)

Happened when booting a DTS ISO burned to a USB stick

Official DTS instructions are for using dd on Linux. The Windows tool that was used to make the affected USB Flash Drive was Rufus. And Rufus by default have ideas of its own:
https://github.com/pbatard/rufus/wiki/FAQ#why-doesnt-rufus-create-a-windows-installation-usb-that-can-be-booted-in-dual-biosuefi-mode
https://github.com/pbatard/rufus/wiki/FAQ#why-doesnt-rufus-recommend-dd-mode-over-iso-mode-for-isohybrid-images-surely-dd-is-better

**Comment by Firminator** [comment]
I guess that's a hot topic, but I'd apprecite Pete's decade of experience with creating bootable USB flash drives for BIOS, CSM, UEFI devices and dealing GPT, MBR, ISO, and ISOHYBRID issues. He's surely an expert in his field.

**Comment by DaniilKl** [comment]
@TomaszAIR, I could not reproduce this issue. Could you please gime mo details and verify the steps I have made to reproduce the issue?

Flashing steps:
1) Download `rufus-4.4`
2) Download DTS `.iso` image version `1.2.19` from its GitHub
3) Flash an USB drive using ISO flashing in `rufus`:
Clipboard_2024-03-12-14-57-15.png
4) Boot the USB flash drive.

USB drive structure after flashing:

```bash
/mnt
├── autorun.ico
├── autorun.inf
├── bzImage
├── EFI
│   └── BOOT
│       ├── bootx64.efi
│       └── grub.cfg
├── efi.img
├── initrd
├── isolinux
│   ├── boot.cat
│   ├── isolinux.bin
│   ├── isolinux.cfg
│   ├── ldlinux.c32
│   ├── libcom32.c32
│   ├── libutil.c32
│   └── vesamenu.c32
├── ldlinux.sys
├── rootfs.img
├── startup.nsh
├── syslinux.cfg
└── System Volume Information
    ├── IndexerVolumeGuid
    └── WPSettings.dat
5 directories, 20 files
```

**Comment by TomaszAIR** [comment]
@DaniilKl I think that this are exact steps that are needed to reproduce the problem. I did not have it, the description is just a message from matrix channel.

I think we could get back to this when we will be working on making ISO image usable once more. Right now it is removed from release artifacts.

**Comment by macpijan** [comment]
ISO is not supported anymore.
