### ISSUE TITLE
Why Protectli devices don't have Coreboot setup password?

### ISSUE THREAD

**Issue by 0x192** [Dasharo/dasharo-issues#695]
I saw from browsing the documentation [that some versions of Dasharo](https://github.com/search?q=repo%3ADasharo%2Fcoreboot+CONFIG_EDK2_SETUP_PASSWORD&type=code) provide the option to set a UEFI setup password.

[Some protecli devices](https://docs.dasharo.com/variants/protectli_vp46xx/test-matrix/) have `Secure Boot` and `BIOS Lock` support which is great but without a password protection for Dasharo, it is really easy for a evil maid attacker to just disable those features and tamper the firmware / OS / bootloader.

Is there anything stopping you from adding this feature (which you already support on other devices)?

I saw that new Protecli devices will be released (VP6630/VP6650/VP6670) [by looking at your latest commits](https://github.com/Dasharo/docs/pull/746/files) and I'm looking forward to them. Is Dasharo password protection something we can expect? That would be fantastic.

Thank you for your impressive work on Dasharo Coreboot. Open-source firmware are really important. :1st_place_medal:

**Comment by 0x192** [comment]
Actually, Proctecli Devices have verified boot enabled but the recovery partition is not protected with a SPI write protection. Without this security feature, just adding Dasharo password setup protection is a bit pointless as a malicious actor can simply flash a malicious firmware on the recovery partition.

I see this is also something you already implemented on other devices : https://docs.dasharo.com/variants/asus_kgpe_d16/spi-wp/

I'm not sure if **BIOSWE** will be disabled and **SMM_BWP** enabled on these new Protectli devices but if so (correct me if I'm wrong), they would only be vulnerable to an SPI unsoldering attack (and unknown vulnerabilities of course). Sounds pretty good! :slightly_smiling_face:

**Comment by macpijan** [comment]
> Is there anything stopping you from adding this feature (which you already support on other devices)?

No technical limitations. Integrating features is some effort, validating them is another one. So it is the decision of board sponsor (be it a client as Protectli, or 3mdeb/community in case of the community releases) which features are supported in certain releases. 

> I saw that new Protecli devices will be released (VP6630/VP6650/VP6670) [by looking at your latest commits](https://github.com/Dasharo/docs/pull/746/files) and I'm looking forward to them. Is Dasharo password protection something we can expect? That would be fantastic.

The password feature is planned for this new VP series.

> Actually, Proctecli Devices have verified boot enabled but the recovery partition is not protected with a SPI write protection. Without this security feature, just adding Dasharo password setup protection is a bit pointless as a malicious actor can simply flash a malicious firmware on the recovery partition.

`Lock the BIOS boot medium` and `SMM protection` from [security features](https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#dasharo-security-options) provide a similar level of protection, preventing OS-level access to the SPI flash.

The ability to use physical protection via WP pin depends on the board design, and is unfortunately impractical in many cases. The new designs, however, are planned to include programming header for SPI, so application of WP jumper could be potentially feasible.

**Comment by 0x192** [comment]
> Integrating features is some effort, validating them is another one. So it is the decision of board sponsor (be it a client as Protectli, or 3mdeb/community in case of the community releases) which features are supported in certain releases.

Perfectly understandable.

> The password feature is planned for this new VP series.

Awesome!

> `Lock the BIOS boot medium` [...] from [security features](https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#dasharo-security-options)

Is this feature the same as [`Bios Lock`](https://docs.dasharo.com/unified-test-documentation/dasharo-security/20J-bios-lock-support/) and only corresponds to the BIOS Lock Enable bit (`BLE`)?

> The new designs, however, are planned to include programming header for SPI, so application of WP jumper could be potentially feasible.

This is good to hear. Thanks for your response!

**Comment by macpijan** [comment]
The setup password feature heas been added in the 1.2.0 release for the VP46X0 series: https://docs.dasharo.com/variants/protectli_vp46xx/releases/#v120-2024-03-25

**Comment by macpijan** [comment]
If the questions was not answered, please comment/reopen.
