### ISSUE TITLE
FADT PM Profile is unspecified/0

### ISSUE THREAD

**Issue by jpnssl** [Dasharo/dasharo-issues#696]
### Device

NovaCustom NS5x_NS7xPU

### Dasharo version

v1.7.2

### Affected component(s) or functionality

ACPI / FADT, potentially userspace power management

### Brief summary

FADT PM Profile is set to 0 (unspecified) instead of 2 (mobile)

### How reproducible

always

### How to reproduce

$ cat /sys/firmware/acpi/pm_profile

### Expected behavior

The command should return 2, indicating that the FADT PM profile is set to mobile.

### Actual behavior

The actual return value is 0. (unspecified)

### Additional context

In an upcoming release, power-profiles-daemon will begin to [change the CPU governor to performance](https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/commit/5fd9d0e6ddf4b9aca6f80315343e4d101cdc8234) if the value of /sys/firmware/acpi/pm_profile is 0. [Similar logic](https://github.com/torvalds/linux/commit/32f80b9adfdb43f8af248596724f59dde938a190) is already present the kernel. While this is currently only the case for amd-pstate, it might make sense to fix this just in case the intel-pstate driver receives similar treatment in the future.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/coreboot/pull/459

**Comment by miczyg1** [comment]
@jpnssl thanks for reporting it
