### ISSUE TITLE
Cannot perform initial deployment for NovaCustom NV4x TGL with DTS v1.2.18

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#699]
### Device

NovaCustom NV4x TGL

### Dasharo version

DTS 1.2.18 (others probably too)

### Affected component(s) or functionality

Dasharo initial deployment

### Brief summary

Initial deployment fails, because flashrom cannot install EC

### How reproducible

Always

### How to reproduce

Perform initial deployment on NV4xME/MB/MZ

### Expected behavior

Deployment successful

### Actual behavior

EC firmware is not installed.

### Screenshots

```
failed to connect to EC: Io(Custom { kind: NotFound, error: "Failed to find Dasharo ACPI device" })
ITE EC programmer not (yet) supported on this device
Probing on unsupported laptop may irritate your EC and cause fan failure, backlight failure and sudden poweroff.
You can force probing with "-p ite_ec:boardmismatch=force".
Aborting...
Error: Programmer initialization failed.
```

### Additional context

Previously we used ec_transition to perform the installation of EC. This script had the followigjn flags for flashrom EC programmer `ite_ec:boardmismatch=force,romsize=128K,autoload=disable`. These should be used on all NvaCustom devices for the initial deployment but somehow they are not present in `dts-functions.sh` used by `dasharo-deploy update` which is called during installation of Dasharo firmware on NovaCustom laptops with proprietary firmware.

**Comment by DaniilKl** [comment]
The problem has been fixed in https://github.com/Dasharo/meta-dts/pull/100 . The fix will be added in the future release.

**Comment by artur-rs** [comment]
Release v1.2.20 is now live - see the changelog [here](https://github.com/Dasharo/meta-dts/blob/main/CHANGELOG.md#v1220---2024-03-19).
