### ISSUE TITLE
  TPM not detected by V1210 under Windows

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#700]
### Device

v1210

### Dasharo version

Dasharo v0.9.2

### Affected component(s) or functionality

```
PS C:\Users\user> get-tpm
[...]
TpmPresent : False
TpmReady : False
TpmEnabled : False
[...]
```
```
PS C:\Users\user> wmic /namespace:\\root\cimv2\security\microsofttpm path win32_tpm get * /format:textvaluelist.xsl
No Instance(s) Available.
```
```
PS C:\Users\user> tpmtool getdeviceinformation
Failed to get information.
Command failed with 0x800710df - The device is not ready for use.
```

### Brief summary

TPM not detected by V1210 under Windows

### How to reproduce

Run the tests:
https://docs.dasharo.com/unified-test-documentation/dasharo-security/200-tpm-support/

### Expected behavior

TPM Support under Windows

### Actual behavior

TPM not detected under Windows

### Screenshots

[tpm-support_log.zip](https://github.com/Dasharo/dasharo-issues/files/14207245/tpm-support_log.zip)

**Comment by miczyg1** [comment]
Right, I think I know what went wrong: https://github.com/Dasharo/coreboot/pull/462
