### ISSUE TITLE
"sudo cbmem -T" return "Failed to gain memory access: Operation not permitted" for V1210

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#701]
### Device

V1210

### Dasharo version

Dasharo v0.9.2

### Affected component(s) or functionality

```
ubuntu@3mdeb:~$ sudo cbmem -T
Failed to gain memory access: Operation not permitted
```

### Brief summary

`sudo cbmem -T` return `Failed to gain memory access: Operation not permitted` for V1210

### How to reproduce

Execute `sudo cbmem -T` on DUT

### Expected behavior

cbmem has access to memory

### Actual behavior

```
ubuntu@3mdeb:~$ sudo ./cbmem -T
Failed to gain memory access: Operation not permitted
```

**Comment by mkopec** [comment]
Was secure boot disabled? cbmem uses `/dev/mem` which is locked down by the kernel when Secure Boot is enabled.

**Comment by Psotas** [comment]
@mkopec 
You are right, the problem was secure boot enabled.
