### ISSUE TITLE
Execute "sensors" return "ERROR: Can't get value of subfeature temp2_min: I/O error" for nvme-pci-0300 under v1210

### ISSUE THREAD

**Issue by Psotas** [Dasharo/dasharo-issues#702]
### Device

V1210

### Dasharo version

Dasharo v0.9.2

### Affected component(s) or functionality

```
ubuntu@3mdeb:~$ sensors 
nvme-pci-0300
Adapter: PCI adapter
Composite:    +19.9°C  (low  =  -0.1°C, high = +84.8°C)
                       (crit = +94.8°C)
ERROR: Can't get value of subfeature temp2_min: I/O error
ERROR: Can't get value of subfeature temp2_max: I/O error
Sensor 1:     +32.9°C  (low  =  +0.0°C, high =  +0.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +28.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +22.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +22.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +22.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +21.0°C  (high = +105.0°C, crit = +105.0°C)
```

### Brief summary

Execute `sensors` return `ERROR: Can't get value of subfeature temp2_min: I/O error` for v1210

### How to reproduce

Execute `sensors` on DUT

### Expected behavior

No errors

### Actual behavior

ERROR: Can't get value of subfeature temp2_min: I/O error
ERROR: Can't get value of subfeature temp2_max: I/O error

**Comment by mkopec** [comment]
Looks like it's an SSD issue, these sensors are read directly from the SSD, not much that can be done from x86 firmware here. Maybe try updating the SSD's firmware, or try a different SSD?

**Comment by macpijan** [comment]
Does not look like a firmware problem
