### ISSUE TITLE
Please fix the DTS Dasharo Community Version install for the Dell OptiPlex 7010

### ISSUE THREAD

**Issue by AndrewBorah38** [Dasharo/dasharo-issues#706]
### Device

Dell OptiPlex 7010

### Dasharo version

[DTS](https://github.com/Dasharo/meta-dts) - [v1.2.18](https://github.com/Dasharo/meta-dts/releases/tag/v1.2.18) - Dasharo Community Version

### Affected component(s) or functionality

[DTS](https://github.com/Dasharo/meta-dts) - Dasharo Community Version Install:
- [meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh](https://github.com/Dasharo/meta-dts/blob/main/meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh) -> download_artifacts()

### Brief summary

When attempting to install Dasharo Community Version through DTS on a Dell OptiPlex 7010 I encounter the error:
```
"Cannot access $FW_STORE_URL while downloading signature. Please check your internet connection"
```
### How reproducible

Every time.

### How to reproduce

- Create a bootable [DTS](https://github.com/Dasharo/meta-dts) USB using the wic.gz and dd
- Disable secure boot and short the service jumper
- Boot the [DTS](https://github.com/Dasharo/meta-dts) USB
- Connect to the internet via ethernet
- Dump the hardware info
- Attempt to install Dasharo Community Version

### Expected behavior

Dasharo Community Version should install.

### Actual behavior

I encounter the error:
```
"Cannot access $FW_STORE_URL while downloading signature. Please check your internet connection"
```

**Comment by pietrushnic** [comment]
@macpijan @BeataZdunczyk @artur-rs is there any chance someone could look into that issue before DUG#6?

**Comment by lenzj** [comment]
I had the same issue others have mentioned and was able to manually edit a script on the thumb drive and successfully complete a firmware flash on an Optiplex 9010 and 7010.  Pull request is listed just above this.

**Comment by pietrushnic** [comment]
@lenzj thank you very much for your contribution. @BeataZdunczyk let's make sure someone will review it. It is just 3 lines of code. I assigned @macpijan and @miczyg1, but I'm unsure if they will have time. @artur-rs, including this fix in the next release, would be best.

**Comment by macpijan** [comment]
Will be a part of v1.2.22 release.
