### ISSUE TITLE
Heads shuts down instead of rebooting

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#711]
### Device

NovaCustom NV4x ADL

### Dasharo version

v0.9.0-rc3

### Affected component(s) or functionality

Reboot

### Brief summary

When issuing a `reboot` command in shell or via GUI, the machine shuts down instead of rebooting.

### How reproducible

100%

### How to reproduce

- boot into Heads recovery shell
- type in `reboot`
- press Enter

### Expected behavior

Laptop reboots

### Actual behavior

Laptop shuts down

### Additional context

Doing OEM factory reset / re-ownership involves multiple resets, so powering off and waiting for a power button press is unexpected by the user.

**Comment by miczyg1** [comment]
These routines are only needed after EC firmware update. Otherwise regular reboot should be used AFAIK.

**Comment by mkopec** [comment]
Correct, these are needed to reset the EC while it's in Scratch ROM to restore normal operation

**Comment by macpijan** [comment]
Included in: https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases_heads/#v091-2024-06-27
