### ISSUE TITLE
Enable the watchdog option in the PC Engines apu Dasharo firmware

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#714]
**Dasharo version (if applicable)**

Dasharo v0.9.0 for PC Engines apu boards (apu2/apu3/apu4/apu6) 

**Brief summary**

Enable the Watchdog option in the setup menu and configure the timeout. When enabled the firmware shall configure the AMD FCH watchdog during boot with the specified timeout.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/edk2/pull/119
https://github.com/Dasharo/docs/pull/767

**Comment by BeataZdunczyk** [comment]
Closing the issue as all PRs have been merged.
