### ISSUE TITLE
Enable the PCIe power management features option in the PC Engines apu Dasharo firmware

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#722]
### Dasharo version (if applicable)

Dasharo v0.9.0 for PC Engines apu boards (apu2/apu3/apu4/apu6)

### Brief summary

Enable the PCIe power management features in the setup menu. Firmware shall configure CLK PM, ASPM L0s and L1 on PCIe ports.

**Comment by miczyg1** [comment]
https://github.com/Dasharo/edk2/pull/119
https://github.com/Dasharo/docs/pull/767

**Comment by BeataZdunczyk** [comment]
Closing the issue as all PRs have been merged.
