### ISSUE TITLE
Enable the Core Performance Boost option in the PC Engines apu Dasharo firmware

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#723]
### Dasharo version (if applicable)

Dasharo v0.9.0 for PC Engines apu boards (apu2/apu3/apu4/apu6)

### Brief summary

Enable the Core Performance Boost in the setup menu. Firmware shall configure AMD Core Performance Boost during boot if enabled..

**Comment by BeataZdunczyk** [comment]
Closing the issue as all PRs have been merged.
