### ISSUE TITLE
Integrate the Verified Boot into the PC Engines apu Dasharo firmware

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#724]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

Firmware, by default, is not protected against modified code execution. This kind of protection is provided by a verified boot that signs particular firmware components, so it is verified before execution. Verified boot allows for the execution of authorized code only. Extend the chain of trust, initialized by the Boot Guard with Dasharo verified boot.

**Additional context**

**Comment by macpijan** [comment]
Implemented in: https://github.com/Dasharo/coreboot/pull/467
