### ISSUE TITLE
Incorrect date on 29/02/2024

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#725]
### Device

All

### Dasharo version

All

### Affected component(s) or functionality

The bug comes from coreboot itself: https://review.coreboot.org/c/coreboot/+/80790

Others are also affected by this incorrect date, as many OS services rely on the current date. If the date in OS was taken from RTC rather than synchronized via NTP, some features might not work correctly, such as the SSL certificates verification.

This is the case for DTS as well:
- unable to boot via HTTPS
- unable to verify firmware updates: "Failed to verify Dasharo firmware signature"

### Brief summary

Leap year is not correctly handled, causing RTC date to go back in time.

### How reproducible

100%

### How to reproduce

Check the date on the device

### Expected behavior

Date is correct: 29/02/2024

### Actual behavior

Date is incorrect depending on the device, it goes back to dates in 2024 or even before (date of last release).

### Additional context

The problem should be gone tomorrow (March 1st). The fix shall be included in all future releases, so the problem is not there in the next 4 years.

**Comment by mkopec** [comment]
On most Dasharo builds the date will be re-set to the firmware build date. This affects not only reboots but also wake from S3, as my workstation had incorrect time this morning :)

On Heads builds (with timeless enabled) the date will be reset to 1970-01-01 00:00:00 (null timestamp)

**Comment by macpijan** [comment]
It's been fixed by a coreboot rebase https://doc.coreboot.org/releases/coreboot-24.02-relnotes.html#release-24-02-1
