### ISSUE TITLE
Add support for PC Engines legacy testing in OSFV CLI and OSFV

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#728]
Work is happening in the following two PRs:

- https://github.com/Dasharo/open-source-firmware-validation/pull/213
- https://github.com/Dasharo/osfv-scripts/pull/16

**Comment by macpijan** [comment]
CLI already supported: https://github.com/Dasharo/osfv-scripts/tree/main/osfv_cli/src/osfv/models

**Comment by pietrushnic** [comment]
I would close this since OSFV would be tracked in https://github.com/Dasharo/dasharo-issues/issues/914, which was linked in the release notes as something we should address. If you have any ideas on how to approach migration, I would appreciate that.
