### ISSUE TITLE
DTS should sync time before doing time-sensitive tasks

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#732]
### The problem you're addressing (if any)

Some operations, like signature verification, depend on time to be valid.

### Describe the solution you'd like

DTS should sync time before doing these tasks.

### Additional context

`chronyc waitsync` in the right place in DTS scripts should do the trick

**Comment by DaniilKl** [comment]
@mkopec, DTS uses `chronyd` via `chronyf.service` to sync system clock. Do you mean syncing before `systemd` services is being loaded?

**Comment by mkopec** [comment]
Chronyd seems to have a delay from starting the service to the clock actually getting synced. The point of this issue is to ensure time is synced when we need it, e.g. when verifying signatures, for example by calling `chronyc waitsync` just before doing these tasks.

**Comment by DaniilKl** [comment]
IMHO there is no need for syncing every time, syncing on system start and then waiting for `chronyd.service` to start will be just enough.

**Comment by DaniilKl** [comment]
@mkopec, checkout this PR https://github.com/Dasharo/meta-dts/pull/112.

**Comment by DaniilKl** [comment]
Ok, it seems syncing on the beginning is not always a good solution, @mkopec could you specify which sections need system clock to be synced?
