### ISSUE TITLE
Watchdog help text incorrectly stating boundaries

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#733]
### Device

All

### Dasharo version

At least Protectli VP46XX v1.2.0. Probably all.

### Affected component(s) or functionality

EDK2 menu help text

### Brief summary

Watchdog timeout help text 

### How reproducible

100%

### How to reproduce

1. Enter Dasharo System Features -> Chipset Configuration

### Expected behavior

Help text is consistent with the actual code checks

### Actual behavior

Text says the minimum value is 60s, while the actual minimum accepted value is 300s.

**Comment by macpijan** [comment]
I am not certain which is wrong and why. The help text, or the code check.

**Comment by macpijan** [comment]
This also applies to [documentation](https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/#chipset-configuration)

```
Watchdog timeout value - watchdog timeout in seconds. Allowed range is 60-1024 seconds. The Option is only visible if watchdog is set to enabled.
```

**Comment by miczyg1** [comment]
The lower boundary is actually 1s, but it is pointless. The minimum is also uarch dependent (there is a value that should not be exceeded in order to let the full memory training to pass). Nevertheless, the help text needs udpate.

**Comment by mkopec** [comment]
https://github.com/Dasharo/DasharoModulePkg/pull/41
https://github.com/Dasharo/edk2/pull/123

**Comment by macpijan** [comment]
Thanks.
