### ISSUE TITLE
Later DTS versions will not work with Dasharo 1.1.1 on MSI Z690

### ISSUE THREAD

**Issue by BrettLMiller** [Dasharo/dasharo-issues#738]
### Device

ms7d25

### Dasharo version

1.1.1

### Affected component(s) or functionality

DTS 1.2.13 1.2.18 1.2.19 interface.
The DTS webpage notes recommends to always use the latest DTS release.

### Brief summary

Later DTS release do not function correctly on old Dasharo 1.1.1

### How reproducible

Failed 3/3 attempts (all different DTS releases).

### How to reproduce

Z690 with Dasharo 1.1.1 & try boot USB stick with DTS 1.2.13 or later.

### Expected behavior

Expect all DTS versions to run on all & any older Dasharo releases.

### Actual behavior

System is MSI ms7d25 Z690 DDR5 running Dasharo v1.1.1.
DTS 1.2.18 kernel panics.
DTS 1.2.13 & 1.2.19 start in emergency mode shell.

DTS 1.2.8 runs okay & supports Dasharo v1.1.2.
Once v1.1.2 was installed/flashed then DTS 1.2.19 runs okay & can upgrade/flash to Dasharo v1.1.3

### Solutions you've tried

As above, Dasharo v1.1.1 to v1.1.3 must be done incrementally (2 steps).

**Comment by macpijan** [comment]
We do not have an easy way to reproduce this, and according to the above report the DTS boots fine in combination with the latest version. Let's reopen if we bump into similar scenario again.
