### ISSUE TITLE
Incorrect vendor name in SMBIOS NS70/50 v1.1.0

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#74]
**Dasharo version**

v1.1.0

**Dasharo variant**

Dasharo workstation

**Affected component(s) or functionality**

Vendor name display

**Brief summary**

The vendor name is different than expected.

**How reproducible**

The issue occurs every time vendor name is checked.

**How to reproduce**

1. Open a terminal window and run `sudo dmidecode -t bios`
2. n the `BIOS` Information section, check the `Version` field against the guidelines and `dmidecode.log`

**Expected behavior**

The Vendor field, for firmware with an initial release date after 13 January 2021, is set as follows:

`3mdeb`

**Actual behavior**

The Vendor field is set as follows:

`3mdeb Embedded Systems Consulting`

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment]
@mkopec @miczyg1 Do we follow this rule for new releases? Should it be really `13 January 2021`, not 2022? It comes from here: https://docs.dasharo.com/dev-proc/smbios-rules/

Changing vendor changes fwupd GUIDs?

**Comment by pietrushnic** [comment]
@macpijan it should be 2022, I don't know how I missed that in review.

**Comment by mkopec** [comment]
> @mkopec @miczyg1 Do we follow this rule for new releases? Should it be really `13 January 2021`, not 2022? It comes from here: https://docs.dasharo.com/dev-proc/smbios-rules/
> 
> Changing vendor changes fwupd GUIDs?

Yes, changing the vendor field will change the GUIDs.

**Comment by macpijan** [comment]
@pietrushnic Another thing to consider would be:
"The Vendor field, for firmware with **initial** release date" - so, of the initial release for the given platform was prior that date, we would stick to the old vendor name, even for the newer releases.

I think we should update the vendor name in **all** releases past given date. WDYT?

**Comment by pietrushnic** [comment]
@macpijan yes, that make sense.

**Comment by macpijan** [comment]
Can you also fix SMBIOS documentation according to the discussion above (if not done already)?

**Comment by mkopec** [comment]
@macpijan fix: https://github.com/Dasharo/docs/pull/204

**Comment by mkopec** [comment]
Closing as fixed in [v1.2.0](https://docs.dasharo.com/variants/novacustom_ns5x/releases/#v120-2022-05-26)
