### ISSUE TITLE
VP4670 v2 - firmware does not make it possible to enable or disable watchdog

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#749]
### Device

VP4670 v2

### Dasharo version

1.2.0

### Brief summary

Watchdog enablement is not possible

### How to reproduce

Try to enable or disable watchdog in the firmware setup menu.

### Expected behavior

Enabling or disabling watchdog should be possible.

### Actual behavior

Enabling and disabling watchdog is not possible.

**Comment by mkopec** [comment]
isn't this the same issue as https://github.com/Dasharo/dasharo-issues/issues/745 ? 

WDT has been removed from the scope of this release as I understand it

**Comment by pkubaj** [comment]
That issue is for Chipset Configuration menu being unavailable, the fail here is another test - F9 resets Enable watchdog to default.

**Comment by macpijan** [comment]
Yes it is the same.
