### ISSUE TITLE
Ubuntu 22.04.4 randomly reboots during booting on APU3

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#750]
### Device

APU3

### Dasharo version

0.9.0

### Brief summary

Ubuntu 22.04.4 randomly reboots during booting

### How to reproduce

Try to boot Ubuntu after installation.

### Expected behavior

System should boot.

### Actual behavior

After successful installation (which required cleaning the disk from DTS because Ubuntu's installer crashed during partitioning), the system doesn't boot. During booting, before getting to getty, but after starting init, system crashes and reboots.

**Comment by pkubaj** [comment]
UPDATE: it seems the error is not that random and always happens at similar time. Attached is a boot log.
[minicom.log](https://github.com/Dasharo/dasharo-issues/files/14704519/minicom.log)

**Comment by pkubaj** [comment]
After passing `init=/bin/bash` to the kernel command line, system booted to bash, but after a while rebooted.

**Comment by mkopec** [comment]
watchdog timeout? maybe watchdog was left enabled in the setup menu after the watchdog test suite?

**Comment by pkubaj** [comment]
That looks like it, how can I check which error causes this issue?

**Comment by mkopec** [comment]
@pkubaj Do you think this issue can be closed? I guess it's a problem with some manual watchdog configration in the OS, not with the firmware itself?
