### ISSUE TITLE
DTS option 2 assumes ICMP is allowed

### ISSUE THREAD

**Issue by ThePlexus** [Dasharo/dasharo-issues#752]
### Device

Z690

### Dasharo version

1.2.11

### Brief summary

DTS option 2 assumes ICMP is allowed

### How reproducible

consistent

### How to reproduce

block ICMP at the network layer, boot DTS and select option 2. It will be blocked from proceeding to reach the "dasharo cloud"

### Expected behavior

liveness tests should use a layer7 protocol 

### Actual behavior

it did not proceed with the install

**Comment by tym2k1** [comment]
Created a [Pull Request](https://github.com/Dasharo/meta-dts/pull/113) that addresses this issue

**Comment by macpijan** [comment]
Should be in DTS v1.2.22 and above
