### ISSUE TITLE
`igb: The NVM Checksum Is Not Valid` error on apu6

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#756]
### Device

PC Engines apu6

### Dasharo version

Dasharo (coreboot+UEFI) v0.9.0

### Affected component(s) or functionality

Ethernet

### Brief summary

An unexpected boot error from igb appears in system logs

### How reproducible

100%

### How to reproduce

STB002.001

- boot to Ubuntu
- run `sudo dmesg -l emerg,alert,crit,err`

### Expected behavior

No unexpected errors appear

### Actual behavior

One error appears:

```
[   26.703238] igb 0000:01:00.0: The NVM Checksum Is Not Valid
```

### Additional context

01:00.0 is the SFP I210 NIC

**Comment by miczyg1** [comment]
@mkopec that's an old problem... The apu6 that came to us was shipped with unprogrammed NICs. One of the NICs refused to be programmed correctly, which resulted n the NVM checksum being not valid. Haven't found solution to that yet.

But it should be safe to assume, that the units in the world have it programmed properly. Our unit was very fresh from factory.

**Comment by mkopec** [comment]
Makes sense, in this case the issue can probably be closed, unless some other users report this problem.
