### ISSUE TITLE
[RFC] Dasharo Entry Subscription naming scheme

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#762]
We have many issues with the current naming scheme and the growing number of supported platforms. I want to start a discussion with the community about potential improvements in the naming scheme. I want to make it public so others in the future can refer to this discussion and understand the background and decision-making process.

### Naming

"Entry Subscription" suggests an ongoing, renewable service, which contradicts the product's prepaid nature. This is problematic for many community members focused on privacy since subscriptions are typically renewable and require keeping records of payment-related data, which, in the long run, could be of various for specific players. Those are not all concerns related to the subscription model, but we don't want to talk about the business model here. The name is confusing and does not reflect reality.

**Proposal:** We could change it to something like **Dasharo Entry Package**. We can also prevent changes in abbreviations and keep S as Suite/Set/Solution/System/Series, etc.

### Complexity of naming

* Dasharo Entry Subscription for Network Appliance = DESfNA
* Dasharo Entry Subscription for Network Appliance Legacy = DESfNAL
* Naming does not reflect what is inside, e.g., DESfNA consists of Dasharo (coreboot+UEFI), DESfNAL consists of Dasharo (coreboot+SeaBIOS), which itself may have two types based on mainline or legacy line

**Proposal:** If the following description would be something we would like to discuss more widely, I will move it to separate PR so that everyone can comment.

```man
DASHARO(1)                   User Manuals                   DASHARO(1)

NAME
       Dasharo - Defines the naming scheme for firmware configuration
       and subscription packages tailored to various market segments.

SYNOPSIS
       Dasharo (firmware_framework[+payload]) Entry Subscription for
       market_segment

DESCRIPTION
       Dasharo's naming scheme is crafted to convey the
       essential details of each firmware subscription package. It
       includes the base firmware framework, an optional payload, and
       the targeted market segment. This structure assists in
       identifying the most suitable package for specific technological
       needs and market segments.

       Components of the naming scheme:

       Dasharo (firmware_framework[+payload]) Entry Subscription for
       market_segment

       - firmware_framework: Mandatory. Specifies the base firmware
         framework used in the package. Options include:
             coreboot | UEFI
         'UEFI' signifies EDK II reference implementation of the UEFI Specification.

       - payload (optional): Details the additional software loaded
         by the firmware. Options are:
             none | UEFI | SeaBIOS | Heads
         The omission of this component implies no additional payload.

       - market_segment: Indicates the target market segment for the
         subscription package. Possible segments:
             Network Appliance/Embedded | Laptop | Desktop |
             Workstation | Server

       This naming convention aims to provide clarity and precision,
       facilitating ease of understanding across Dasharo's firmware
       offerings.

EXAMPLES
       Dasharo (coreboot+Heads) Entry Subscription for Laptop
              A package aimed at laptops, incorporating coreboot with
              the Heads payload.

       Dasharo (UEFI) Entry Subscription for Desktop
              A package for desktops that employs UEFI with no
              additional payload specified.

SEE ALSO
       For a comprehensive understanding and a complete range of
       available packages, please refer to the Dasharo official
       website and product catalog.

3mdeb (c) 2024
```

### Introduction strategy

Changing the naming convention could pose challenges in communication with the community and customers.

**Proposal:**
- [x] Q2'24 - Announcement: Communicate the reasons for the change, emphasizing benefits such as clarity and ease of understanding during DUG#6
- [x] Q3'24 - Q4'24 - Transition Period: This is a grace period during which both naming conventions are used, gradually phasing out the old names.
- [x] Q3'24 - Q4'24 - Update all official documents, FAQs, and marketing materials to reflect the new naming convention, with a glossary or table mapping old names to new ones for reference.
- [x] EOQ4'24 - Switch to new naming

**Comment by tlaurion** [comment]
> This is problematic for many community members focused on privacy since subscriptions are typically renewable and require keeping records of payment-related data, which, in the long run, could be of various for specific players.

->This is problematic for many community members focused on privacy since subscriptions are typically renewable and require keeping records of payment-related data, which, in the long run, could be of problematic for specific players.

various -> "problematic" ?

Opening up a PR is a good idea.

**Comment by Firminator** [comment]
Yes Entry Package has lower negative connotation than Subscription from my consumer viewpoint.

**Comment by pietrushnic** [comment]
As noted internally there is also a need for differentiation in name when business customers buy in bulk. I tried to incorporate the above description in following documentation: https://github.com/Dasharo/docs/pull/820

**Comment by pietrushnic** [comment]
> Q3'24 - Q4'24 - Update all official documents, FAQs, and marketing materials to reflect the new naming convention, with a glossary or table mapping old names to new ones for reference.

@rafkoch @Stanislaw-bnk, how do we feel about that? Are there any gaps? Do you think we can assume this is completed? From what I saw, most changes have already been made public. Please check my comment: https://github.com/Dasharo/docs/pull/841#discussion_r1879133919
