### ISSUE TITLE
tpm2_create:  ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#767]
### Component

Dasharo firmware

### Device

PC Engines APU2, PC Engines APU3

### Dasharo version

0.9.0

### Brief summary

tpm2_create -C primary.ctx -c obj.key results in ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported

### How to reproduce

```
root@3mdeb:/home/ubuntu# tpm2_createprimary --key-context primary.ctx
root@3mdeb:/home/ubuntu# tpm2_create -C primary.ctx -c obj.key
```

### Expected behavior

tpm2_create should succeed.

### Actual behavior

```
WARNING:esys:src/tss2-esys/api/Esys_CreateLoaded.c:368:Esys_CreateLoaded_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_CreateLoaded.c:129:Esys_CreateLoaded() Esys Finish ErrorCode (0x000b0143) 
ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported
ERROR: Unable to run tpm2_create
```

**Comment by pkubaj** [comment]
Yes, it looks like it is. Shouldn't #751 be at least crossposted to https://github.com/Dasharo/open-source-firmware-validation/?

**Comment by macpijan** [comment]
Can you do that? We should definitely try to do something about this in test environment.
