### ISSUE TITLE
Changing priority of `meta-dts-distro`

### ISSUE THREAD

**Issue by DaniilKl** [Dasharo/dasharo-issues#769]
**Dasharo version (if applicable)**

Dasharo Tools Suite built on commit `386e4d402abd29661b88c76e0ef5bb6568766dac`.

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

`meta-dts-distro` layer.

**Brief summary**

Considering changing `meta-dts-distro` priority to `11`.

**Additional context**

* Reason: DTS layers should have higher priority in the build, otherwise recipes from `meta-dts-distro` will be overwritten by other layers whenever it is possible and lead to errors or misunderstanding.
* Example: on commit `386e4d402abd29661b88c76e0ef5bb6568766dac` (which is latest `develop` branch) recipe `hidapi_1.4.1.bb` from `meta-dts-distro` is being overwritten during build by recipe `hidapi_git.bb` from `meta-openembedded`. This can be verified by checking workdir of the package `hidapi` after build:

```bash
λ ls build/tmp/work/core2-64-dts-linux/hidapi
0.11.2-r0
```

Which matches version from the recipe from `meta-openembedded`, which is:

```bash
λ cat ./meta-oe/recipes-support/hidapi/hidapi_git.bb
(...)
PV = "0.11.2"
(...)
```

**Comment by DaniilKl** [comment]
Found out about this during digging in issue https://github.com/Dasharo/dasharo-issues/issues/729.

**Comment by macpijan** [comment]
why label `invalid`? Do we want to implement this, or not? If not, let’s simply close.

**Comment by artur-rs** [comment]
@DaniilKl ping, question above

**Comment by DaniilKl** [comment]
> why label invalid?

My bad.

> Do we want to implement this, or not?

I still think we should implement this, but the team opinion was to live it the way it is.
