### ISSUE TITLE
Move DTS to a separate repository

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#773]
Maintenance of DTS script under meta-dts is not optimal. It is difficult to manage this DTS tool independently. Meta layer should focus on metadata for the build, not on the specific implementation. When separated, the DTS scripts can be more easily unit tested, also in CI, without the necessity of full Yocto integration.

Preliminary work, preserving the history, has been already done here: https://github.com/Dasharo/dts-v2

Next steps:
- move around files and clean up this repository from yocto metadata, leaving manageable structure for scripts
- provide Yocto recipe in meta-dts, including this repository,
  - in the same MR, remove the dts scripts from meta-dts

**Comment by DaniilKl** [comment]
@macpijan, shall we change the new repository name, e.g. to `dts-scripts`? `dts-v2` is not a clear name as for me.

**Comment by DaniilKl** [comment]
@macpijan, seems like the new repo is not properly set up, I cannot push branches:
```bash
λ git push origin yocto-cleanup 
ERROR: Permission to Dasharo/dts-v2.git denied to DaniilKl.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by macpijan** [comment]
@DaniilKl

> seems like the new repo is not properly set up, I cannot push branches: 

Should be fixed now.

> shall we change the new repository name, e.g. to dts-scripts? dts-v2 is not a clear name as for me.

We might move it back to dts but I wanted to first ensure we move everything from the old repo. I would not worry too much about the repo name now, it is very easy to change it.
