### ISSUE TITLE
Implement pre-commit in DTS repo

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#774]
You can use pre-commit init script: https://github.com/3mdeb/hooks/tree/main/pre-commit-init that would help you to integrate create pre-commit configs. We will be mostly interested in shellcheck, as it will be mostly shell scripts here, but also markdown, codespell, conform, would be useful.

**Comment by DaniilKl** [comment]
@macpijan, access error, is `Dasharo/hooks` configured appropriately?
```bash
dklimuk in ~/Repos/hooks on config-spell λ git push origin config-spell 
ERROR: Permission to 3mdeb/hooks.git denied to DaniilKl.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

P.S. Found a spel in the code in this repo.

**Comment by macpijan** [comment]
> Is 3mdeb/hooks configured appropriately?

should be now.

Thanks for contributing right away, I really appreciate this.
