### ISSUE TITLE
Protectli VP6670 - disabling USB stack does not work

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#776]
### Component

Dasharo firmware

### Device

Protectli VP6670

### Dasharo version

0.9.0rc2

### Brief summary

disabling USB stack does not work on VP6670

### How to reproduce

Disable USB stack in UEFI setup.
Run `lsusb` in Ubuntu.

### Expected behavior

No devices should be printed.

### Actual behavior

```
ubuntu@3mdeb:~$ lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1c4f:0002 SiGma Micro Keyboard TRACER Gamma Ivory
Bus 001 Device 003: ID 05c6:90b3 Qualcomm, Inc. MDG200
Bus 001 Device 005: ID 0cf3:e300 Qualcomm Atheros Communications QCA61x4 Bluetooth 4.0
Bus 001 Device 002: ID 413c:301a Dell Computer Corp. Dell MS116 Optical Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

**Comment by miczyg1** [comment]
@pkubaj disablign USB stack causes the USB driver in firmware to not be loaded. It does not affect OS drivers...

**Comment by pkubaj** [comment]
Thanks, I wasn't sure about it, my first impression was that it should disable the USB cotroller entirely.
