### ISSUE TITLE
VP6670 - overheating

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#777]
### Component

Dasharo firmware

### Device

Protectli VP6670

### Dasharo version

0.9.0rc2

### Brief summary

overheating VP6670

### How to reproduce

unknown

### Expected behavior

temperature should be below 82C.

### Actual behavior

`Current temperature: 89.0°C`

**Comment by mkopec** [comment]
Doesn't look like TCC offset is defined anywhere in the devicetree: https://github.com/Dasharo/coreboot/blob/dasharo/src/mainboard/protectli/vault_adl_p/devicetree.cb

so the CPU is free to boost up to 100 degC (Tjunction)

**Comment by miczyg1** [comment]
https://github.com/Dasharo/coreboot/pull/478

**Comment by pkubaj** [comment]
`'87.0 < 82' should be true.`

**Comment by pkubaj** [comment]
```
        Version: Dasharo (coreboot+UEFI) v0.9.0-rc3
        Release Date: 04/16/2024
```

**Comment by macpijan** [comment]
We have concluded that the test case should be more sophisticated, allowing for a very short temperature spikes, which is not a real problem. The problem is if this higher temperature persists for a longer period.
