### ISSUE TITLE
VP66?0: enabling BIOS Lock is noop

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#778]
### Component

Dasharo firmware

### Device

Protectli VP6650, Protectli VP6670

### Dasharo version

0.9.0rc2

### Brief summary

enabling BIOS Lock on VP6?0 doesn't enforce the lock

### How to reproduce

```
flashrom -p internal
```

### Expected behavior

`PR0: Warning: 0x.{8}-0x.{8} is read-only.`

### Actual behavior

```
flashrom v1.2-1033-g24b8fcf-dirty on Linux 6.5.0-27-generic (x86_64)            
flashrom is free software, get the source code at https://flashrom.org          
                                                                                
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).               
Cannot open file stream for /dev/mtd0                                           
coreboot table found at 0x768d5000.                                             
Found chipset "Intel Alder Lake-P".                                             
Enabling flash write... Warning: Setting BIOS Control at 0xdc from 0x8b to 0x89.
New value is 0x8b.                                                              
SPI Configuration is locked down.                                               
FREG0: Flash Descriptor region (0x00000000-0x00000fff) is read-write.           
FREG1: BIOS region (0x00580000-0x00ffffff) is read-write.                       
FREG2: Management Engine region (0x00001000-0x004c0fff) is read-write.          
OK.                                                                             
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific).
No operations were specified.                                                   
```

**Comment by miczyg1** [comment]
Probably a bug in the test. On the VP6670 in lab, there is no such issue:

```
flashrom -p internal -w /tmp/protectli_vp66xx_v0.9.0-rc1.rom --fmap -i 
flashrom v1.2-1037-g5b4a5b4 on Linux 5.15.36-yocto-standard (x86_64)
flashrom is free software, get the source code at https://flashrom.org 
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns). 
coreboot table found at 0x768d5000.
Found chipset "Intel Alder Lake-P". 
Enabling flash write... Warning: Setting BIOS Control at 0xdc from 0x8b to 0x89 failed.
New value is 0x8b.
SPI Configuration is locked down.
FREG0: Flash Descriptor region (0x00000000-0x00000fff) is read-write.
FREG1: BIOS region (0x00580000-0x00ffffff) is read-write.
FREG2: Management Engine region (0x00001000-0x004c0fff) is read-write.
PR0: Warning: 0x00b00000-0x00ffffff is read-only.
At least some flash regions are write protected. For write operations,
you should use a flash layout and include only writable regions. See 
manpage for more details.
OK.
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on internal.
Using region: "COREBOOT". 
Reading old flash chip contents... done.
Erasing and writing flash chip... Transaction error between offset 0x00b08000 and 0x00b07fff (= 0x00b08000 + -1)! 
Reading current flash chip contents... done. Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
No usable erase functions left.
FAILED!
Uh oh. Erase/write failed. Checking if anything has changed.
Reading current flash chip contents... done.
Good, writing to the flash chip apparently didn't do anything.
This means we have to add special support for your board, programmer or flash 
chip. Please report this to the mailing list at flashrom@flashrom.org or on 
IRC (see https://www.flashrom.org/Contact for details), thanks!
------------------------------------------------------------------------------- 
You may now reboot or simply leave the machine running.
```

**Comment by pkubaj** [comment]
OK, so we shouldn't test by running `flashrom -p internal`, but actually attempt to flash some binary?

**Comment by pkubaj** [comment]
OK, I'm not sure what happened. Is power-cycling necessary? 6650 has the same issue and I just manually confirmed that there's no information about the lock.

**Comment by miczyg1** [comment]
No, PR0 is reset to 0 with platform reset, so BIOS has to program it on each Boot and S3 resume.

**Comment by miczyg1** [comment]
> Power cycle is needed after changing pretty much any Dasharo config option.

Changing any setup option will force a reset, so the board will always boot with the desired PR0 state, yes

**Comment by mkopec** [comment]
> Changing any setup option will force a reset

It should, but it's possible to boot without resetting via the boot manager...

**Comment by miczyg1** [comment]
> It should, but it's possible to boot without resetting via the boot manager...

How? 

1. If I change a setting, save it, go to One Time Boot and try to select something, I get a pop up to reset the board.
2. If I change a setting, save it, go to Boot Maintenance Manager, choose to boot from file and try to select something from an EFI partition, like grubx64.efi, I get a pop up to reset the board.

I think it is not possible to exit the setup without a reset if a setting has been changed @mkopec

**Comment by mkopec** [comment]
The save settings reminder only appears when exiting via "Reset" or "Continue". If someone forgets to save the setting (because they're usually prompted to do so when exiting), the reminder won't appear when booting something via boot maintenance manager

**Comment by miczyg1** [comment]
> The save settings reminder only appears when exiting via "Reset" or "Continue". If someone forgets to save the setting (because they're usually prompted to do so when exiting), the reminder won't appear when booting something via boot maintenance manager

Aha! So for unsaved changes. It means they are not applied, so all fine. I though you can change and apply a setting and boot something without resetting.

**Comment by pkubaj** [comment]
I'm not sure how to reproduce it. Our 6650 already has BIOS Lock enabled:
![2024-04-10-113437_732x246_scrot](https://github.com/Dasharo/dasharo-issues/assets/4457924/bfb9428b-97bc-4437-beb9-3a536d02862b)

It had been enabled already when I entered setup, so I assume that it's already saved.
However, executing `flashrom -p internal` yields only:
```
flashrom v1.2-1033-g24b8fcf-dirty on Linux 6.5.0-27-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Cannot open file stream for /dev/mtd0
coreboot table found at 0x768d5000.
Found chipset "Intel Alder Lake-P".
Enabling flash write... Warning: Setting BIOS Control at 0xdc from 0x8b to 0x89 failed.
New value is 0x8b.
SPI Configuration is locked down.
FREG0: Flash Descriptor region (0x00000000-0x00000fff) is read-write.
FREG1: BIOS region (0x00580000-0x00ffffff) is read-write.
FREG2: Management Engine region (0x00001000-0x004c0fff) is read-write.
OK.
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on internal.
No operations were specified.
```

**Comment by macpijan** [comment]
@pkubaj Perhaps it happens only after first flashing? Have you tried switch off -> save -> switch on - > save? Can you try to narrow it a bit more?

**Comment by pkubaj** [comment]
After reflashing and cycling that option, I am getting the required warning.

**Comment by miczyg1** [comment]
The lock is default true: https://github.com/Dasharo/coreboot/blob/dasharo/src/vendorcode/dasharo/options.c#L166

It should work straight away after flashing.

**Comment by pkubaj** [comment]
I can't reproduce it anymore. The lock is enabled by default and it seems to work correctly. I'm not sure what happened before that made it not to work.
