### ISSUE TITLE
VP2410: UUID not settable

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#779]
### Component

Dasharo firmware

### Device

Protectli VP2410

### Dasharo version

1.1.0

### Brief summary

DCU001.001 fails due to UUID not being detected

### How to reproduce

`dmidecode | grep UUID`

### Expected behavior

UUID should be printed.

### Actual behavior

`	UUID: Not Settable`

**Comment by miczyg1** [comment]
The option for settable UUID is set: https://github.com/Dasharo/coreboot/blob/dasharo/configs/config.protectli_vp2410#L24

What are the errors?

**Comment by pkubaj** [comment]
There are no errors. DCU sets the UUID just fine:
```
(venv) debian@debian:~/open-source-firmware-validation$ ./dcu/dcu smbios -u `uuid` protectli_vp2410_v1.1.0.rom 
Will modify protectli_vp2410_v1.1.0.rom

Setting System UUID to 49174f9e-f7ec-11ee-9059-cf63d1773c00
Success
```

However, after flashing, dmidecode doesn't print it, but instead prints `Not Settable`.

**Comment by pkubaj** [comment]
I'm not sure what changed, but after proceeding to the next case, serial number change, UUID changed as well.

**Comment by pkubaj** [comment]
UPDATE: I reflashed a clean binary from Nextcloud and UUID is yet again `Not Settable`.

**Comment by macpijan** [comment]
But what is the whole scenario?

1. Flash clean firwmare
2. Set UUID in binary
3. Flash modified binary
4. Check ?

**Comment by miczyg1** [comment]
> UPDATE: I reflashed a clean binary from Nextcloud and UUID is yet again `Not Settable`.

Clean binary has no UUID, that is why it displayed as not settable.

You have to configure the binary first with the desired UUID then flash it...

**Comment by pkubaj** [comment]
Yes, I know. I think I set UUID on the proper ROM file, which I then flashed, but now I'm not sure...
Let's close it for now.

**Comment by miczyg1** [comment]
@pkubaj don't close an issue if you are not sure. If you have reported a possible defect, deliver proofs that it indeed is an issue or is not an issue with 100% certainty

**Comment by macpijan** [comment]
I would appreciate it if you can answer my question from @pkubaj  : https://github.com/Dasharo/dasharo-issues/issues/779#issuecomment-2051799814

1. We flash clean binary
2. We check UUID / serial - `not settable` is expected
3. We change **one of them** and reflash
4. Check both - one should be set, the other one not
5. Set the second one and check again.

Your initial finding suggested there might be a problem with displaying until we set both of them. But I have yet to see either a confirmation or negation of this scenario from yout side.

**Comment by pkubaj** [comment]
Yes, I tried that procedure again, but currently UUID is set up correctly. It was either my mistake or some other factor, but currently I can't reproduce this issue.

**Comment by macpijan** [comment]
I was able to make the UUID case pass several times: `DCU001.001 Change the UUID :: This test case verifies that the UUI... | PASS |`
