### ISSUE TITLE
Any progress with the Dell 7010/9010

### ISSUE THREAD

**Issue by Firminator** [Dasharo/dasharo-issues#78]
**Dasharo version**

Whatever .bin was posted @ https://docs.dasharo.com/variants/dell_optiplex/releases/ several month ago

**Question text**

I'm running Dasharo on this Dell box. Just wondering if there is going to be any new releases or if development is abandoned in favor of the MSI Z690-A WIFI

**Comment by pietrushnic** [comment]
@Firminator please excuse us we are so sloppy with that. We want to make proper Dasharo release. I even rebased everything to most recent coreboot. What I miss is time for debricking my setup and testing new release.

I can't promise anything, but would appreciate any support if you have time. Would you mind to join [Dasharo Matrix](https://matrix.to/#/#dasharo:matrix.org) ?

**Comment by Firminator** [comment]
No problem. Just checking.
Thanks for the invitation... I might join and read around if I can find time which is increasingly difficult.

**Comment by moriel5** [comment]
Since my CH341b (it turns out that it was not the "a" variant, however the "b" variant is equivalent, since the only difference is that it has a choice between external and internal oscillation, with mine using external components, in the same exact way as my CH341a has) has arrived (just in case I'll need it), I am currently in the process of cloning the necessary repositories (although I am not using Docker, since I do not have enough experience with it yet).

There aren't any binaries on the website, which I can understand, however the only tag is a prerelease v0.0.0, which doesn't seem right.

Can I please be pointed towards where v0.1.0 is (since the last version is unleased)?

**Comment by pietrushnic** [comment]
Hi @moriel5 thanks for letting us know you working on it. We also found time to move things little bit forward and there is discussion on Dasharo Matrix channel. Most recent status is in the documentation, please check [here](https://github.com/Dasharo/docs/pull/139) - building manual section would be most intreesting to you.

**Comment by moriel5** [comment]
Thanks for the update @pietrushnic.

Unfortunately I seem to be having issues compiling GCC 8 at the moment, I'll see what could be the the problem, and then I'll continue.

**Comment by pietrushnic** [comment]
@moriel5 why not to use my instruction directly? I assume you may need Docker, but [installation is quite trivial](https://docs.docker.com/engine/install). Trying to compile toolchain would cause some overhead and mess with you OS (additional packages needed).

**Comment by moriel5** [comment]
@pietrushnic I agree, and that is my plan in the long run, however as I had already said, I lack experience with Docker.

That, and the fact that my system is already supposed to be set up for compiling toolchains regardless, makes it faster and easier for me to work like the for the time being.

**Comment by pietrushnic** [comment]
@moriel5 ok, just wanted to point that Docker setup is couple simple steps away and gives nice isolation. Please let us know what results you get using your way.

**Comment by moriel5** [comment]
@pietrushic Thanks, from what I have heard, that is one of the benefits of Docker. It's just that in these few weeks I have less time than usual (I need/ed to travel quite a bit, for things such as a friend's wedding), and so learning how to use Docker will need to wait.

No problem, I'll make sure to post the results here, and if you wish to post them anywhere else, free free to do so.

**Comment by pietrushnic** [comment]
@moriel5 sure, no problem. We appreciate your support.

**Comment by pietrushnic** [comment]
@moriel5 I assume it may be more related to coreboot itself than to Dasharo. Feel free to post it as separate issue, but solving toolchain issues is not something we should deal in Dasharo, but more in upstream projects.

**Comment by moriel5** [comment]
@pietrushnic Yeah, that certainly makes sense, this isn't like meklort's BCM5719 firmware, where a custom variant of LLVM 10 is needed.

I'll post it as a separate issue, however meant to be a sort of "hub" for any possible issues I may encounter while trying to compile Dasharo, and I'll keep the GCC part as minimal as possible.
