### ISSUE TITLE
Unrecoverable firmware error

### ISSUE THREAD

**Issue by renehoj** [Dasharo/dasharo-issues#789]
### Component

Dasharo firmware

### Device

MSI Pro Z690-A

### Dasharo version

v1.1.3

### Brief summary

System isn't able to boot and gives the error: ASSERT c:\myworkspace\MdePkg\Library\BaseLib\String.c(166) String != (void *) 0)

### How reproducible

100% reproducible.

### How to reproduce

Reboot the system.
The step after the boot splash art will produce two error lines with the message: ASSERT c:\myworkspace\MdePkg\Library\BaseLib\String.c(166) String != (void *) 0)

### Expected behavior

The system would be able to boot, or give a better error message.

### Actual behavior

The system doesn't boot, and gives the error ASSERT c:\myworkspace\MdePkg\Library\BaseLib\String.c(166) String != (void *) 0)

### Additional context

The motherboard is in a home server running Proxmox, which has been working for 1-2 months, and hasn't had any issues with rebooting.

After updating the hypervisor I wasn't able to reboot the system, I was getting the error ASSERT c:\myworkspace\MdePkg\Library\BaseLib\String.c(166) String != (void *) 0)

I tried resetting cmos and reflashing the firmware, it didn't solve the issue.

I then tried flashing the MSI firmware, which worked, and the system booted without any issues.

The server has 2 PCI extension cards, I think the error could be related to the raid controller, but the controller is working.

### Solutions you've tried

I tried resetting cmos and reflashing the firmware.

**Comment by miczyg1** [comment]
@renehoj `c:\myworkspace\MdePkg\Library\BaseLib\String.c(166) String != (void *) 0)` is not a path that should be present in our firmware builds. Have you possible built Dasharo under Windows? if not, this ASSERT must be from an external EFI binary, e.g. a bootloader or something like that.

**Comment by renehoj** [comment]
I haven't compiled Dasharo myself, I'm using the official release build.

I'm pretty sure the root problem was the raid controller, I had by mistake done pass-through on the device. The error could be from the controller, the on-board configuration tool looks like it could have been made with tiancore.

I thought it was Dasharo generating the error, and that is why it couldn't boot.
