### ISSUE TITLE
VP6650 - USB-C hub not detected

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#792]
### Component

Dasharo firmware

### Device

Protectli VP6650

### Dasharo version

0.9.0rc3

### Brief summary

VP6650 doesn't detect USB-C hub; dmesg and lsusb are indifferent to plugging it in and out.
In consequence,  there's no video output, ethernet, nor USB HID over USB-C on VP6650.

### How reproducible

Tried with two different hubs

### How to reproduce

Try to plug a USB-C hub, notice  no changes in dmesg nor lsusb

### Expected behavior

The hub should pop up in dmesg and lsusb, ethernet should connect and display output should be sent to monitors connected to the hub

### Actual behavior

No observable behavior in reaction to plugging the hub in and out

**Comment by miczyg1** [comment]
I have a VP6650 at hand and USB-C display works for me in firmware and Windows

**Comment by macpijan** [comment]
> Try to plug a display output via USB-C port using VGA or HDMI adapters.

@pkubaj  Please provide which models and interfaces failed then, if some works, and some do not.

**Comment by pkubaj** [comment]
I use a noname USB-C hub. After plugging it to my laptop, the following devices are added:
```
@@ -13,4 +13,8 @@
 Bus 003 Device 008: ID 0d8c:0014 C-Media Electronics, Inc. Audio Adapter (Unitek Y-247A)
 Bus 003 Device 009: ID 046d:c077 Logitech, Inc. Mouse
 Bus 003 Device 010: ID 050d:004b Belkin Components USB-C 11-in-1 Multiport Dock
+Bus 003 Device 013: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub             
 Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
+Bus 004 Device 008: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub             
+Bus 004 Device 009: ID 067b:2733 Prolific Technology, Inc. USB SD Card Reader     
+Bus 004 Device 010: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
```

I believe the problem here is not exactly the lack of video output, however. After plugging the same hub to VP6650, no devices are added, which suggests that the hub is not detected at all.

**Comment by miczyg1** [comment]
Do you plug it to USB-C SS port? Or the COM USB-C port?

**Comment by macpijan** [comment]
> I use a noname USB-C hub.

For reference: https://web.archive.org/web/20240417102326/https://novacustom.com/product/usb-c-hub/

**Comment by pkubaj** [comment]
USB-C SS port.

**Comment by miczyg1** [comment]
I am also using rc3 and I can't reproduce it...

**Comment by mkopec** [comment]
you might want to try https://github.com/mkopec/tipd in monitor mode to sniff USB-C Alt mode events, maybe the TPS65994 in the VP6650 is misconfigured

**Comment by pkubaj** [comment]
Same result on VP6670, currently it's plugged in.

**Comment by miczyg1** [comment]
Maybe a monitor difference then? I don't understand why we have different results.

**Comment by macpijan** [comment]
I just confirmed yesterday the USB-C hub mentioned here: https://github.com/Dasharo/dasharo-issues/issues/792#issuecomment-2060934634 was detected on the unit @dawidlesiak is testing with.

**Comment by filipleple** [comment]
having consulted with @pkubaj, I've updated the scope of the issue - from just the video output (being only a single symptom) to no USB-C hub detection at all

**Comment by filipleple** [comment]
Turned out to be the same as https://github.com/Dasharo/dasharo-issues/issues/823 - patched in a recent release candidate.
