### ISSUE TITLE
Enable memory access above 4GB

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#795]
**Brief summary**

Capsules may be located in any part of RAM, not only lowest 4GB. Support for accessing higher
memory must be added to coreboot.

What is the scope of the task.

 Function(s) able to copy data from memory higher than 4GB to lower memory, along with
code for entering and leaving long mode. Linking with other parts of coreboot is not
required. Dynamic memory allocation isn't allowed, to not overwrite capsule data.

**Comment by krystian-hebel** [comment]
Both our local PR and upstream changes has been merged.
