### ISSUE TITLE
Parse capsule location from UEFI variables in coreboot

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#796]
**Brief summary**

 Location of capsules is saved in one or more CapsuleUpdateData UEFI variables, created
by edk2 UpdateCapsule(). Lists contained in those variables will be passed to function
created in #795 

As part of this task, flow should be analyzed to find out which component is responsible
for deleting those variables, and if this would be coreboot, also delete them.

**Comment by krystian-hebel** [comment]
https://github.com/Dasharo/coreboot/pull/509 (in particular https://github.com/Dasharo/coreboot/pull/509/commits/fc0c76227da6b4cbe42850ecfc2ab0764609b9be) implements parsing capsule locations from UEFI variables. It is intertwined with other tasks in a way that doesn't allow to clearly separate them, so they are implemented by the same commit.
