### ISSUE TITLE
Gather capsules into one region

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#797]
**Brief summary**

Capsules must be located in consecutive physical memory, as required by StartImage(). To make memory management easy for edk2, capsules should be defragmented before payload is started. At this point, the size and location of available target memory may be hardcoded, obtaining it is part of next  task.

**Comment by krystian-hebel** [comment]
https://github.com/Dasharo/coreboot/pull/509 (in particular https://github.com/Dasharo/coreboot/pull/509/commits/fc0c76227da6b4cbe42850ecfc2ab0764609b9be) implements gathering capsules into one region. It is intertwined with other tasks in a way that doesn't allow to clearly separate them, so they are implemented by the same commit.
