### ISSUE TITLE
Reserve memory containing capsules and pass it to the payload

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#798]
**Brief summary**

This task consists of allocating and reserving adequately sized memory region for coalesced capsules. The size will be calculated from capsule sizes, and the region will be chosen from available memory. Both address and size will be passed to the payload.  No restriction on how to pass it to the payload. Possible solutions include HOB, new type of memory range in memory map or UEFI variable.

**Comment by krystian-hebel** [comment]
https://github.com/Dasharo/coreboot/pull/509 (in particular https://github.com/Dasharo/coreboot/pull/509/commits/fc0c76227da6b4cbe42850ecfc2ab0764609b9be) implements reserving capsules memory and creating `LB_TAG_CAPSULE` table entry for being consumed by the payload. It is intertwined with other tasks in a way that doesn't allow to clearly separate them, so they are implemented by the same commit.
