### ISSUE TITLE
Add SMI handler for flashing firmware updates

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#799]
**Brief summary**

Access to flash is limited to SMM code. As SMRAM is locked in coreboot, edk2 can't install new SMI handlers. In order to be able to initiate writing new firmware image to flash, appropriate handler must be installed by coreboot, but enabled only if a valid capsule update is present.

**Comment by krystian-hebel** [comment]
PR that adds SMI handler: https://github.com/Dasharo/coreboot/pull/511
