### ISSUE TITLE
Modify FDF/DSC files and capsule processing

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#801]
**Brief summary**

Update the Firmware Descriptor (FDF) and Device Scope Configuration (DSC) files. Enable boot mode selection and invoke ProcessCapsules() at the necessary stages during the firmware update process.

**Comment by SergiiDmytruk** [comment]
EDK2 PR: https://github.com/Dasharo/edk2/pull/147

**Comment by krystian-hebel** [comment]
I've approved the PR, but we will not merge it yet to keep all changes related to capsules on dedicated branch until the whole solution is in working state.
