### ISSUE TITLE
Parse version reported by coreboot for ESRT

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#802]
**Brief summary**

Extract coreboot version information and incorporate it into the EFI System Resource Table (ESRT) within UEFI, to reflect the updated firmware and prevent rolling back to earlier versions.

**Comment by SergiiDmytruk** [comment]
EDK PR: https://github.com/Dasharo/edk2/pull/145
coreboot PR: https://github.com/Dasharo/coreboot/pull/527

**Comment by krystian-hebel** [comment]
https://github.com/Dasharo/coreboot/pull/527 has been integrated into https://github.com/Dasharo/coreboot/pull/509 and closed.
