### ISSUE TITLE
End-user documentation

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#808]
**Brief summary**

Document steps required by end-users to perform update using capsules.

**Additional context**

This gathers instructions created in other tasks (https://github.com/Dasharo/dasharo-issues/issues/803, https://github.com/Dasharo/dasharo-issues/issues/806, https://github.com/Dasharo/dasharo-issues/issues/807) into a guide on docs.dasharo.com. In addition, a cross-links between created guide and knowledge base page should be created where applicable.

Requirement for ME state must also be documented: https://github.com/Dasharo/dasharo-issues/issues/800#issuecomment-2247928107.

**Comment by SergiiDmytruk** [comment]
What about `CapsuleApp.efi`, has it been decided how it is to be distributed?  Will it be zipped along with every capsule or provided separately for download?  Not sure what kind of incompatibilities are possible in the latter case.  I can just not detail it much, but this will have to be decided anyway.

**Comment by SergiiDmytruk** [comment]
PR: https://github.com/Dasharo/docs/pull/890

**Comment by philipandag** [comment]
The instructions work on qemu and look good to me.

**Comment by philipandag** [comment]
# Before update:
![Screenshot from 2024-09-06 17-43-39](https://github.com/user-attachments/assets/39378571-4f85-46f4-b524-01ebf1902e91)


# Proof that some capsule update was performed:
![Screenshot from 2024-09-06 17-47-21](https://github.com/user-attachments/assets/18f9f841-5949-4bac-9bb2-2c462d925c0f)


# After update:
![Screenshot from 2024-09-06 17-44-41](https://github.com/user-attachments/assets/7ee31f1d-9215-40b3-9294-2f842d7cc945)
