### ISSUE TITLE
VP66?0 - Wifi card not detected in Windows 11

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#818]
### Component

Dasharo firmware

### Device

Protectli VP6650, Protectli VP6670

### Dasharo version

0.9.0rc3

### Brief summary

VP66?0 - wifi card not detected in Windows 11

### How to reproduce

`netsh wlan show network`

### Expected behavior

Wifi networks should be detected.

### Actual behavior

`There is no wireless interface on the system.`

### Additional context

On Ubuntu the card is detected as:
`07:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)`

**Comment by pkubaj** [comment]
After FW upgrade there's no BSOD anymore. However, there is still no Wifi card - Windows Update can't find the driver.

**Comment by miczyg1** [comment]
Then you have to find them manually:
https://www.ath-drivers.eu/download-driver-nr-382-for-atheros-QCA6174A-and-Windows10.html
https://www.ath-drivers.eu/download-driver-nr-353-for-atheros-QCA6174A-and-Windows10.html

**Comment by macpijan** [comment]
@BeataZdunczyk Let's document this before we release documentation. Similarly to: https://github.com/Dasharo/docs/blob/master/docs/variants/protectli_vp46xx/post-install.md

**Comment by miczyg1** [comment]
The driver has to be installed manually via Device Manager. When you choose to update the driver, you have to browse the computer for drives and point to the directory where the unpacked ZIP with driver is.
