### ISSUE TITLE
VP66?0: no Chipset Configuration config menu

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#822]
### Component

Dasharo firmware

### Device

Protectli VP6650, Protectli VP6670

### Dasharo version

0.9.0rc3

### Brief summary

no Chipset Configuration config menu on VP66?0

### How to reproduce

Enter Dasharo System Features in setup menu. Try to enter Chipset Configuration menu.

### Expected behavior

Chipset Configuration menu should be visible.

### Actual behavior

Chipset Configuration menu is not visible.

**Comment by macpijan** [comment]
It is exactly the same story as here: https://github.com/Dasharo/dasharo-issues/issues/745#issuecomment-2009111179

Please be more specific in reports which test case triggers this issue. It should not be executed until the feature gets implemented.
