### ISSUE TITLE
Fix SMM handling in coreboot for QEMU

### ISSUE THREAD

**Issue by krystian-hebel** [Dasharo/dasharo-issues#827]
**Dasharo version (if applicable)**

n/a

**Dasharo variant (if applicable)**

qemu_q35

**Affected component(s) or functionality (if applicable)**

SMM save state and everything depending on it (SMMSTORE, GSMI, GNVS)

**Brief summary**

QEMU uses AMD64 format for SMM save state (`amd64_smm_state_save_area_t`), even though it emulates Intel chipset. In coreboot for Q35, I82801IX southbridge is chosen, which assumes Intel format (`em64t101_smm_state_save_area_t`). Due to this mismatch, wrong register values are read by SMI handler.

**Additional context**

This can be done by applying https://review.coreboot.org/c/coreboot/+/45473/11 and relation chain. This change was abandoned due to lack of activity, but otherwise seems valid. Ideally those changes should be reactivated on upstream.

SMI_STS register in QEMU is always 0, not sure if mentioned relation chain deals with it. This register is checked in `southbridge_smi_handler()`, in the current form no additional handlers are executed unless a corresponding bit it is set in the register.

**Comment by BeataZdunczyk** [comment]
PR addressing this scope https://github.com/Dasharo/coreboot/pull/514 is merged, closing the issue.
