### ISSUE TITLE
issues dasharo on custom clevo ns50mu built by novacustom

### ISSUE THREAD

**Issue by davidsnik** [Dasharo/dasharo-issues#83]
**Dasharo version**

not certain but a newer version

**Dasharo variant**

Dasharo running on custom clevo ns50mu laptop from novacustom.

**Affected component(s) or functionality**

cpu frequency. cpu sound. temperature.

**Brief summary**

My laptop is a new custom built laptop running dasharo firmware. I have run the following gnu/linux distros on it to test it: qubes os, debian, ubuntu. with all three distros i run into the following issues:
1. When the demand for the cpu rises the frequency becomes really low.
2. The cpu seems to be making relatively loud electrical 'clicking' sounds that previous laptopts i owned didnt make. this is especially evident when the laptop is being idle and i open a application. it even happens when idle and i go with my mouse over bars on the screen. it seems the loudest when cpu is going from 0% to being used.
3. The laptop also seems to get quite hot quite fast.

**How reproducible**

for me its 100% of the time. however i dont know what issues are caused by the firmware and what issues are native to the laptop since i havent tried it with the original firmware yet.

**Solutions you've tried**

This weekend the original firmware is going to be flashed on it so then i can compare what issues stick around and what issues go away so then i can know for certain what issues are caused by dasharo and i will make an update here.

**Comment by GoodGuyPat** [comment]
Hi!
I am also on a NS51MU (the silver version, NS50 is black, internally they are the same) from NovaCustom, and I have just flashed Dasharo, coming from the original firmware. Currently running on Linux 5.13.0-41-generic.
I cannot say that I am noticing any difference in performance, although truth be told I have not paid much attention to clock speeds, as the limiting factor for this laptop has always been its thermals. I have now tested and my laptop would get to 3.2-3.4 GHz under load, and stay over 3 with temperatures approaching 100 degrees. I can strongly recommend @davidsnik to apply liquid metal to the CPU and report back, as I remember the massive difference that it made when I first got my laptop (almost a year ago now).

**Comment by wessel-novacustom** [comment]
Just as a quick reminder; you can use FN+1 to toggle the fan to full speed.

**Comment by macpijan** [comment]
Welcome in the Dasharo community, and thanks for reporting these problems!

I can elaborate more on the performance issue. This is known one (https://github.com/Dasharo/dasharo-issues/issues/64) and is scheduled to be changed in the next release. It is a matter of setting the power limit, which was set to lower than in the original firmware on the intial release.

**Comment by GoodGuyPat** [comment]
Worth noting that the machine that issue #64 refers to is using an i5-1135G7, whereas this issue was not present in my i7-1165G7.

**Comment by davidsnik** [comment]
Thx for the reccomendation @GoodGuyPat I think i will get the liquid metal cooling in the future when i have time to research/apply it :D

Also in my report above i mentioned i would give a update about what issues went away by flashing the insyde firmware. The cpu frequency is fixed now but this was a known issue anyway i believe. Also the clicking sound i mentioned in my report was just the fans toggling on and of according to @wessel-novacustom so since its just the fans making the sound thats not a big deal imo.

**Comment by wessel-novacustom** [comment]
CPU frequency tables to be checked have been added as a verifying point before new firmware releases. I think this will be optimised in a new firmware release for i5-1135G7.

Exactly. I believe it would be better if the fan would be always spinning (at low speed of course). It now seems that the fan is shutting down under a certain CPU temperature. If the fan is always spinning when the system is active, then it is avoiding the clicking sound, which can indeed be a bit annoying or worrying (even though it's not at all).

**Comment by mkopec** [comment]
It does look like the fan makes a loud click when spinning up from 0 RPM. We'll tweak the fan curve to keep the fan spinning at all times. This will fix the clicking problem

**Comment by wessel-novacustom** [comment]
Exactly. Sounds perfect. :-)
