### ISSUE TITLE
QEMU Q35 (coreboot+UEFI) - edk2 part

### ISSUE THREAD

**Issue by krystian-hebel** [Dasharo/dasharo-issues#830]
**Dasharo version (if applicable)**

n/a

**Dasharo variant (if applicable)**

qemu_q35

**Affected component(s) or functionality (if applicable)**

(coreboot+UEFI), edk2 part

**Brief summary**

This task gathers results from analysis of building and running (coreboot+UEFI) on QEMU Q35 in form of list of what needs to be addressed in edk2 to make it viable. Analysis stopped right after it was possible to boot into UEFI shell, so the list may be incomplete if critical deficiencies are discovered during tests.

**Additional context**

- [x] Break dependency on edk2-platforms, it shouldn't be required (PC Engines will also benefit from this change)
- [x] Analyze and fix hang on https://github.com/Dasharo/edk2/blob/dasharo/MdeModulePkg/Bus/Pci/PciBusDxe/PciIo.c#L1955-L1972 (I had to comment those lines out to allow booting)
- [x] Analyze and fix panic on reboot in `AcpiPlatformDxe`. CR2 value suggests 32b pointer used in 64b environment, although reported fault is #GP and not #PF so I'm not sure if it can be trusted.
- [x] UEFI Shell shows SATA drive even when no such drive is mounted. this may be only cosmetic, but it may also impact OS installation.

**Comment by krystian-hebel** [comment]
Dependency on edk2-platforms broken in https://github.com/Dasharo/DasharoModulePkg/pull/44, https://github.com/Dasharo/edk2/pull/133 and partially https://github.com/Dasharo/coreboot/pull/511.

CI in edk2 fails because it tries to build Dasharo-OVMF-Frankenstein which won't be a thing after the release, so I didn't bother with fixing it just yet. It is left for now as it were, other PRs may still use it. Eventually all changes adding Dasharo files to OvmfPkg should be removed for easier rebases in the future.

**Comment by krystian-hebel** [comment]
Problem with PciIo is resolved by https://github.com/Dasharo/edk2/pull/134. This PR changes one workaround to a different one. Ideal solution should be done to coreboot's resource allocator code, but this would be a much bigger project.

---

Panic on reboot was actually caused by error in coreboot's code, fixed by https://github.com/Dasharo/coreboot/pull/511/commits/e432c9369c988eed130be2276df5348bd4e57b74. This isn't specific to Dasharo or edk2, so it should be upstreamed. Not marking as done to remember about upstreaming.

**Comment by krystian-hebel** [comment]
Upstreamed fix for ACPI: https://review.coreboot.org/c/coreboot/+/82698

**Comment by pietrushnic** [comment]
@krystian-hebel, all the tasks here are done; shouldn't this issue be done? If not, what tasks are missing?

**Comment by krystian-hebel** [comment]
We've had some back and forth juggling of the patches when doing edk2 rebase(s), but it is mostly sorted out now. Breaking the dependency on edk2-platforms is missing the final touch, which is this commit: https://github.com/Dasharo/coreboot/pull/514/commits/f19fd2a516f463b6054189f34ce8d612a6a6b1d8. As it is located on coreboot side, I'm marking this issue as done.
