### ISSUE TITLE
NK3 not detected/discovered at OEM Factory Reset/Re-Ownership

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#831]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

coreboot + heads) v0.9.0 for NV4XPZ

**Affected component(s) or functionality (if applicable)**

USB

**Brief summary**

Apply fix from: https://github.com/linuxboot/heads/commit/67f1dae840446b32d323248c614ac84ee90c880f
Cause: race condition between USB controller kernel modules being loaded and the USB Security dongle being discovered and used. By moving the sleep function after all USB controller kernel modules are loaded, the issue disappears.

**Additional context**

Discussion here: https://github.com/Nitrokey/heads/issues/48

**Comment by macpijan** [comment]
Included in: https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases_heads/#v091-2024-06-27
