### ISSUE TITLE
Intermittent boot failure after upgrade to Linux kernel 6.9

### ISSUE THREAD

**Issue by patrick-g** [Dasharo/dasharo-issues#838]
### Component

Dasharo firmware, other

### Device

NovaCustom NS5x 12th Gen

### Dasharo version

1.7.2

### Brief summary

Intermittent boot failure

### How reproducible

After upgrade to Linux kernel 6.9 on my Arch Linux laptop I see intermittent boot failure. Sometimes, 1 out of 3 boots approximately, the boot sequence froze and I can do nothing apart a hard reset.
I see an error message that seems related to Coreboot and that's why I open a bug report here but I'm not sure at all if this issue is really related to Coreboot.

The error message is : "**Framebuffer coreboot8: probe with driver framebuffer failed with error -17**".

If this issue is not related to Coreboot feel free to close it.
 

### How to reproduce

I don't know how to reproduce this issue reliably. Sometimes the boot sequence is OK and sometimes it's frozen.

### Expected behavior

Normal boot 100% of time.

### Actual behavior

Sometimes the boot sequence is OK and sometimes it's frozen.

### Screenshots

![PXL_20240520_174541126](https://github.com/Dasharo/dasharo-issues/assets/396194/29786d1f-147a-49a1-9fd3-e3df165f5c90)

**Comment by patrick-g** [comment]
Also created a report on Arch forum with additional details : https://bbs.archlinux.org/viewtopic.php?pid=2172578#p2172578

**Comment by xbjfk** [comment]
I have a very strange issue that also occurred after upgrading to 6.9, albeit not on arch. I will do a git bisect.

**Comment by patrick-g** [comment]
Closed because it appears unrelated to Dasharo.
Solution to solve this problem described here : https://bbs.archlinux.org/viewtopic.php?pid=2176130#p2176130
