### ISSUE TITLE
Incorrect vendor name in SMBIOS fw6e v1.0.14

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#84]
**Dasharo version**

v1.0.14

**Dasharo variant**

Dasharo Workstation

**Affected component(s) or functionality**

Vendor name display

**Brief summary**

The vendor name is different than expected.

**How reproducible**

The issue occurs every time vendor name is checked.

**How to reproduce**

1. Open a terminal window and run `sudo dmidecode -t bios`
2. In the BIOS Information section, check the `Version` field against the guidelines and `dmidecode.log`

**Expected behavior**

The Vendor field, for firmware with an initial release date after 13 January 2021, is set as follows:
`3mdeb`

**Actual behavior**

The Vendor field is set as follows:
`3mdeb Embedded Systems Consulting`

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by sulewskiprzemyslaw** [comment]
This bug has been fixed before release. 

On release firmware vendor should be shown as follows:

`3mdeb`
