### ISSUE TITLE
SCP from host to DTS doesn't work

### ISSUE THREAD

**Issue by m-iwanicki** [Dasharo/dasharo-issues#840]
### Component

Dasharo Tools Suite

### Device

QEMU Q35 Emulator

### Dasharo Tools Suite version

1.2.21

### Brief summary

SCP doesn't work, returns `scp: Connection closed`

### How reproducible

Every time

### How to reproduce

* decompress .wic.gz [DTS image](https://github.com/Dasharo/meta-dts/releases/tag/v1.2.21)
* run this image on QEMU from [osfv](https://github.com/Dasharo/open-source-firmware-validation) uefi-sb-release branch:

  ```shell
  DRIVE_PATH=~/Downloads/dts-base-image-v1.2.21.wic ./scripts/ci/qemu-run.sh graphic os
  ```
* boot into DTS and enable ssh server
* Try to send any file from host to DTS via SCP:

  ```shell
  echo "abcd" > abcd
  scp -P 5222 abcd root@localhost:/tmp/abcd`
  ```

### Expected behavior

```shell
scp -P 5222 abcd root@localhost:/tmp/abcd
abcd               100%    5    28.1KB/s   00:00
```

### Actual behavior

```shell
scp -P 5222 abcd root@localhost:/tmp/abcd
scp: Connection closed
```

### Additional context

SCP also didn't work on NovaCustom laptop.

### Solutions you've tried

Change `Subsystem sftp /usr/libexec/sftp-server` to `Subsystem sftp internal-sftp` in `/etc/ssh/sshd_config`.
After that scp works.

**Comment by mkopec** [comment]
`scp -O` is needed when copying to dts for some reason.

**Comment by m-iwanicki** [comment]
It might be because there is no sftp-server installed, there is no file at `/usr/libexec/sftp-server`.
So we can either add sftp-server or change sshd_config to use `internal-sftp`

**Comment by macpijan** [comment]
Fixed in: https://github.com/Dasharo/meta-dts/pull/124
