### ISSUE TITLE
Update 3mdeb store to be clearer for end-users

### ISSUE THREAD

**Issue by mdrobnak** [Dasharo/dasharo-issues#842]
When looking for Qubes certified hardware I found references to "The [Dasharo FidelisGuard Z690](https://3mdeb.com/shop/open-source-hardware/dasharo-fidelisguard-z690-qubes-os-certified/) is a desktop based on the MSI PRO Z690-A DDR4 motherboard. It is certified for Qubes OS 4." which brought me to the site. I also read somewhere on the site that the 690 was nearly unavailable, so I purchased the Z790P instead.

While the mainboard + subscription bundle _does_ mention the TPM:
https://shop.3mdeb.com/shop/dasharo-supported-hardware/msi-pro-z790-p-wifi-ddr5-motherboard-with-dasharo-corebootheads-entry-subscription-for-desktop/

The release page:
https://docs.dasharo.com/variants/msi_z790/heads/ - is not as clear. As a result of this, I ended up buying the TPM a few days later. While it is under the changes section, it should be called out In the first paragraph that the discrete TPM is required, with applicable part number.

Request: 
* Update release page to mention TPM closer to the top of the page. 

--

Graphics compatibility with Heads not clear.
On https://docs.dasharo.com/variants/msi_z790/heads/ is says:
"Generally, the same [hardware configuration](https://docs.dasharo.com/variants/msi_z790/hardware-matrix/) as for the UEFI variant applies."
The issue here is that Heads only currently supports Integrated graphics, meaning a non-F CPU. I accidentally bought an F CPU.

Request:
* After the TPM requirement, please mention that discrete graphics is NOT supported by the standard build.

--

Subscription Confusion - the "supported" method of installing Heads is by installing the UEFI firmware first. However, the Heads subscription does not provide access to the UEFI variant. I have just noted that the standalone Heads subscription has been removed from the store, so no action is required for this item, and thank you for being proactive here.

I hope these changes I've requested will help future customers be better informed.

-Matt

**Comment by Stanislaw-bnk** [comment]
Thank you, @mdrobnak, for your valuable suggestions. While the coreboot+Heads variant is no longer available in our store, we will certainly keep your feedback in mind should the product return to our store in the future.

**Comment by mdrobnak** [comment]
I saw the changes, and they definitely clear things up. It's unfortunate that the product is not currently available, hopefully that can be worked out sometime. :)

Thank you for following through.

-Matt
