### ISSUE TITLE
battery bypass mode

### ISSUE THREAD

**Issue by baptx** [Dasharo/dasharo-issues#843]
### The problem you're addressing (if any)

On https://www.quora.com/How-often-should-I-charge-my-laptops-battery-to-prolong-its-lifespan/answer/Minhaz-Mahmud, I read "Most laptops now should be smart enough to bypass the battery once it hits 100% and just power the laptop directly."
I was told this is not the case currently, that there is no battery bypass mode on my NovaCustom NV41 Series laptop.

### Describe the solution you'd like

All computers using Dasharo / coreboot should stop charging / using the battery when it is charged at 100% and the charger is plugged in.
This should be the case both for USB and DC charging. There also should be a reliable way to check that the battery is bypassed.

### Where is the value to a user, and who might that user be?

Improve battery life of laptop users by not doing unnecessary charge / discharge.

### Describe alternatives you've considered

Until there is a battery bypass mode when the battery is charged at 100%, it looks like there is a workaround by plugging out the charger and plugging it back in when the battery is charged above the minimum charge threshold (95% by default : https://docs.dasharo.com/unified/novacustom/features/#charge-thresholds).
I was able to keep the battery always at 96% when plugged in (with the message "fully charged" on Debian LXQt), so I guess it means the battery is successfully bypassed if the charge percentage does not change. Maybe this workaround is not needed but it is easier to verify the battery bypass when it is not 100% charged.

**Comment by pietrushnic** [comment]
@baptx thank you for the report. @wessel-novacustom cc

**Comment by wessel-novacustom** [comment]
> @baptx thank you for the report. @wessel-novacustom cc

It has been discussed already and it's planned for a next release, if I'm not wrong.

@macpijan cc

**Comment by mkopec** [comment]
The NovaCustom laptops have charging circuits that already implement the requested feature. Only very space constrained devices like smartphones do not bypass the battery once it's fully charged. All NovaCustom laptops bypass the battery when it is not charging.

**Comment by wessel-novacustom** [comment]
@mkopec Can you confirm that this is the case for the current firmware versions already?

If so, can we check it with a Linux command that it is not actually charging?

**Comment by mkopec** [comment]
`cat /sys/class/power_supply/BAT0/current_now` displays how much current is going through the battery (charging or discharging). When fully charged, the indicator should show 0.

**Comment by baptx** [comment]
@mkopec So the "battery bypass mode" that was planned for the next firmware release is cancelled since it is already built-in in the hardware?

**Comment by macpijan** [comment]
@mkopec @wessel-novacustom Can we clarify here and close it? Do you think that we need some documentation update?

**Comment by wessel-novacustom** [comment]
@macpijan I suggest to explain the battery behaviour when fully charged [here](https://docs.dasharo.com/unified/novacustom/features/#battery-charge-management).

**Comment by philipandag** [comment]
Addressing the issue here: https://github.com/Dasharo/docs/pull/864

**Comment by philipandag** [comment]
The documentation was updated to explain the battery behavior better. 
[Documentation](https://docs.dasharo.com/unified/novacustom/features/#battery-charge-management)

Additionally some information about setting optimal charge thresholds was be added to the help message in the setup menu and will probably be included in the next release.

You can check the Pull requests for details:
https://github.com/Dasharo/docs/pull/864, https://github.com/Dasharo/edk2/pull/155
