### ISSUE TITLE
Built v0.9.0 serial gibberish output on post, setup and boot menu (OPNsense boot not affected) on apu4d4

### ISSUE THREAD

**Issue by LeoChaser** [Dasharo/dasharo-issues#852]
### Component

Dasharo firmware

### Device

PC Engines APU4

### Dasharo version

v0.9.0

### Brief summary

Gibberish serial output on apu4d4

### How reproducible

100%

### How to reproduce

Build following steps on [https://docs.dasharo.com/variants/pc_engines/building-manual/](https://docs.dasharo.com/variants/pc_engines/building-manual/), flash .rom file: 
`flashrom -p internal -c "W25Q64JV-.Q" -w pcengines_apu4_v0.9.0.rom`
 and reboot apu4.

### Expected behavior

Fully readable output from post, setup, boot menu, etc.

### Actual behavior

Combination of normal and gibberish characters on post, setup and boot menu, making it almost impossible to read text. UEFI Debian boot from flashdrive also affected. Preinstalled OPNsense autoboots normally.

### Screenshots

![Screenshot from 2024-06-03 13-47-48](https://github.com/Dasharo/dasharo-issues/assets/9063069/e6f57994-bb96-42c3-a9e4-3c6e4dca6a46)
POST options

![Screenshot from 2024-06-03 13-48-42](https://github.com/Dasharo/dasharo-issues/assets/9063069/4cc3e22f-4353-4c3a-9c28-049b5b0e06f6)
Boot menu

![Screenshot from 2024-06-03 13-49-21](https://github.com/Dasharo/dasharo-issues/assets/9063069/6eac30e6-dc7d-42a5-9a93-13e72c13e6bc)
Trying to boot Debian flashdrive

![Screenshot from 2024-06-03 13-52-01](https://github.com/Dasharo/dasharo-issues/assets/9063069/64a0701b-4b2e-4a13-adf0-23b4c2a178d9)
SETUP

![Screenshot from 2024-06-03 14-08-14](https://github.com/Dasharo/dasharo-issues/assets/9063069/c61ea4c0-d1ec-4240-8727-703fd7262c80)
OPNsense

**Comment by LeoChaser** [comment]
Output of lsusb:
`ID 1a86:7523 QinHeng Electronics CH340 serial converter`

It's a cheap and generic brand cable, but it used to work before (on non UEFI legacy). Also, OPNsense boots fine and works flawlessly still.
I've updated the firmware because wanted to test Proxmox (hence trying to boot Debian on UEFI), as my firewall is in a VM now.

**Comment by LeoChaser** [comment]
Just arrived a new cable I've bought from the Internet, 3 times the price of the old one, ugreen make lol
lsusb: `ID 067b:23a3 Prolific Technology, Inc. ATEN Serial Bridge`
Everything is working as expected now, POST, SETUP, and the UEFI boot.
Thank you for your time, I'm closing this.

![image](https://github.com/Dasharo/dasharo-issues/assets/9063069/ac52ce9d-26de-44aa-bc48-e50398db6ce4)

**Comment by macpijan** [comment]
> but it used to work before (on non UEFI legacy).

It is still "interesting" why it would work before, and fails now. Is UEFI payload any more demanding here when it comes to writing to serial? @mkopec @miczyg1

**Comment by miczyg1** [comment]
I recall such a thing to happen randomly on debug UEFI build when during DXE phase initialization the serial port suddenly started to print garbage, like it got unsynchronized for some reason.
