### ISSUE TITLE
Z690 DDR4 Recovery Instructions point to DDR5 board

### ISSUE THREAD

**Issue by Firminator** [Dasharo/dasharo-issues#86]
See https://docs.dasharo.com/variants/msi_z690/recovery/

This is for Z690 DDR5 board:
```
$ wget https://download.msi.com/bos_exe/mb/7D25vA31.zip
$ unzip 7D25vA31.zip
```

The DDR4 board has a different stock BIOS than the DDR5 board, so this would be correct:
```
$ wget https://download.msi.com/bos_exe/mb/7D25v13.zip
$ unzip 7D25v13.zip
```
and
```
$ flashrom -p linux_spi:dev=/dev/spidev1.0,spispeed=16000 -w 7D25v130/E7D25IMS.130
```

**Comment by macpijan** [comment]
Thanks for this report @Firminator 
@miczyg1 could you please verify and fix that if needed? Thanks.

**Comment by miczyg1** [comment]
Yes this is wrong. Already fixed: https://github.com/Dasharo/docs/commit/15546dff85a4c792e38621df44ccdaded9ac1f40
