### ISSUE TITLE
Memory overclocking support for Dasharo compatible with MSI PRO Z690-A DDR4

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#87]
**The problem you're addressing (if any)**
Support memory overclocking for MSI PRO Z690-A DDR4 WIFI

**Describe the solution you'd like**
A BIOS setup option to choose memory overclocking profile.

**Where is the value to a user, and who might that user be?**
Leverage the full capabilities of the memory modules and increase the performance of the overall system.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Firminator** [comment]
+1
I'd love to see XMP available. That would be huge.
Thanks Michal for working on this.

**Comment by miczyg1** [comment]
Haven't yet started. :) We just gather ideas for improvements

**Comment by Firminator** [comment]
I'd say that besides full hardware support (gpu, audio, pcie slots, all 3 nvme slots, all usb 2.0, usb3.0 and usb3.1 ports) having XMP support would be the single most important feature as it increases memory to 3200 MHz or even higher depending on which modules people have. I have two 8 GB 3200 MHz and had to enable the XMP feature in the stock BIOS to make use of the speed. The speed before was I believe 2400 MHz JEDEC standard.

Am I right in assuming that we should all wait for v1.0 before trying to attempt the switch from stock to coreboot/dasharo? I recently bought the mainboard based on the announcement of 3mdeb to support it with coreboot and I'm super-impressed about the progress so far. The machine is already running since a few days as a 2nd Linux gaming box so I will switch to Dasharo as soon as it's safe to do.

**Comment by pietrushnic** [comment]
@Firminator thank you for trusting us and for the support. We don't envision v1.0.0 release until sufficient testing would be made. We know about some companies preparing benchmarks and internal testing as part of considering Dasharo compatible mainboard as products for their shops. We believe that v0.4.0 is good enough to be used every day, but it was not extensively tested, so there may be some corner cases that we didn't cover. We don't want to overpromise. At this point our priorities are:

- Testing, testing, testing
- Sustainable business model, so we can provide regular updates, features and improvements - we need B2B partners, Patrons, donors and supporters
- Testing, testing, testing

How long it would take? It is hard to say. Maybe until end of June.

We would like to understand better your needs. What does it mean "safe". There is always risk while flashing firmware and no matter who is the vendor. Probably biggest risk right now is memory compatibility, but from our experience there is probably 5% chance memory will cause problems. If we can mitigate your risk by any means just please let us know.

**Comment by pietrushnic** [comment]
@Firminator also feel invited to [Dasharo open-source firmware vPub](https://vpub.dasharo.com/) it would be great to talk with you live.

**Comment by Hypocrite1127** [comment]
I hope it's not too bad a place to ask this question. How do I modify Dasharo to use XMP profile? There are some reports using XMP profiles on the [memory HCL page](https://docs.dasharo.com/variants/msi_z690/memory-hcl/), and I'd like to know how it's done, so I can use it and report it myself. Which files do I need to modify and what should I pay attention to?

**Comment by miczyg1** [comment]
@Hypocrite1127 you would need to add the following line here for XMP profile 1:
https://github.com/Dasharo/coreboot/blob/msi_ms7d25/release/src/mainboard/msi/ms7d25/romstage_fsp_params.c#L63

```
memupd->FspmConfig.SpdProfileSelected = 2;
```

Depending on needs and the used DIMM the possible values are:

- 0:Default SPD Profile,
- 1:Custom Profile,
- 2:XMP Profile 1,
- 3:XMP Profile 2,
- 4:XMP Profile 3,
- 5:XMP User Profile 4,
- 6:XMP User Profile 5

**WARNING** it may render your board unbootable if the memory training fails in FSP. Do it on your own responsibility or if you have a recovery way.

**Comment by Hypocrite1127** [comment]
Great, thank you very much! Might be worth adding to the relevant wiki page, of course with that warning clearly visible. I'll make sure to report my results.

**Comment by mkopec** [comment]
@miczyg1 We could easily wire these up to CMOS, no?

**Comment by Hypocrite1127** [comment]
@miczyg1 It worked, but unfortunately is not stable at all — MemTest86 throws a lot of errors that don't happen on stock BIOS (at least since I upgraded it to the latest version, the factory installed one was even worse in that regard). Is there anything else I could try?

**Comment by miczyg1** [comment]
You may try other available profiles if you have tried just one of the above. Nothing else comes to my mind at the moment.

**Comment by Hypocrite1127** [comment]
I know HCL is only about FSP initialization, but are you aware of any stress tests using XMP profiles? And is there any chance of it being resolved in the future?

**Comment by miczyg1** [comment]
MemTest86 is a bunch of memory stress tests to begin with. When we get to the point where memory profiles are configurable with the Dasharo firmware setup, we will try to resolve the reported issues.

**Comment by mkopec** [comment]
It could be that the stock BIOS enables higher System Agent voltages automatically when enabling XMP. AFAIK we do not do anything like this, which could lead to instability.

**Comment by miczyg1** [comment]
True, letting the FSP set the "sane defaults" might not always work in our favor.

**Comment by pietrushnic** [comment]
Indirectly this lead to very interesting conclusion about IBV relation with Silicon Vendors. Open ecosystem can get something, but not as good as well-established ecosystem partners.

I wonder if we would get support about that from IPS.

**Comment by miczyg1** [comment]
> Indirectly this lead to very interesting conclusion about IBV relation with Silicon Vendors. Open ecosystem can get something, but not as good as well-established ecosystem partners.
> 
> I wonder if we would get support about that from IPS.

We have all we need on our end (along with overclocking guidelines and documentation). The thing is just to sit and do it properly instead of tweaking single options.

**Comment by miczyg1** [comment]
> > MemTest86 is a bunch of memory stress tests to begin with.
> 
> I know it is, I probably should have asked if you are aware of any _other_ stress tests done using XMP profiles, as HCL shows XMP 3600 Mhz has been tried.
> 
> > It could be that the stock BIOS enables higher System Agent voltages automatically when enabling XMP.
> 
> Is there any way I could configure this in code right now as well?

Yes, there is, but at this point this leads into a direction of trial and error, where you would have to compile and flash repeatedly. I hoped the single option would work (just like it did for me) and we certainly don't want to advise something that may damage/brick your hardware.

**Comment by pietrushnic** [comment]
> We have all we need on our end (along with overclocking guidelines and documentation). The thing is just to sit and do it properly instead of tweaking single options.

And that is key difference - we don't have business justification to sepnt those resources. At least this is how it looks now, maybe it will change in near future.

**Comment by Hypocrite1127** [comment]
> we certainly don't want to advise something that may damage/brick your hardware

I understand that, but I don't think this would count as advising, just providing reference material for a fearless experimenter. Someone will have to try that at some point anyway, right?

**Comment by mkopec** [comment]
@Hypocrite1127 You can try adding the following parameters [here](https://github.com/Dasharo/coreboot/blob/msi_ms7d25/release/src/mainboard/msi/ms7d25/romstage_fsp_params.c#L63)

```c
memupd->FspmConfig.SaOcSupport = 1;
memupd->FspmConfig.SaVoltageOffset = [voltage offset in milivolts];
``` 

We have not tested this at all, so obviously do this at your own risk. I can't guarantee that this won't make your computer explode instantly :) Start with lower offsets and verify in software if the voltage was increased as expected. On Windows you can use HWINFO64 for this.

**Comment by Hypocrite1127** [comment]
Ah, I think I'm out of luck — my CPU is 12700 non-K and Intel [locked](https://www.intel.com/content/www/us/en/support/articles/000089916/processors.html) System Agent voltages there.

**Comment by mkopec** [comment]
Ah, right, Intel locked this in non-K SKUs... There are also other options like SA Gear 2 mode that the stock BIOS might be doing here. Needs to be investigated properly.

**Comment by Hypocrite1127** [comment]
Just in case this isn't obvious already, I have absolutely no idea what I'm doing. I just tried this, though, based on your suggestion:
```c
memupd->FspmConfig.SpdProfileSelected = 2; // XMP Profile 1
memupd->FspmConfig.SaGv = 0; // SAGV disabled
memupd->FspmConfig.GearRatio = 2; // SAGV disabled Gear 2
```
I've just started MemTest86, but no errors so far — before it was throwing those immediately. I have good hopes for that, I'll keep you posted.
For now, do you think it might be a good idea leaving that parameters on or is there also something to watch out for?

**Comment by mkopec** [comment]
These look fine, they don't increase voltages beyond spec so they should be safe. Disabling SaGv might increase idle power consumption slightly but I'm not sure if we were even using SaGv before.

**Comment by miczyg1** [comment]
It was set to `SaGv_Enabled` by default

**Comment by mkopec** [comment]
I think SA Loadline may also help in this case but it looks like it's not wired up in the alderlake code in coreboot. I'll have a look if it can even be adjusted with FSP

**Comment by Firminator** [comment]
Any updates in this matter or are we stuck?

**Comment by miczyg1** [comment]
We had many conferences in the past 2 weeks. Additionally, this feature may not necessarily be the highest priority (given that we have problems w dGPUs for example).

**Comment by zirblazer** [comment]
Note than before implementing any kind of Memory Overclocking, I suggest to first consider how on earth are you going to recover if you want to, say, use a XMP Profile that is far higher than what the Processor Memory Controller supports and makes the system to get into a no-POST situation, which may effectively be a brick. This is not unusual if you set things too high or maybe too low. Example: https://www.reddit.com/r/buildapc/comments/s6dbza/no_post_after_xmp_is_enabled/

I know than there is an "overclocking watchdog" somewhere (Was it Chipset? Recall some mentions on either the Alder Lake FSP Integration Guide or Alder Lake Data Sheets), do you have the piping necessary to restore previous known-good settings if you get no-POST due to overclock being too high?
Alternatively, if the settings gets saved to UEFI NVRAM, as a last resort USB BIOS Flashback could work as a poor's man method to recovery. Or overclocking settings could be saved to RTC SRAM so that you can Clear CMOS to go back to defaults.

**Comment by pietrushnic** [comment]
@miczyg1 you added this item to v1.1.2, did we released it? TBH I can't see it on release notes.

**Comment by miczyg1** [comment]
@pietrushnic like I said elsewhere, the milestones are outdated.

**Comment by pietrushnic** [comment]
@miczyg1 we have to correct the assignment, I guess you have the most recent knowledge of what should be assigned to which milestone. Or maybe that can be addressed by @BeataZdunczyk ?

**Comment by miczyg1** [comment]
Updated the milestones yesterday

**Comment by pietrushnic** [comment]
@miczyg1 Yes, you did updates and I see that in the history of this issue, but the key question is if this is the only issue affected. I don't want to go through all the issues and ask individually.

**Comment by macpijan** [comment]
I believe @miczyg1 meant that milestones have been generally updated, not only in this one issue. I saw much more updates, and in general the state looks correct.

**Comment by SergiiDmytruk** [comment]
https://github.com/Dasharo/coreboot/pull/403
https://github.com/Dasharo/edk2/pull/81
https://github.com/Dasharo/DasharoModulePkg/pull/32

**Comment by ShalokShalom** [comment]
The link on the homepage to this issue here does contain an additional `)` character, that prevents it from resolving the URL correctly. 

![Screenshot_20231015_112316](https://github.com/Dasharo/dasharo-issues/assets/6344099/5b1dc5a7-17d0-45bf-95c7-be610a7606c1)

**Comment by pietrushnic** [comment]
@ShalokShalom thank you very much for that report and all the other contributions.

**Comment by Stanislaw-bnk** [comment]
@ShalokShalom The URL has been fixed. We appreciate you bringing it to our attention.

**Comment by BeataZdunczyk** [comment]
Closing this issue as the changes have been merged. We are currently completing testing for the release, and further updates will be provided on testing issues https://github.com/Dasharo/dasharo-issues/issues/612 and https://github.com/Dasharo/dasharo-issues/issues/613.
