### ISSUE TITLE
Fix warning about local hash equivalence server

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#878]
### Component

Dasharo Tools Suite

### Device

PC Engines APU2

### Dasharo Tools Suite version

v1.2.21

### Brief summary

warnings while building DTS

### How reproducible

always

### How to reproduce

on current develop run: https://docs.dasharo.com/dasharo-tools-suite/documentation/#building

### Expected behavior

No warning which may concern developer.

### Actual behavior

```
WARNING: You are using a local hash equivalence server but have configured an sstate mirror. This will likely mean no sstate will match from the mirror. You may wish to disable the hash equivalence use (BB_HASHSERVE), or use a hash equivalence server alongside the sstate mirror.
```

**Comment by macpijan** [comment]
We should look closer into: https://docs.yoctoproject.org/overview-manual/concepts.html#hash-equivalence and either setup public hash equivalence server, or disable this feature

**Comment by m-iwanicki** [comment]
https://github.com/Dasharo/meta-dts/pull/205 disables this feature and warning.

**Comment by DaniilKl** [comment]
The issue seems to be solved.
