### ISSUE TITLE
meta-dts cache problem

### ISSUE THREAD

**Issue by DaniilKl** [Dasharo/dasharo-issues#880]
### Component

Dasharo Tools Suite

### Device

other

### Dasharo version

-

### Dasharo Tools Suite version

22840b7e4e1199952bb04f8aa0760531998793e3

### Brief summary

No cache is being used during build

### How reproducible

100%

### How to reproduce

BUild `meta-dts` on commit `22840b7e4e1199952bb04f8aa0760531998793e3`:

```bash
kas-container build meta-dts/kas.yml
```

### Expected behavior

At least small part of cache from `cache.dasharo.com` is being used.

### Actual behavior

No cache is being used and build starts from zero.

### Screenshots

```bash
(...)
Checking sstate mirror object availability: 100% |#####################################################| Time: 0:01:13
Sstate summary: Wanted 3388 Local 1 Mirrors 0 Missed 3387 Current 796 (0% match, 19% complete)
(...)
```

### Additional context

The problem seems to be connected with branch `pre-commit` cos it have appeared just after merging the branch into `develop`.

**Comment by DaniilKl** [comment]
@PLangowski , @m-iwanicki, feel free to add some ideas here.

**Comment by m-iwanicki** [comment]
@DaniilKl Maybe because `cache.dasharo.com` contains only sstate from main branch. I checked couple random dependencies and in all cases cache contained older versions e.g.
`./6a/08/sstate:sqlite3-native::3.38.5:r0::10` (cache) and `./8a/ef/sstate:sqlite3-native::3.45.1:r0::12` (local)

**Comment by macpijan** [comment]
So what do we need here to solve this issue? Should we host both master and develop caches? That sounds reasonable to me.

**Comment by DaniilKl** [comment]
Sounds ok. I left this issue open, because we are going to make some changes in our infrastructure, and this issue will server as a reminder.

**Comment by macpijan** [comment]
Tried building from master now, no cache was reused. Something is off.

**Comment by DaniilKl** [comment]
It [should be ok for `main`](https://github.com/Dasharo/meta-dts/actions/runs/9817875970), closing this issue.
