### ISSUE TITLE
Audio subsystem problems on V560TU

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#881]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc2

### Brief summary

Both Ubuntu and Windows don't detect external audio headset. Windows doesn't detect the internal mic and speakers.

### How reproducible

100%

### How to reproduce

Try to play or record any audio at all on Windows. Try to plug in a headset on Ubuntu and see if it gets detected.

### Expected behavior

Internal and external audio devices should get detected and be functional on both OSes.

### Actual behavior

No audio devices detected on Windows with or without a headset. On Ubuntu, only the headset doesn't get detected.

**Comment by macpijan** [comment]
@mkopec Please convert to checklist and link relevant resources (firmare PR, documentation update) addressing each of them when ready.

**Comment by mkopec** [comment]
Also needed to add HDA verbs from vendor firmware: https://github.com/Dasharo/coreboot/pull/488/commits/b30c579bc6d6805b5934ee554582511cfc34ea9e

Jack detection now works on Ubuntu. Will move on to Windows now

**Comment by mkopec** [comment]
Also fixed on Windows. All that's missing is sending this patch to LKML: 

```diff
diff --git a/sound/pci/hda/patch_realtek.c b/sound/pci/hda/patch_realtek.c
index a696943aec0d..47a019598767 100644
--- a/sound/pci/hda/patch_realtek.c
+++ b/sound/pci/hda/patch_realtek.c
@@ -10426,6 +10426,7 @@ static const struct snd_pci_quirk alc269_fixup_tbl[] = {
 	SND_PCI_QUIRK(0x1558, 0xa600, "Clevo NL50NU", ALC293_FIXUP_SYSTEM76_MIC_NO_PRESENCE),
 	SND_PCI_QUIRK(0x1558, 0xa650, "Clevo NP[567]0SN[CD]", ALC256_FIXUP_SYSTEM76_MIC_NO_PRESENCE),
 	SND_PCI_QUIRK(0x1558, 0xa671, "Clevo NP70SN[CDE]", ALC256_FIXUP_SYSTEM76_MIC_NO_PRESENCE),
+	SND_PCI_QUIRK(0x1558, 0xa763, "Clevo V54x_6x_TU", ALC256_FIXUP_SYSTEM76_MIC_NO_PRESENCE),
 	SND_PCI_QUIRK(0x1558, 0xb018, "Clevo NP50D[BE]", ALC293_FIXUP_SYSTEM76_MIC_NO_PRESENCE),
 	SND_PCI_QUIRK(0x1558, 0xb019, "Clevo NH77D[BE]Q", ALC293_FIXUP_SYSTEM76_MIC_NO_PRESENCE),
 	SND_PCI_QUIRK(0x1558, 0xb022, "Clevo NH77D[DC][QW]", ALC293_FIXUP_SYSTEM76_MIC_NO_PRESENCE),
--
```

**Comment by mkopec** [comment]
Sent and merged: https://patchwork.kernel.org/project/alsa-devel/patch/20240701111010.1496569-1-michal.kopec@3mdeb.com/

I guess we should close this once it gets released?

**Comment by marmarek** [comment]
Can you reopen this (see my comment above)? Or should I open a new issue?

**Comment by pietrushnic** [comment]
@macpijan @BeataZdunczyk ping

**Comment by marmarek** [comment]
Re-checked on 1.0.0, still an issue. Specific steps:
1. Start the system, no headset, check pavucontrol ("input devices" tab) or `pactl list sources` - at this point "internal mic" port should be active
2. Connect headset, check pavucontrol or pactl - it should switch to headset mic, but it doesn't.

This one reproduces 100% for me. On both Linux 6.12 ("kernel") and Linux 6.15/6.16 ("kernel-latest") in dom0.

The only part that is not 100% reproducible is listing headset as "unplugged" even when it's plugged in.

**Comment by resonant-riches** [comment]
The "headset mic shows up in pavucontrol but is not selected automatically" problem is still there for me in Dasharo V560TU 1.0.1, Qubes 4.3.
