### ISSUE TITLE
Cannot boot from iPXE on v560TU

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#882]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc2

### Brief summary

Trying to boot anything or just running `dhcp` in iPXE results in `Waiting for link-up on net0...... Down`

### How reproducible

100%

### How to reproduce

Try to boot any option from iPXE, or run `dhcp` from iPXE shell

### Expected behavior

It should boot the option

### Actual behavior

`Waiting for link-up on net0...... Down`, even though ethernet link is functional in OSes

**Comment by filipleple** [comment]
@macpijan same in both cases

**Comment by mkopec** [comment]
Some test results from me:
- Keep AC in, go from S0->S5->S0: iPXE works
- Keep AC in, reboot: iPXE works
- Power off, disconnect and reconnect AC, power on (S0->G3->S0): iPXE **doesn't work**

I guess OS does some sort of init that's missing in iPXE, and it gets reset after complete shutdown.

**Comment by macpijan** [comment]
Should we try to update ipxe rev? Or look/report for issues on this driver?

**Comment by mkopec** [comment]
Fixed by including the Intel i219 driver: https://github.com/Dasharo/coreboot/pull/488/commits/493609f5e09b53144933e871b8ad44097504202e
