### ISSUE TITLE
ME option Disabled (HAP) doesn't work

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#883]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc2

### Brief summary

ME option Disabled (HAP) doesn't work, ME is still present in `lspci` (as `00:16.0`)

### How to reproduce

Set ME option to Disabled (HAP) and boot Ubuntu

### Expected behavior

It should disable ME, so it shouldn't be present in `lspci`

### Actual behavior

It is present in `lspci`

**Comment by miczyg1** [comment]
The newest laptops do not have HAP support yet added in coreboot, so this is "expected" result for now.

We will post an update here if it gets implemented.

**Comment by mkopec** [comment]
Fixed by https://github.com/Dasharo/coreboot/pull/488/commits/c82793785de76470504ef4d518e589060914d5fd , will close the issue once confirmed.

**Comment by mkopec** [comment]
HAP is now visible, but there's an issue with sending EOP when the bit is set, which prevents booting

**Comment by mkopec** [comment]
Setting the bit causes the operation mode of CSME to be set to 2 (Debug). coreboot should not allow sending EOP or other HECI cmds in this state
