### ISSUE TITLE
Firmware Setup Menu is barely readable on high resolution screens

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#885]
### The problem you're addressing (if any)

Firmware Setup Menu is barely readable on high resolution screens
![20240520_143850](https://github.com/Dasharo/dasharo-issues/assets/19353650/6ea01e79-3956-4b1c-950e-e8078c13dcd3)

### Describe the solution you'd like

Fonts are bigger, so can be easily readable

**Comment by mkopec** [comment]
Fixed by https://github.com/Dasharo/coreboot/pull/488/commits/1193e3f15802e35725f92bdd22a5e785b0eb4c60 . Will close once confirmed fixed on hardware.

**Comment by mkopec** [comment]
Confirmed fixed by enabling fixed display mode @ 1920x1200.
