### ISSUE TITLE
MTL platforms fail to boot with some memory modules

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#886]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc3

### Brief summary

Some memory modules don't work well with MTL laptops.

### How to reproduce

with 16GB module:
- booting once after flashing works
- rebooting works
- power off and power back on **doesn't work**

with 32GB module:
- booting with module in slot 2 works
- booting with module in slot 1 **doesn't work**

### Expected behavior

All modules must work.

### Actual behavior

Not all modules work.

**Comment by marmarek** [comment]
> with 16GB module:
> 
>     * booting once after flashing works
> 
>     * rebooting works
> 
>     * power off and power back on **doesn't work**

I have similar experience with 48GB module in slot 2, but in my case even rebooting doesn't work.

The same module in slot 1 doesn't work even once (but this I tried on a slightly older build, I can re-test with a recent build if needed).

All tests on V560TU.

**Comment by mkopec** [comment]
Apparently fixed by using FSP v4122_14. Need to test 48GB modules still.

**Comment by wessel-novacustom** [comment]
On V540TU with Ultra 7, the laptop doesn't boot after external flashing `v0.9.0-rc4` and the belonging EC, then going to the BIOS settings immediately and select Reset (as in: restart).

Powering off and on doesn't bring the device back to life either, the screen display remains off.

So it did boot the first time.

The unit has 1x 16 GB internal memory installed in slot 2, and a PX600 SSD installed in the slot on top of the mainboard.

**Comment by marmarek** [comment]
Same for me with rc4 - still broken the same way.

**Comment by marmarek** [comment]
Is there some extra debugging info I can extract to help? Or maybe test some specific procedure?

**Comment by wessel-novacustom** [comment]
On V560TU with Ultra 7, with `v0.9.0-rc4` for this laptop, with 2x 48 = 96 GB internal memory and PX600 500GB SSD, booting, rebooting and cold boot works fine. Boot time after first memory initialisation is about 8 seconds.

**Comment by mkopec** [comment]
Okay, I've reproduced on a V560TU unit. Could not reproduce on a V540TU unit. I get an FSP-S error (Not FSP-M weirdly, so maybe not related to memory after all)

```
[16:22:00.638] [INFO ]  FSPS returned 80000003
[16:22:00.654] [EMERG]  FspSiliconInit returned with error 0x80000003
```

(plus some FSP debug logs that I can't paste here)

**Comment by wessel-novacustom** [comment]
> On another V540 with Ultra 5 and `v0.9.0-rc4` BIOS and belonging EC, with 1x 32 GB internal memory installed in slot 2, and 1x PX600 SSD on the MB, then going to the BIOS settings immediately and select Reset (as in: restart). Powering off and on doesn't bring the device back to life either, the screen display remains off.
> 
> So it did boot the first time. It looks like the chips on the internal memory modules are sometimes different:
> 
> I'll now try with the other module to see if the behaviour is the same.

- Same behaviour.

**Comment by wessel-novacustom** [comment]
Tested 6 units so far. 3 of them work fine and these all have an Ultra 7 155H. The 3 failing units have an Ultra 5 125H CPU.

**Comment by marmarek** [comment]
I forgot to mention mine failing one is Ultra 5 125H too.

**Comment by macpijan** [comment]
So we are starting to get some pattern emerging at least :upside_down_face:

**Comment by mkopec** [comment]
According to https://review.coreboot.org/c/coreboot/+/81269/2 there's a critical bug in the cache-as-ram logic in the CPU itself if the cache set count is not a power of 2 :)

On 155H there are 32768 cache sets, on 125H there are 24576. Seems like we're running into this issue, where booting hangs just before postcar.

**Comment by mkopec** [comment]
Yes this fixed the affected V560TU unit with 125H.

**Comment by wessel-novacustom** [comment]
@mkopec Would be nice if you could prepare another release candidate, maybe also with an [iPXE fix](https://github.com/Dasharo/dasharo-issues/issues/882).

**Comment by mkopec** [comment]
-rc5 was sent to @wessel-novacustom @marmarek and the issue is confirmed resolved I believe.

**Comment by wessel-novacustom** [comment]
@mkopec I confirm the correct functionality on `rc-5`, platform V540TU, Ultra 5.
