### ISSUE TITLE
'Reset to Defaults' tries setting up too many variables

### ISSUE THREAD

**Issue by krystian-hebel** [Dasharo/dasharo-issues#887]
### Component

Dasharo firmware

### Device

PC Engines APU2, PC Engines APU3, PC Engines APU4, PC Engines APU6, QEMU Q35 Emulator, other

### Dasharo version

Noticed on https://github.com/Dasharo/edk2/commit/f4b94d7f1d4c59ad269db15034d4f9a6149afc55, but probably applies to pre-rebased edk2 as well

### Brief summary

Default values for variables that aren't used by given platform are restored, and may fail validity checks. An example of such setting is `CPU Throttling Threshold` on QEMU Q35 and probably PC Engines platforms as well.

### How reproducible

100%

### How to reproduce

- build QEMU from https://github.com/Dasharo/coreboot/pull/514/commits/71450da7c495c8cd9c746f9c4283d3c70576e59b (`./build.sh q35`)
- boot and enter setup
- restore defaults (F9) and try to save them (F10)

### Expected behavior

Defaults restored and saved without errors

### Actual behavior

Error saying that CPU throttling value is out of range

### Screenshots

![Zrzut ekranu z 2024-06-19 16-46-26](https://github.com/Dasharo/dasharo-issues/assets/40995177/0cb4f0ee-bcf2-4e90-9c57-e98dd623acb0)
![Zrzut ekranu z 2024-06-19 16-47-16](https://github.com/Dasharo/dasharo-issues/assets/40995177/b9db61a2-2439-4da5-b865-947e3f46df8c)
![Zrzut ekranu z 2024-06-19 17-10-51](https://github.com/Dasharo/dasharo-issues/assets/40995177/56cb142f-b446-4f57-ac21-f696fff6f445)

### Additional context

List of variables introduced in https://github.com/Dasharo/DasharoModulePkg/pull/45 and updated in https://github.com/Dasharo/DasharoModulePkg/pull/48 may be extended to include PCD name (or bolean value based on it? This would allow for non-trivial requirements in the future) that controls whether the menu is shown (e.g. `PcdShowCpuThrottlingThreshold` for this case, similarly for others).

### Solutions you've tried

Error can be discarded, which allows to reset other settings. Trying to get to higher menu level by pressing ESC when on `Power Management Options` page immediately exits setup app. That page isn't accessible by traversing the menu.

**Comment by pietrushnic** [comment]
@macpijan @BeataZdunczyk I guess this should go to v0.9.1, but is there no such milestone yet?

**Comment by krystian-hebel** [comment]
This touches more platforms than anticipated: https://github.com/Dasharo/DasharoModulePkg/pull/50#issuecomment-2186623086

**Comment by miczyg1** [comment]
That is why https://github.com/Dasharo/DasharoModulePkg/pull/50 must land to fix this
