### ISSUE TITLE
Headsets connected to the docking station are not recognizable on NS70/50, NV4X v1.2.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#89]
**Dasharo version**
v1.2.0

**Dasharo variant**
Clevo NS50/70, Clevo NV41MZ/MB

**Affected component(s) or functionality**
miniJack 3.5mm slot on the docking station

**Brief summary**
After plug 3.5mm jack into the slot on the docking station, headsets are not recognizable.

**How reproducible**
The issue occurs every time when 3.5mm jack is plugged to the docking station 

**How to reproduce**

1. Connect the docking station to USB-C port on the DUT
2. Plug 3.5mm jack into the slot on the docking station.
OR
1. Plug 3.5mm jack into the slot on the docking station.
2. Connect the docking station to USB-C port on the DUT

**Expected behavior**
Connected headsets are recognized by OS.

**Actual behavior**
Connected headsets are not recognized by OS.

**Screenshots**

**Additional context**
This issue applies to Ubuntu 22.04 and Windows 11
                                                                                                               
**Solutions you've tried**

**Comment by Pokisiekk** [comment]
The problems were due to the specifications of the docking station used for testing and the need to connect a VGA cable to it.

**Comment by wessel-novacustom** [comment]
Hi,

Good to know, thank you for letting me know.

This is not what our customers expect, which is why we decided not to continue with the docking station in question.

We now have another docking station with PowerDelivery (PD) 100W on board, which we will provide you as a replacement.

Many thanks!
