### ISSUE TITLE
0 MB RAM in Setup Menu on V560TU

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#891]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc2

### Brief summary

Setup Menu on V560TU displays 0 MB RAM under CPU clock

### How reproducible

100%

### How to reproduce

Enter EDK2 setup menu on V560TU

### Expected behavior

It should display the correct amount of RAM (it's not 0)

### Actual behavior

It displays 0 MB RAM

**Comment by mkopec** [comment]
This is fixed by including the correct MemInfoHob.h for the FSP version we're using. However that header is not public. Until client MTL FSP is published, public builds will not have this feature.

**Comment by mkopec** [comment]
Fixed by including all matching headers in v0.9.0-rc5
