### ISSUE TITLE
Pressing ENTER does not select the default answer in DTS

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#895]
### Component

Dasharo Tools Suite

### Device

other

### Dasharo version

N/A

### Dasharo Tools Suite version

v1.2.22

### Brief summary

When given prompt with  `(Y|n)`, I would expect pressing ENTER to select the option with capital case. This is not the case.

### How to reproduce

Boot DTS and update firmware using option 5. It applies to all prompts in DTS, though.

### Expected behavior

When given prompt with  `(Y|n)`, I would expect pressing ENTER to select the option with capital case. This is not the case.

### Actual behavior

I need to actually press `y` then ENTER

**Comment by EduKav1813** [comment]
This was successfully implemented in https://github.com/Dasharo/dts-scripts/pull/34

Pr with version bump: https://github.com/Dasharo/meta-dts/pull/175
