### ISSUE TITLE
Power State After Power Failure restoration fails

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#900]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc2

### Brief summary

After power failure, the device will remain powered off regardless of what the option is set to.

### How reproducible

100%

### How to reproduce

* Disconnect the battery
* Set the `Power state after power failure` option to `Powered On`
* Reset to save changes, boot OS, power off from OS
* Unplug AC
* Plug it back in after a couple seconds

Same thing if you pick `The state at the moment of power failure` and unplug the AC while the platform is powered on

### Expected behavior

The platform should power back on after getting the AC plugged in

### Actual behavior

It doesn't

### Additional context

I did reset first so that the option is saved

**Comment by mkopec** [comment]
Fixed by https://github.com/Dasharo/ec/commit/4751cebfcbab752d6294273f1d31c404180b4d7e
