### ISSUE TITLE
Logo customisation not working

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#904]
### Component

Dasharo firmware, Dasharo Tools Suite

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc5

### Dasharo Tools Suite version

v2.0.0-rc1

### Brief summary

Changing the logo was not successful

### How reproducible

100% reproducible.

### How to reproduce

1. Host the image _BLANK.bmp_ on a local web server. This is an uncompressed fully black image. The command `file BLANK.bmp` returns: `BLANK.bmp: PC bitmap, Windows 3.x format, 577 x 432 x 24, image size 748224, resolution 2835 x 2835 px/m, cbSize 748278, bits offset 54`
2. Disable flash protections in the UEFI firmware settings.
3. Boot to the Dasharo Tools Suite (DTS) and drop to a shell.
4. Execute the following lines:

`flashrom -p internal -r ROM.BIN`
`wget http://192.168.x.x/path/to/BLANK.bmp`
`dcu ROM.BIN logo -l BLANK.bmp` (command successful)
`flashrom -p internal --ifd -i bios -w ROM.BIN && systemctl poweroff`

### Expected behavior

The NovaCustom logo is replaced with the blank image.

### Actual behavior

The NovaCustom logo is still the BIOS boot splash logo.

### Additional context

Is the file type supported and does it make sense to try another file type?

**Comment by mkopec** [comment]
I can see coreboot correctly loads a logo into CBMEM, but EDK2 doesn't apply it. Probably got lost during EDK2 rebase

**Comment by SergiiDmytruk** [comment]
> Probably got lost during EDK2 rebase

They weren't marked as required for inclusion into rebased version.  I thought that's because they are in upstream now, but doesn't look like it.  @mkopec, should I add them or you're doing it already?

**Comment by mkopec** [comment]
@SergiiDmytruk I haven't started doing it yet, if you could help with that it would be great :)

**Comment by SergiiDmytruk** [comment]
I'll add them to the branch then.

**Comment by SergiiDmytruk** [comment]
Picking up https://github.com/Dasharo/edk2/pull/129/commits/43302b40dae80ac3ac651421d04b232cd85cb358 should fix this.  Works for me in Q35.

**Comment by wessel-novacustom** [comment]
> Picking up [Dasharo/edk2@43302b4](https://github.com/Dasharo/edk2/commit/43302b40dae80ac3ac651421d04b232cd85cb358) should fix this. Works for me in Q35.

- Thank you, I will wait for another release candidate from @mkopec and then try again and close the issue if it has indeed been solved.

**Comment by mkopec** [comment]
Confirmed resolved by uprevving edk2 to https://github.com/Dasharo/edk2/pull/129/commits/43302b40dae80ac3ac651421d04b232cd85cb358

**Comment by filipleple** [comment]
I haven't managed to set a custom logo in `0.9.0-rc7` on V540TU either

**Comment by wessel-novacustom** [comment]
@mkopec It is not working yet for `0.9.0-rc7` on the V560TU.

**Comment by wessel-novacustom** [comment]
Solved with `0.9.0-rc10`.

**Comment by mkopec** [comment]
@filipleple Could you confirm that the issue is fixed on rc10? It works on my end with a V560TU rc10

**Comment by filipleple** [comment]
@mkopec yes, after a quick consultation I can confirm this is resolved for V540TU as well :D
