### ISSUE TITLE
Unexpected GNA-related error in dmesg

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#908]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc2

### Brief summary

`ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.GNA_`

### How reproducible

100%

### How to reproduce

Boot the platform and check dmesg

### Expected behavior

Harmless, common errors or ideally none at all

### Actual behavior

`ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.GNA_`

**Comment by mkopec** [comment]
there are also ACPI erorrs for missing HEC1 and SRAM devices. I had to add these to ACPI LPI table to stop windows BSODing due to missing devices, but I guess I also need to add some stubs for them

**Comment by mkopec** [comment]
Missing GNA device- https://github.com/Dasharo/coreboot/pull/488/commits/a1539d64771f76ff7d2b8a61cf84a4d360151ddb
Missing HEC1 and SRAM devices: https://github.com/Dasharo/coreboot/pull/488/commits/9be361d2deaffff8674686ef55b455cc86065a77
