### ISSUE TITLE
Explanation of apu1, apu5, and apu7 Removal in Dasharo Firmware Update 24.05.00.01

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#909]
The removal of apu1, apu5, and apu7 from the latest Dasharo release for PC Engines can be explained by specific factors affecting each model:

### **apu1 Removal**:
   - **Memory Allocator Issues**: apu1 was removed from the supported platforms in the latest coreboot version due to problems with migration to the new coreboot memory allocator.
   ** Aging Platform **: Additionally, apu1 is described as quite old. This implies that it may need to meet the latest hardware efficiency, security standards, or performance expectations, making it less suitable for inclusion in a firmware update focused on maintaining and enhancing current standards.

### **apu5 and apu7 Removal**:
- **Limited Public Sale**: The apu5 and apu7 platforms were not sold publicly, which limited their market exposure and user base. The small user base makes it less viable for firmware developers to allocate extensive resources to these platforms, as the impact of such support is minimal relative to other platforms with a more comprehensive user base.
- **Cost-Benefit Consideration**: Supporting apu5 and apu7 may need to be more economically and practically feasible for a company that aims to deliver regular, impactful updates to a broader audience. The decision to exclude these platforms likely involved analyzing the benefits relative to the costs, leading to their removal from active development focus in this release.

#### **Configuration Remains**:
- **Build Configurations in Tree**: Although apu5 and apu7 have been removed from the list of actively supported platforms in this firmware update, their configuration files remain available in the coreboot tree. This inclusion means that the foundational setup for building firmware for these platforms is still accessible to developers or interested parties.
- **Lack of Testing and Extensions**: It's important to note that while the configurations exist, they still need to be tested or updated to build the latest firmware version 24.05.00.01. This indicates that any attempts to use these configurations to make the firmware might not reflect the latest improvements or security fixes included in newer versions and may only function as intended with additional development and validation.

### **General Considerations**:
The decision to remove these platforms aligns with the release's goal to provide a stable and secure foundation for the most widely used and currently relevant hardware. While the firmware does not aim to modernize extensively, it seeks to enhance the reliability, compatibility, and security of the platforms it supports.

### **Openness to Recovery**:
It’s important to note that the company is open to revisiting these decisions. The company has expressed willingness to consider the "sponsored recovery" of these platforms, suggesting that if there is enough interest or financial backing from the community or clients, support could be restored in future releases. This approach allows for flexibility and responsiveness to user needs and market demand.

If you have further inquiries or would like to discuss potential support options, don't hesitate to contact Dasharo Team at **contact@dasharo.com** or visit **[https://www.dasharo.com/pages/contact](https://www.dasharo.com/pages/contact)**.

**Comment by pietrushnic** [comment]
@miczyg1 I would appreciate confirmation if I'm not confusing things regarding those platforms.

**Comment by miczyg1** [comment]
Nothing catches my eye here. Not sure about the apu7 situation, though. It was an experimental board with i225 NICs because of component shortage, but never heard if it hit production state and was sold actively.

**Comment by pietrushnic** [comment]
Thanks. For apu7, there are no signs of it being sold publicly ever.
