### ISSUE TITLE
Laggy behaviour on Manjaro (KDE) with open drivers

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#911]
### Component

Dasharo firmware, EC firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.0-rc5

### Dasharo Tools Suite version

N/A

### Brief summary

The screen display is not responding smoothly when selecting and dragging on the desktop.

### How reproducible

100% reproducible.

### How to reproduce

1. Install Manjaro (KDE), latest version.
2. Install all updates and restart.
3. Drag over the background of the desktop while holding the left touchpad button.

### Expected behavior

The selection rectangle resizes smoothly.

### Actual behavior

The selection rectangle resizes with laggy behaviour.

### Screenshots

https://github.com/Dasharo/dasharo-issues/assets/100232604/11b38da5-d15a-4fd1-9be3-3ab0cf191bb1

### Additional context

While Manjaro may not be part of the test scope, it might be useful to find a fix for this, I suspect that the performance is set too low when (almost) idling.

### Solutions you've tried

None.

**Comment by macpijan** [comment]
Which kernel version is this? Can be software rendering due to older kernel perhaps?

**Comment by wessel-novacustom** [comment]
@macpijan `6.9.3-3-MANJARO`

 I found out that switching to Wayland causes freezing at logging in (100% reproducible).

Might be because of Meteor Lake, but the kernel seems rather new to me.

**Comment by wessel-novacustom** [comment]
Can proprietary drivers be necessary here? We selected open drivers at the installation menu of the USB pen drive.

**Comment by mkopec** [comment]
@wessel-novacustom could you paste the output from `sudo dmesg` here? I found sometimes the distro provided linux-firmware is too old for MTL graphics

**Comment by thtliife** [comment]
I had a similar issue running hyprland on arch. 
Fixed it by adding the following kernel parameter and rebooting.

`initcall_blacklist=simpledrm_platform_driver_init`

Seems arch was loading the old Intel drivers without that parameter set

**Comment by wessel-novacustom** [comment]
> I had a similar issue running hyprland on arch. Fixed it by adding the following kernel parameter and rebooting.
> 
> `initcall_blacklist=simpledrm_platform_driver_init`
> 
> Seems arch was loading the old simple framebuffer device module without that parameter set, which doesn't work on Intel arc igpu

Some kind of driver must have been missing, the problem disappeared after a while during regular OS system updates.
