### ISSUE TITLE
Secure Boot disables itself after reset after EDK2 rebase

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#918]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc2

### Brief summary

Secure Boot disables itself after reset after EDK2 rebase

### How reproducible

100%

### How to reproduce

Enable secure boot in setup menu, reset, reenter setup menu and observe that it's disabled again

### Expected behavior

It should stay enabled and take effect ( as in prevent booting unsigned binaries )

### Actual behavior

It disables itself upon each reset, effectively it's impossible to enable

**Comment by mkopec** [comment]
This was resolved in https://github.com/Dasharo/edk2/pull/129#issuecomment-2179212147 and I confirm the issue is no longer there in rc5
