### ISSUE TITLE
Drop sensitive information from dasharo-hcl-report

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#92]
Drop MAC etc. when uploading HCL data to Dasharo server.

See: https://github.com/Dasharo/docs/pull/197#discussion_r882027862

**Comment by TomaszAIR** [comment]
@kotylamichal please lets use this issue to add one more minor change. Lets add link to Dasharo HCL report description from docs.dasharo.com in the report disclaimer.

**Comment by kotylamichal** [comment]
@TomaszAIR done

**Comment by rafkoch** [comment]
I moved this issue (card) to DONE column in project "Nlnet October 2022", because status is CLOSED.
