### ISSUE TITLE
Memtest errors on V560TU

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#926]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc6

### Brief summary

Memtest finds errors in certain RAM sticks on V560TU with Intel Core Ultra 7 155H, even though they reliably manage to boot into and operate in an OS (Ubuntu)

### How reproducible

100%

### How to reproduce

Try to run memtest on V560TU with the following sticks inserted:

* 1x48GB

### Expected behavior

PASS

### Actual behavior

FAIL; for 48GB sticks memtest stops at 10000 errors - even though they operate under Ubuntu without causing any trouble

### Additional context

memtest 10.6; 48GB sticks re-tested with 10.7 for confirmation

**Comment by mkopec** [comment]
I guess SaGv might be causing us problems here, might want to disable some of the SaGv points

**Comment by wessel-novacustom** [comment]
I have seen the same with 2x 32 GB. Only ran the first test stage. After exchanging the modules, the issue no longer happened. But other chips seem to be used on those other modules.

**Comment by mkopec** [comment]
Apparently also fixed https://github.com/Dasharo/coreboot/commit/d7eb079076fc5213d525468425e4def12bf6c204 , at least the 48GB module seems to be passing without errors, after the CMOS reset
