### ISSUE TITLE
Automate dumping UUID/serial of the MSI Z690

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#93]
https://github.com/Dasharo/docs/pull/197#discussion_r882123175

**Comment by TomaszAIR** [comment]
After implementing initial deployment for MSI PRO Z690-A WIFI DDR4 this is could be closed

**Comment by miczyg1** [comment]
We already have it implemented: https://github.com/Dasharo/meta-dts/blob/4791b78aa9a2785dec989eca7114ba808a6fb88c/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy#L440
