### ISSUE TITLE
Play/Pause and Touchpad On/Off hotkeys do not work in Ubuntu on V540TU

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#932]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.0-rc7

### Brief summary

Play/Pause and Touchpad On/Off hotkeys do not work in Ubuntu on V540TU

### How reproducible

100%

### How to reproduce

Try to use the Play/Pause and Touchpad On/Off hotkeys 

### Expected behavior

The Play/Pause should play and pause, and the Touchpad On/Off should turn the touchpad on and off

### Actual behavior

On Ubuntu, they don't. Only a `∅` icon appears at the bottom of the screen. However, all hotkeys work just fine on Windows.

**Comment by macpijan** [comment]
Ubuntu version missing in the report

**Comment by wessel-novacustom** [comment]
Touchpad Fn key switch requires a [post installation step](https://docs.dasharo.com/unified/clevo/post-install/#touchpad-hotkey-enablement) whenafter it works for me.

**Comment by mkopec** [comment]
The play / pause hotkey produces the `KEY_PLAYPAUSE` keycode in `libinput debug-events` correctly. I'm guessing you didn't have an application listening for the play/pause event, hence the `∅` popup.

When I play YouTube in Firefox, the hotkey works correctly. @filipleple could you retest with some app playing media to confirm it works for you too?

**Comment by macpijan** [comment]
> The play / pause hotkey produces the KEY_PLAYPAUSE keycode in libinput debug-events correctly.

This is where our test should probably end.

If we submit a bug, ideally we should refer to the test case ID which we claim is failing here.

**Comment by mkopec** [comment]
> the media stream doesn't react.

The application doesn't support MPRIS, I guess not all browsers support it out of the box. In any case if the correct event appears in libinput debug-events, then the firmware's job is done, whatever happens in userspace depends on userspace
