### ISSUE TITLE
DTS not functional on MTL laptop

### ISSUE THREAD

**Issue by marmarek** [Dasharo/dasharo-issues#933]
### Component

Dasharo Tools Suite

### Device

NovaCustom V56 14th Gen

### Dasharo version

0.9.0-rc5

### Dasharo Tools Suite version

1.2.23

### Brief summary

wired network and nvme doesn't work in DTS

### How reproducible

always?

### How to reproduce

Boot DTS via iPXE; I used "firmware update mode", but I believe it doesn't change anything related to this issue

### Expected behavior

Boots normally

### Actual behavior

First a long pause after iPXE and first messages (blank screen, I almost reset the device waiting, because I thought it hanged here already).
Then, waits until 3min timeout on "Wait for udev to Complete Device Initialization"
And when it starts finally, network doesn't work, and also nvme isn't detected.
USB appears to be broken too (lsusb hangs).

I'd attach kernel log, but without network/nvme/usb, it's hard to save it anywhere...
But I do see several errors there, including:
- `e1000e 0000:00:1f.6 eno0: Detected Hardware Unit Hang:`, just after `Link is Up 1000 Mbps Full Duplex`
- `nvme nvme0: I/O QID 0 timeout, disable controller`
- `DMAR: DRHD: handling fault status reg 2`
- `DMAR: [DMA Read NO_PASID] Request device [01:00.0] fault addr 0x1010bc000 [fault reason 0x5a] SM: Non-zero reserved field set in PASID Table Entry` (also for other devices: 00:0d.0, 00:14.0)

Early boot DMA protection is not enabled.

**Comment by macpijan** [comment]
We are aware of that, the kernel etc is simply too old for MTL.

We have shared with @wessel-novacustom a test build from devleop branch, which already boots into MTL just fine.

We plan to release something like v2.0.0-rc1 this week so new MTL users will be able to use DTS to update from RC firmware versions to more recent versions.

**Comment by wessel-novacustom** [comment]
@marmarek I made it publically available: https://novacustom.com/forum/d/15-call-for-beta-testers/15

**Comment by BeataZdunczyk** [comment]
DTS release was published for MTL laptops (v0.9.0): https://github.com/Dasharo/meta-dts/releases/tag/v2.0.0-rc3.
Closing this issue.
