### ISSUE TITLE
Debug output enabled in iPXE, v0.9.0-rc7 v540TU

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#936]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.0-rc7

### Brief summary

Debug output enabled in iPXE in v0.9.0-rc7, to be disabled in next RC builds

### How reproducible

100%

### How to reproduce

Boot v0.9.0-rc7 and go into iPXE

### Expected behavior

No debug output

### Actual behavior

Very verbose debug output from network controller

**Comment by filipleple** [comment]
@mkopec this is probably resolved already by the rc8 build?

**Comment by mkopec** [comment]
@filipleple yes, this was fixed in rc8 with [this commit](https://github.com/Dasharo/coreboot/pull/488/commits/d73ffe0ad4bafd41ce0a03a0366ae699640ac170)
