### ISSUE TITLE
meta-dts GitHub Actions (`push to develop`) fail on `Deploying to boot.dasharo.com`

### ISSUE THREAD

**Issue by m-iwanicki** [Dasharo/dasharo-issues#941]
### Component

Dasharo Tools Suite

### Device

other

### Dasharo Tools Suite version

v2.0.0-rc1

### Brief summary

`Deploy DTS on boot.dasharo.com` tries to copy nonexistent file

### How to reproduce

Rerun https://github.com/Dasharo/meta-dts/actions/runs/9853372474 or push tag ending with `-rc*`

### Expected behavior

Job should succeed

### Actual behavior

```
Run DTS_VER="v2.0.0-rc1"
cp: cannot stat 'dts-base-image-genericx86-64.cpio.gz': No such file or directory
Error: Process completed with exit code 1.
```

### Additional context

The only `*.cpio.gz` files when built from develop branch are

```
core-image-minimal-initramfs-genericx86-64-20240619085253.cpio.gz
core-image-minimal-initramfs-genericx86-64.cpio.gz -> core-image-minimal-initramfs-genericx86-64-20240619085253.cpio.gz
dts-base-image-genericx86-64.rootfs-20240619085253.cpio.gz
dts-base-image-genericx86-64.rootfs.cpio.gz -> dts-base-image-genericx86-64.rootfs-20240619085253.cpio.gz
```

On main there is `dts-base-image-genericx86-64.cpio.gz` without `rootfs` part.

**Comment by tym2k1** [comment]
This seems to be related to the [IMAGE_NAME_SUFFIX](https://docs.yoctoproject.org/ref-manual/variables.html#term-IMAGE_NAME_SUFFIX) Yocto variable but it's neither set in `main` nor `develop`. The `main` branch uses the `kirkstone` Yocto version but it's specified that the `.rootfs` is a default value for both versions. Further verification if this variable has an effect is needed.
