### ISSUE TITLE
NovaCustom MTL performance

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#942]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc7

### Brief summary

Low performance on battery power

### How to reproduce

1. Boot to Windows
2. Disconnect charger
3. Start ThrottleStop (without changing any settings)
4. In ThrottleStop, start `TS Bench` with size `infinite`
5. Observe CPU power draw, frequencies and temperatures

### Expected behavior

Good performance and temperatures while maintaining low noise

### Actual behavior

CPU power is limited to ~22W, which in an all core load means frequencies <2GHz, which is too low. Temperatures are also way below the throttle point of 80 degrees

### Additional context

Tweak Psys power limits in EC (set to charger wattage on AC power / to battery discharge rating on DC power)
Tweak PL1 limit in coreboot (default 28W is too conservative, 155H happily boosts to 42W)

**Comment by wessel-novacustom** [comment]
Glad you found the details :-)

**Comment by mkopec** [comment]
Power limits increased in:
- https://github.com/Dasharo/coreboot/commit/4c06be01a06f049f11f2c1090b40227469864113
- https://github.com/Dasharo/ec/commit/4bc18af0d57fa7a3ab291c3e3ddf18631f929a5b
