### ISSUE TITLE
Some USB sticks are not bootable after edk2 rebase

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#946]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc9

### Brief summary

Some EL Torito-formatted USB sticks aren't bootable anymore after EDK2 rebase. There is no entry in the boot manager menu and the ESP can't be found in UEFI shell.

### How to reproduce

- Download iso from https://github.com/leahneukirchen/hrmpf/releases/tag/v20231124
- `dd` it to a USB stick
- Insert USB stick into laptop and power it on
- Open boot manager menu, look for USB stick
- Open UEFI shell, look for partition 2 on USB stick

### Expected behavior

All partitions are enumerated, ESP is detected and live OS is booted

### Actual behavior

Only partition 1 is enumerated and browseable, ESP is unavailable, live OS does not boot

### Additional context

Works fine on EDK2 revisions from before rebase

**Comment by mkopec** [comment]
Should be fixed by https://github.com/Dasharo/edk2/pull/150

**Comment by wessel-novacustom** [comment]
Couldn't reproduce any issues with `v0.9.0-rc10`, I think this is indeed fixed.

**Comment by mkopec** [comment]
Confirmed fixed, closing
