### ISSUE TITLE
VP66xx Windows doesn't detect sound subsystem

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#947]
### Component

Dasharo firmware

### Device

Protectli VP6670, Protectl VP6650

### Dasharo version

v0.9.0-rc6 from cloud

### Dasharo Tools Suite version

origin/osfv-integration-regression

### Test case ID

AUD001.002

### Brief summary

Windows doesn't detect the audio device

### How reproducible

Every time

### How to reproduce

With connected HDMI dongle:
- turn on the device
- boot to windows
- login via ssh
- execute `Get-WmiObject -class Win32_SoundDevice`

### Expected behavior

The output should contain info about sound devices detected

### Actual behavior

The output is empty

### Screenshots

![image](https://github.com/Dasharo/dasharo-issues/assets/94222245/3148c1ac-8bf6-4f4f-938c-ad70fdd6d21f)

### Additional context

Test AUD001.001 on ubuntu works just fine

**Comment by philipandag** [comment]
@dawidlesiak Could it be caused by a missing windows driver? Would you like to look into that?

**Comment by dawidlesiak** [comment]
tested on 6650 @philipandag I don't think its a driver issue.
I couldn't get any output with the mentioned command. However, it worked when I tried using other classes. The Get-AudioDevice -list command worked without any issues.
![image](https://github.com/user-attachments/assets/91370662-d836-46a6-86b0-a179fdd34ecf)
Also, the DP dongle used in the 6650 does not emulate audio output.

**Comment by philipandag** [comment]
> Tested on 6650 @philipandag I don't think its a driver issue. I couldn't get any output with the mentioned command. However, it worked when I tried using other classes. The Get-AudioDevice -list command worked without any issues. ![image](https://private-user-images.githubusercontent.com/166387055/348754811-91370662-d836-46a6-86b0-a179fdd34ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDY1MTMsIm5iZiI6MTcyMTEwNjIxMywicGF0aCI6Ii8xNjYzODcwNTUvMzQ4NzU0ODExLTkxMzcwNjYyLWQ4MzYtNDZhNi04NmIwLWExNzlmZGQzNGVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNTAzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmFhYTA1MGMzNzEzYWExOWE4NDg2ZmE1ZmI1M2NkMzRhYmRjZGRhYWMyMmRmZmUzYTdlMzY3NGNiYzE2MDJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z_jXTjNKJX1Y0ZnaaNW2yTkikCUtfh4ON7N80KdR-sg) Also, the DP dongle used in the 6650 does not emulate audio output. Additionally, Connecting with RDP disconnects Display Audio devices
> 
> **Update** After connecting proper HDMI monitorto 6650 and running:
> 
> ```
> Get-WmiObject -Class CIM_LogicalDevice 
> ```
> 
> audio device is clearly visible, but listed under Win32_PnPEntity instead of Win32_SoundDevice
> 
> ```
> Availability                :
> Caption                     : EA244WMi (HD Audio Driver for Display Audio)
> ClassGuid                   : {c166523c-fe0c-4a94-a586-f1a80cfbbf3e}
> CompatibleID                : {GenericAudioEndpoint, SWD\GenericRaw, SWD\Generic}
> ConfigManagerErrorCode      : 0
> ConfigManagerUserConfig     : False
> CreationClassName           : Win32_PnPEntity
> Description                 : Audio Endpoint
> DeviceID                    : SWD\MMDEVAPI\{0.0.0.00000000}.{5318CE90-BBC5-414A-90FC-E0B647B9A40F}
> ```

The command used was copied from an automatic test AUD001.002. In that case it may be an error in the test case not on the platform hardware/firmware/software. I don't know which of the classes is correct and can't say if this is an expected or at least an acceptable behaviour. I think I am not the one who should decide on closing this issue :)

@macpijan what do you think?

**Comment by dawidlesiak** [comment]
6670
The setup includes only the HDMI dongle.
![image](https://github.com/user-attachments/assets/c5b00147-b983-427f-af12-2591858ab324)
Endpoint listed as `Win32_PnPEntity`
![image](https://github.com/user-attachments/assets/cf1a0813-f2a8-43a2-9740-66094c3ff18c)
