### ISSUE TITLE
Freezing on Fedora 40 KDE

### ISSUE THREAD

**Issue by heheihahthe** [Dasharo/dasharo-issues#950]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

0.9.0-rc10

### Brief summary

OS randomly freezes during use

### How reproducible

Happened 3 out of 3 times when booting after flashing bios

### How to reproduce

Use the computer 

### Expected behavior

The computer should not freeze

### Actual behavior

The computer will freeze and not unfreeze---the first occurrence was quitting firefox through a kde error box after firefox crashed (may also be a firmware issue), the second time when opening a terminal with a keyboard shortcut, the third time when hovering over the wifi icon causing an overlay to appear

### Solutions you've tried

None

**Comment by macpijan** [comment]
Any change you can test with GNOME as well? We have installed Fedora with GNOME and have not spotted such problems so far.

**Comment by heheihahthe** [comment]
Can't boot the computer right now, I'll try to reflash the bios tomorrow and try again

**Comment by heheihahthe** [comment]
Even after reflashing, I'm unable to boot Fedora on kernels 6.9.8.200, 6.9.7-200, and 6.8.5-301. I can enter my luks password, but once the fedora boot logo disappears the computer is left at a blank screen. It also appears as if bios settings are not applied, as they reset every boot.

**Comment by heheihahthe** [comment]
I reinstalled fedora with gnome and the problem seems to be absent on this desktop environment.

**Comment by heheihahthe** [comment]
Reinstalling the operating system seems to resolve the issue entirely, even on kde. Will mark as closed for now.
