### ISSUE TITLE
meta-dts workflow can delete `~/.ssh/config` in some exceptional situations

### ISSUE THREAD

**Issue by iwanicki92** [Dasharo/dasharo-issues#954]
### Component

Dasharo Tools Suite

### Device

other

### Brief summary

Stopped/failed CI action can delete `~/.ssh/config` which will lead to failure on next run

### How reproducible

Always

### How to reproduce

* Push tag or rerun workflow that's run on tag push
* Cancel immediately (before second job starts/DTS finishes building)
* Repeat step 1

### Expected behavior

Previous workflow errors shouldn't influence current one

### Actual behavior

workflow fails because previous action change expected state
https://github.com/Dasharo/meta-dts/actions/runs/9997346441/job/27634154969

### Additional context

https://github.com/Dasharo/meta-dts/actions/runs/9996958212/job/27633519716
and
https://github.com/Dasharo/meta-dts/actions/runs/9997346441/job/27634154969

* Second job creates `config-old`: [ci.yml](https://github.com/Dasharo/meta-dts/blob/80bc82c7df36b00f095d271f99e729a69fc8dc5c/.github/workflows/ci.yml#L60)
* Third job (cleanup) is always run (even on failures) [ci.yml](https://github.com/Dasharo/meta-dts/blob/80bc82c7df36b00f095d271f99e729a69fc8dc5c/.github/workflows/ci.yml#L143)
  * deletes `config`
  * moves `config-old` to `config`

If workflow is stopped before second job then `config` is deleted in third and next step fails because there is no `config-old` to move.
Next run fails on second job because in previous job `config` was deleted but not recreated.

### Solutions you've tried

Not tested but quick fix would be to remove `rm -f ~/.ssh/config`.
Next step (`mv ~/.ssh/config-old ~/.ssh/config`) would still fail in this case but `config` wouldn't be deleted.

**Comment by PLangowski** [comment]
How about moving  `cp ~/.ssh/config ~/.ssh/config-old` to the beginning of the first workflow? That would reduce the probability of `config-old` not existing.

**Comment by macpijan** [comment]
How about simply create from scratch a config for this job, and do not touch original ~/.ssh/config at all?

This seems like the core of the problem, unccessary complexity.

Refer to the manual:

```

       -F ssh_config
               Specifies an alternative per-user configuration file for ssh.  This option is directly passed to ssh(1).
```

**Comment by m-iwanicki** [comment]
@PLangowski I guess it's ok, this way `clean` job would most likely always succeed, but I would still remove `rm` part and leave only `mv`.
Or you can do it as @macpijan said and maybe create copy of `~/.ssh/config` if it's needed.

**Comment by PLangowski** [comment]
@m-iwanicki the PR has been merged. Can you close this issue or is there something more to be done?

**Comment by m-iwanicki** [comment]
@PLangowski Closed, I wonder why it wasn't closed automatically when PR was merged.
