### ISSUE TITLE
DTS script 2.0.0-rc3 does not start standard DTS interface

### ISSUE THREAD

**Issue by eljejer** [Dasharo/dasharo-issues#956]
**Dasharo version**

coreboot+UEFI v0.9.0-rc10

**Dasharo variant**

Workstation

**Question text**

I downloaded https://github.com/Dasharo/meta-dts/releases/tag/v2.0.0-rc3 and flashed to USB thumb drive with etcher.
I expected to see the standard DTS interface to be able to update to the latest stable v2.0.0-rc3.
In stead I go to the interface where I could enter a shell to flash as I did with the beta firmware.

See attached [screenshot](https://filedn.eu/lsgq5dzkBPem4g1eYLxUkRL/2024-07-19-09-49-40-548.jpg)

What did I do wrong?

**Comment by m-iwanicki** [comment]
@eljejer `DTS v2.0.0`  has new UI. Just merged documentation update:
https://docs.dasharo.com/dasharo-tools-suite/documentation/#hcl-report
I had to clear browser cache before I saw changes.

**Comment by macpijan** [comment]
> In stead I go to the interface where I could enter a shell to flash as I did with the beta firmware.

You pressed `2` to proceed with firmware update, which is perfectly fine.

You can also press `S` to drop to shell if want to to it manually.
