### ISSUE TITLE
 Power Management Options / Battery Start & Stop Threshold

### ISSUE THREAD

**Issue by eljejer** [Dasharo/dasharo-issues#959]
**Dasharo version**

v0.9.0

**Dasharo variant**

workstation NovaCustom V56 Series

**Question text**

Question regarding Power Management Options / Battery Start & Stop Threshold:
I have always understood that the optimal SoC (State of Charge) of rechargeable batteries is around 80%.
I wonder why the default setting in firmware v0.9.0 is 95%.
Can you elaborate?

B.t.w.: on [this](https://docs.dasharo.com/dasharo-menu-docs/dasharo-system-features/) page, there is a typo: Treshold in stead of Threshold

**Comment by BeataZdunczyk** [comment]
Thank you for your contribution, @eljejer. It is greatly appreciated. 

This is related to [#843](https://github.com/Dasharo/dasharo-issues/issues/843). We will explain the battery behavior [here](https://docs.dasharo.com/unified/novacustom/features/#battery-charge-management) and provide updates in this issue.

**Comment by eljejer** [comment]
> Thank you for your contribution, @eljejer. It is greatly appreciated.
> 
> This is related to [#843](https://github.com/Dasharo/dasharo-issues/issues/843). We will explain the battery behavior [here](https://docs.dasharo.com/unified/novacustom/features/#battery-charge-management) and provide updates in this issue.

Thanks for the clarification 🙃
But will a contant SoC 96% in stead the proposed 80% not stress the battery too much then?

**Comment by mkopec** [comment]
Hi @eljejer ,

It's a balance between usable battery runtime and battery logevity. The values of 95/98 were chosen to prevent constantly topping up the battery when the laptop is plugged in most of the time. We didn't want to impact battery runtime too much, but you do have the option to configure your own limits if you wish.

To preserve battery longevity when your laptop spends most of the time plugged in, it's indeed better to set the limits lower, e.g. 75/80, as you pointed out.

**Comment by eljejer** [comment]
Okay, thanks for your further clarification. I will set it to 75 then

**Comment by eljejer** [comment]
Okay, thanks for your further clarification. I will set it to 75 then

**Comment by philipandag** [comment]
The documentation was updated to explain the battery behavior better. Check it out:
https://docs.dasharo.com/unified/novacustom/features/#battery-charge-management
