### ISSUE TITLE
Dasharo EC port for NovaCustom MTL dGPU models

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#963]
### The problem you're addressing (if any)

The dGPU boards are different to iGPU models and require a separate EC port.

### Describe the solution you'd like

Develop a port of Dasharo EC for NovaCustom Meteor Lake models with discrete graphics. 
- [x] Add GPIO configuration
- [x] Add dGPU config
- [x] Verify USB-PD config
- [ ] potentially also handle display mux override

**Comment by mkopec** [comment]
https://github.com/Dasharo/ec/pull/62

**Comment by BeataZdunczyk** [comment]
Closing this issue as we have moved the `potentially also handle display mux override` to a separate issue: https://github.com/Dasharo/dasharo-issues/issues/1024
