### ISSUE TITLE
Windows 11 installation error: This PC can't run Windows 11

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#97]
**Dasharo version**

v1.2.0

**Dasharo variant**

NovaCustom NS5x, NS70MU-i7-1165G7

**Affected component(s) or functionality**

Installation of Windows 11

**Brief summary**

While using a USB pen drive to install Windows 11, an error message shows up.

**How reproducible**

100% reproducible.

**How to reproduce**

1. Boot the laptop to a USB pen drive containing the official Windows 11 installation image.
2. Go through the setup steps to install Windows 11.

**Expected behavior**

Windows 11 can be installed without errors.

**Actual behavior**

The installation wizard shows an error after selecting the Windows version.

**Screenshots**

![Windows-11-setup-error](https://user-images.githubusercontent.com/100232604/171105775-e72b48e1-0af7-4010-9ecc-8d7e7b4e602d.png)

**Additional context**

This problem also occurred with the NV4x Series but has been fixed there since v1.0.0.
This problem seems that the Secure Boot and/or TPM 2.0 requirement could not be verified at the installation.

**Solutions you've tried**

There is a workaround for this issue. You can bypass the check for Secure Boot and TPM 2.0 by clicking on the X icon at the right upper corner and quit the setup. Then, hold the Shift key and press F10. Give the command `regedit`. Navigate to KEY_LOCAL_MACHINE\SYSTEM\Setup and create a new key (folder) here named ‘LabConfig’. Within this key, create a new DWORD (32 bits) value named ‘BypassSecureBootCheck’. Create another DWORD (32 bits) value named ‘BypassTPMCheck’. Don’t forget to set both values to 1!

**Comment by micmarluc** [comment]
Hello
I noticed the exact same thing on my NovaCustom NS70 notebook.

**Comment by mkopec** [comment]
@wessel-novacustom Is the TPM working on Linux? Here's a quick test to see if the TPM is detected:

```bash
ls /sys/class/tpm
```

it should list one TPM instance, e.g. `tpm0`.

If not, it's possible it's the Intel PTT causing conflicts with the discrete TPM again. Did you follow the Initial Installation steps from https://docs.dasharo.com/variants/novacustom_ns5x/installation/#installing-dasharo? It should be enough to make the PTT nonfunctional and dTPM functional.

**Comment by djg11** [comment]
Hi,
I am having the same issue on a NovaCustom NS50MU.
The Windows 11 installation from a USB is not working as described in the first comment.
On a Linux System the TPM is recognized but also not working (see below), I did not perform any flashing of the ROM. 

```terminal
$ lsmod | grep tpm

tpm                   102400  1 trusted
rng_core               20480  1 tpm
```

```terminal
$ sudo dmesg | grep -i tpm

[    0.000000] efi: ACPI 2a.0=0x76a54000 SMBIOS=0x760a0000 SMBIOS 3.0=0x7609d000 TPMFinalLog=0x75fbf000 RNG=0x75fa2a18 TPMEventLog=0x750b3018
[    0.017033] ACPI: TPM2 0x0000000076A5E390 00004C (v04 COREv4 COREBOOT 00000000 CORE 20200925)
[    0.017066] ACPI: Reserving TPM2 table memory at [mem 0x76a5e390-0x76a5e3db]
[   24.996102] systemd[1]: systemd 251.2-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
```

```terminal
$ bootctl status

System:
     Firmware: UEFI 2.70 (EDK II 1.00)
  Secure Boot: enabled (user)
 TPM2 Support: firmware only, driver unavailable
 Boot into FW: supported
```

```terminal
$ sudo tpm2_pcrread

** (process:88752): CRITICAL **: 19:08:59.762: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: Timeout was reached
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
ERROR:tcti:src/tss2-tcti/tcti-device.c:452:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: No such file or directory
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
ERROR:tcti:src/tss2-tcti/tcti-device.c:452:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm0: No such file or directory
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
WARNING:tcti:src/util/io.c:262:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:614:Tss2_Tcti_Swtpm_Init() Cannot connect to swtpm TPM socket
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-swtpm.so.0
WARNING:tcti:src/util/io.c:262:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-mssim.so.0
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:254:tctildr_get_default() No standard TCTI could be loaded
ERROR:tcti:src/tss2-tcti/tctildr.c:428:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
ERROR: Could not load tcti, got: "(null)"
```

**Comment by wessel-novacustom** [comment]
@djg11 thank you for your feedback!

The firmware was applied with fpt in an UEFI shell environment.

Let me investigate if there are any differences with flashing manually. I will be back shortly.

**Comment by wessel-novacustom** [comment]
We should be sure that we are using the same firmware binary, especially the ME region, as some sold units might have been dispatched with an Intel ME version that is officially not compatible. We will be back soon with a procedure to make sure that you have the right ME version, as having the right ME version might solve the problem.

**Comment by wessel-novacustom** [comment]
This particular problem has been solved by using a certain Intel ME version. It will therefore be closed.

Customers that have bought their laptop after 14th of June should not have this problem any longer. Customers that have bought their laptop before 14th of June can contact the vendor to ask for a fix procedure.

**Comment by djg11** [comment]
Thank you for the update.
best regards,Daniel


Sent with Proton Mail secure email.
------- Original Message -------
