### ISSUE TITLE
Onboard Intel I219-V is not working within linux installation

### ISSUE THREAD

**Issue by alexgithublab** [Dasharo/dasharo-issues#970]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

0.9.0

### Brief summary

Tested on Ubuntu 22 and 24 and Fedora 40

### How to reproduce

boot on live USB Ubuntu or Fedora...

### Expected behavior

Internet connection from RJ45 cable

### Actual behavior

result of :
lshw -c net

*-network:1 UNCLAIMED
       description: Ethernet controller
       product: Ethernet Connection (13) I219-V
       vendor: Intel Corporation
       physical id: 1f.6
       bus info: pci@0000:00:1f.6
       version: 20
       width: 32 bits
       clock: 33MHz
       capabilities: cap_list
       configuration: latency=0
       resources: memory:b54a0000-b54bffff

**Comment by wessel-novacustom** [comment]
I cannot reproduce. Did you take care not overwriting the GBE region? It breaks Ethernet functionality.
