### ISSUE TITLE
Audio recording very noisy from internal mic

### ISSUE THREAD

**Issue by marmarek** [Dasharo/dasharo-issues#972]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

0.9.0-rc7

### Brief summary

Recording from internal mic is very noisy 

### How reproducible

Always?

### How to reproduce

1. Start Fedora 40 Xfce (Live USB) (affects Qubes OS 4.2 too)
2. Record with `pw-record` or `audacity`, say few test words
3. Try to play it back

### Expected behavior

Test words clearly recorded with silent background

### Actual behavior

Very noisy background, even when the fan is not spinning.

### Solutions you've tried

Changing "mic boost" to 0 using `alsamixer` (it defaults to full) makes it better. But it's very unfriendly method, as needs to bypass pipewire/pulseaudio (needs to call `alsamixer -c 0`, otherwise the setting is hidden). And the setting can't be changed in normal audio volume control.

**Comment by mkopec** [comment]
It may be possible to tweak the HD Audio codec to reduce the mic gain somewhat. Depends on access to ALC245 documentation

**Comment by wessel-novacustom** [comment]
> It may be possible to tweak the HD Audio codec to reduce the mic gain somewhat. Depends on access to ALC245 documentation

- I have asked the factory for documentation and I expect a response in about 2 weeks.

**Comment by marmarek** [comment]
It might be also solvable(?) in Linux, take a look at function `alc269_fixup_limit_int_mic_boost()`, I see it applied to some ALC245 systems too. I see @mkopec already submitted some quirk for the V5xx models (about mic detection), I guess it can be extended to reduce mic boost too.

**Comment by mkopec** [comment]
@marmarek I see your patch has been merged and landed in v6.11, thanks! https://github.com/torvalds/linux/commit/562755501d44cfbbe82703a62cb41502bd067bd1

I think this can be closed then?
