### ISSUE TITLE
RGB keyboard illumination inactive after sleep mode

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#98]
**Dasharo version**

v1.2.0

**Dasharo variant**

NovaCustom NS5x, NS70MU-i7

**Affected component(s) or functionality**

RGB keyboard illumination

**Brief summary**

When waking up from sleep mode, the RGB keyboard illumination has to be reactivated manually. It doesn't turn on automatically.

**How reproducible**

100% reproducible.

**How to reproduce**

1. Boot the laptop to Windows 11 Pro.
2. Put the laptop into sleep mode (for instance with FN+F12, or by closing the lid)
3. Wake up the laptop by pressing any key or by pressing the power button.

**Expected behavior**

RGB keyboard illumination turns on automatically after sleep mode.

**Actual behavior**

RGB keyboard illumination doesn't turn on automatically after sleep mode. Instead, it has to be reactived manually with the FN shortcut key. 

**Additional context**

Running Windows 11, but it has also been noticed in a live environment of Ubuntu 22.04 LTS.

**Comment by mkopec** [comment]
I can reproduce on one NS70 laptop, but not on two NS51 laptops we have here at the office. All of them are running the same EC firmware version, 1.07.07. This problem may need some deeper investigation

**Comment by macpijan** [comment]
@wessel-novacustom On your side, it happens on both models, or the NS70 only as well?

**Comment by wessel-novacustom** [comment]
You are right! It only happens on NS70 ...

**Comment by wessel-novacustom** [comment]
Label [clevo_ns50mu](https://github.com/Dasharo/dasharo-issues/labels/clevo_ns50mu) should be removed as it only affects the NS70MU platform.

**Comment by wessel-novacustom** [comment]
Even though I didn't confirm that it has been solved, we assume so as we have had so many updates since then. Moreover, I remember that we have discussed this issue and solved it. We will re-open if we will see this problem happening again.
