### ISSUE TITLE
Intel ME Interface missing from sysfs

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#984]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.1-rc1

### Test case ID

MNE006.001

### Brief summary

Can't check ME version because ME interface is missing from sysfs in ubuntu 24.04

### How reproducible

100%

### How to reproduce

1) Make sure Intel ME is enabled in setup
2) boot to ubuntu and run `sudo cat /sys/class/mei/mei0/fw_ver`

### Expected behavior

Example output:

0:16.0.15.1735
0:16.0.15.1735
0:16.0.15.1723

### Actual behavior

```
root@3mdeb:~# cat /sys/class/mei/mei0/fw_ver
cat: /sys/class/mei/mei0/fw_ver: No such file or directory
root@3mdeb:~# ls /sys/class/mei
ls: cannot access '/sys/class/mei': No such file or directory
root@3mdeb:~#
```

**Comment by mkopec** [comment]
@philipandag can you paste output of `dmesg` here? Hard to say why Linux isn't creating these devnodes

**Comment by mkopec** [comment]
ah, forgot to remove `CONFIG_DISABLE_HECI1_AT_PRE_BOOT=y` from the config

**Comment by mkopec** [comment]
fixed by https://github.com/Dasharo/coreboot/pull/548/commits/058ae7afed1319c3fa54859e1ff4808ffe3dcb6a
