### ISSUE TITLE
dGPU doesn't show up in lspci on V560TNE

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#993]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc1

### Test case ID

NVI001.001

### Brief summary

dGPU doesn't get detected on V560TNE

### How reproducible

100%

### How to reproduce

Run `lspci | grep -i nvidia` on V560TNE, which has an NVIDIA dGPU

### Expected behavior

An entry similar to `2d:00.0 3D controller: NVIDIA Corporation TU117M (rev a1)`

### Actual behavior

Empty output

**Comment by mkopec** [comment]
Well yes, rc1 has the gpu disabled completely. rc2 re-enables the GPU and it's now detected in lspci correctly.
